### ISSUE TITLE
BUG：下载一段时间后，显示出现的问题i

### ISSUE THREAD

**Issue by mskgroup** [nilaoda/N_m3u8DL-CLI#103]
下载一段时间后，显示出现的问题
<xxx Complete>不再显示，只会显示downloading和watiting还有定时器间隔，而且只在最后一行刷新，上面是没有任何内容的。
但是下载没有问题，log也没问题，就是显示出了问题
[![image](https://user-images.githubusercontent.com/51709279/75754358-93265900-5d67-11ea-849c-d0caa5b10457.png)
](url)

log里记录是正常的：
16:01:16.647 / (NORMAL) <4713 Downloading>
16:01:17.137 / (NORMAL) <4713 Complete>
16:01:17.210 / (NORMAL) <4714 Downloading>
16:01:17.710 / (NORMAL) <4714 Complete>
16:01:17.797 / (NORMAL) <4715 Downloading>
16:01:18.305 / (NORMAL) <4715 Complete>
16:01:18.378 / (NORMAL) Waiting...
16:01:19.761 / (NORMAL) 定时器间隔 4.5s 下次进入时间:2020/3/3 16:01:24

**Comment by nilaoda** [comment]
收到
