### ISSUE TITLE
优酷独播无法下载？

### ISSUE THREAD

**Issue by z279493** [nilaoda/N_m3u8DL-CLI#105]
使用JS获取M3U8和KEY，分别填入N_m3u8DL-CLI-SimpleG.exe里面，点击GO出现命令框，显示到分片后就弹出一个红色英文 然后闪一下就退出了？这个这么解决？

**Comment by nilaoda** [comment]
提供视频地址

**Comment by z279493** [comment]
> 提供视频地址
https://v.youku.com/v_show/id_XMjM5MDY3MzYw.html?spm=a2hbt.13141534.1_3.d1_4 爱情公寓2 第4集
用js代码获取到的m3u8
http://valipl-vip.cp31.ott.cibntv.net/65727EE44FD34715640685B9C/05004A00005D66037C8BB780000000ECA83276-9D77-47B8-8E06-052272C02636-1-114.m3u8?ccode=0502&duration=3152&expire=18000&psid=f6e549ce2a3e11c958c2129d24d0980a&ups_client_netip=df0a9445&ups_ts=1583280031&ups_userid=371828788&utid=QJ3SFvlrWW0CAd8KkhRHhbse&vid=XMjM5MDY3MzYw&vkey=B78429543b16737ec8c57b6e25da1c776&sm=1&operate_type=1&dre=u38&si=78&eo=1&dst=1&iv=1&s=8acc113c6fbf11df97c0&bc=2
获取到的Key
HwIjnSeuldmlW4KCNP+Qlg==
还有法阵先锋4，乡村爱情12 同样都是获取这两个，放进程序里面到分片的时候弹出一串红色英文闪一下就退出了

**Comment by z279493** [comment]
> 提供视频地址

不好意思，我弄错了软件版本，我之前用的应该是2.4.8的所以下载不了，重新下载了2.5.6的可以用了
