### ISSUE TITLE
同一视频页面，2台设备解析到不一样的参数

### ISSUE THREAD

**Issue by qq457834782** [nilaoda/N_m3u8DL-CLI#106]
为什么同一个视频，一台电脑解析到1080P，另外一台电脑能解析到TV的4K，这是怎么回事

**Comment by nilaoda** [comment]
爱奇艺吗

**Comment by qq457834782** [comment]
是优酷的，比如这个https://v.youku.com/v_show/id_XNDAxNTc2MTQ3Ng==.html?spm=a2h0k.11417342.soresults.dselectbutton&s=347cb46fcd1e49718d76

**Comment by qq457834782** [comment]
是优酷的，比如这个https://v.youku.com/v_show/id_XNDAxNTc2MTQ3Mg==.html?spm=a2hbt.13141534.app.5~5!2~5!2~5~5~5!2~5~5!2~5!2~5!2~5~A!2
家里的电脑，WIN10，Google Chrome浏览器，点解析，得到乡村爱情11 02_default_643.46MB，分辨率是1080P，然后白天在单位的电脑win7，也是同浏览器，得到的是1个多G的，分辨率4K的视频

**Comment by qq457834782** [comment]
> 愛奇藝嗎

我今天把家里的电脑也装WIN7，结果解析到的还是1080P，想不出哪里不一样了，希望鸟大指点迷津
