### ISSUE TITLE
求问腾讯超前点播下载视频里面没内容,怎么解决?(已经购买了点播)

### ISSUE THREAD

**Issue by z279493** [nilaoda/N_m3u8DL-CLI#109]
用2.5.6版本下载腾讯枕上书点播,下载的视频 打开后里面没内容怎么解决?我两个代码都用了,下载下来都是一样的?
视频地址 https://v.qq.com/x/cover/vooy2m9hi5p1jqm/e0033dhp87m.html

普通代码 https://apd-b6a9241a7ba2ccaac0686cd00c7d53ec.v.smtcdns.com/vhqts.tc.qq.com/Ag6yYvsrC4vkkF9REDU9d21lm4EZmsYmJbgOmaPf07uQ/3_euTuvbDZsrOHpzx_jROHVAZMteYOzcfZsl79lX5eJjZDEt1sAR2M1ns9dHxy_5CgPeA22HeXIEXixw8EdTUMvTvMOgNuTGwJy1e0w8-wCpMXb_MH2wVHGCAioB3buqt9xXNIyt8COvJUKKYFGdu6mG3xlG1zRXUUgdtck53fI/e0033dhp87m.320181.mp4.m3u8?ver=5

[三生三世枕上书 第45集[v+a].zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/4293199/45.v%2Ba.zip)
DRM代码直接是文件
不管哪个下载下来 里面都没内容,求解决方法

**Comment by nilaoda** [comment]
目前没有办法解决，除非你知道怎么解密。。下载器只是下载，并不能解密
