### ISSUE TITLE
怎样获取腾讯视频M3U8文件？

### ISSUE THREAD

**Issue by ZELINK35** [nilaoda/N_m3u8DL-CLI#11]
是指VIP视频，我开通有会员的，之前用Chrome插件「猫抓」可以抓取到m3u8文件，近段时间都抓不到了，请问有其他软件或者方法获取吗？

链接：https://v.qq.com/x/cover/rm3tmmat4li8uul/j0031zu0tam.html

**Comment by aLuvletter** [comment]
javascript:prompt(PLAYER._DownloadMonitor.context.dataset.title,PLAYER._DownloadMonitor.context.dataset.currentVideoUrl);

**Comment by zackmark29** [comment]
> javascript:prompt(PLAYER._DownloadMonitor.context.dataset.title,PLAYER._DownloadMonitor.context.dataset.currentVideoUrl);

Hi
How can I do that on other website?
