### ISSUE TITLE
爱奇艺部f4v视频获取不到，TS格式的可以。

### ISSUE THREAD

**Issue by 602383883** [nilaoda/N_m3u8DL-CLI#12]
比如https://www.iqiyi.com/v_19rrnr1a5k.html
输入playerObject._player._core._movieinfo.originalData.data.program.video获取到的5个m3u8都是空的，所需数据在其中一个的fs里面。

**Comment by nilaoda** [comment]
好的 有时间我搞一下

**Comment by aLuvletter** [comment]
同感，我通过https://github.com/ZSAIm/iqiyi-parser/releases这大佬的下载f4v的，ts还是用这个，杠杠的！

**Comment by joshua1973** [comment]
同求，目前TS的都能下载，如果f4v也支持的话，那就真的太完美了~

**Comment by nilaoda** [comment]
已解决

**Comment by aLuvletter** [comment]
> 已解决

还是不能获取爱奇艺f4v

**Comment by nilaoda** [comment]
> > 已解决
> 
> 还是不能获取爱奇艺f4v

给个网址？以及你是用的最新版JS代码么 https://nilaoda.github.io/N_m3u8DL-CLI/GetM3u8.html

**Comment by aLuvletter** [comment]
https://www.iqiyi.com/v_19rr7peols.html

**Comment by aLuvletter** [comment]
> > > 已解决
> > 
> > 
> > 还是不能获取爱奇艺f4v
> 
> 给个网址？以及你是用的最新版JS代码么 https://nilaoda.github.io/N_m3u8DL-CLI/GetM3u8.html

是用最新的
https://www.iqiyi.com/v_19rr7peols.html

**Comment by nilaoda** [comment]
> > > > 已解决
> > > 
> > > 
> > > 还是不能获取爱奇艺f4v
> > 
> > 
> > 给个网址？以及你是用的最新版JS代码么 https://nilaoda.github.io/N_m3u8DL-CLI/GetM3u8.html
> 
> 是用最新的
> https://www.iqiyi.com/v_19rr7peols.html

网页上都无法播放，别说出m3u8了……

**Comment by aLuvletter** [comment]
> > > > > 已解决
> > > > 
> > > > 
> > > > 还是不能获取爱奇艺f4v
> > > 
> > > 
> > > 给个网址？以及你是用的最新版JS代码么 https://nilaoda.github.io/N_m3u8DL-CLI/GetM3u8.html
> > 
> > 
> > 是用最新的
> > https://www.iqiyi.com/v_19rr7peols.html
> 
> 网页上都无法播放，别说出m3u8了……

可以啊，我都看完了，没平台限制

**Comment by nilaoda** [comment]
> > > > > > 已解决
> > > > > 
> > > > > 
> > > > > 还是不能获取爱奇艺f4v
> > > > 
> > > > 
> > > > 给个网址？以及你是用的最新版JS代码么 https://nilaoda.github.io/N_m3u8DL-CLI/GetM3u8.html
> > > 
> > > 
> > > 是用最新的
> > > https://www.iqiyi.com/v_19rr7peols.html
> > 
> > 
> > 网页上都无法播放，别说出m3u8了……
> 
> 可以啊，我都看完了，没平台限制

![image](https://user-images.githubusercontent.com/20772925/61365992-474ba000-a8bb-11e9-8776-5867098633f2.png)
