### ISSUE TITLE
优酷drm貌似失效了

### ISSUE THREAD

**Issue by wc410514046** [nilaoda/N_m3u8DL-CLI#120]
https://v.youku.com/v_show/id_XNDUxNDQ4MDQwNA==.html?spm=a2hbt.13141534.app.5~5!2~5!2~5~5~5!2~5~5!2~5!2~5!2~5~A!22
以这个为例,现在使用教程中的drm普通解密方式,页面获取key后下载下来0字节了
大佬,帮忙看看

**Comment by nilaoda** [comment]
`dlKjTsj6LI+++bX56EUh0g==`

**Comment by wc410514046** [comment]
> dlKjTsj6LI+++bX56EUh0g==

能告诉下这个key是怎么来的吗？

**Comment by wc410514046** [comment]
> > dlKjTsj6LI+++bX56EUh0g==
> 
> 能告诉下这个key是怎么来的吗？

或者能给个联系方式么
