### ISSUE TITLE
大神 我承认我可能有点烦 还是优酷key无效的问题

### ISSUE THREAD

**Issue by wc410514046** [nilaoda/N_m3u8DL-CLI#122]
你之前说的那个
暂时用优酷旧版播放器js。
具体是怎么做呢？下载个旧版的播放器？然后用你的获取key的js在上面跑吗？问题是客户端怎么跑js呢。。。
还是说有个老的获取key的js现在有用了？
帮忙解答下 不胜感激

**Comment by nilaoda** [comment]
https://github.com/nilaoda/Blog/issues/19
