### ISSUE TITLE
2.4.9之前用的好好的，升级2.6.0后没法用了

### ISSUE THREAD

**Issue by Crazp** [nilaoda/N_m3u8DL-CLI#129]
m3u8带key的，无论输入base64的参数还是包含在本地key文件，都是文件读取失败，直接用ffmpeg下载合并一切正常

**Comment by nilaoda** [comment]
无法解密 是否有报错信息？以及能否提供m3u8用于测试

**Comment by Crazp** [comment]
> 无法解密 是否有报错信息？以及能否提供m3u8用于测试

`23:26:18.971 / (NORMAL) Start Parsing tmp - 副本.m3u8
23:26:19.310 / (NORMAL) Parsing Content
23:26:19.383 / (NORMAL) Opening tmp.key
23:26:19.690 / (NORMAL) Writing Json: [meta.json]
23:26:20.036 / (NORMAL) Start Downloading
23:26:21.017 / (ERROR) DOWN: 远程服务器返回错误: (403) 已禁止。 【*】media_b6000000_0.ts
23:26:21.115 / (NORMAL) Reading Video Info
23:26:21.169 / (NORMAL) Error in reading file
23:26:21.802 / (ERROR) DOWN: 远程服务器返回错误: (403) 已禁止。 
【*】media_b6000000_703.ts`

> https://send.firefox.com/download/675937e86684074e/#BZFqH3FKyn0mgUyhOu8-fw

m3u8和key都在里面了

**Comment by nilaoda** [comment]
链接过期。403错误是否是UA之类的问题呢

**Comment by Crazp** [comment]
> 链接过期。403错误是否是UA之类的问题呢

https://send.firefox.com/download/5f5078e4dca11a66/#YJKW5fgc-4DoJ7ty3N9mMA

前几天我用2.4.9还是一切正常的

**Comment by nilaoda** [comment]
> > 链接过期。403错误是否是UA之类的问题呢
> 
> https://send.firefox.com/download/5f5078e4dca11a66/#YJKW5fgc-4DoJ7ty3N9mMA
> 
> 前几天我用2.4.9还是一切正常的

网页做了限制，不是下载器的问题。找到原网页分析UA、Cookie、Referer等请求头，填入软件应该就能下载了

**Comment by Crazp** [comment]
> > > 链接过期。403错误是否是UA之类的问题呢
> > 
> > 
> > https://send.firefox.com/download/5f5078e4dca11a66/#YJKW5fgc-4DoJ7ty3N9mMA
> > 前几天我用2.4.9还是一切正常的
> 
> 网页做了限制，不是下载器的问题。找到原网页分析UA、Cookie、Referer等请求头，填入软件应该就能下载了

OK，我加了UA没问题了，看来ffmpeg是自带UA了
