### ISSUE TITLE
SimpleG启动器不支持桌面下载的m3u8文件

### ISSUE THREAD

**Issue by Cyclonekid** [nilaoda/N_m3u8DL-CLI#130]
直接使用命令行执行N_m3u8DL-CLI_v2.6.0.exe "C:\Users\Kids\Desktop\m3u8.txt" --workDir "D:\\" --enableDelAfterDone 可以正常下载
但是使用SimpleG启动器  将m3u8.txt 拖放到m3u8地址栏 点击go   程序就崩溃退出

**Comment by nilaoda** [comment]
请将m3u8.txt命名为m3u8.txt.m3u8

因为txt文件在GUI中，被当做了批量下载（每行一个m3u8地址）的标志。
