### ISSUE TITLE
如何获取m3u8地址

### ISSUE THREAD

**Issue by yuxia5454** [nilaoda/N_m3u8DL-CLI#136]
之前一直用的你帖子里的教程，帖子被锁了，看不到了，发现这个软件简介里也没了教程了，感谢

**Comment by snow212-cn** [comment]
[](https://github.com/nilaoda/N_m3u8DL-CLI/blob/4b5a64eb989fc0cc77fa86d57c306cf7ab69fefa/docs/GetM3u8.html)
