### ISSUE TITLE
下载爱奇艺的M3U8文件后，258块，下载到257块就下不动了

### ISSUE THREAD

**Issue by jasonbohan** [nilaoda/N_m3u8DL-CLI#14]
导致进度卡在99.6%，因为缺少最后1块，导致视频无法合成。能后修改一下程序，丢掉最后一小块。

**Comment by fox0618** [comment]
网络的问题吧，我用电信下也是很不稳定的，然而我换移动内网下，速度瞬间狂飙

**Comment by fox0618** [comment]
@jasonbohan
网络的问题吧，我用电信下也是很不稳定的，然而我换移动内网下，速度瞬间狂飙

**Comment by joshua1973** [comment]
要不要贴个网址大家帮你测试一下

**Comment by jasonbohan** [comment]
的确是网络问题导致的。同样是联通网络，也会出现这个问题。百思不得其解，换个网络就好了。
