### ISSUE TITLE
这个之前可以解码 现在不行了 老大能帮看看么

### ISSUE THREAD

**Issue by kqysw** [nilaoda/N_m3u8DL-CLI#140]
https://live.polyv.cn/watch/944322

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-KEY:METHOD=AES-128,URI="https://hls.videocc.net/b2c69d831d/d/b2c69d831d276d5c60adbfebb07995ad_3.key",IV=0xe994a3d4bb75f6832c269ef69beaa7b1
#EXT-X-TARGETDURATION:18
#EXTINF:5.138000,
https://ab-dts.videocc.net/b2c69d831d/0/1234567890123/d/79/95/ad_3/b2c69d831d276d5c60adbfebb07995ad_3_0.ts?pid=1585059695209X1680476&device=desktop
#EXTINF:5.000000,

**Comment by nilaoda** [comment]
无法打开
