### ISSUE TITLE
如何下载链接合并后ts文件

### ISSUE THREAD

**Issue by ownerowner** [nilaoda/N_m3u8DL-CLI#141]
此工具贴入m3u8地址，如果利用ffmpeg下载合并后视频自动封装mp4文件，如何让它自动封装ts文件呢，如果没有ffmpeg软件可以自行合并为ts文件吗

**Comment by nilaoda** [comment]
本程序不能用ffmpeg封装为ts，但你可以开启二进制合并，会合并为ts文件

**Comment by ownerowner** [comment]
> 本程序不能用ffmpeg封装为ts，但你可以开启二进制合并，会合并为ts文件

感谢解答
