### ISSUE TITLE
如何加载本地key文件解密

### ISSUE THREAD

**Issue by liuqiqi79** [nilaoda/N_m3u8DL-CLI#145]
老大：
请教N_m3u8DL-CLI如何加载本地key文件？
加密：#EXT-X-KEY:METHOD=AES-128,URI="#####"命令适用有网页key的，如果只能知道key，如何调用本地的key？

**Comment by nilaoda** [comment]
```
    --useKeyFile File           使用外部16字节文件定义AES-128解密KEY
    --useKeyBase64 Base64String 使用Base64字符串定义AES-128解密KEY
```

**Comment by liuqiqi79** [comment]
> ```
>     --useKeyFile File           使用外部16字节文件定义AES-128解密KEY
>     --useKeyBase64 Base64String 使用Base64字符串定义AES-128解密KEY
> ```

谢谢！
