### ISSUE TITLE
simpleG建议两个新功能

### ISSUE THREAD

**Issue by joshatt** [nilaoda/N_m3u8DL-CLI#146]
simpleG 建议两个新选项:
1, 每个任务下载完成后, 声音播报
2, m3u8链接不太了解, 如果它不带时效, 那么能否增加个功能: 按GO后加入队列, 多个任务排队下载, 例如可以设置最大任务数

**Comment by nilaoda** [comment]
排队下载目前已经支持两种情况：

1. 拖入txt文件，txt文件内容为每行一个`url`或者`filename,url`(自定义文件名)，程序进行顺序下载
2. 拖入一个文件夹，程序将扫描文件夹下的所有m3u8文件进行顺序下载

最大任务数，请自行控制同时启动n个bat文件
