### ISSUE TITLE
抓取的直链不能播放

### ISSUE THREAD

**Issue by ownerowner** [nilaoda/N_m3u8DL-CLI#147]
http://mpd.kekenet.com:80/Sound/2018/05/gbs212.mp4 
类似这个，下载后发现不能播放
抓包发现两个数据，请您分析一下该如何解密
{
	"AppFlag":0,
	"ApTime":1585621666249,
	"ApVersion":"4.1.3",
	"ApVersionCode":40103,
	"Method":"listen_video_getvideoextensivelisten",
	"Params":{
		"videoid":3931
	},
	"Sign":"78a9d88755539e80812c66e80b547138",
	"Terminal":3,
	"Token":"3D7F6EFEBF2F5140EB807D4A3EE0C4A6",
	"UID":"28972648",
	"Version":"4.0"
}

POST /v3/report HTTP/1.1
X-App-Key: 310c89a83e46f16a91d52c82
Authorization: Basic MjM5Nzg3MTkxNTg6ZTNlMGQxYjc1ZDljYTE2ODFjM2ZjNjQ3N2FmOGVlOTQxODUyYTMxNDowM2YwNTMyYTljYWQ3YjFjNDM0ZDJmNGY4NTkzMmExZA==
Accept: application/jason
Charset: UTF-8
Accept-Encoding: gzip
Content-Length: 320
Content-Type: application/x-www-form-urlencoded
User-Agent: Dalvik/2.1.0 (Linux; U; Android 8.1.0; JKM-AL00a Build/HUAWEIJKM-AL00a)
Host: gd-stats.jpush.cn
Connection: Keep-Alive

**Comment by nilaoda** [comment]
程序仅支持`m3u8`，不支持直链。

**Comment by ownerowner** [comment]
> 程序仅支持`m3u8`，不支持直链。

我知道，但是视频无法播放，意思是使用mp4decrypt如何解密
