### ISSUE TITLE
大佬，你这个仍是不支持CSDN视频下载吗？难道只有vvtoolbox可以？

### ISSUE THREAD

**Issue by Eacolt** [nilaoda/N_m3u8DL-CLI#148]
CSDN学院视频地址：https://edu.csdn.net/course/play/852/11713
m3u8地址：https://vedu.csdnimg.cn/0d00dcb3a68e4df8843ed554aadb7713/ebe3731293c580a3eb8003759d5cbab5-4k-encrypt-stream.m3u8
base64key:T4clE/MeNONi9EtNpwGQmw== (通过vvtoolbox获取)

但是，通过你的这个软件，按照要求，只填写了key和m3u8，还是无法下载，下载下来是一个空文件
![image](https://user-images.githubusercontent.com/15901920/77985940-6191b500-7348-11ea-8840-cabe078f7c82.png)

下载下来是这样：
![image](https://user-images.githubusercontent.com/15901920/77985989-85ed9180-7348-11ea-844c-3cbf196a007b.png)
![image](https://user-images.githubusercontent.com/15901920/77985993-8be37280-7348-11ea-8ab4-d4bc8cdec16d.png)

难道是不支持CSDN视频吗

**Comment by nilaoda** [comment]
出于某些原因，已经移除了对阿里云加密的支持。

**Comment by BenSYZ** [comment]
> 出于某些原因，已经移除了对阿里云加密的支持。

**出于某些原因** 艹😂
