### ISSUE TITLE
优酷 腾讯 爱奇艺 都不知道啥原理，而且还是今年最新刚刚改版的

### ISSUE THREAD

**Issue by handashuai** [nilaoda/N_m3u8DL-CLI#151]

**Comment by nilaoda** [comment]
https://cdn.jsdelivr.net/gh/nilaoda/N_m3u8DL-CLI@2.4.9/docs/GetM3u8.html

**Comment by wyl5602443** [comment]
老大，看不太懂，呵呵，不好意思了，基础有点太差了。之前他们发的都是各个视频站的直接的代码，而且写的如何利用浏览器书签进行获取以及很详细的步骤。您这个完全看不懂。唉...............

**Comment by manamikk** [comment]
> https://cdn.jsdelivr.net/gh/nilaoda/N_m3u8DL-CLI@2.4.9/docs/GetM3u8.html

哇还能这么玩吗
