### ISSUE TITLE
Could you please share source code for with GUI Version?

### ISSUE THREAD

**Issue by zackmark29** [nilaoda/N_m3u8DL-CLI#154]
Thank you

**Comment by heywolf15** [comment]
1+

**Comment by nilaoda** [comment]
Internationalization support will appear in a future version.

**Comment by pedrothelion** [comment]
Yes please we need English version for the GUI.

**Comment by zackmark29** [comment]
> Internationalization support will appear in a future version.

Hi nilaoda.
Could you share the source code for GUI version?

**Comment by HackerBoy0412** [comment]
Any news?
