### ISSUE TITLE
 N_m3u8DL-CLI_v2.6.1 页面出现乱码

### ISSUE THREAD

**Issue by toyou-shu** [nilaoda/N_m3u8DL-CLI#156]
字符出现乱码。 N_m3u8DL-CLI_v2.6.0 及以下版本正常。
![QQ图片20200417175603](https://user-images.githubusercontent.com/31024780/79557234-ce40d980-80d4-11ea-8e68-89006b614a4a.png)

**Comment by nilaoda** [comment]
你是什么系统？

**Comment by toyou-shu** [comment]
> 你是什么系统？最新版将控制台输出编码切换为了UTF-8

WIN7

**Comment by nilaoda** [comment]
好吧 字符显示在win7下还是有问题。先撤回更新了

**Comment by nilaoda** [comment]
试一下2.6.2

**Comment by nilaoda** [comment]
2.6.3已经恢复2.6.0及之前的编码
