### ISSUE TITLE
N_m3u8DL-CLI_v2.6.2 無法打開

### ISSUE THREAD

**Issue by Kaillis** [nilaoda/N_m3u8DL-CLI#158]
一打開就顯示以下錯誤：
![Snipaste_2020-04-17_20-58-19](https://user-images.githubusercontent.com/20882298/79571841-744d0d80-80ee-11ea-9d3b-b92c575db6d0.jpg)

另外不知道可否更改編碼兼容繁體系統？有些字會顯示問號，雖然影響不大，但如果出錯可能會看不懂錯誤提示。（2.6.0 版截圖）
![Snipaste_2020-04-17_21-00-55](https://user-images.githubusercontent.com/20882298/79572030-d574e100-80ee-11ea-8d77-de63cc58ed1b.jpg)

**Comment by nilaoda** [comment]
[N_m3u8DL-CLI.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/4493212/N_m3u8DL-CLI.zip)

试一下这个版本？

**Comment by nilaoda** [comment]
算了，不打算搞编码问题了。蛋疼。

**Comment by nilaoda** [comment]
繁体显示的相关问题，未来有空的时候我弄一下多语言支持。

**Comment by Kaillis** [comment]
好的，謝謝老大

**Comment by nilaoda** [comment]
> 好的，謝謝老大

2.7.0版本已经支持繁体中文，期待测试。

**Comment by Kaillis** [comment]
> > 好的，謝謝老大
> 
> 2.7.0版本已经支持繁体中文，期待测试。

測試過還是沒有正常顯示

![未命名1](https://user-images.githubusercontent.com/20882298/87857030-06ff8180-c956-11ea-8b3c-243d7c18d9b4.jpg)

**Comment by nilaoda** [comment]
> > > 好的，謝謝老大
> > 
> > 
> > 2.7.0版本已经支持繁体中文，期待测试。
> 
> 測試過還是沒有正常顯示
> 
> ![未命名1](https://user-images.githubusercontent.com/20882298/87857030-06ff8180-c956-11ea-8b3c-243d7c18d9b4.jpg)

请帮忙测试一下这个程序会输出什么内容：
[CheckCulture.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/4943081/CheckCulture.zip)

**Comment by nilaoda** [comment]
> > > 好的，謝謝老大
> > 
> > 
> > 2.7.0版本已经支持繁体中文，期待测试。
> 
> 測試過還是沒有正常顯示
> 
> ![未命名1](https://user-images.githubusercontent.com/20882298/87857030-06ff8180-c956-11ea-8b3c-243d7c18d9b4.jpg)

打包错误啦，2.7.1应该正常了

**Comment by Kaillis** [comment]
> > > > 好的，謝謝老大
> > > 
> > > 
> > > 2.7.0版本已经支持繁体中文，期待测试。
> > 
> > 
> > 測試過還是沒有正常顯示
> > ![未命名1](https://user-images.githubusercontent.com/20882298/87857030-06ff8180-c956-11ea-8b3c-243d7c18d9b4.jpg)
> 
> 打包错误啦，2.7.1应该正常了

2.7.1正常了，老大辛苦了
