### ISSUE TITLE
有个关于m3u8下载后时长的一个问题请教一下

### ISSUE THREAD

**Issue by lemonyouzicha** [nilaoda/N_m3u8DL-CLI#16]
打扰了 我用ffmpeg -i 看了m3u8链接的时长假设为10min   但是我ffmpeg -i test.m3u8 test.mp4下载后时长被缩短了
然后我用你提供的下载方式却是正常的
所以我想问一下你是否是直接用ffmpeg下载的  参数改如何定义

**Comment by nilaoda** [comment]
我不是用ffmpeg下载的，ffmpeg在我这里几乎只有合并作用

**Comment by lemonyouzicha** [comment]
那方便告诉我是什么方式下载的  我去研究研究

**Comment by nilaoda** [comment]
> 那方便告诉我是什么方式下载的 我去研究研究

HttpWebRequest发起请求，读取ResponseStream写入文件

**Comment by lemonyouzicha** [comment]
好的 谢谢了
