### ISSUE TITLE
求问一下大神们，解析各大影视平台的M3U8地址的最新JS代码是什么？

### ISSUE THREAD

**Issue by wyl5602443** [nilaoda/N_m3u8DL-CLI#161]
请问一下怎么提取爱奇艺，腾讯视频，优酷，WeTV，MGTV以及搜狐这些视频站的M3U8代码的呢？我记得之前有浏览器的JS代码可以解析获取的啊，但是找了很久也没找到。请问能给个地址吗？像这个弄到了在线看的视频地址，但是找不到M3U8地址还是下载不了啊！

**Comment by nilaoda** [comment]
#151
