### ISSUE TITLE
Can't Download M3u8

### ISSUE THREAD

**Issue by zackmark29** [nilaoda/N_m3u8DL-CLI#164]
Hi I can't download m3u8 from this site:
https://www.iwant.ph/tv/watch/forevermore?id=e623653d-cd04-4be6-98d4-adcf1a859ecc

Could you tell me what to do?

I can't actually understand the text in the app

[https://i.imgur.com/YlnSzUS.png](url)
[https://i.imgur.com/rWoQI7o.png](url)

**Comment by nilaoda** [comment]
If it is an AES-128-CBC encryption program and cannot be downloaded, try adding headers.

I don’t have an account for this site, so I can’t test it.

**Comment by zackmark29** [comment]
> If it is an AES-128-CBC encryption program and cannot be downloaded, try adding headers.
> 
> I don’t have an account for this site, so I can’t test it.

HI thank you for the reply.
But I already tried adding headers but nothing is happening
You can use my account if you want :)
but I don't know how I can message you

**Comment by zackmark29** [comment]
I already sent you my account via email

**Comment by zackmark29** [comment]
> If it is an AES-128-CBC encryption program and cannot be downloaded, try adding headers.
> 
> I don’t have an account for this site, so I can’t test it.

I found the solution :)
I just noticed it's not downloading the master.m3u8 
but when I tried the index.m3u8 it worked :) with header user-agent

Is it possible to download the file instead of url?
so that I can stored first the m3u8 files and then download later
