### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by xmhwws** [nilaoda/N_m3u8DL-CLI#167]
m3u8链接：https://raw.githubusercontent.com/xmhwws/AApk/master/e511c84e757afed1ee4bb41e02dc1669-S00000001-100000-od-encrypt-stream.m3u8

视频链接：https://ke.yijincc.com/study-2905.htm
注册一个账号就可以观看。

失败截图：
![2020-04-30_13-23-35](https://user-images.githubusercontent.com/42903751/80675150-5916d080-8ae6-11ea-9a5a-83623e32da3a.png)

之前通过下载器下载，只要在请求头里面加个refer（抓包可得具体refer）就可以直接下载，且能正常观看。现在网站改版了，加refer后虽然可以下载，但无法正常播放。

**Comment by nilaoda** [comment]
js打断点就能获取key

![image](https://user-images.githubusercontent.com/20772925/80678338-4c49ab00-8aed-11ea-9d9f-63face9bfe85.png)

![image](https://user-images.githubusercontent.com/20772925/80678407-71d6b480-8aed-11ea-91f5-f8278b337a43.png)

**Comment by xmhwws** [comment]
使用我提供在github上的m3u8，还是不行，也许我步骤有误？
![image](https://user-images.githubusercontent.com/42903751/80689277-ac494d00-8aff-11ea-81a9-dc239a87178c.png)

![image](https://user-images.githubusercontent.com/42903751/80689331-bd925980-8aff-11ea-8e71-c2d48f1229ca.png)

![image](https://user-images.githubusercontent.com/42903751/80689551-1bbf3c80-8b00-11ea-9edf-f74a7d69afef.png)

**Comment by xmhwws** [comment]
感谢，上个问题已经解决（输入key、baseURL），但又出现了新的问题：`填光无效，无法被移除。`

视频链接：https://ke.yijincc.com/study-759.htm
key：`MzM5MTdkM2Q4ZDVlMDk4NTI0Y2JlMGZhMmY4M2JmYmE=`
![image](https://user-images.githubusercontent.com/42903751/80692065-a6556b00-8b03-11ea-9baa-27e93b92e3e3.png)


![image](https://user-images.githubusercontent.com/42903751/80691805-55de0d80-8b03-11ea-8334-a4450373f388.png)

![2020-04-30_16-53-06](https://user-images.githubusercontent.com/42903751/80691911-7312dc00-8b03-11ea-9e79-bd3f95a2a8ff.png)

**Comment by nilaoda** [comment]
同样的位置断点，可得key`7q/JiqV5iy9S5mm6PYrBVQ==`

**Comment by xmhwws** [comment]
> 同样的位置断点，可得key`7q/JiqV5iy9S5mm6PYrBVQ==`

现在我得到的key也是这个，之前不知道为什么是错误的key，真是奇怪。
感谢大佬解惑

**Comment by nilaoda** [comment]
对了，不需要加referer，抓到的m3u8链接就能直接下载
