### ISSUE TITLE
How to get the m3u8 link without looking on developer tool

### ISSUE THREAD

**Issue by zackmark29** [nilaoda/N_m3u8DL-CLI#168]
I watched someone used this javascript to easily get the m3u8 link:
avascript:prompt(PLAYER._DownloadMonitor.context.dataset.title,PLAYER._DownloadMonitor.context.dataset.currentVideoUrl.replace(/:.*qq.com/g,"://defaultts.tc.qq.com/defaultts.tc.qq.com"));

is it possible to do this with m3u8DL-CLI? to easily get the m3u8 link

**Comment by arbarbosa1979** [comment]
### **Stream Detector** (_Easily detect .m3u8 url etc._)

This Firefox extension which allow you to easily get the .m3u8 or mpd links without looking on developer's network tab.

**Info**:
This is a Firefox addon written in JavaScript which provides an easy way to keep track of URLs to playlists and subtitles used by Apple HLS, Adobe HDS, MPEG-DASH, and Microsoft Smooth Streaming streams.

Also assembles readymade youtube-dl (recommended)/FFmpeg/Streamlink/hlsdl commands which (should) include all of the necessary cookies and headers.

## Firefox extension link:

[Firefox Extension](https://addons.mozilla.org/en-US/firefox/addon/hls-stream-detector/)

Just play the video and it will automatically detect and give you the links via right click or the extension icon.

> ### Features:
> - Can easily detect any website that using .m3u8 or mpd links after you load the video
> - Copy the links as youtube-dl/streamlink/ffmpeg/hlsdl command
> or just the url for .m3u8 or mpd
> - Can add custom additional parameters (from options)

For more info from the creator: [Github Stream Detector](https://github.com/rowrawer/stream-detector)
