### ISSUE TITLE
只能获取一个分段视频https://v.qq.com/x/cover/786ipgg4iqf5jqx/s0907rkwx9x.html

### ISSUE THREAD

**Issue by redstoneleo** [nilaoda/N_m3u8DL-CLI#17]
我在Win7 32bit，Chrome浏览器上用
`PLAYER._DownloadMonitor.context.dataset.currentVideoUrl`
在Chrome浏览器里只能获取
https://v.qq.com/x/cover/786ipgg4iqf5jqx/s0907rkwx9x.html
的一个分段视频，并非m3u8 url，请问怎么获取所有的视频分段？

**Comment by bnm14744** [comment]
https://apd-c395b4f88b09e8dd6650438c18718113.v.smtcdns.com/omts.tc.qq.com/Az0Q6rbOWmbCtY43wjxFb1xFrGBRkECkHZstfBIAMEe4/uwMROfz2r5xgoaQXGdGnC2df64gVTKzl5C_X6A3JOVT0QIb-/O_vrxJXL7ajQUTkbbGrLmAIX_bnXpvI4GI7ILbfsKNV1Uky2fddZ-_aIvkIjSJbyfoKK7kc-o0830gaRwI2FG_kOwa4E9BDHNq04hCc5l6D0K3am_DYUG3ZymeM3rNfFMAfjhBDnnaPcoYsXWxnyUzYHY1YwjUHEMrchRUDTMYo/s0907rkwx9x.321004.ts.m3u8?ver=4


这个是这个视频的 M3U8  建议用插件抓取

**Comment by redstoneleo** [comment]
插件名字是什么？
