### ISSUE TITLE
请问一下获取JS的那个网址要怎么使用？

### ISSUE THREAD

**Issue by tsungho15** [nilaoda/N_m3u8DL-CLI#170]
非常抱歉，小弟是新手。之前有人问过了，获取M3u8的网址如下：
https://cdn.jsdelivr.net/gh/nilaoda/N_m3u8DL-CLI@2.4.9/docs/GetM3u8.html
可以请问这个网址要怎么使用吗？

**Comment by nilaoda** [comment]
存成本地html文件，浏览器打开
