### ISSUE TITLE
无法下载233网校收费视频

### ISSUE THREAD

**Issue by xugui0821** [nilaoda/N_m3u8DL-CLI#171]
免费视频可以下，无法下载已购买的收费视频

**Comment by xugui0821** [comment]
提示key403错误，从chrome F12把key下载到本地拖到simpleG上提示非16byte文件

**Comment by xugui0821** [comment]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-ALLOW-CACHE:YES
#EXT-X-KEY:METHOD=AES-128,URI="https://hls.videocc.net/4adf37ccc0/7/4adf37ccc075588ae6d9162787877527_2.key",IV=0xbad06c98fddf2caab90d6f01e0fe7179
#EXT-X-TARGETDURATION:14
#EXTINF:13.043000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_0.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_1.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_2.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_3.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_4.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_5.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_6.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_7.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_8.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_9.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_10.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_11.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_12.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_13.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_14.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_15.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_16.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_17.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_18.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_19.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_20.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_21.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_22.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_23.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_24.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_25.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_26.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_27.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_28.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_29.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_30.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_31.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_32.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_33.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_34.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_35.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_36.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_37.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_38.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_39.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_40.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_41.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_42.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_43.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_44.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_45.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_46.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_47.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_48.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_49.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_50.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_51.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_52.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_53.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_54.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_55.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_56.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_57.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_58.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_59.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_60.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_61.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_62.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_63.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_64.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_65.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_66.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_67.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_68.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_69.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_70.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_71.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_72.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_73.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_74.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_75.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_76.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_77.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_78.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_79.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_80.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_81.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_82.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_83.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_84.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_85.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_86.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_87.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_88.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_89.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_90.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_91.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_92.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_93.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_94.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_95.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_96.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_97.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_98.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_99.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_100.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_101.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_102.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_103.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_104.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_105.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_106.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_107.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_108.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_109.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_110.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_111.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_112.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_113.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_114.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_115.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_116.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_117.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_118.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_119.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_120.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:10.000000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_121.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:8.640000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_122.ts?pid=1588492564602X1117231&device=desktop
#EXTINF:3.200000,
https://ab-dts.videocc.net/4adf37ccc0/10/1577869705159/7/87/75/27_2/4adf37ccc075588ae6d9162787877527_2_123.ts?pid=1588492564602X1117231&device=desktop
#EXT-X-ENDLIST

**Comment by xugui0821** [comment]
[key.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/4569798/key.zip)
这个是key

**Comment by nilaoda** [comment]
网校的下载建议自己debug找key，key一般都是经过加密的

**Comment by wzdata** [comment]
> 免费视频可以下，无法下载已购买的收费视频

😂老哥，现在解决了吗，我也遇到了跟你一样的问题，他好像是key加了token,然后再用这个解密m3u8

**Comment by fgcd8964** [comment]
老哥你现在解决没有？
