### ISSUE TITLE
Choosing best Quality

### ISSUE THREAD

**Issue by zackmark29** [nilaoda/N_m3u8DL-CLI#174]
Hi nilaoda.
What is the parameter for choosing best quality?

**Comment by nilaoda** [comment]
automatically

**Comment by deepblue2000** [comment]
how can I choose the quality, if there are 5 different resolutions ?

**Comment by nilaoda** [comment]
> how can I choose the quality, if there are 5 different resolutions ?

Unfortunately, you cant do this now. =^=

**Comment by deepblue2000** [comment]
ok thanks,

I tought it would be possible cause ffmpeg supports it with .mpd" -map 0:6 -map 0:4
 but if I download it with ffmpeg the file is not decryptable
