### ISSUE TITLE
未来是否考虑加入sample AES解密

### ISSUE THREAD

**Issue by ownerowner** [nilaoda/N_m3u8DL-CLI#176]
目前程序不支持解密sample aes，不知道未来是否考虑加入

**Comment by nilaoda** [comment]
有测试链接吗

**Comment by zackmark29** [comment]
> Do you have a test link?

Niloada is there any chance to download Manifest.mpd?

**Comment by ownerowner** [comment]
> 有测试链接吗

https://www.mewatch.sg/en/series/big-white-duel-dual-sound/ep50/924345

**Comment by nilaoda** [comment]
> > Do you have a test link?
> 
> Niloada is there any chance to download Manifest.mpd?

m3u8 only

**Comment by zebwong** [comment]
同样有这个需求，YOUKU VIP视频有些就下载了播放不了，提示sample AES解密不了，参考连接：https://v.youku.com/v_show/id_XNDUwMDIzNzExMg==.html?spm=a2h0c.8166622.PhoneSokuProgram_1.dselectbutton_15   不知道有没机会处理。

**Comment by Weein** [comment]
腾讯也开始使用SAMPLE-AES-CTR，希望可以加入解密支援

**Comment by nilaoda** [comment]
即使未来版本支持解密，没有KEY也是无能为力的~

**Comment by ownerowner** [comment]
> 即使未来版本支持解密，没有KEY也是无能为力的~

好吧

**Comment by Yesterday17** [comment]
最近搓了一个解 Sampe-AES 加密了的 ts 块的工具，有没有机会考虑支持一下（

https://github.com/Yesterday17/iori/releases/tag/ssadecrypt-v0.1.0

使用例：

```bash
ssadecrypt --key <hex-of-key> --iv <hex-of-iv> input.ts output.ts
```

**Comment by nilaoda** [comment]
> 最近搓了一个解 Sampe-AES 加密了的 ts 块的工具，有没有机会考虑支持一下（
> 
> https://github.com/Yesterday17/iori/releases/tag/ssadecrypt-v0.1.0
> 
> 使用例：
> 
> ssadecrypt --key <hex-of-key> --iv <hex-of-iv> input.ts output.ts

fMP4比较多，TS比较少见的说……有链接看看吗

**Comment by Yesterday17** [comment]
Bento4 的 mp42hls 可以通过指定 --encryption-mode=SAMPLE-AES
--encryption-iv-mode=fps 来生成这样加密的 m3u8+ts；一般直播/视频网站的话如果要支持 iOS 播放也会提供对应的
HLS 版本，不少就会用这种 TS，如果需要这种的话我单独邮件发你（

2025年2月9日(日) 2:19 nilaoda ***@***.***>:
