### ISSUE TITLE
未经处理的异常: System.BadImageFormatException: 

### ISSUE THREAD

**Issue by onemedicine** [nilaoda/N_m3u8DL-CLI#179]
刚开始可以使用，后来再用会保错

未经处理的异常:  System.BadImageFormatException: 未能加载文件或程序集“133120 bytes loaded from N_m3u8DL-CLI, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。试图加载格式不正确的程序。 ---> System.BadImageFormatException: 无法成功完成操作，因为文件包含病毒或潜在的垃圾软件。 (异常来自 HRESULT:0x800700E1)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Reflection.RuntimeAssembly.LoadModule(RuntimeAssembly assembly, String moduleName, Byte[] rawModule, Int32 cbModule, Byte[] rawSymbolStore, Int32 cbSymbolStore, ObjectHandleOnStack retModule)
   在 System.Reflection.RuntimeAssembly.LoadModule(String moduleName, Byte[] rawModule, Byte[] rawSymbolStore)
   在 Main(String[] )

**Comment by nilaoda** [comment]
看样子是被某些杀毒软件误杀了

**Comment by onemedicine** [comment]
> 看样子是被某些杀毒软件误杀了了

只有win10防火墙开着，也没有安全通知；卸载microsoft Framework 4.8 之后还是不行，在经历两次重启之后恢复了正常。本来想着装.net4.6，却发现在具有Windows 10 Fall Creators Update的系统上，您无法安装.NET Framework 4.6.2。。。
