### ISSUE TITLE
这个网址无法下载

### ISSUE THREAD

**Issue by joshatt** [nilaoda/N_m3u8DL-CLI#18]
https://www8.watchmovie.io/series/the-voice-season-16-episode-8
麻烦看一下, 默认的服务器, 也就是server m1, 能观看但不能下载.
解析后是这个:
https://b2slave12.kngfe.info/drive//hls/0f308e655695a44f58e080c4aecafd81/0f308e655695a44f58e080c4aecafd81.m3u8

**Comment by nilaoda** [comment]
添加`Referer`即可  
 
`N_m3u8DL-CLI "https://b2slave12.kngfe.info/drive//hls/0f308e655695a44f58e080c4aecafd81/0f308e655695a44f58e080c4aecafd81.m3u8" --headers "referer:https://vidcloud.icu/streaming.php"`

![image](https://user-images.githubusercontent.com/20772925/64581809-1f118680-d3be-11e9-8770-3d89d1a1d948.png)

**Comment by joshatt** [comment]
> "https://b2slave12.kngfe.info/drive//hls/0f308e655695a44f58e080c4aecafd81/0f308e655695a44f58e080c4aecafd81.m3u8" --headers "referer:https://vidcloud.icu/streaming.php"

多谢解答, 挺管用的
