### ISSUE TITLE
N_m3u8DL-CLI_v2.6.3.exe 下载途中跳红字显示

### ISSUE THREAD

**Issue by toyou-shu** [nilaoda/N_m3u8DL-CLI#180]
LOG 2020/05/10
Save Path: D:\N_m3u8DL-CLI-V2.03\Logs
Task Start: 2020/05/10 13:36:01
Task CommandLine: "N_m3u8DL-CLI_v2.6.3.exe"  "C:\Users\Administrator\Desktop\m3u8\霹靂魔封 第57集.m3u8" --workDir "K:\霹靂魔封" --saveName "霹靂魔封 第57集" --maxThreads "100" --minThreads "10" --retryCount "300" " --enableDelAfterDone --disableDateInfo 

13:36:01.401 / (NORMAL) Start Parsing C:\Users\Administrator\Desktop\m3u8\霹靂魔封 第57集.m3u8
13:36:01.447 / (NORMAL) Parsing Content
13:36:01.447 / (NORMAL) Opening base64:
13:36:01.479 / (NORMAL) Writing Json: [meta.json]
13:36:01.635 / (NORMAL) Start Downloading
13:36:01.666 / (NORMAL) Reading Video Info
13:36:01.837 / (NORMAL) PID 0x100: Video h264 (High), yuv420p(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc
13:36:01.837 / (NORMAL) PID 0x101: Audio aac (LC), 48000 Hz, stereo, fltp, 126 kb/s
13:36:13.564 / (ERROR) DOWN: The operation has timed out https://d2p41mmvclsfdv.cloudfront.net/V201811DPM057/1920x1080/segment-209.ts
13:36:23.724 / (ERROR) DOWN: The operation has timed out. https://d2p41mmvclsfdv.cloudfront.net/V201811DPM057/1920x1080/segment-017.ts
13:36:40.971 / (ERROR) DOWN: The operation has timed out. https://d2p41mmvclsfdv.cloudfront.net/V201811DPM057/1920x1080/segment-180.ts
13:36:54.200 / (ERROR) *Padding is invalid and cannot be removed.*

Padding is invalid and cannot be removed.后闪退

**Comment by toyou-shu** [comment]
![QQ图片20200510135307](https://user-images.githubusercontent.com/31024780/81491861-9c7ef500-92c5-11ea-84cf-b8f9cc57f278.png)

**Comment by nilaoda** [comment]
key可能有问题（也许只能解密一部分）

**Comment by toyou-shu** [comment]
> key可能有问题（也许只能解密一部分）
我跳过闪退得方法是，全选然后就不会再闪退就等下载器强行下载完毕！
![9DCMTDHX94)E5PP9R@E)K$B](https://user-images.githubusercontent.com/31024780/81493109-2df36480-92d0-11ea-96d0-97cb7d86dc23.png)
