### ISSUE TITLE
怎么以最高分辨率下载？

### ISSUE THREAD

**Issue by atjjme** [nilaoda/N_m3u8DL-CLI#181]
虽然下载时显示“已自动选择最高分辨率”，但下载下来是低分辨率的，大小也只有一半左右
例如下面这个链接：本来是1G多，下载后只有600M多
HD1280高清国语中字版$https://xigua-cdn.haima-zuida.com/20200416/6099_262b1ab9/index.m3u8

**Comment by nilaoda** [comment]
下载器是根据master m3u8中的平均码率自动选择最高清晰度的

**Comment by atjjme** [comment]
没太懂，服务器中m3u8可下载的最高清晰度吗？
有办法提高一下吗

**Comment by nilaoda** [comment]
意思就是如果下载的不是最高清晰度，说明该m3u8里关于码率的描述有误

**Comment by atjjme** [comment]
我找了个1080的视频，找到源，倒是也能下载，或许是源的问题
