### ISSUE TITLE
Download from WETV

### ISSUE THREAD

**Issue by zackmark29** [nilaoda/N_m3u8DL-CLI#185]
Hi sir Nilaoda,

Is it possible to download from wetv with just a link of the video not the m3u8 link?
Because I can't find the m3u8 link from developer tool.

Or any chance or tool to get the m3u8 link?

**Comment by nilaoda** [comment]
```js
javascript:var a=prompt(PLAYER._DownloadMonitor.context.dataset.title,PLAYER._DownloadMonitor.context.dataset.ckc?PLAYER._DownloadMonitor.context.dataset.currentVideoUrl:PLAYER._DownloadMonitor.context.dataset.currentVideoUrl.replace(/:.*qq.com/g,"://defaultts.tc.qq.com/defaultts.tc.qq.com"));
```

**Comment by zackmark29** [comment]
Wooooow I've been looking for this script.
Now I know the scripts from this site is all yours
https://www.avdll.com/view/3054.html

Thank you so much Nilaoda.

**Comment by zackmark29** [comment]
Nilaoda could you help me create script for this link?
I'm trying to modify your script but can't success

https://iwantnow-vh.akamaihd.net/i/c/dolceamore/20160215/20160215-dolceamore-hd-,150000,300000,500000,800000,1000000,1300000,1500000,.mp4.csmil/master.m3u8?hdnea=ip=110.54.247.159~exp=1589528097~acl=/*~hmac=eabd2e090f1559403f04394ecb9aa8922137a710ae53f15d5ee7abfefbaddfe7

**Comment by jeniferlevy** [comment]
i have tool that can download full series in single click

**Comment by PSXJowie** [comment]
@jeniferlevy Do you mind share that tool with me? Thanks in advance.

**Comment by nilaoda** [comment]
> @jeniferlevy Do you mind share that tool with me? Thanks in advance.

https://github.com/nilaoda/Blog/discussions/28
