### ISSUE TITLE
爱奇艺m3u8链接下载提示文件读取错误

### ISSUE THREAD

**Issue by YFTX2015** [nilaoda/N_m3u8DL-CLI#190]
![屏幕截图(1)](https://user-images.githubusercontent.com/12757305/83339106-f3904c80-a2fc-11ea-8cfd-a7a859d35557.png)
如图
[2020-05-31_05-08-27.log](https://github.com/nilaoda/N_m3u8DL-CLI/files/4706516/2020-05-31_05-08-27.log)
所示，
![屏幕截图(2)](https://user-images.githubusercontent.com/12757305/83339160-9fd23300-a2fd-11ea-8452-c2cda389aac4.png)
下载不了，用很萌M3U8下载器则能正常下载，因此排除是爱奇艺M3U8链接的问题。

**Comment by toyou-shu** [comment]
他下载器没问题的，
![3](https://user-images.githubusercontent.com/31024780/83351820-dc437480-a379-11ea-8159-b70e2bb5e6c4.png)
![QQ图片20200531195902](https://user-images.githubusercontent.com/31024780/83351797-9edee700-a379-11ea-9a47-b2a6b262ccf0.png)
![QQ图片20200531200002](https://user-images.githubusercontent.com/31024780/83351798-a2726e00-a379-11ea-99f9-b377b59e8207.png)

**Comment by YFTX2015** [comment]
我这边还是不得行，我是用Getvideo获取的M3U8链接，我不晓得你是用啥子工具获取的
