### ISSUE TITLE
用txt批量下载的时候如何修改saveName

### ISSUE THREAD

**Issue by hrj5032188** [nilaoda/N_m3u8DL-CLI#191]
通过SimpleG去下载一个txt里面的多个视频的时候
软件应该是自动默认了url作为文件名?
接下来就报错说文件名太长
那么如何在txt中设置每个文件的saveName

**Comment by nilaoda** [comment]
在txt中，英文逗号前会被识别为标题。
```
name1,http://
name2,http://
```
