### ISSUE TITLE
How to make sure the downloader go through socks5 or http/https as proxy when using shadowsocks/v2ray in PAC mode?

### ISSUE THREAD

**Issue by catshitz** [nilaoda/N_m3u8DL-CLI#192]
Put this into "启动参数" of N_m3u8DL-CLI-SimpleG.exe, would that work?
`--proxy socks5://127.0.0.1:1080`
or is threre a update version with new option of this down below would be needed?
socket = "socks5://127.0.0.1:1080"

**Comment by nilaoda** [comment]
Can't customize proxy, the program will use the system's proxy(HTTP) settings.

**Comment by nilaoda** [comment]
Future versions will try to add custom proxy functions.

**Comment by sino1641** [comment]
> Future versions will try to add custom proxy functions.

Also looking forward to it! 
Much thx for your great work!
