### ISSUE TITLE
使用java程序“Runtime.getRuntime().exec(cmd);”调用时出错

### ISSUE THREAD

**Issue by MineYuanlu** [nilaoda/N_m3u8DL-CLI#195]
![图片](https://user-images.githubusercontent.com/38997444/84029832-9d3ea000-a9c5-11ea-9766-971950916d8e.png)

**Comment by MineYuanlu** [comment]
未经处理的异常:  System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.IO.IOException: 句柄无效。

   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.Console.set_CursorVisible(Boolean value)
   在 N_m3u8DL_CLI.NetCore.Program.Main(String[] args)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   在 System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 Main(String[] )

**Comment by nilaoda** [comment]
有一段java的demo吗？我调试看看

**Comment by MineYuanlu** [comment]
我改了，原来就是直接在eclipse里面调用，我认为问题是这个下载器会修改控制台上的文字，而eclipse是不支持的。

**Comment by MineYuanlu** [comment]
/**
	 * 下载视频
	 * 
	 * @param toolPath  下载器工具路径
	 * @param videoUrl  视频地址
	 * @param outDir    输出文件夹
	 * @param outName   输出文件名
	 * @param append    额外数据
	 * @param summonBat 是否仅生成下载脚本(不实际执行下载)
	 * @param extra     生成脚本时在文件内额外添加的数据
	 * @throws IOException IO错误(生成脚本/执行下载)
	 */
	private static void downloadVideo(String toolPath, String videoUrl, String outDir, String outName, String append,
			boolean summonBat, IOConsumer<FileOutputStream> extra) throws IOException {
		val cmds = new String[] { //
				"cmd.exe /C start /min \"vido download" + RANDOM.nextInt() + '"', //
				__ToCmdPath(toolPath), __ToCmdPath(videoUrl), //
				"--workDir", __ToCmdPath(outDir), //
				"--saveName", outName, //
				"--retryCount", "9999", //
				"--enableDelAfterDone", //
				append == null ? "" : append
				//
		};
		val cmd = String.join(" ", cmds);
		if (summonBat){
			val f = new File(outDir, outName + ".cmd");
			f.getParentFile().mkdirs();
			try (val out = new FileOutputStream(f)){
				val c = Charset.forName("GBK");
				out.write(cmd.getBytes(c));
				out.write("\r\ndel %0".getBytes(c));
				if (extra != null) extra.accept(out);
			}
		} else{
			Runtime.getRuntime().exec(cmd);
		}
	}

**Comment by MineYuanlu** [comment]
/**
	 * 下载视频
	 * 
	 * @param toolPath  下载器工具路径
	 * @param videoUrl  视频地址
	 * @param outDir    输出文件夹
	 * @param outName   输出文件名
	 * @param append    额外数据
	 * @param summonBat 是否仅生成下载脚本(不实际执行下载)
	 * @param extra     生成脚本时在文件内额外添加的数据
	 * @throws IOException IO错误(生成脚本/执行下载)
	 */
	private static void downloadVideo(String toolPath, String videoUrl, String outDir, String outName, String append,
			boolean summonBat, IOConsumer<FileOutputStream> extra) throws IOException {
		val cmds = new String[] { //
				"cmd.exe /C start /min \"vido download\"", //
				__ToCmdPath(toolPath), __ToCmdPath(videoUrl), //
				"--workDir", __ToCmdPath(outDir), //
				"--saveName", outName, //
				"--retryCount", "9999", //
				"--enableDelAfterDone", //
				append == null ? "" : append
				//
		};
		val cmd = String.join(" ", cmds);
		if (summonBat){
			val f = new File(outDir, outName + ".cmd");
			f.getParentFile().mkdirs();
			try (val out = new FileOutputStream(f)){
				val c = Charset.forName("GBK");
				out.write(cmd.getBytes(c));
				out.write("\r\ndel %0".getBytes(c));
				if (extra != null) extra.accept(out);
			}
		} else{
			Runtime.getRuntime().exec(cmd);
		}
	}

**Comment by MineYuanlu** [comment]
cmd.exe /C start /min "title" downloader.exe url 
就可以正常运行了，这样会打开一个新的窗口

但是我推荐，添加一个参数：--noGui  关闭掉控制台输出
