### ISSUE TITLE
[Feather request] Folders amount downloads

### ISSUE THREAD

**Issue by catshitz** [nilaoda/N_m3u8DL-CLI#197]
Thx, but what if I have several m3u8 folders with the same names of files in it but different folder names like this down below,
fo123
> u.m3u8
key.bin
info.json

ld456
> u.m3u8
key.bin
info.json

er789
> u.m3u8
key.bin
info.json

...

How to drag multiple folders into "M3U8地址" in order to download them in sequence please?

**Comment by nilaoda** [comment]
Now, you can download multiple m3u8 files in sequence with `N_m3u8DL-CLI-SimpleG.exe`. You can find this program at [here](https://github.com/nilaoda/N_m3u8DL-CLI/releases).

First, put all `.m3u8` files into a folder, then drag this folder to `M3U8地址` textbox. After that, click the `GO` button. The program will read all m3u8 files in the folder and generate a batch file`(.bat)` for batch download.

---

OR, you can create a new text file`(.txt)`, and write something like this:
(Custom filename)
```
FILENAME1,URL1
FILENAME2,URL2
...
```
OR
```
URL1
URL2
URL3
...
```

**Comment by catshitz** [comment]
Thx, but what if I have several m3u8 folders with the same list of filenames in it but different folder names like this down below,
folder1
`0.m3u8
key.bin
playinfos.json`
folder2
`0.m3u8
key.bin
playinfos.json`
folder3
...
How am I supposed to drag multiple folders in "M3U8地址" in order to download them in sequence please?
