### ISSUE TITLE
下载到最后 无法合并文件

### ISSUE THREAD

**Issue by yanglei9999** [nilaoda/N_m3u8DL-CLI#198]
版本: N_m3u8DL-CLI_v2.6.3
问题: 所有 ts 块都下载完成了, 到合并的时候就闪退了 调用不了 ffmpeg 合并文件
 
问题原因: 因为用的是虚拟机win10 , 所以 文件的执行路径是: "\\Mac\Home\Downloads\N_m3u8DL-CLI_v2.6.3_with_ffmpeg_and_SimpleG" , 导致下载可以, 但是 ffmpeg 合并失败 (试过把 ffmpeg 安装在Windows环境变量里)

解决方法: 无奈之下找个真机pc 做测试, 一切正常, 推测是路径问题, 随后把文件 copy 到虚拟机 c 盘根目录, 文件的执行路径为 "c:\N_m3u8DL-CLI_v2.6.3_with_ffmpeg_and_SimpleG", 之后一切正常!!

不知道可否解决此问题?

**Comment by nilaoda** [comment]
手动在cmd窗口执行下载，看看闪退的时候有什么报错么？

**Comment by yanglei9999** [comment]
手动执行过, 也是闪退, 并且没有任何,提示信息

**Comment by yanglei9999** [comment]
估计是路径问题导致

**Comment by nilaoda** [comment]
我的意思是手动打开cmd，输入命令后回车执行，这样闪退的信息能看到。

**Comment by yanglei9999** [comment]
cmd 好像 识别不了 \\Mac\Home\Downloads\ 这种路径格式

![image](https://user-images.githubusercontent.com/5676213/87765521-7e47ef00-c84a-11ea-8931-76b1a63cf229.png)
