### ISSUE TITLE
本地m3u8識別為直播

### ISSUE THREAD

**Issue by tamplin** [nilaoda/N_m3u8DL-CLI#20]
本地m3u8格式如下
`#EXTM3U`
`0.ts`
`1.ts`
`2.ts`
`3.ts`
`....`
使用自定义baseurl后报错

>20:08:56.619_ 开始解析地址...
20:08:56.638 获取m3u8内容
20:08:56.639 解析m3u8内容
20:08:56.650 写出meta.json
20:08:56.693 文件时长：00m00s
20:08:56.694 总分片：0, 已选择分片：0
20:08:56.694 识别为直播流, 开始录制
20:08:56.700 Waiting...
20:09:04.707 获取m3u8内容
20:09:12.708 获取m3u8内容
20:09:20.709 获取m3u8内容
20:09:28.709 获取m3u8内容
20:09:36.710 获取m3u8内容
20:09:44.711 获取m3u8内容
20:09:52.712 获取m3u8内容
20:10:00.712 获取m3u8内容
20:10:08.712 获取m3u8内容
20:10:16.713 获取m3u8内容
20:10:24.714 获取m3u8内容
20:10:32.714 获取m3u8内容
20:10:40.715 获取m3u8内容
20:10:48.715 获取m3u8内容
20:10:56.716 获取m3u8内容
20:11:04.717 获取m3u8内容
20:11:12.717 获取m3u8内容

**Comment by nilaoda** [comment]
最后一行需要`#EXT-X-ENDLIST`
