### ISSUE TITLE
运行N_m3u8DL-CLI_v2.6.3不能粘贴

### ISSUE THREAD

**Issue by kjtkingwin** [nilaoda/N_m3u8DL-CLI#200]
你好，运行N_m3u8DL-CLI_v2.6.3不能粘贴，不知什么原因，谢谢

**Comment by nilaoda** [comment]
在win10下可以直接粘贴，旧版系统可以右键标题栏-编辑-粘贴。

**Comment by kjtkingwin** [comment]
您好，为什么有此付费的网课不能下载（我已付费），试过多个版本一样。谢谢

在 2020年6月22日星期一，nilaoda ***@***.***> 写道：
