### ISSUE TITLE
无法下载qiqiuyun的视频

### ISSUE THREAD

**Issue by u-u-u-u-u-u** [nilaoda/N_m3u8DL-CLI#205]
视频页面:需要付费,我已经购买了,因为我购买的太晚了过一段时间就会下架视频,我想下载下来
但是访问视频文件网址不需要登录
m3u8的url:每次刷新视频播放页都会变化
key:每次访问key的url都会变化

下面是在视频播放页请求m3u8网址的Response:
虽然每次m3u8的url都是不同的,但是Response里每个片段的网址都是相同的
每次刷新,每个片段的key的url都会变化
key的url每次访问得到的key都是不同的

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:11
#EXT-X-ALLOW-CACHE:YES
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x044306558ec6ad5c640d3b7e46f926cf
#EXTINF:10.080,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_0_ehls_cb9bfe[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xc7fc3e457c82ec1f8b23229cab9d8fbc
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_1_ehls_6c67ba[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x887d58f1013dd111a09ad7c0e95df898
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_2_ehls_7b51aa[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x221aa76d6a65169480f00043824df606
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_3_ehls_e263af[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x15119e041c503b78633531da998a6c93
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_4_ehls_902760[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x00b2243470c0e6efb54f75ece7cf62b6
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_5_ehls_44d045[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xf088a7d440f3db61a32080a46f85e184
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_6_ehls_81764e[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x9dc4901bf3f1cef31cc913b9f51974f8
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_7_ehls_e41ab0[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x34b38232cb7b2f5597d37585c38e102b
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_8_ehls_c93014[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x7b1740b3faae77144040f378aa34e6ac
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_9_ehls_23a57a[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xfa40f0e6812f10a3146a6ba0283dbba3
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_10_ehls_76f8e3[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x16b30ebb8f6cffd7c6ca90ad234ddf19
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_11_ehls_9defba[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x58f5f014d91aeb33b18e234ad4649150
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_12_ehls_e06f5e[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x335be8909e4d66ec8f3494deb77a91ef
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_13_ehls_1132e9[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xc0e1b42af4a53dfef7fc777fad3bf8f3
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_14_ehls_053ae7[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x0df1bf240286346adcf46843d390d411
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_15_ehls_c6f32f[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x306cdb974ae9c2b3e9352eb4601f03ec
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_16_ehls_eb6e15[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x50d18b7508ce5a5863238addbeaaf5f6
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_17_ehls_3bf163[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xf62e4531d2b876c3d526f1fa1e47451a
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_18_ehls_48fae9[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x5ce8609efaa0cc01a450706251e5c207
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_19_ehls_f74462[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xa9d4e20a29575536dd0174ce9761f093
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_20_ehls_4300a2[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xe62de19bff6af61e3a2a82d1c35e0342
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_21_ehls_c83a52[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x084e6829ab0c2195ab02d35383de5548
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_22_ehls_ba2212[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xa6852ada662ac62572817c8a42ec637c
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_23_ehls_5bb3f2[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x8810b44cd68c4cbff1d8c613b71669be
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_24_ehls_789cb5[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xc22f3d496c4819be7c3fec59e59ac151
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_25_ehls_bb2a8d[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xe515f3c56efe625a8bb4fd4ae421dee5
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_26_ehls_28d409[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xb1c68905ed06fee0a3dc1a9efe0d0782
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_27_ehls_a0f000[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x5ebfaf111f6eb70d3731fe85c8ac0fe0
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_28_ehls_a9595e[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xe89956f3f867ad16a906b30bd8e722c8
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_29_ehls_bdf318[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x01a71942f105bcf9f1f19bf766a8f50a
#EXTINF:10.080,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_30_ehls_3cb48c[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xffac970f662f52442ff8d58b723b6f64
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_31_ehls_3fa103[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xfc04265af43fa2ac41e194923db6c7dd
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_32_ehls_ee06cb[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x3968d1780dfde35f1e5d15b85b68004a
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_33_ehls_18ad6b[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x2174dfc3ac044e4e80a3cef0df3f101c
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_34_ehls_ee35fa[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x4e2e154c14f8a9f39bedb7f83ad8aed9
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_35_ehls_ffe247[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x03f7c81cf194e7e634594901dda0c06f
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_36_ehls_3f0592[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x5afd3677f801983a480d7f3d9073eb2a
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_37_ehls_394223[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x62447750cfcbc1286f77c8ecf6709b71
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_38_ehls_60f537[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x2092f9ace8cc0a53ea67fd0509b02541
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_39_ehls_2ef76e[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x9ae3c1c9e9130a13f0b53e0bc002b712
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_40_ehls_a57c0d[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x55e604e85e9d2df880eefe2fc3dcc1af
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_41_ehls_1bd154[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x012bf8bf996bf2139106733579b93157
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_42_ehls_6353e2[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xdc4275506cc0c1e2d51f585ad804af73
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_43_ehls_11acc3[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x8dc13e7aba517b78a4daf564af4801d0
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_44_ehls_c46a8c[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x1d40c62a9919303165146c0f5eaddaf3
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_45_ehls_29c137[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x11aa743c81537e10795546b343f6ffdb
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_46_ehls_e5cbb1[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xbc7ba8bbaecdb00e6c5a2c554078ca53
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_47_ehls_3ded5a[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x2b61eee3639146d025cafa8cf8889898
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_48_ehls_604468[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x4f1a13f10b03994777d58cd97f5929db
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_49_ehls_44eb7d[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x51d514bc05125f72d6c2d73cacdf3b6e
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_50_ehls_ac1ebb[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x397da1119766f15f358b9963b22f9489
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_51_ehls_08c3a0[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x6a1945c1d19a012513d90200d6bc49c1
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_52_ehls_19f133[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xff8b48b547ba7a6bef9c2cdc67ceb638
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_53_ehls_baa847[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x5791e57cc35e2ead18dec09ceac01b2e
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_54_ehls_4e2797[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x2b75ccc1bdfd57e4f89f1407c5c203f1
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_55_ehls_0a660e[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x2b7d7b2708ba9e4d83a59577f195a59d
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_56_ehls_8e17d1[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0xa4318f37c05fcc82fbfac6748f0aa7a9
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_57_ehls_d863e2[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x71c10096df5c43737536cc2f62373c65
#EXTINF:10.000,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_58_ehls_8e1e5e[/url]
#EXT-X-KEY:METHOD=AES-128,URI="http://www.jingtongxue.com/hls/4204/clef/cae8d216bf3011ea9f3100163e2cf5b6",IV=0x4608f44b2051ea98492296a53b10db45
#EXTINF:3.680,
[url]http://ese4a0b9c0d3sq-pub.pub.qiqiuyun.net/40903/cf57ca2015424542ba913e176d9d9512/lhdBGdaGgKT0gwxe-merged-shd_seg_59_ehls_442c48[/url]
#EXT-X-ENDLIST

**Comment by nilaoda** [comment]
查看此文档，获取会有帮助。

https://raw.githubusercontent.com/nilaoda/N_m3u8DL-CLI/2.4.9/docs/qiqiuyun.html
