### ISSUE TITLE
从下载的release包中发现特洛伊木马

### ISSUE THREAD

**Issue by volnet** [nilaoda/N_m3u8DL-CLI#206]
Windows安全中心给出来的提示：

下载：N_m3u8DL-CLI_v2.6.3_with_ffmpeg_and_SimpleG.zip

已检测到威胁：Trojan:Win32/Occamy.AA
警报级别：严重
日期：2020/7/6 13:53
类别：特洛伊木马
详细信息：这个程序很危险，而且执行来自攻击者的命令。

**Comment by zhangyz1997** [comment]
估计是误报，我已经提交样本了

**Comment by nilaoda** [comment]
> 估计是误报，我已经提交样本了
> 更新：已经[解除误报](https://www.microsoft.com/en-us/wdsi/submission/9ce1e5cd-12f8-44a5-8cf1-874f85ca4798)

感谢

**Comment by nilaoda** [comment]
https://www.microsoft.com/en-us/wdsi/submission/8271d6c5-9155-45f1-a1e3-1f1700991319

**Comment by nilaoda** [comment]
2.7.1:
https://www.microsoft.com/en-us/wdsi/submission/e25cea3d-389b-42dc-a032-96bffabd6d43

**Comment by ccicnce113424** [comment]
360有类似的误报

**Comment by nilaoda** [comment]
2.7.2:  
https://www.microsoft.com/en-us/wdsi/submission/33c7e73d-9254-4451-8f7b-a60c045eb16b

**Comment by nilaoda** [comment]
1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

**Comment by iamv7** [comment]
2.7.4 having same issue on Windows Defender

**Comment by iflyun** [comment]
现在会报 Trojan:Win32/CryptInject!ml 木马

**Comment by nilaoda** [comment]
2.8.5
https://www.microsoft.com/en-us/wdsi/submission/78804b2d-b40a-4294-b367-a17e2de541bb

**Comment by huluxia** [comment]
确实报毒

**Comment by nekomiao123** [comment]
N_m3u8DL-CLI_v2.9.3_with_ffmpeg_and_SimpleG.zip    Google浏览器直接报毒不让下载

**Comment by nilaoda** [comment]
> N_m3u8DL-CLI_v2.9.3_with_ffmpeg_and_SimpleG.zip Google浏览器直接报毒不让下载

之后更新个版本应该就没事了

**Comment by metalbug** [comment]
N_m3u8DL-CLI_v2.9.5.exe
报毒

**Comment by nilaoda** [comment]
> N_m3u8DL-CLI_v2.9.5.exe
> 报毒

我也没辙了 不放心的话只能自己下载源码编译

**Comment by CocosGames** [comment]
确认是误报

**Comment by moshengren88** [comment]
2.9.7报毒

**Comment by moshengren88** [comment]
> 2.9.7 下载N_m3u8DL-CLI_v2.9.7_with_ffmpeg_and_SimpleG.zip 报毒
