### ISSUE TITLE
之前能下载，现在提示地址错误了。

### ISSUE THREAD

**Issue by JayaHuang** [nilaoda/N_m3u8DL-CLI#207]
在某个网站，前段时间可以下载，现在下载提示“地址错误”；然后我估计是网站采取措施了，我就尝试把请求头的cookies复制过来。地址正确了，但还是下载不了，在下载首分片的时候，提示“读取文件信息...Error in reading file”
![image](https://user-images.githubusercontent.com/18739970/86810931-f88cac80-c0af-11ea-871a-073edd2b79e2.png)

这个有解决方案吗？

**Comment by TsungDeng** [comment]
用网页播放一个该站的视频，F12查看缓存TS的请求头看看都有哪些，然后在N_m3u8DL-CLI的请求头里面附上这些请求头就可以了，一般关键的请求头有Host、Referer和User-Agent这三个。如果是某讯视频的话，就需要带上以上三个

**Comment by TsungDeng** [comment]
总之，我的套路就是当N_m3u8DL-CLI不伪装请求头不能下载的时候，就用chrome内核浏览器的F12大法找请求头，这个不算最佳。最佳的方法是：下载该视频站的官方客户端，用这个客户端随意观看或下载一个视频，然后用影音神探或者findller对其进行嗅探，查看嗅探出来的链接中m3u8、TS或者mp4的请求头，记录在一个记事本中，以后在N_m3u8DL-CLI的请求头中附上这些请求头就可以伪装成官方客户端来下载视频了，至今我还没有遇到不能下载的视频。举个例子：某讯视频官方客户端的请求头是这样子的“Host: domain name|Referer: url|User-Agent: QQLive/1.3.68.360”，呵呵

**Comment by wallaceqwang** [comment]
> 总之，我的套路就是当N_m3u8DL-CLI不伪装请求头不能下载的时候，就用chrome内核浏览器的F12大法找请求头，这个不算最佳。最佳的方法是：下载该视频站的官方客户端，用这个客户端随意观看或下载一个视频，然后用影音神探或者findller对其进行嗅探，查看嗅探出来的链接中m3u8、TS或者mp4的请求头，记录在一个记事本中，以后在N_m3u8DL-CLI的请求头中附上这些请求头就可以伪装成官方客户端来下载视频了，至今我还没有遇到不能下载的视频。举个例子：某讯视频官方客户端的请求头是这样子的“Host: domain name|Referer: url|User-Agent: QQLive/1.3.68.360”，呵呵

如果没有视频网站没客户端呢？尝试加了两个请求头，基本都是下载不成功，偶尔能成功一次。。。F12看有token啥的加密

**Comment by TsungDeng** [comment]
> > 总之，我的套路就是当N_m3u8DL-CLI不伪装请求头不能下载的时候，就用chrome内核浏览器的F12大法找请求头，这个不算最佳。最佳的方法是：下载该视频站的官方客户端，用这个客户端随意观看或下载一个视频，然后用影音神探或者findller对其进行嗅探，查看嗅探出来的链接中m3u8、TS或者mp4的请求头，记录在一个记事本中，以后在N_m3u8DL-CLI的请求头中附上这些请求头就可以伪装成官方客户端来下载视频了，至今我还没有遇到不能下载的视频。举个例子：某讯视频官方客户端的请求头是这样子的“Host: domain name|Referer: url|User-Agent: QQLive/1.3.68.360”，呵呵
> 
> 如果没有视频网站没客户端呢？尝试加了两个请求头，基本都是下载不成功，偶尔能成功一次。。。F12看有token啥的加密

请求头是“Host: domain name|Referer: url|User-Agent: QQLive/1.3.68.360”这样子的，其中"domain name"是m3u8地址的域名，“url”是视频播放页的地址，“QQLive/1.3.68.360”就是客户端版本号，我抓包得到的这个。另外腾讯客户端现在限制非VIP用户的下载限制得非常厉害，白天基本上只能成功下载一两集，晚上12点的样子会放开限制，放开限制后可以满速下载，我有一次一次性下载了3个剧集200多G。请低调下载，别到处去嚷嚷

**Comment by TsungDeng** [comment]
> > 总之，我的套路就是当N_m3u8DL-CLI不伪装请求头不能下载的时候，就用chrome内核浏览器的F12大法找请求头，这个不算最佳。最佳的方法是：下载该视频站的官方客户端，用这个客户端随意观看或下载一个视频，然后用影音神探或者findller对其进行嗅探，查看嗅探出来的链接中m3u8、TS或者mp4的请求头，记录在一个记事本中，以后在N_m3u8DL-CLI的请求头中附上这些请求头就可以伪装成官方客户端来下载视频了，至今我还没有遇到不能下载的视频。举个例子：某讯视频官方客户端的请求头是这样子的“Host: domain name|Referer: url|User-Agent: QQLive/1.3.68.360”，呵呵
> 
> 如果没有视频网站没客户端呢？尝试加了两个请求头，基本都是下载不成功，偶尔能成功一次。。。F12看有token啥的加密

有token的可以尝试使用IDM来进行下载，但是必须得安装IDM的chrome扩展才能正常解析，播放视频调整到需要的清晰度，然后把鼠标放在播放区域出现下载按钮点击下载就可以了。另外，最好先把IDM的UA伪装成浏览器，浏览器正确的User-Agent通过F12可以看到，比如360极速浏览器的User-Agent就是“Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36”，^-^

**Comment by TsungDeng** [comment]
> > 总之，我的套路就是当N_m3u8DL-CLI不伪装请求头不能下载的时候，就用chrome内核浏览器的F12大法找请求头，这个不算最佳。最佳的方法是：下载该视频站的官方客户端，用这个客户端随意观看或下载一个视频，然后用影音神探或者findller对其进行嗅探，查看嗅探出来的链接中m3u8、TS或者mp4的请求头，记录在一个记事本中，以后在N_m3u8DL-CLI的请求头中附上这些请求头就可以伪装成官方客户端来下载视频了，至今我还没有遇到不能下载的视频。举个例子：某讯视频官方客户端的请求头是这样子的“Host: domain name|Referer: url|User-Agent: QQLive/1.3.68.360”，呵呵
> 
> 如果没有视频网站没客户端呢？尝试加了两个请求头，基本都是下载不成功，偶尔能成功一次。。。F12看有token啥的加密

如果方便的话，可以提供网站地址，我看看怎样才能下载它，邮箱dehooy#163.com，把#替换为@

**Comment by mozhenshis** [comment]
解决了吗
