### ISSUE TITLE
qiqiuyun好像更新了 用https://raw.githubusercontent.com/nilaoda/N_m3u8DL-CLI/2.4.9/docs/qiqiuyun.html此方法无法获取到m3u8

### ISSUE THREAD

**Issue by u-u-u-u-u-u** [nilaoda/N_m3u8DL-CLI#210]
qiqiuyun好像更新了 用https://raw.githubusercontent.com/nilaoda/N_m3u8DL-CLI/2.4.9/docs/qiqiuyun.html此方法无法获取到m3u8

我原来的方法:
1.在课程页面搜索data-url,进入data-url的值的网页,进入的网页就是视频播放页
2.在进入的网页再搜索data-url,其值就是m3u8的网址

今天再尝试就不可以了,在第二个网页搜索data-url是空值

**Comment by nilaoda** [comment]
周末的有空的时候我看下

**Comment by u-u-u-u-u-u** [comment]
好的,谢谢

**Comment by u-u-u-u-u-u** [comment]
好的,谢谢

**Comment by RiotGamesU** [comment]
> 周末的有空的时候我看下

大佬 有头绪了么
