### ISSUE TITLE
能否编译一个linux的版本呢？

### ISSUE THREAD

**Issue by lbcake** [nilaoda/N_m3u8DL-CLI#211]
想要一个linux版本的 大佬  可否编译一个

**Comment by nilaoda** [comment]
Linux版本将在遥远的未来出现。。。

**Comment by railannad** [comment]
已经够遥远了，今天还是没有。。（哭了）

**Comment by nilaoda** [comment]
> 已经够遥远了，今天还是没有。。（哭了）

会逐步迁移到.net5 但是会大改

**Comment by lbcake** [comment]
> > 已经够遥远了，今天还是没有。。（哭了）
> 
> 会逐步迁移到.net5 但是会大改
老哥  很久不更新了啊。 有时候录制直播 会缺片段 好像这个bug还没有解决。   

我环境是win端的  直接录制m3u8的直播源 录制出来  有时候会缺片段  希望可以在这方面在优化一下
