### ISSUE TITLE
下载出现地址无效如何解决？

### ISSUE THREAD

**Issue by wallaceqwang** [nilaoda/N_m3u8DL-CLI#218]
之前用下载视频没任何问题，地址是通过猫抓插件嗅探到的，现在同样的方法却出现地址无效（具体如图示）是什么原因呢？该如何克服呀。。。 求大神解答，谢谢
![image](https://user-images.githubusercontent.com/34992985/88280471-7390cc80-cd18-11ea-9077-3d7e83890f1d.png)

**Comment by nilaoda** [comment]
如果是同一个网站的话，应该是该网站升级了防盗链机制。尝试加入一些请求头进行下载。可以在f12中过滤`m3u8`字样看看。

**Comment by wallaceqwang** [comment]
实在小白，请问老大请求头具体怎么找呢？

**Comment by wallaceqwang** [comment]
> 如果是同一个网站的话，应该是该网站升级了防盗链机制。尝试加入一些请求头进行下载。可以在f12中过滤`m3u8`字样看看。

实在小白，请问老大请求头具体怎么找呢？

**Comment by nilaoda** [comment]
在GUI的请求头部分写入如下内容即可下载：
```
user-agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36
```

![image](https://user-images.githubusercontent.com/20772925/88386171-6fc97c80-cde2-11ea-8961-0187c15b2ba4.png)
