### ISSUE TITLE
English Version!

### ISSUE THREAD

**Issue by arbarbosa1979** [nilaoda/N_m3u8DL-CLI#219]
Is English available? And if it is available, how do I select it?

`SUPPORTED MULTIPLE LANGUAGE: zh-CN zh-TW en-US`

**Comment by nilaoda** [comment]
Should be automatically switched.

**Comment by arbarbosa1979** [comment]
Only Chinese characters appear in cmd here. It doesn't stop me from using it, but I'm not fluent in Chinese.

Any prediction of when the GUI will be translated?

**Comment by nilaoda** [comment]
> Only Chinese characters appear in cmd here. It doesn't stop me from using it, but I'm not fluent in Chinese.
> 
> Any prediction of when the GUI will be translated?

So, whats your language now? Do you know your LCID?

**Comment by arbarbosa1979** [comment]
Spanish is my main language, but I use windows in English.
