### ISSUE TITLE
下载过程中自动暂停了，

### ISSUE THREAD

**Issue by bnm14744** [nilaoda/N_m3u8DL-CLI#22]
![image](https://user-images.githubusercontent.com/36909175/65832791-24962880-e2fb-11e9-8ce3-6b030d848458.png)
这种情况怎么办？只能重新下载？还是可以续传？

**Comment by nilaoda** [comment]
使用相同名字可以续传。其实这种情况不是暂停了，是你不小心选择了某个字符导致控制台被阻塞了，通常点一下右键就恢复了

**Comment by bnm14744** [comment]
发现按一下 回车键就开启了 重试
