### ISSUE TITLE
某酷VIP视频灰屏

### ISSUE THREAD

**Issue by yuzukiss** [nilaoda/N_m3u8DL-CLI#220]
有VIP账号，写了请求头（ser-Agent Host Referer）也正常下载正常合并了（音频和视频没混流），但是除了开头之外后面所有画面都是灰屏。请问有救吗

**Comment by yuzukiss** [comment]
补充一下，下非VIP但优酷独播的也是灰屏

**Comment by nilaoda** [comment]
请阅读readme。不支持优酷视频。
