### ISSUE TITLE
ts文件合并错乱

### ISSUE THREAD

**Issue by iceshell** [nilaoda/N_m3u8DL-CLI#221]
如果ts分片有120，121，122......1000,1001,1002,软件合并时会优先把1000，1001，1002这些分片软件放到最开头，合并后文件最后面的内容跑到最开头，麻烦修复这个问题

**Comment by nilaoda** [comment]
为什么会有这种文件？程序生成的应该是0120, 0121, 0122......1000,1001,1002这样呀

**Comment by nilaoda** [comment]
@iceshell
