### ISSUE TITLE
Unable to download closed captions!

### ISSUE THREAD

**Issue by arbarbosa1979** [nilaoda/N_m3u8DL-CLI#224]
I tried to download some closed captions on the pureflix website, but the program always has this error:

`12:32:36.560 Output file #0 does not contain any stream`

It only recognizes the video and audio in the m3u8 file, but the closed captions is not recognized. Is there any way to make it work to download sub captions?

I am using this software --> **M3U8X** to download closed captions, but I would like to use only yours to do the whole process.

**Comment by nilaoda** [comment]
I’ll test if I'm free.

**Comment by nilaoda** [comment]
```
Pure Flix memberships are not yet available in your area.
```
What area can watch content? And could you send me an account name and password? nilaoda@live.com

**Comment by arbarbosa1979** [comment]
U.S.A
Proxy/VPN required if you live outside the U.S.

**Comment by nilaoda** [comment]
> I sent you the credentials in the email.
> 
> U.S.A
> Proxy/VPN required if you live outside the U.S.

ok

**Comment by nilaoda** [comment]
I have fixed some logical problems with the external audio track or subtitle track, but there is a tricky problem:

The websit's subtile's timestamps is **relative** :  

01.vtt:
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:900000,LOCAL:00:00:00.000

00:00:01.466 --> 00:00:05.466
THEME SONG: Let's
go to Pa-ha-ha-ha-ha
```
02.vtt:
```
WEBVTT
X-TIMESTAMP-MAP=MPEGTS:6300000,LOCAL:00:00:00.000

00:00:02.800 --> 00:00:05.900
The nativity is an
artistic representation
```
Now my program cannot concat such subtitles correctly. I have to re-adjust the timestamps through X-TIMESTAMP-MAP, then concat them to complete subtitle. So I plan to take time to fix this bug on Saturday or Sunday.

Thanks for your feedback.

**Comment by nilaoda** [comment]
BUG FIXED. v2.7.2.

**Comment by nilaoda** [comment]
There are still some hard to solve problems, please wait for the updated version.
