### ISSUE TITLE
下载hmvod的m3u8文件时出错。错误为：[AVBSFContext @ 000001c231da8080] Error parsing ADTS frame header!

### ISSUE THREAD

**Issue by pmoled** [nilaoda/N_m3u8DL-CLI#225]
下载hmvod的m3u8文件时出错。但是使用ffmpeg直接下载时无此错误。错误为：[AVBSFContext @ 000001c231da8080] Error parsing ADTS frame header!
m3u8地址为：https://m.anyplex.com/api/getm3u8.jsp;jsessionid=C13C5FDA07182B03E1821C1C25E0F9FA?programGuid=dba83824-01e6-4cd1-98ef-2d1d30bb6763&bitrate=middle&dserver=d3.anyplex.com

**Comment by nilaoda** [comment]
已查明，为程序在生成IV时的逻辑错误所导致。已经在最新版中修复。

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-CLI/releases/tag/2.7.2
