### ISSUE TITLE
wetv个别视频无法下载

### ISSUE THREAD

**Issue by bmw1398** [nilaoda/N_m3u8DL-CLI#228]
大佬，WETV上发现有二个视频M3U8解析后转到下载器去解析会提示出错，能帮忙看下吗？穿越火线的24/26二集
https://wetv.vip/zh-cn/play/mkrdnvmefgqck80-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF/k0034zagbaa-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF_24
https://wetv.vip/zh-cn/play/mkrdnvmefgqck80-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF/c00346qmqdj-%E7%A9%BF%E8%B6%8A%E7%81%AB%E7%BA%BF_26
出错信息：不支持SAMPLE-AES-CTR加密方式，将不被处理，且强制开启二进制合并
写出meta.json文件时长：52m00s总分片：390，已选择分片：390开始下载文件
下载MAP文件.
读取文件信息.
PID NULL:Video h264（avcl/0x31637661），none，1920x1080，25k tbr，25k tbn，50k tbc（default）
文件下载下来是花屏，碼率有16000多。另猫抓显示的320181 326002编码M3
这是新加密吗？能帮忙看看吗？谢谢

**Comment by bmw1398** [comment]
用的是WETV.EXE解析的M3地址+2.7.2版本下载器

**Comment by nilaoda** [comment]
加密
