### ISSUE TITLE
FFmpeg无法合并，貌似是key解密问题

### ISSUE THREAD

**Issue by aLuvletter** [nilaoda/N_m3u8DL-CLI#229]
[https://vod.hundun.cn/960c9a4b65994eb3895365a3577321d6/37f1942ff0b640879d9ad813558c4643-sd-encrypt-stream.m3u8?auth_key=1597575228-null-null-aa7970f11607a8a60f36ea7eafdff2b8](url)

m3u8地址如上，下载视频后无法合并

**Comment by aLuvletter** [comment]
视频是混沌大学里的视频

**Comment by jiarukai** [comment]
我也遇到了，这个m3u8文件 VLC也无法播放（无声音无图像），应该是加密了，栗子：https://vod.hundun.cn/04af9c341dd44aba8b9f9194a3a5a374/5b7e86f12a1348df9f8d7ed50bfb7fc8-7acddf6a3c754124a5ff1135605876e6-sd-encrypt-stream.m3u8?auth_key=1598546653-null-null-de826732dafb23479937b54ab3d6c44a

**Comment by nilaoda** [comment]
等周末我看下这个网站什么情况

**Comment by jiarukai** [comment]
这个m3u8文件还有有效期，现在就不能打开了，稍后我再发您新的

**Comment by nilaoda** [comment]
> 这个m3u8文件还有有效期，现在就不能打开了，稍后我再发您新的

建议邮件私发我账号密码

**Comment by nilaoda** [comment]
KEY为`r.config._sce_dlgtqredxx`。调试一下可以得到。

![image](https://user-images.githubusercontent.com/20772925/93693866-093db200-fb38-11ea-81fe-61f438444474.png)


但是解密方式和优酷的一样，所以**不考虑支持**。
