### ISSUE TITLE
气球云读取失败，一直重试

### ISSUE THREAD

**Issue by tangxunhu** [nilaoda/N_m3u8DL-CLI#23]
视频网址：http://ucourse.unipus.cn/course/1825/task/20593/show
账户：bak14000@qq.com
密码：Hon123456
分片应该是抓成功了，我看见download目录里有，
可能是需要特殊的设定，我不太了解，望解答，谢谢！
![D65938348EBEB0F83947EB61047098C0](https://user-images.githubusercontent.com/24522611/66265943-f5c70780-e850-11e9-97a0-47a87c19e9a6.png)

**Comment by nilaoda** [comment]
问题发生在目前是自动检测是否为气球云，稍后我会更新新版，加入`qncdn.edusoho.net`的识别

**Comment by nilaoda** [comment]
`2.3.3`已解决此问题。安全起见，记得修改你的账户密码 @tangxunhu

**Comment by imThree** [comment]
请问二位找到m3u8以后怎么下载的视频，我找到了Key，但是提示“非16 Bytes文件”
![image](https://user-images.githubusercontent.com/4982919/82759325-55ddde80-9e1f-11ea-9fc9-964f21eef27c.png)
