### ISSUE TITLE
M3U8地址無效

### ISSUE THREAD

**Issue by leesnow1107** [nilaoda/N_m3u8DL-CLI#235]
我想請問一下~

原本都沒問題的

突然9月開始 找到的M3U8  開始無效了 , 而且也有顯示出視頻位址

但都無法完成下載

直接在瀏覽器輸入 出現 foribben 地址遺失

該視頻網站 : HAMI

**Comment by nilaoda** [comment]
尝试置入请求头，如UA、Cookie之类的。hami我好久没下过了不知道现在什么情况

**Comment by leesnow1107** [comment]
cookie 請求頭 , 應該從哪裡下手呢?

**Comment by ownerowner** [comment]
谷歌浏览器开发者选项

**Comment by leesnow1107** [comment]
[https://imgur.com/RDkCDV9.jpg](url)

這上面有我截的 cookies 

測了 有內容 疑似 key 的東西 , 目前還是都無法使用

**Comment by nilaoda** [comment]
hami的我抽空看下吧

**Comment by leesnow1107** [comment]
get it ,

感謝幫忙

**Comment by qbabe** [comment]
@nilaoda 
我也遇到同樣問題
我有加上請求頭了但卻顯示地址無效
能不能請求幫忙告訴我哪裡出了問題
目前我的Hamivideo是有時效性的
時間到了的就不能看了
可以的話能不能請ower @nilaoda nilaoda告訴我該怎麼做?
拜託 拜託您了
謝謝


![002](https://user-images.githubusercontent.com/38503091/109038906-30ac3280-7707-11eb-8d61-2621385bccbb.jpg)
![000](https://user-images.githubusercontent.com/38503091/109038642-e7f47980-7706-11eb-8f19-a42d5e8b24ed.jpg)
![001](https://user-images.githubusercontent.com/38503091/109038664-ecb92d80-7706-11eb-8ad4-6d5fc5488ef3.jpg)


> 置入Referer即可：
> 
> ![image](https://user-images.githubusercontent.com/20772925/92742698-7754dd00-f3b2-11ea-99c6-f91e6cbf2f9c.png)
> 
> ![image](https://user-images.githubusercontent.com/20772925/92742723-7de35480-f3b2-11ea-8ed1-8be028b3a7b9.png)

**Comment by leesnow1107** [comment]
你請求頭錯誤了~    在 2021年2月25日 星期四 上午01:20:04 [GMT+8]， qbabe<notifications@github.com> 寫道：  
 
 


@nilaoda
我也遇到同樣問題
我有加上請求頭了但卻顯示地址無效
能不能請求幫忙告訴我哪裡出了問題
目前我的Hamivideo是有時效性的
時間到了的就不能看了
可以的話能不能請ower @nilaoda nilaoda告訴我該怎麼做?
拜託 拜託您了
謝謝






置入Referer即可：
