### ISSUE TITLE
老哥.最近很多那种写入了图片信息在头部的TS下载合并后有问题.能做个识别吗?

### ISSUE THREAD

**Issue by hktrace** [nilaoda/N_m3u8DL-CLI#237]
很多伪造了图片传到各大图片图床的.想老哥写下去除头部那些图片信息在合并的.谢谢.
https://puui.qpic.cn/newsapp_ls/0/12432955469/0 这个是个例子.下载后转存为ts.c32打开去除头部的png信息就能播放~

**Comment by nilaoda** [comment]
目前这样的无法合并是吗

**Comment by hktrace** [comment]
是的。我用工具载入后发现头部的png信息都没去掉。合并后无法播放。

nilaoda <notifications@github.com> 于 2020年9月10日周四 08:53写道：

**Comment by hktrace** [comment]
应该是合并的时候没去除ts内的png信息导致合并后的无法播放.合并还是能合并的

>

**Comment by nilaoda** [comment]
有没有完整的这种图床m3u8链接给我测试？

**Comment by hktrace** [comment]
好的.我提供一个给您.

**Comment by xhlove** [comment]
估计说的这种（nfmovies）

https://q.nfmovies.com/hls/bt9vgnihejp0rd0ptm6g/1599750765/32436d2e29529261b5395f58883373ab/playlist.m3u8

**Comment by hktrace** [comment]
嗯嗯。能下载合并吗？

xhlove <notifications@github.com> 于 2020年9月10日周四 23:13写道：

**Comment by nilaoda** [comment]
已修复，晚些时候发布新版本。

**Comment by nilaoda** [comment]
已发布新版本。请更新测试。
