### ISSUE TITLE
關於catchplay+

### ISSUE THREAD

**Issue by leesnow1107** [nilaoda/N_m3u8DL-CLI#238]
我想請教一下 關於該網站抽取 VTT字幕的問題 ~

因最近的某幾個網頁視頻 都是以分片顯示字幕

導致VTT無法一併取得

請問是否可以處理 (影片為WIDEVINE ) 但字幕是明碼應該是沒有加密的

能否告知  處理的思路 , 也可提供帳號一試

**Comment by nilaoda** [comment]
字幕是否是单独的m3u8？

**Comment by leesnow1107** [comment]
> 字幕是否是单独的m3u8？

不是
分割成好幾段的
會隨著影片前進

**Comment by nilaoda** [comment]
如果不是m3u8本软件应该不会支持的~
目测是dash那一套切片。

你把账号密码发我邮箱我有空看下吧。

**Comment by leesnow1107** [comment]
已發送~麻煩

**Comment by nilaoda** [comment]
这个没办法了，字幕也是加密的

**Comment by nilaoda** [comment]
https://github.com/xhlove/mpd-content-parser
https://github.com/xhlove/dash-mp4-vtt-extractor

别的大佬写的字幕下载脚本
