### ISSUE TITLE
珠峰培训 免费视频 无法下载m3u8 求大佬出个解决思路 之前是可以的

### ISSUE THREAD

**Issue by zhanjunhao** [nilaoda/N_m3u8DL-CLI#239]
例如课程地址：http://www.javascriptpeixun.cn/course/11/task/160/show 大佬有空分析看看 Thanks♪(･ω･)ﾉ

**Comment by zhanjunhao** [comment]
![image](https://user-images.githubusercontent.com/25976993/93290406-3c6c0280-f813-11ea-8ba6-adec0e26f12a.png)
![image](https://user-images.githubusercontent.com/25976993/93290412-4130b680-f813-11ea-8416-69a506d76aa4.png)

**Comment by zhanjunhao** [comment]
![1](https://user-images.githubusercontent.com/25976993/93672216-a7e7f580-fadb-11ea-9b3e-d224fb9af9fc.png)
已解决 修改UA

**Comment by lifeike** [comment]
最近又不能下载了，谁有办法阿
