### ISSUE TITLE
老大研究下这个网站的视频，也是m3u8格式但是直接打开就显示一个二维码图片。

### ISSUE THREAD

**Issue by niaoxiao** [nilaoda/N_m3u8DL-CLI#243]
老大研究下这个网站的视频，也是m3u8格式但是直接打开就显示一个二维码图片。
这个站的视频主要是没水印清晰度高！
https://epang.ml

**Comment by nilaoda** [comment]
JS存书签用于获取m3u8：
```js
javascript:console.log(prompt("fake m3u8", "https://hls.ddyunp.com/ddyun/"+document.getElementsByClassName("viframe")[0].src.slice(39)+"/1/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/playlist.m3u8"))
```

![image](https://user-images.githubusercontent.com/20772925/93670907-4a4eab80-fad1-11ea-9a5d-57b1d38d9b12.png)


`https://hls.ddyunp.com/ddyun/371faee8e8d5133975c0ecf862a68bbe/1/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/playlist.m3u8`

其中`xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`是一个动态变化的参数，参数失效则提示404

此参数计算已经集成到下载器2.7.4中。**可以直接拿上面的地址给下载器进行下载**

![image](https://user-images.githubusercontent.com/20772925/93670866-196e7680-fad1-11ea-9cef-ce9b4884ea4b.png)

![image](https://user-images.githubusercontent.com/20772925/93670878-2e4b0a00-fad1-11ea-99a0-292e0d8d7712.png)

看着唬人，其实算法很简单

**Comment by niaoxiao** [comment]
谢谢老大，我们小白对代码一窍不通啊，只能用现成的软件复制粘贴地址下载视频！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nilaoda"<notifications@github.com&gt;; 
发送时间: 2020年9月19日(星期六) 晚上11:43
收件人: "nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;; 
抄送: "赵梦琪"<122668989@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [nilaoda/N_m3u8DL-CLI] 老大研究下这个网站的视频，也是m3u8格式但是直接打开就显示一个二维码图片。 (#243)





 
JS存书签用于获取m3u8：
 javascript:console.log(prompt("fake m3u8", "https://hls.ddyunp.com/ddyun/"+document.getElementsByClassName("viframe")[0].src.slice(39)+"/1/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/playlist.m3u8"))
 

 
https://hls.ddyunp.com/ddyun/371faee8e8d5133975c0ecf862a68bbe/1/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/playlist.m3u8
 
其中xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx是一个动态变化的参数，参数失效则提示404
 
此参数计算已经集成到下载器2.7.4中。可以直接拿上面的地址给下载器进行下载
 

 

 
看着唬人，其实算法很简单
 
&mdash;
