### ISSUE TITLE
key非16 bytes 文件？

### ISSUE THREAD

**Issue by 775405984** [nilaoda/N_m3u8DL-CLI#245]
[这个直播回放](https://www.sciconf.cn/m/lives/details/1246?video_id=146509)是加密的，我用Fiddler抓了key文件拖进去说非16 bytes 文件
![Screenshot_1](https://user-images.githubusercontent.com/7196377/93789890-0096ca00-fc65-11ea-8879-85392441f1f1.png)

另外，请求头、baseURL、混流文件这些在哪能找到？
谢谢了！ @nilaoda @youxia2016 @Suwmlee

**Comment by nilaoda** [comment]
保利威视参考：https://www.52pojie.cn/forum.php?mod=viewthread&tid=1268514&highlight=%C3%A8%BF%CE
