### ISSUE TITLE
地址无效或者填充失败

### ISSUE THREAD

**Issue by rickywu** [nilaoda/N_m3u8DL-CLI#247]
直接用m3u的url报地址无效

https://live-hz.xxx.com/player/src/get?id=43aebI1Q051EHJaz&resolution=HD&line=1&session=1832079&token=7h7dgbeqk9fv0

然后尝试把m3u内容保存成文件下载报填充无效

LOG 2020/09/23
Save Path: E:\Download\M3U8\Logs
Task Start: 2020/09/23 16:06:57
Task CommandLine: "E:\Download\M3U8\N_m3u8DL-CLI_v2.7.4.exe" "e:\Download\M3U8\video.m3u" --workDir "E:\Download\M3U8" --saveName "gd" --maxThreads "10" --minThreads "2" --useKeyBase64 "39AC852681867A90AA11C855034B202A" --useKeyIV "19290e922a347cd6240e90d24e7b0891" 

16:06:57.950 / (NORMAL) 开始解析 e:\Download\M3U8\video.m3u
16:06:57.980 / (NORMAL) 解析m3u8内容
16:06:57.986 / (NORMAL) 获取m3u8 key... base64:39AC852681867A90AA11C855034B202A
16:06:57.998 / (NORMAL) 写出meta.json
16:06:58.065 / (NORMAL) 开始下载文件
16:07:06.703 / (ERROR) 填充无效，无法被移除。

#EXT-X-KEY:METHOD=AES-128,URI="https://live-hz.xxx.com/player/authorize?id=43aebI1Q051EHJaz&session=1832079&token=47829osk0ai2a",IV=0x19290e922a347cd6240e90d2

KEY的URI要认证授权，怎么破？

meta.json:
        {
          "index": 0,
          "method": "AES-128",
          "key": "39AC852681867A90AA11C855034B202A",
          "iv": "0x19290e922a347cd6240e90d24e7b0891",
          "duration": 30.08,
          "segUri": "https://video1-cdn.xxx.com/pub/43aebI1Q051EHJaz/HD/0.ts"
        },

**Comment by nilaoda** [comment]
这是什么网站的内容呢

**Comment by rickywu** [comment]
gaodun的，获取key要刷新token，只能手动
