### ISSUE TITLE
下载芒果TV显示地址无效

### ISSUE THREAD

**Issue by StrollStars** [nilaoda/N_m3u8DL-CLI#251]
从猫抓获取的[m3u8地址](https://sxdx-73eff959-titan.hitv.com/c1/2020/09/23_0/F07FAC7B77FEB7739111DF21EE9F9831_20200923_1_1_536_mp4/463A2AE86C0AFEC15453C6022E7F3CE2.m3u8?arange=0&pm=7OnW7_BI_5ES2a0gOaoeH_Q4OSs7o_d_m1DFe2WIMcgm34lUUSELl3U5I_rFIuuMBGOdaIBDqIGIUWNjQpi0Iky8~_pO0KiAf7GEDMh2CDLIuECAXooyidcZ7tNT1Nk5TZUlfg97ECdhz6hST_mEPo4YEnuEjTZWPzIP8GWOo3BfNHw~iiegWSM3ZN2V55d9UfOb14OTzpicTEDC0mw4o6hxRTi4422OGuJcyILyLc4t~gHTOcNQwGRhJGEngyDLUXjijFi6TzYlRJLtrvAixoSKrGWcXg4HzjPVTmlWbUEpDjvOuhaXhv0HNVC6xV02C2~USEfiAz8YZ1XoUeJnci1_Y9MbayN1GwSDN7XBKbOtYpg2tiZtF6rwCEfY_M3YDELr1Hu0fJg6hPDdAArn~D9y0ObRCoAYUq1b6YCJJu1bwgThEF25NDT4PtpcBUZ4CGsMEZWMbvfmL9dE6BWf6A--&mr=59eT953Oz1YZA4ch0PhrsNtdP1xsAnHfRUoDf9frGqBQtOYdHiaTVS1CmDnyc1yQ6FIZQ400e6tQ0Nda9gF8nqYBUZ9fU_ipLqmzioaozT5YUNFr5tKl5PAJnKafLTvYzRcIsA~LP9Wj6668sT0KPgTP5MKmcsgOZj7Jr7p8oEA1eirDMTK5sKJ9Z2pEEl0aEcTaf2i4_k~Zwtl7pQV~H8v1nxGh6sj2TEa6tvXNrxEJNZiE6Jxnw0cEm~eoNUi~Pv4eVE~8TjZiJTBqk3~lrGZbQuww49OPpHZh8echaAcxYpZq&vcdn=0&scid=35&_t=1601137713063)，和原来的不同，显示下载失败：

01:28:01.666 开始解析
01:28:01.666 获取m3u8内容
01:28:01.663 地址无效

**Comment by momoko2806** [comment]
Idm dowload

**Comment by nilaoda** [comment]
有无视频播放页地址？

**Comment by StrollStars** [comment]
@nilaoda 今天再试了一下，发现地址恢复了，最新版也能正常下载，感谢回复，有问题再来反馈。
