### ISSUE TITLE
第一次用，打开软件的问题

### ISSUE THREAD

**Issue by jie-neng** [nilaoda/N_m3u8DL-CLI#255]
https://nilaoda.github.io/N_m3u8DL-CLI/Introductory.html  看里面的使用入门，没有找到.exe的文件呀。命令行输入N_m3u8DL-CLI.exe <URL|JSON|FILE> [OPTIONS] 或N_m3u8DL-CLI.exe也不行。是要把N_m3u8DL-CLI的文件夹弄成.exe格式的吗?

**Comment by nilaoda** [comment]
没有exe？可能被杀毒软件干掉了。。。

**Comment by jie-neng** [comment]
只安装了火绒。应该是我的问题。这个项目打包解压后，是应该有.exe的文件，对吧？解压后就是个文件夹。

**Comment by nilaoda** [comment]
> 只安装了火绒。应该是我的问题。这个项目打包解压后，是应该有.exe的文件，对吧？解压后就是个文件夹。

是的 文件夹里应该有三个exe ffmpeg N_m3u8DL-CLI 和 N_m3u8DL-CLI-SimpleG

**Comment by jie-neng** [comment]
成功了，感谢。不过m3u8这个下载器能用到哪方面的视频？我只在腾讯课堂上下了，b站的不行。哪些网站一般用m3u8的？

**Comment by nilaoda** [comment]
百分之80的网站都是m3u8

**Comment by jie-neng** [comment]
> 百分之80的网站都是m3u8

好滴，谢谢
