### ISSUE TITLE
More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one 

### ISSUE THREAD

**Issue by wangjian1119** [nilaoda/N_m3u8DL-CLI#256]
你好，极客时间里的购买课程下载 遇到这种问题

[aac @ 01a80ec0] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 01a80ec0] channel element 1.0 is not allocated
[aac @ 01a80ec0] Number of bands (20) exceeds limit (12).
[aac @ 01a80ec0] Multiple frames in a packet.
[aac @ 01a80ec0] Reserved bit set.
[aac @ 01a80ec0] Number of bands (12) exceeds limit (9).
[aac @ 01a80ec0] channel element 3.0 is not allocated
[aac @ 01a80ec0] Inconsistent channel configuration.
[aac @ 01a80ec0] get_buffer() failed
[aac @ 01a80ec0] channel element 2.6 is not allocated
[aac @ 01a80ec0] Reserved bit set.
[aac @ 01a80ec0] Number of scalefactor bands in group (58) exceeds limit (49).
[aac @ 01a80ec0] invalid band type
[aac @ 01a80ec0] channel element 2.15 is not allocated
[aac @ 01a80ec0] SBR was found before the first channel element.
[aac @ 01a80ec0] channel element 2.13 is not allocated
[aac @ 01a80ec0] channel element 2.4 is not allocated
[aac @ 01a80ec0] channel element 2.11 is not allocated
[aac @ 01a80ec0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 01a80ec0] Inconsistent channel configuration.
[aac @ 01a80ec0] get_buffer() failed
[aac @ 01a80ec0] channel element 1.9 is not allocated
[aac @ 01a80ec0] Reserved bit set.
[aac @ 01a80ec0] Number of bands (30) exceeds limit (3).
[aac @ 01a80ec0] channel element 3.14 is not allocated
[aac @ 01a80ec0] SBR was found before the first channel element.
[aac @ 01a80ec0] channel element 1.13 is not allocated
[aac @ 01a80ec0] Reserved bit set.
[aac @ 01a80ec0] Number of scalefactor bands in group (50) exceeds limit (43).
[aac @ 01a80ec0] Number of bands (15) exceeds limit (13).
[aac @ 01a80ec0] channel element 3.4 is not allocated
[aac @ 01a80ec0] SBR was found before the first channel element.
[aac @ 01a80ec0] channel element 2.3 is not allocated
[aac @ 01a80ec0] channel element 2.10 is not allocated
[aac @ 01a80ec0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 01a80ec0] Inconsistent channel configuration.
[aac @ 01a80ec0] get_buffer() failed
[aac @ 01a80ec0] channel element 3.15 is not allocated
[aac @ 01a80ec0] Number of bands (15) exceeds limit (13).
[aac @ 01a80ec0] channel element 3.4 is not allocated
[aac @ 01a80ec0] Number of bands (18) exceeds limit (15).
[aac @ 01a80ec0] channel element 3.10 is not allocated
[aac @ 01a80ec0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 01a80ec0] channel element 3.14 is not allocated
[aac @ 01a80ec0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 01a80ec0] Inconsistent channel configuration.
[aac @ 01a80ec0] get_buffer() failed
[mpegts @ 02457a00] decoding for stream 1 failed
[mpegts @ 02457a00] start time for stream 0 is not set in estimate_timings_from_pts
[mpegts @ 02457a00] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[mpegts @ 02457a00] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 5.0, fltp, 487 kb/s): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'concat:00.ts|01.ts|02.ts|03.ts|04.ts|05.ts|06.ts|07.ts|08.ts|09.ts|10.ts|11.ts|12.ts|13.ts|14.ts|15.ts|16.ts|17.ts|18.ts|19.ts|20.ts|21.ts|22.ts|23.ts|24.ts|25.ts|26.ts|27.ts|28.ts|29.ts|30.ts|31.ts|32.ts|33.ts|34.ts|35.ts|36.ts|37.ts|38.ts|39.ts|40.ts|41.ts|42.ts|43.ts|44.ts|45.ts|46.ts|47.ts|48.ts|49.ts|50.ts|51.ts|52.ts|53.ts|':
  Duration: 00:08:52.25, start: 2.833556, bitrate: 267 kb/s
  Program 1 
    Metadata:
      service_name    : Service01
      service_provider: FFmpeg
    Stream #0:0[0x100]: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc
    Stream #0:1[0x101]: Audio: aac ([15][0][0][0] / 0x000F), 5.0, fltp, 487 kb/s
[mp4 @ 09c7a980] dimensions not set
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)

请问怎么解决，我看78的issues 被删除了

**Comment by nilaoda** [comment]
你好，极客时间采用的是阿里云的加密方案，故本软件不予支持。
