### ISSUE TITLE
有办法支持mpd格式吗

### ISSUE THREAD

**Issue by heiyutian** [nilaoda/N_m3u8DL-CLI#257]
网上说mpd和m3u8类似，我从视频网站抓了一个mpd的链接，直接下载链接得到一个跟m3u8一样的mpd小文件，用文本编辑去看里面可以看到各种清晰度的链接，这些链接我直接下载是可以下载到好几G的文件，但是打不开，这个应该是mpd的文件加密了，需要同时下载音频文件，然后合并，我把各种链接都下载了，用ffmpeg去合并还是不能识别合并不了，我应该是没找到需要正确合并的对应视频和音频文件。

所以我想这个软件能不能也支持下mpd，通过作者的解密逻辑自动找到对应的音频视频去下载，然后合并就能解决问题了。

刚在网页播放的时候，idm可以抓到文件链接，看大小应该是音频和视频的文件，下载的格式都是mp4，然后跟我在mpd文件里面的链接下载的一样，都是不能直接播放。

**Comment by 592767809** [comment]
我猜应该是wv加密，下载视频和音频以后，自行获取key，然后使用https://github.com/nilaoda/Blog/issues/31进行解密混流

**Comment by heiyutian** [comment]
> 我猜应该是wv加密，下载视频和音频以后，自行获取key，然后使用[https://github.com/nilaoda/Blog/issues/31进行解密混流](https://github.com/nilaoda/Blog/issues/31%E8%BF%9B%E8%A1%8C%E8%A7%A3%E5%AF%86%E6%B7%B7%E6%B5%81)

那个工具导入文件后提示的KID就是key吗?我测试用那个没有用啊，解密成功生成的视频还是不能播放。

**Comment by nilaoda** [comment]
MPD不属于m3u8，本下载器不会支持。
