### ISSUE TITLE
关于下载速度的小期望

### ISSUE THREAD

**Issue by cocowobo** [nilaoda/N_m3u8DL-CLI#259]
经常下载视频，m3u8下载器中，我非喜欢大佬你的工具，但是横向对比其他下载工具 
大佬你的下载器的下载速度在众多下载器中，都只有中等偏下的水平
常用，手机端的荟萃浏览器，Lj视频下载器，m3u8loader，m3u8下载器，这些下载器下载基本上不论任何地址都是能跑满网速的
电脑端。52上面的[原创工具] M3U8 批量下载器，和TsMaster下载都能跑很快的速度
但是大佬的下载器似乎是对分片文件单个分片只有一个进程下载一样，不论我设置多高的最大进程，也只有一小会的告诉下载，大部分时间都会下载速度回落，甚至会出现因为其中某个分片下载只有几kb导致整个视频下载卡在这单独分片的进度的情况，
所以好希望大佬，能完善下对下载分片的处理逻辑，
顺便想让大佬能单独提供个 分片合并功能，对外的那种，偶会会用到，网上找的合并工具都不好用，有的很笨重
谢谢大佬。为你的成果点赞

**Comment by cocowobo** [comment]
比如。我将整个m3u8文件，复制到剪切板，导入IDM批量下载，下载速度杠杠的，但是下载下来都是分片，
很希望大佬出个合并工具，直接调用ffmpeg。简单便捷。
PS:IDM下载分片真的好快呀

**Comment by nilaoda** [comment]
IDM和本软件的原理不相同。IDM是将所有分片都进行多线程下载，而本软件的思路是同时下载N个分片达到多线程的目的。

**Comment by cocowobo** [comment]
单分片下载加速,或者调用第三方下载是个很好的思路,大佬方便做,就做上,不方便就算了,
已经换其他的下载器了,
大佬的产品解码强,但是下载速度没法看下去了,

**Comment by nilaoda** [comment]
> 单分片下载加速,或者调用第三方下载是个很好的思路,大佬方便做,就做上,不方便就算了,
> 已经换其他的下载器了,
> 大佬的产品解码强,但是下载速度没法看下去了,

嗯。未来一段时间内应该不会使用第三方工具。关于单分片加速，我觉得切片这么小(几M~十几M)的文件用不到再切成小片下载...针对MPD整段大文件的情况是会增加多片下载的

**Comment by cocowobo** [comment]
> > 单分片下载加速，或者调用第三方下载是个很好的思路，大佬方便做，就做上，不方便就算了，
> > 已经换其他的下载器了，
> > 大佬的产品解码强，但是下载速度没法看下去了，
> 
> 嗯。未来一段时间内应该不会使用第三方工具。关于单分片加速，我觉得切片这么小 (几 M~ 十几 M) 的文件用不到再切成小片下载... 针对 MPD 整段大文件的情况是会增加多片下载的

提供下我的使用场景,在柬.不知道为啥,单片2m大小的文件,假如有300个,下载中总是出现10来个下载速度为5k/s,甚至0k/s的情况,所以搞得我需要人工排查有问题的几个片段,或许是大家都在国内吧,当然大佬后面对mpd整段大文件增加大文件下载后,要是能做个开关默认对小片段也可以开启多线程下载就太好了,毕竟我使用其他的下载器,同样的下载地址,分片,都是满速下载的.

**Comment by nilaoda** [comment]
> > > 单分片下载加速，或者调用第三方下载是个很好的思路，大佬方便做，就做上，不方便就算了，
> > > 已经换其他的下载器了，
> > > 大佬的产品解码强，但是下载速度没法看下去了，
> > 
> > 
> > 嗯。未来一段时间内应该不会使用第三方工具。关于单分片加速，我觉得切片这么小 (几 M~ 十几 M) 的文件用不到再切成小片下载... 针对 MPD 整段大文件的情况是会增加多片下载的
> 
> 提供下我的使用场景,在柬.不知道为啥,单片2m大小的文件,假如有300个,下载中总是出现10来个下载速度为5k/s,甚至0k/s的情况,所以搞得我需要人工排查有问题的几个片段,或许是大家都在国内吧,当然大佬后面对mpd整段大文件增加大文件下载后,要是能做个开关默认对小片段也可以开启多线程下载就太好了,毕竟我使用其他的下载器,同样的下载地址,分片,都是满速下载的.

你可以设置一下stopSpeed这个参数 作用是当整体的下载速度低于这个值时，就会进入重试阶段。逻辑是删除上次没下完的片段并重新下载剩余片段。
