### ISSUE TITLE
音频解析问题

### ISSUE THREAD

**Issue by frank-ZHAO1983** [nilaoda/N_m3u8DL-CLI#260]
![ZEC2~D_MM EQ(7($O2TPER5](https://user-images.githubusercontent.com/57846065/94998025-a0e3db80-05e1-11eb-90f9-950a4b165ace.png)

某网站M3U8解析出来的，结果一个音频了含有4个轨道，而实际上这个音频本身只有一个AAC轨道，其他三个轨道是重复的，盼鸟大修复软件，谢谢！

**Comment by nilaoda** [comment]
这是feature，不是bug。本身就是为了支持多音轨的。。
