### ISSUE TITLE
指定的路径或文件名太长，或者两者都太长

### ISSUE THREAD

**Issue by bestlake** [nilaoda/N_m3u8DL-CLI#264]
https://1258712167.vod2.myqcloud.com/5a81e359vodtranssh1258712167/53c08f575285890792504778165/drm/voddrm.token.dWluPTE0NDExNTIxMjQ4NTM3ODI1Nzt2b2RfdHlwZT0wO2NpZD00MjE1NzY7dGVybV9pZD0xMDA1MDMyMzc7ZXh0PTY3YWQ4MGMyMzFhNDcyZDQzOWMyY2Y5OGRmZjQyNThhMTQ3YjNmZDQyNDY1ZWE2ODQ2YTQxYmU2ZjU3ZDJhZjBiOThmMmI5NGJkMzFjYmNkMWJmNGJjNzRmN2E2NmJlNzMzZjEzMmI0MDJkZTQ3MDQ5YTlhZDdmNTBkMDY5OWY1ODZhMGIzZTQzNTNiNGVmMg==.v.f30741.m3u8?exper=0&sign=f3c47e320df9e60bd0e73b23b7fad15a&t=5fae42a6&us=1022903122104529384

16:25:40.616 文件名称：voddrm.token.dWluPTE0NDExNTIxMjQ4NTM3ODI1Nzt2b2RfdHlwZT0wO2NpZD00MjE1NzY7dGVybV9pZD0xMDA1MDMyMzc716:25:40.617 指定的路径或文件名太长，或者两者都太长。完全限定文件名必须少于 260 个字符，并且目录名必须少于 248 个字符。j
NzRmN2E2NmJlNzMzZjEzMmI0MDJkZTQ3MDQ5YTlhZDdmNTBkMDY5OWY1ODZhMGIzZTQzNTNiNGVmMg==.v.f30741_20201014162540

**Comment by nilaoda** [comment]
[2.7.5](https://github.com/nilaoda/N_m3u8DL-CLI/releases/tag/2.7.5)已修复
