### ISSUE TITLE
能否加个cookies支持，有些m3u8文件需要登录后才能下载

### ISSUE THREAD

**Issue by yufeiyohi** [nilaoda/N_m3u8DL-CLI#266]
请问，你的程序是否支持cookies，因为有些m3u8文件需要登录后才允许下载，不然就返回错误，这种情况有什么好的解决办法？

**Comment by iMeedo** [comment]
程序不是我做的，我只是fork别人的程序。我不懂技术，不好意思。







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nilaoda/N_m3u8DL-CLI"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 晚上11:38
收件人:&nbsp;"nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[nilaoda/N_m3u8DL-CLI] 能否加个cookies支持，有些m3u8文件需要登录后才能下载 (#266)





 
请问，你的程序是否支持cookies，因为有些m3u8文件需要登录后才允许下载，不然就返回错误，这种情况有什么好的解决办法？

**Comment by yufeiyohi** [comment]
找到解决办法了，搞定了。

**Comment by nilaoda** [comment]
添加请求头

**Comment by MM977** [comment]
> 找到解决办法了，搞定了。

请问你是怎么解决的，能详细说说吗，我也遇到了这样的问题。谢谢

**Comment by MM977** [comment]
> 添加请求头

能否分享一下添加的格式，我不太懂格式。谢谢
