### ISSUE TITLE
嘛时候编译支持一下Mac系统的

### ISSUE THREAD

**Issue by xuzhimin1993** [nilaoda/N_m3u8DL-CLI#27]
嘛时候编译支持一下Mac系统的？最好集成多任务m3u8下载，m3u8(ts)合并，转化等，在mac下用ffmpeg命令行还是怪怪的

**Comment by nilaoda** [comment]
目前跨平台版本存在一些小BUG（如速度为0时无法自动重试）。
如果你想使用的话，安装dotnet SDK，自行编译即可。
https://github.com/nilaoda/N_m3u8DL-CLI_Core
