### ISSUE TITLE
以前可以下，这个月开始GG了

### ISSUE THREAD

**Issue by NERO-Tsui** [nilaoda/N_m3u8DL-CLI#271]
这网站之前一直可以下，最近站长似乎升级了服务器，会出现读取文件错误Error in reading file，不知大佬可否修复，感谢~
https://media.18asmr.club/videos/202010/26/5f95e3c7a23a537a12a9fb4f/28ac28/index.m3u8
https://media.18asmr.club/videos/202010/26/5f95e3c7a23a537a12a9fb50/a07487/index.m3u8
https://media.18asmr.club/videos/202010/25/5f94697ca23a537a12a9f509/291gce/index.m3u8
主站https://18asmr.net/

**Comment by nilaoda** [comment]
在请求头填写：`User-Agent:Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko`
