### ISSUE TITLE
m3u8分part视频自动合并

### ISSUE THREAD

**Issue by waahaa** [nilaoda/N_m3u8DL-CLI#275]
有几个分part的m3u8文件，比如：abc-part1.m3u8、abc-part2.m3u8、abc-part3.m3u8，如果用N_m3u8DL-CLI-SimpleG批量下载，下载下来的是三个单独的视频：abc-part1.mp4、abc-part2.mp4、abc-part3.mp4，我需要下载完成以后所有的分part视频合并为一个视频：abc.mp4，能否考虑添加这个功能？

**Comment by nilaoda** [comment]
下载器暂时不会考虑此类情况。推荐使用二进制合并，然后手动执行`copy /b abc-part1.ts+abc-part2.ts+abc-part3.ts abc.ts`
