### ISSUE TITLE
[feature request]更新m3u8地址后的断点续传

### ISSUE THREAD

**Issue by sino1641** [nilaoda/N_m3u8DL-CLI#279]
RT，因完整视频文件过大，且网站会定时更新m3u8地址。
更新地址后发现生成的缓存文件夹时间戳（？）后缀不同，并重新下载，不能断点续传。
原缓存文件夹内文件名不连续，也不方便直接设置分片下载。
期待解决方案，感谢

**Comment by nilaoda** [comment]
如果分片内容相同，可以用`--saveName`设置为相同的文件名进行下载，这样就会跳过已经下载过的分片
