### ISSUE TITLE
索引超出数组界限

### ISSUE THREAD

**Issue by Starpuccino** [nilaoda/N_m3u8DL-CLI#28]
解析本地的m3u8文件出问题了
![image](https://user-images.githubusercontent.com/33953383/67154495-1b174380-f330-11e9-98ae-294d53acab27.png)
源码好像缺文件了Newtonsoft.Json.Linq
找不到JArray JObject

**Comment by nilaoda** [comment]
使用Nuget安装一下Newtonsoft.Json
