### ISSUE TITLE
N_m3u8DL-CLI 2.8.1 下载多音轨MPD时，只下载一个音轨。

### ISSUE THREAD

**Issue by zengduoduo** [nilaoda/N_m3u8DL-CLI#283]
例如这个：链接: https://pan.baidu.com/s/17IsyyhDqUeF5PVbKDnE73g 提取码: 9527

**Comment by nilaoda** [comment]
是的，目前不支持多音轨，请等待后续改进。

**Comment by nilaoda** [comment]
v2.8.6中，增加了选择某种语言下载的功能，但是只能选择一条下载。先将就用吧，哈哈……
