### ISSUE TITLE
从11月19日开始，使用几次后不能再用，需重启电脑。

### ISSUE THREAD

**Issue by liuqiqi79** [nilaoda/N_m3u8DL-CLI#284]
大佬：
请教一下。
win10系统，2.7.5版本从11月19日开始出现无法读取信息现象。重启电脑可恢复正常，使用几次或几小时后，再次无法读取信息。只能通过不断重启电脑破解。（m3链接确认有效，使用另外两种m3下载器可正常下载。）
[尝试关闭系统自带防火墙和360安全卫士，没用。格盘重装系统，没用。更新2.8.0和2.8.1版本，没用。想请教大佬，还有什么我没想到的因素可能会限制N_m3u8DL-CLI的正常使用吗？N_m3u8DL-CLI已经用了一年多，从没出现这样的情况。
https://s3.ax1x.com/2020/11/22/D8bm5T.png

**Comment by nilaoda** [comment]
忽略这个错误，是否正常下载完？

**Comment by liuqiqi79** [comment]
> 忽略这个错误，是否正常下载完？

无法忽略。一旦出现“Error in reading file”，除非重启电脑，否则再也无法下载任何资源。也有大文件下载到一半，没有任何提示就无法继续，重新获取m3，重启N_m3u8DL-CLI，显示“Error in reading file”。
出错的规律是开机，下载半小时（不间断下载各种资源），会出错。或开机很久之后，一旦开始使用N_m3u8DL-CLI下载一两次，之后即便不再下载，几个小时后，也会出错，没法再用。

**Comment by nilaoda** [comment]
看一下程序目录下Logs文件夹中的日志，有没有什么有用的信息？

**Comment by liuqiqi79** [comment]
> 看一下程序目录下Logs文件夹中的日志，有没有什么有用的信息？

LOG 2020/11/22
Save Path: D:\DIRECTX\N_m3u8DL-CLI\Logs
Task Start: 2020/11/22 17:12:50
Task CommandLine: "D:\DIRECTX\N_m3u8DL-CLI\N_m3u8DL-CLI_v2.8.1.exe" "https://cache.m.iqiyi.com/mus/******/af25e0e935a6a927379f053c15d***************************bf8a42a31a04c125b19.m3u8?vt=0&previewTime=360&qd_originate=puma&k_uid=*********************************" --workDir "C:\Users\******\Downloads" --saveName "小*********" --enableDelAfterDone --disableDateInfo --noProxy 

17:12:50.458 / (NORMAL) 开始解析 https://cache.m.iqiyi.com/mus/******/af25e0e935a6a927379f053c15d***************************bf8a42a31a04c125b19.m3u8?vt=0&previewTime=360&qd_originate=puma&k_uid=*********************************
17:12:51.189 / (NORMAL) 解析m3u8内容
17:12:51.222 / (NORMAL) 写出meta.json
17:12:51.279 / (NORMAL) 开始下载文件
17:12:51.299 / (NORMAL) 读取文件信息...
17:12:51.555 / (NORMAL) PID 0x100: Video hevc, yuv420p10le(tv, bt2020nc/bt2020/smpte2084), 3840x1584 [SAR 1:1 DAR 80:33], 24 fps, 24 tbr, 90k tbn, 24 tbc
17:12:51.556 / (NORMAL) PID 0x101: Audio aac, 44100 Hz, stereo, fltp, 127 kb/s
17:13:01.643 / (ERROR) DOWN: 操作超时 
http://data.video.iqiyi.com/videos/*********************************c8ee.265ts?start=549752796&end=564345544&contentlength=******************************************************************4edfa17a1fb
17:13:01.674 / (ERROR) DOWN: 操作超时 
http://data.video.iqiyi.com/videos/*********************************80d5.265ts?start=721638940&end=730976900&contentlength=******************************************************************4edfa17a1fb
17:13:01.675 / (ERROR) DOWN: 操作超时 
http://data.video.iqiyi.com/videos/*********************************2a15e.265ts?start=26757288&end=41833008&contentlength=15075720&sd=742666&qdv=1&qd_uid=1408596670&qd_tvid=2337758300&qd_vip=1&qd_src=02022001010000000000&qd_tm==******************************************************************395b7c443
17:13:11.695 / (ERROR) DOWN: 操作超时 http://data.video.iqiyi.com/videos/******************************************************************f2a15e.265ts?start=41833008&end=53677948&contentlength=******************************************************************d395b7c443
17:13:11.703 / (NORMAL) 完成数量 1150 of 1154
17:13:11.703 / (NORMAL) 重试次数 1 / 15
17:13:17.742 / (NORMAL) 开始下载文件
17:13:20.730 / (NORMAL) 强制退出: 强制

Task End: 2020/11/22 17:13:20

这种是下载到一半突然断掉，重新获取m3，重试很多次都无法继续的情况。还有就是

**Comment by liuqiqi79** [comment]
LOG 2020/11/22
Save Path: D:\DIRECTX\N_m3u8DL-CLI\Logs
Task Start: 2020/11/22 15:42:39
Task CommandLine: "D:\DIRECTX\N_m3u8DL-CLI\N_m3u8DL-CLI_v2.8.1.exe" "https://cache.m.iqiyi.com/mus/**************.m3u8?vt=0&code=2*********d7b6c1213034" --workDir "D:\\" --saveName "电视先锋榜之*****_29.58" --enableDelAfterDone --disableDateInfo --noProxy 

15:42:39.426 / (NORMAL) 开始解析 "https://cache.m.iqiyi.com/mus/**************.m3u8?vt=0&code=2*********d7b6c1213034"
15:42:40.032 / (NORMAL) 解析m3u8内容
15:42:40.041 / (NORMAL) 写出meta.json
15:42:40.079 / (NORMAL) 开始下载文件
15:42:50.121 / (ERROR) DOWN: 操作超时 http://data.video.iqiyi.com/videos/vts/*********a77d2f.ts?start=0&end=3067972&contentlength=30**************276b8c9c9c78c3a256c409fba9
15:42:50.125 / (NORMAL) 读取文件信息...
15:42:50.126 / (NORMAL) Error in reading file
15:42:55.616 / (NORMAL) 强制退出: 强制

Task End: 2020/11/22 15:42:55

这种是开机后使用过一两次N_m3u8DL-CLI，之后很久，再次需要下载时，就完全不能用了。

**Comment by nilaoda** [comment]
我也是第一次见到你这种情况……我看你有提到说11月19日开始有这种现象。你有安装过什么软件或者其他东西么？感觉是你系统或网络的问题，因为程序是调用.net类库进行下载的。你或者找很旧的版本试试，应该也会出现相同的情况。也可以尝试重新安装一下.net Framework 4.6。

**Comment by liuqiqi79** [comment]
> 我也是第一次见到你这种情况……我看你有提到说11月19日开始有这种现象。你有安装过什么软件或者其他东西么？感觉是你系统或网络的问题，因为程序是调用.net类库进行下载的。你或者找很旧的版本试试，应该也会出现相同的情况。也可以尝试重新安装一下.net Framework 4.6。

11月10日左右安装了TeamViewer，之后N_m3u8DL-CLI的使用频率不高，没发现异样。19日发现不能使用后重启电脑会有改善，卸载了TeamViewer，无效；换回旧版2.5.7，无效；下载地址设置到不同的硬盘，无效；格盘、重装win10，依然无效。看来只能是网络的原因？可网络是唯一从头到尾不曾改动过的因素。。。无奈。我尝试重装一下.net Framework 4.6吧，非常感谢您的耐心解答。

**Comment by nilaoda** [comment]
下载所有视频都这样还是只有iqy呢？你在cmd中直接使用命令行下载 看看有没有什么异常退出的情况

**Comment by xhlove** [comment]
估计是DNS出问题了，检查下DNS吧

nilaoda <notifications@github.com> 于2020年11月22日周日 下午7:50写道：

**Comment by liuqiqi79** [comment]
> 下载所有视频都这样还是只有iqy呢？你在cmd中直接使用命令行下载 看看有没有什么异常退出的情况

在cmd中直接使用命令行下载也不行。经测试，确实只有iqy是这样。无法下载的m3，换个下载器就可以下载了。

**Comment by nilaoda** [comment]
> > 下载所有视频都这样还是只有iqy呢？你在cmd中直接使用命令行下载 看看有没有什么异常退出的情况
> 
> 在cmd中直接使用命令行下载也不行。经测试，确实只有iqy是这样。无法下载的m3，换个下载器就可以下载了。

你可以试试把m3u8文件里所有http:替换为https:

**Comment by liuqiqi79** [comment]
> > > 下载所有视频都这样还是只有iqy呢？你在cmd中直接使用命令行下载 看看有没有什么异常退出的情况
> > 
> > 
> > 在cmd中直接使用命令行下载也不行。经测试，确实只有iqy是这样。无法下载的m3，换个下载器就可以下载了。
> 
> 你可以试试把m3u8文件里所有http:替换为https:

从2.8.5版开始，至今使用正常，万分感谢！
