### ISSUE TITLE
芒果tv近期无法下载

### ISSUE THREAD

**Issue by GaryNotGay** [nilaoda/N_m3u8DL-CLI#285]
老版本（m3u8_dl_GUI）开启curl下载时即可正常下载芒果tv的m3u8，猜测应该是芒果近期限制了下载方式，网页访问m3u8地址会提示请求遭到拒绝，可能是限制了http访问？希望能修复一下

**Comment by nilaoda** [comment]
希望能提供无法下载的m3u8链接

**Comment by GaryNotGay** [comment]
https://pcvideotx.titan.mgtv.com/c1/2020/11/07_0/7229571F26B85D4CDCDD239DF858AB31_20201107_1_1_1441_mp4/5E7FB212C4C9914B37A4F3F579353869.m3u8?arange=0&pm=BY5jE1DyXr8b6jehFW6BKrW7eySSQMwHKeKhdCLXouiuY8dQsl648ty0~J6SEsw8wKXv8go~2ygIisHsdaPVHsiPBhl3X2mMCacQOrZRpf9W3by6_iCTgQx~QdvBElrbUd7jBTTyPZY9hyTB_2e3qs91WJpHig5zg~bs0BeHvmPl9TPqQDO6URGWPW~mFQRzcToYdMaBIvRm4XWa3mKKkni~DWCbhU4tq9t0_EEsWDj9apggAna0Oz_Ll0_IDK9nCxyi~HW3OQ4kFiQLrbOF2CagOH53Kd19kz27A9xA15ma2x7YxRot1csNSwzs2xT3nWLQx8MUrxcZBC_I6f5Tg2fPgnOOywDlwFzccQHCY~1eeji3vUem~ZiSqgAwsh4vVEHLAJmt3F0FqEPyXolPmBRxTxf_k1m09nLLi9SszZu9His~DTuuhcCMugtXBll_SOFV6cVm0fb4r2PpTMpdU~CDYX6SK3rL5Am8wvJpyxA-&mr=phgDKYmUOf~rvy7p6yABeF_AQ5tq_qYGWVNTrCIjHt9CfOVTYIAYa2u2o4dUKP2A8sYi8xPkWP5SEDKEhARyhyBHdP4dKfIit2eNtZvDMxzqMrghftK2MXsZ~M5KnTbdHek4oRmnydzcx8nSMJ1ODyUebkhOKeNOovWfh99zxOAhiIOlGvEXuDKqBeRIAiIZUvxFbbDoF38sPA~OnBMibJiXRBYoVFmcjmgh2NDjnvj~USpKo~zvEMUkdM6sAC4GEHocV~KWo5BqdpVmcCOzUNGhHq876AFFvj4MxvepirwrHMhpzEeLS52bbfe7BLyT3IsYZBdmY8kObmpmZ6IeYgGsrWS2PUcWAKOFbxhQ0sscOoVr5oRISy9WGkRQJTsoK5Jja_NKTRT4i22GCSg1GRDfKNgDtXcnyH5lNx0a76g_Agy_h3dpNg--&uid=4086cd556d3543249f13bf08197b23fa&vcdn=0&scid=25015&_t=1606139257214

**Comment by GaryNotGay** [comment]
事实上，随便哪一个都不能下。。。

**Comment by nilaoda** [comment]
好的 新版本将自动添加Referer请求头
