### ISSUE TITLE
2.8.4版本被Windows Defender报毒

### ISSUE THREAD

**Issue by jeffminim** [nilaoda/N_m3u8DL-CLI#289]
> 已检测：Trojan:Win32/Wacatac.D1!ml

> 详细信息：这个程序很危险，而且执行来自攻击者的命令。

请作者检查一下。

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-CLI/issues/206

参考这里手动给他们反馈就没事了

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-CLI/issues/206

参考这里手动给他们反馈就没事了

**Comment by nilaoda** [comment]
#206

参考这里手动给他们反馈就没事了

**Comment by nilaoda** [comment]
#206

参考这里手动给他们反馈就没事了

**Comment by nilaoda** [comment]
#206

参考这里手动给他们反馈就没事了

**Comment by nilaoda** [comment]
我今天给他们提交反馈
