### ISSUE TITLE
mpd无法解析这个网站

### ISSUE THREAD

**Issue by tyzh279** [nilaoda/N_m3u8DL-CLI#294]
https://www.myvideo.net.tw/

**Comment by nilaoda** [comment]
能否提供mpd链接用于测试

**Comment by tyzh279** [comment]
> 能否提供mpd链接用于测试

https://dastrm2.myvideo.net.tw/Media/20190430/Smooth/THR01000000016H/THR01000000016HPC.ism.json/manifest.mpd?_=1606379908642

**Comment by tyzh279** [comment]
[manifest.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/5601510/manifest.zip)
这个是mpd文件，你解压看一下

**Comment by nilaoda** [comment]
好的 收到 择日更新

**Comment by nilaoda** [comment]
2.8.8版本已经支持。

**Comment by tyzh279** [comment]
下载下来发现是加密了的，而且不是wv加密，不知道怎么破，求指教！



---原始邮件---
发件人: "nilaoda"<notifications@github.com&gt;
发送时间: 2020年11月26日(周四) 晚上9:11
收件人: "nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"ABC"<229722857@qq.com&gt;;
主题: Re: [nilaoda/N_m3u8DL-CLI] mpd无法解析这个网站 (#294)




 
2.8.8版本已经支持。

**Comment by tyzh279** [comment]
Apple tv+的m3u8，多流选择后一闪而过，无法下载

**Comment by nilaoda** [comment]
> Apple tv+的m3u8，多流选择后一闪而过，无法下载

可以发送一下样品到我邮箱
