### ISSUE TITLE
2.8.9打开卡死

### ISSUE THREAD

**Issue by xzeu** [nilaoda/N_m3u8DL-CLI#297]
2.8.9打开慢，右键直接无响应，2.7.4没有这这种反应

**Comment by nilaoda** [comment]
我这边没有遇到这个问题 你重新下载试试？

**Comment by xzeu** [comment]
下载了，还是一样，不很奇怪然后还提示有病毒

**Comment by xzeu** [comment]
我下载源码重新编译了，已经不出现无响应的问题了，感谢

**Comment by xzeu** [comment]
使用Costura.Fody插件将程序打包成一个可以独立运行的EXE文件，运行后不提示病毒也不显示无响应了，文件的大小变成了645k

**Comment by nilaoda** [comment]
> 使用Costura.Fody插件将程序打包成一个可以独立运行的EXE文件，运行后不提示病毒也不显示无响应了，文件的大小变成了645k

谢谢，的确是一个很好插件！今后会使用此种方式打包。
