### ISSUE TITLE
一直Waiting...，保存的文件大小没变化

### ISSUE THREAD

**Issue by binjoo** [nilaoda/N_m3u8DL-CLI#300]
![image](https://user-images.githubusercontent.com/219092/101316594-c28a6900-3897-11eb-9453-85f8efb419bf.png)

M3U8地址是：

> http://116.62.93.216:9211/HLSLIVE/S1802080373.m3u8?528660F5-6666-4dea-A02F-2D1651292947

`目前已失效`

**Comment by nilaoda** [comment]
不建议使用此软件的录制功能

**Comment by binjoo** [comment]
> 不建议使用此软件的录制功能

请问有没有什么推荐的M3U8的录制软件吗？

**Comment by nilaoda** [comment]
> > 不建议使用此软件的录制功能
> 
> 请问有没有什么推荐的M3U8的录制软件吗？

streamlink

**Comment by binjoo** [comment]
@nilaoda 谢谢。
