### ISSUE TITLE
最近几版下载iqiyi的m3u8速度比以前慢很多

### ISSUE THREAD

**Issue by lleeopen** [nilaoda/N_m3u8DL-CLI#301]
发现最近几个版本下载iqiyi的m3u8速度比以前慢很多，换另一款下载m3u3软件速度比较快，不知道是不是个例？
只是iqiyi的比较慢，其他的比如txsp youku速度都很快正常，联通200M以前下载iqiyi的m3u8速度没有低于过5M/S~~
![iqiyi](https://user-images.githubusercontent.com/35162785/101476138-458aec80-3988-11eb-9098-38a7b8f27c2f.gif)
这是另外一款软件，同一个m3u8文件速度比较快~~
![iqiyi2](https://user-images.githubusercontent.com/35162785/101476695-1de85400-3989-11eb-8196-e5b87f52ebe0.gif)

**Comment by nilaoda** [comment]
两者原理并不相同。他的速度比我快很正常~不过你说的速度变慢我倒是没遇到

![image](https://user-images.githubusercontent.com/20772925/101490829-df10c900-399d-11eb-89c8-0770e8aad53c.png)

**Comment by lleeopen** [comment]
以前都是很快的，只是最近自动更新了这几版都是比较慢，只是下载iqiyi比较慢，txsp youku都很快

**Comment by nilaoda** [comment]
你可以挨个试试 从哪个版本开始变慢 我看看是不是有什么调整

**Comment by lleeopen** [comment]
今天上午又试了一下iqiyi，速度又变的比较正常了，是不是和网络和时间有关，之前都是晚上测试的，上午没试过，反正txsp youku在晚上速度一直都是很快~~
![iqiyi](https://user-images.githubusercontent.com/35162785/101570141-c55c9980-3a10-11eb-8b83-f47562e5cbfc.gif)
