### ISSUE TITLE
N_m3u8DL-CLI 填充无效 虎课网

### ISSUE THREAD

**Issue by tjzhlong** [nilaoda/N_m3u8DL-CLI#309]
之前都是能下载的，最近一段时间没用了，今天更新 ，发现下载不了了

https://vkceyugu.cdn.bspapp.com/VKCEYUGU-imgbed/b6b7f7ff-5b78-43ea-9e77-6f99bf0ee572.png

**Comment by nilaoda** [comment]
请等待新版本

**Comment by Nchujx** [comment]
想问下大佬是如何只根据虎课网的m3u8链接就能下载虎课网视频的，我之前分析过虎课网的视频，写了一款批量解析虎课网视频的软件，也是需要用key的，但是你我看了你的2.9.1版本只需输入m3u8 链接就能下载，让我很是疑惑，希望能于大佬进行技术交流，谢谢！
这是我之前分析的过程
https://github.com/Nchujx/huke/blob/main/%E8%99%8E%E8%AF%BE%E7%BD%91%E8%A7%86%E9%A2%91%E5%88%86%E6%9E%90.md

**Comment by Nchujx** [comment]
> 请等待新版本
想问下大佬是如何只根据虎课网的m3u8链接就能下载虎课网视频的，我之前分析过虎课网的视频，写了一款批量解析虎课网视频的软件，也是需要用key的，但是你我看了你的2.9.1版本只需输入m3u8 链接就能下载，让我很是疑惑，希望能于大佬进行技术交流，谢谢！
这是我之前分析的过程
https://github.com/Nchujx/huke/blob/main/%E8%99%8E%E8%AF%BE%E7%BD%91%E8%A7%86%E9%A2%91%E5%88%86%E6%9E%90.md

**Comment by nilaoda** [comment]
> 想问下大佬是如何只根据虎课网的m3u8链接就能下载虎课网视频的，我之前分析过虎课网的视频，写了一款批量解析虎课网视频的软件，也是需要用key的，但是你我看了你的2.9.1版本只需输入m3u8 链接就能下载，让我很是疑惑，希望能于大佬进行技术交流，谢谢！
> 这是我之前分析的过程
> https://github.com/Nchujx/huke/blob/main/%E8%99%8E%E8%AF%BE%E7%BD%91%E8%A7%86%E9%A2%91%E5%88%86%E6%9E%90.md

m3u8中的参数有所需key和iv。其他逻辑我是照抄他js里的，可以看源代码

https://github.com/nilaoda/N_m3u8DL-CLI/blob/master/N_m3u8DL-CLI/DecodeHuke88Key.cs

**Comment by Nchujx** [comment]
感谢回复，可以加下我的微信吗？方便交流，谢谢 15803297610------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;nilaoda&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月30日(星期三) 中午1:21
收件人:&nbsp;&quot;nilaoda/N_m3u8DL-CLI&quot;<N_m3u8DL-CLI@noreply.github.com&gt;;
抄送:&nbsp;&quot;南昌航空大学XXX&quot;<1203083157@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] N_m3u8DL-CLI 填充无效 虎课网 (#309)

**Comment by Nchujx** [comment]
可以加下我的微信吗，方便交流，谢谢！
15803297610

**Comment by yuanzhentao1990** [comment]
请问大神，邢帅教育网站，在下载时出现闪退。

**Comment by wenmin92** [comment]
现在是不是又不能下载了？
![image](https://user-images.githubusercontent.com/6901815/130655343-e6ac93e0-55ce-4336-9ed1-6b3362cae96c.png)
