### ISSUE TITLE
提几个优化问题

### ISSUE THREAD

**Issue by SONGjiemo** [nilaoda/N_m3u8DL-CLI#31]
1. 去掉 【执行程序】【启动参数】个人感觉是多余的。 
【GO】按钮 可以换成 【确定】和【关闭】。确定就是 开始下载，取消就是关闭软件。
2.是否可以  添加一个【aria2c】下载引擎来下载呢！
就是希望可以添加  多个下载引擎进行下载。
https://baijiahao.baidu.com/s?id=1595877979348356747&wfr=spider&for=pc

**Comment by nilaoda** [comment]
1.【执行程序】是为了应用不同的程序名称设定的（比如用户留了多个版本的主程序），【启动参数】提供复制，方便调试程序功能，定制BAT语句等，【GO】按钮好像没有什么歧义吧 个人感觉改成确定和关闭才有点奇怪……
2.我对aria2的可靠性抱有怀疑态度……且aria2不支持HTTP的range请求头，这将影响一部分m3u8的正常下载

**Comment by SONGjiemo** [comment]
谢谢解答！
对于aria2是增加一个下载，用于切换的  并非替换。
而且aria2对于下载更加稳定，期望考虑一下。
可以默认内置命令下载，也可以切换aria2去下载。

**Comment by SONGjiemo** [comment]
> 1.[[[][][]，[[]，["，["，[GO]。
> 2.2.2[href2][http_range]，[m3u8]



> 1.【执行程序】是为了应用不同的程序名称设定的（比如用户留了多个版本的主程序），【启动参数】提供复制，方便调试程序功能，定制BAT语句等，【GO】按钮好像没有什么歧义吧 个人感觉改成确定和关闭才有点奇怪……
> 2.我对aria2的可靠性抱有怀疑态度……且aria2不支持HTTP的range请求头，这将影响一部分m3u8的正常下载

谢谢解答！
对于aria2是增加一个下载，用于切换的 并非替换。
而且aria2对于下载更加稳定，期望考虑一下。
可以默认内置命令下载，也可以切换aria2去下载。

**Comment by nilaoda** [comment]
> > 1.[[[][][]，[[]，["，["，[GO]。
> > 2.2.2[href2][http_range]，[m3u8]
> 
> > 1.【执行程序】是为了应用不同的程序名称设定的（比如用户留了多个版本的主程序），【启动参数】提供复制，方便调试程序功能，定制BAT语句等，【GO】按钮好像没有什么歧义吧 个人感觉改成确定和关闭才有点奇怪……
> > 2.我对aria2的可靠性抱有怀疑态度……且aria2不支持HTTP的range请求头，这将影响一部分m3u8的正常下载
> 
> 谢谢解答！
> 对于aria2是增加一个下载，用于切换的 并非替换。
> 而且aria2对于下载更加稳定，期望考虑一下。
> 可以默认内置命令下载，也可以切换aria2去下载。

没看出哪里稳定，而且我这里用aria2丢包率极高
