### ISSUE TITLE
不支持批量下载可惜了

### ISSUE THREAD

**Issue by Bunnyk001** [nilaoda/N_m3u8DL-CLI#314]
这么好的软件不支持批量下载可惜了

**Comment by nilaoda** [comment]
可以使用BAT实现批量下载。或者使用[SimpleG](https://nilaoda.github.io/N_m3u8DL-CLI/SimpleGUI.html)等辅助软件

**Comment by xuanxs** [comment]
> 可以使用BAT实现批量下载。或者使用[SimpleG](https://nilaoda.github.io/N_m3u8DL-CLI/SimpleGUI.html)等辅助软件

请问SimpleG批量下载时，文件内容格式是怎么样的，链接+文件名？怎么分割

**Comment by nilaoda** [comment]
txt内容：

```
name1,url1
name2,url2
```

**Comment by xuanxs** [comment]
> txt内容：
> 
> ```
> name1,url1
> name2,url2
> ```

收到，感谢及时回复
