### ISSUE TITLE
获得链接，下载不能开始

### ISSUE THREAD

**Issue by jie-neng** [nilaoda/N_m3u8DL-CLI#316]
视频地址：  https://www.hezhimeng.cn/videoDet.html?videoId=6073094c2b5ea09f1867c74648696774
链接：    https://wxres.hezhimeng.cn/236%E9%95%BF%E7%89%88-%E4%BC%9A%E5%91%98%E6%B0%B4%E5%8D%B0%E7%89%881_BiliBili.mp4

**Comment by nilaoda** [comment]
这是mp4不是m3u8
