### ISSUE TITLE
爱奇艺视频获取M3U8地址后 无法下载

### ISSUE THREAD

**Issue by cookle0106** [nilaoda/N_m3u8DL-CLI#321]
https://www.iqiyi.com/v_19rr9i2qss.html

使用JS代码获取地址后无法现在 打开m3u8发现媒体文件都是m4s格式。

**Comment by nilaoda** [comment]
加密了，暂时没有办法

**Comment by hotliuyu** [comment]
> 

大哥，可以请教一下你是怎么通过js代码获取地址的
