### ISSUE TITLE
能否在GUI面板增加http或者socks代理选项

### ISSUE THREAD

**Issue by heiyutian** [nilaoda/N_m3u8DL-CLI#325]
我一般都是通过GUI来启动下载，我相信大多数非程序员朋友都是差不多，但是现在下载很多时候需要代理，所以能否在GUI面板增加一个127.0.0.1:1080这样的代理选项，我知道很多朋友是使用的系统IE代理，我为了避免让任何软件都走了代理，所以我没有开启系统代理，都是在浏览器或者别的需要代理的地方手动设置的。

**Comment by heiyutian** [comment]
我刚才想着在Terminal用cmd面板来开启代理
set http_proxy=http://127.0.0.1:1080
我通过这条命令开启了cmd的代理，然后通过ffmpeg是可以看到ffmprg是走了代理的，但是我重新来尝试在cmd面板让m3u8dl来走代理，但是发现没成功，一直走的直连，下面是m3u8dl的代码参数
"D:\sss\N_m3u8DL-CLI_v2.9.5.exe" "https://qq.com/qq.m3u8" --workDir "D:\m3u8" --maxThreads "16" --minThreads "1" --retryCount "3000" --timeOut "5" --maxSpeed "9999" --enableBinaryMerge

**Comment by nilaoda** [comment]
最新版已经增加

**Comment by gzlboy** [comment]
请问可以支持socks5协议吗？
