### ISSUE TITLE
Error in reading file!!! Download Content of Manifest

### ISSUE THREAD

**Issue by balleno75** [nilaoda/N_m3u8DL-CLI#328]
Hello, downloading the content of the following manifest, the following error is generated,

https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/4880098471001/754fbb2f-832c-4658-b552-751f6bb7c878/6s/manifest.mpd?fastly_token=NWZmMmUyODFfMWNhYjQ0YzdlYjY1MDdjMjViOWFjNTBiNzYxYzc4NTkwODM0ZDQ1NzIzOGE3OGRmYjdiNmM1MDY4MjU4MWYxNA%3D%3D

![image](https://user-images.githubusercontent.com/39314271/103494050-32f3be00-4e35-11eb-8b8a-ab92127796d7.png)

![image](https://user-images.githubusercontent.com/39314271/103494067-44d56100-4e35-11eb-9d02-96b27d198bb0.png)

Please, can you review the error, or tell me what is happening?

Thank you. A greeting.

**Comment by PlaceboPRS** [comment]
You should check the logs and see what they say, I had a similar issue today with Optus because the base url was very different to the MPD url but once I identified the correct base url and used the --baseUrl "URL" command it worked :)

What site are you trying to use? That MPD doesn't download for me so I can't test.

**Comment by balleno75** [comment]
Hello,

This is the error that is generated in the log. I am trying to download from the Filmin España platform and I have a subscription for it, so I have a username and password to access the service.


00:54:26.438 / (NORMAL) 读取文件信息...
00:54:26.441 / (NORMAL) Error in reading file
00:54:26.497 / (ERROR) DOWN: The remote server returned an error: (403) Forbidden. https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/4880098471001/7b0948b3-da9b-4306-922e-25e1dbd958f3/6s/83ae9e61-9786-46fc-ace4-da7de0e41859/3x/segment119.m4f?
00:54:26.497 / (ERROR) DOWN: The remote server returned an error: (403) Forbidden. https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/4880098471001/7b0948b3-da9b-4306-922e-25e1dbd958f3/6s/83ae9e61-9786-46fc-ace4-da7de0e41859/3x/segment178.m4f?
00:54:26.498 / (ERROR) DOWN: The remote server returned an error: (403) Forbidden. https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/4880098471001/7b0948b3-da9b-4306-922e-25e1dbd958f3/6s/83ae9e61-9786-46fc-ace4-da7de0e41859/3x/segment60.m4f?


From a browser and with this link, I can download the mpd, but when I try to download the video and audio parts with the tool from the mpd itself locally, the same error is generated.

It has a solution?.

Thank you. A greeting.

**Comment by PlaceboPRS** [comment]
I can't test without logging in unfortunately, but try opening the console with F12, filtering for mp4 (or m4f or whatever is relevant to this site) and when it finds something copy the url and check if the URL is the same as the manifest url from the logs, if not specify the correct base URL. If you have Discord you can always DM me there if I can help: Placebo#8409

**Comment by balleno75** [comment]
Hello, indeed, the links of the m4f files were different from the mpd link, so I had to indicate the --baseUrl parameter and they have been downloaded correctly.

Thanks a lot. A greeting.

**Comment by PlaceboPRS** [comment]
Excellent well done for figuring it out! :)
