### ISSUE TITLE
获取到视频标题

### ISSUE THREAD

**Issue by cnsnet** [nilaoda/N_m3u8DL-CLI#334]
打开GUI的时候会自动从剪贴板获取m3u8地址并获取到视频标题, 能否加上复制完m3u8地址后, 文本框blur后重新获取视频标题呢?这样就不用每次都重新打开GUI了.
谢谢.

**Comment by nilaoda** [comment]
1. 双击地址栏即可读取剪贴板
2. 双击名称文本框即可获取标题

**Comment by cnsnet** [comment]
多谢告知.
