### ISSUE TITLE
无法双击 打开 N_m3u8DL-CLI_v2.9.1 

### ISSUE THREAD

**Issue by shan20xing** [nilaoda/N_m3u8DL-CLI#335]
无法双击 打开 N_m3u8DL-CLI_v2.9.1 ，
打开显示错误！马上闪退，是哪里出了问题
图片如下：
【https://zhidao.baidu.com/question/1698572497479180428.html】

**Comment by nilaoda** [comment]
尝试升级.net framework到最新版本

**Comment by shan20xing** [comment]
> 尝试升级.net framework到最新版本

还是不行，已经下载过很多不同版本！全部都是打开显示，已停止运作！！

**Comment by nilaoda** [comment]
安装 .net 4.6
