### ISSUE TITLE
项目使用vs2015打开会各种语法报错？

### ISSUE THREAD

**Issue by MaxZzyo** [nilaoda/N_m3u8DL-CLI#336]
默认的环境.net4.6，ide是vs2015，win10系统
![image](https://user-images.githubusercontent.com/40203749/104628223-f052a100-56d2-11eb-93f0-1e65746552b1.png)
![image](https://user-images.githubusercontent.com/40203749/104628259-fb0d3600-56d2-11eb-9d2a-000c69ef5cb6.png)

有啥需要配置的吗？clone完代码直接生成就这样了

**Comment by nilaoda** [comment]
使用vs2019试试呢

**Comment by MaxZzyo** [comment]
> 使用vs2019试试呢

换2019已经正常了
