### ISSUE TITLE
English Translation

### ISSUE THREAD

**Issue by morpheus2n2** [nilaoda/N_m3u8DL-CLI#338]
Hi is it possible for text when its downloaded be translated into english, its a bit confusing looking at question marks all the time.
Also is the SimpleGUI able to be translated? 
Thank you for your help.

**Comment by nilaoda** [comment]
whats your system language?

**Comment by morpheus2n2** [comment]
English UK

**Comment by PlaceboPRS** [comment]
Yeah I'm getting lots of ??? too

**Comment by nilaoda** [comment]
Costura.Fody does not embed the resource file, I will fix this problem in the next version.

**Comment by PlaceboPRS** [comment]
Awesome! Can't wait thanks :)

**Comment by nilaoda** [comment]
Plz try [2.9.2](https://github.com/nilaoda/N_m3u8DL-CLI/releases/tag/2.9.2)
