### ISSUE TITLE
Would you ever consider changing the name of this software?

### ISSUE THREAD

**Issue by 775405984** [nilaoda/N_m3u8DL-CLI#339]
I mean, how do you even pronounce N_m3u8DL-CLI?
You should change it to m3u8 Downloader, or maybe something better.
The current name is way too complicated. But maybe that's your primary motive, to scare off basic users so that the software won't get popular enough to receive any legal challenges. If that's the case, never mind.
@nilaoda @youxia2016 @Suwmlee

**Comment by PlaceboPRS** [comment]
Name's fine IMO, keeps it nicely under the radar.

**Comment by xhlove** [comment]
There is too many project/program named 'm3u8 Downloader',

N_m3u8DL-CLI is highly recognizability.

**Comment by 775405984** [comment]
> N_m3u8DL-CLI is highly recognizability.
And easily forgotten. Because its spelling is TOO complicated.
