### ISSUE TITLE
有没有优酷4k下载脚本

### ISSUE THREAD

**Issue by ownerowner** [nilaoda/N_m3u8DL-CLI#34]
不知大佬能发布吗，目前只能下载1080p的

**Comment by nilaoda** [comment]
JS无法实现

**Comment by ownerowner** [comment]
> JS无法实现

我看网上有人使用软件解析获取m3u8，大佬可以发布吗

**Comment by angelkyo** [comment]
![Snipaste_2019-11-20_13-35-40](https://user-images.githubusercontent.com/4989290/69211931-b0f5f680-0b9a-11ea-84d5-f7d6c21ae6cd.png)
https://www.lanzous.com/b07r5v35e 密码:35n5

**Comment by ownerowner** [comment]
> ![Snipaste_2019-11-20_13-39-28](https://user-images.githubusercontent.com/4989290/69212098-3bd6f100-0b9b-11ea-9c2a-644ff9ab9bf2.png)
> 
> https://www.lanzous.com/b07r5v35e 密码:35n5

感谢您的分享

**Comment by angelkyo** [comment]
这是程序向优酷服务器发送请求，请求信息里包含需要4K，请求信息有个签名参数是需要加密计算的，服务器才会返回4K的地址。脚本要做到这样的事情，似乎很固难~
目的是获取4K地址，你还要在意获取途径和过程，就有点强人所难




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ownerowner"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 上午8:00
收件人: "nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;; 
抄送: "丶小眼乱电"<3640593@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [nilaoda/N_m3u8DL-CLI] 有没有优酷4k下载脚本 (#34)



 

 
https://www.lanzous.com/b07r5v35e 密码:35n5
  
感谢您的分享

**Comment by ownerowner** [comment]
> 这是程序向优酷服务器发送请求，请求信息里包含需要4K，请求信息有个签名参数是需要加密计算的，服务器才会返回4K的地址。脚本要做到这样的事情，似乎很固难~ 目的是获取4K地址，你还要在意获取途径和过程，就有点强人所难
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ownerowner"<notifications@github.com&gt;; 发送时间: 2019年11月21日(星期四) 上午8:00 收件人: "nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;; 抄送: "丶小眼乱电"<3640593@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [nilaoda/N_m3u8DL-CLI] 有没有优酷4k下载脚本 (#34) https://www.lanzous.com/b07r5v35e 密码:35n5 感谢您的分享 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

我不了解这些，抱歉。你的主页地址怎么访问不了 angel

**Comment by faxianzhilu** [comment]
这个叫AK视频解析的软件实在是太强大了。以前试过Annie、you-get、youtube-dl、IDM网页抓取、猫抓插件+M3U8下载器、官方客户端下载再解密转换等各种方法，都有各种各样的缺点，而这个软件简直完美，在此感谢开发者的分享。
