### ISSUE TITLE
下载保利威视频时只能从外部文件读取key，使用base64编码的key闪退

### ISSUE THREAD

**Issue by Nchujx** [nilaoda/N_m3u8DL-CLI#340]
测试文件：
https://aohua.lanzous.com/iaqcRkkf74b
只能使用外部引用的key ，但将key编码为base64时闪退
编码的key:   SEl99MgcKj3LrxklB8/abA==

**Comment by jerryrat** [comment]
key 二次加密了

**Comment by Nchujx** [comment]
我已经将key解密了，目前下载器进行aes解密时，会对保利威的视频产生错误，其他的没问题，猜测是下载器的问题。 其实只要对ts文件进行普通的aes解密就行了，2.6.3的版本都可以正常下载------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;jerryrat&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月28日(星期四) 晚上10:10
收件人:&nbsp;&quot;nilaoda/N_m3u8DL-CLI&quot;<N_m3u8DL-CLI@noreply.github.com&gt;;
抄送:&nbsp;&quot;南昌航空大学XXX&quot;<1203083157@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 下载保利威视频时只能从外部文件读取key，使用base64编码的key闪退 (#340)

**Comment by nilaoda** [comment]
> 我已经将key解密了，目前下载器进行aes解密时，会对保利威的视频产生错误，其他的没问题，猜测是下载器的问题。 其实只要对ts文件进行普通的aes解密就行了，2.6.3的版本都可以正常下载------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;jerryrat&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月28日(星期四) 晚上10:10 收件人:&nbsp;&quot;nilaoda/N_m3u8DL-CLI&quot;<N_m3u8DL-CLI@noreply.github.com&gt;; 抄送:&nbsp;&quot;南昌航空大学XXX&quot;<1203083157@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 下载保利威视频时只能从外部文件读取key，使用base64编码的key闪退 (#340)

你指的错误是？
下载器从2.7.1开始的版本都无法正常解密吗？

**Comment by Nchujx** [comment]
是的，明明使用2.6.3版本可以正常下载，但是高版本却不能下载，我已经解出16字节正确的key了。

**Comment by nilaoda** [comment]
> 是的，明明使用2.6.3版本可以正常下载，但是高版本却不能下载，我已经解出16字节正确的key了。

方便提供一下正确的key以及m3u8么 可能是程序里某些逻辑有问题

**Comment by Nchujx** [comment]
> > 是的，明明使用2.6.3版本可以正常下载，但是高版本却不能下载，我已经解出16字节正确的key了。
> 
> 方便提供一下正确的key以及m3u8么 可能是程序里某些逻辑有问题

测试文件：
https://aohua.lanzous.com/iaqcRkkf74b
base64编码的key: SEl99MgcKj3LrxklB8/abA==

**Comment by Nchujx** [comment]
希望能建一个QQ群，方便交流哈

**Comment by nilaoda** [comment]
新版修复

**Comment by royiie** [comment]
> 我已经将key解密了，目前下载器进行aes解密时，会对保利威的视频产生错误，其他的没问题，猜测是下载器的问题。 其实只要对ts文件进行普通的aes解密就行了，2.6.3的版本都可以正常下载------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;jerryrat&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月28日(星期四) 晚上10:10 收件人:&nbsp;&quot;nilaoda/N_m3u8DL-CLI&quot;<N_m3u8DL-CLI@noreply.github.com&gt;; 抄送:&nbsp;&quot;南昌航空大学XXX&quot;<1203083157@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 下载保利威视频时只能从外部文件读取key，使用base64编码的key闪退 (#340)

能分享下如何从32位解密成16位的key吗？
