### ISSUE TITLE
simpleg source code and change into english?

### ISSUE THREAD

**Issue by 0lm** [nilaoda/N_m3u8DL-CLI#342]
hi there, just wanted to ask where exactly find the source code for the simplegui thats offered in the zip file in releases. and also, it says english is supported here but i cant find a way to change the simpleg language into english. any ideas?

**Comment by nilaoda** [comment]
N_m3u8DL-CLI already supported, not SimpleG.

**Comment by mmshasan** [comment]
Kindly add English support for SimpleG, would be a great help for users around the world.

**Comment by mmshasan** [comment]
> hi there, just wanted to ask where exactly find the source code for the simplegui thats offered in the zip file in releases. and also, it says english is supported here but i cant find a way to change the simpleg language into english. any ideas?

For now, use Google Lens to translate

**Comment by 0lm** [comment]
I see, thanks for the info.
And just btw. the virus alert I got recently is false alert I guess? (for version 2.9.3)

**Comment by nilaoda** [comment]
> I see, thanks for the info. And thanks for adding English translation!
> And btw, recently I got virus alert for v 2.9.3 (both, simpleG and the main exe).
> Now I get virus alert for simpleG only. I assume for main exe it was false alert. But since there is no source code for simpleG, idk about that. Thats why I asked if there is any source code for the gui?

you can manully scan it

https://www.virscan.org/
