### ISSUE TITLE
是否可以增加本地解码和合成视频功能 x64 解密 

### ISSUE THREAD

**Issue by 283832316** [nilaoda/N_m3u8DL-CLI#343]
有写网站有的视频可以解码
有些不可以
我下下来，发现本地也无法解码 是64位密码
[2021-01-22_23-42-58.log](https://github.com/nilaoda/N_m3u8DL-CLI/files/5856912/2021-01-22_23-42-58.log)

**Comment by Nchujx** [comment]
你这个是保利威的视频，已经解出16字节key的话可以先用2.6.3的版本下载

**Comment by Albert9364** [comment]
> 你这个是保利威的视频，已经解出16字节key的话可以先用2.6.3的版本下载

请问保利威的视频怎么才能解出16字节key？谢谢！

**Comment by Nchujx** [comment]
需要就加我qq聊吧 1203083157------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月17日(星期六) 凌晨0:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 是否可以增加本地解码和合成视频功能 x64 解密  (#343)
