### ISSUE TITLE
Unable to download complete movie from Disney+

### ISSUE THREAD

**Issue by Machow8** [nilaoda/N_m3u8DL-CLI#344]
I'm using this your program..

While it worked previously and now don't, something changed from Disney+ side.

Here is a m3u8 url which i'm using to download Soul movie from Disney+: https://vod-akc-sa-east-1.media.dssott.com/oswald/ps01/disney/49d2f2a2-e3f0-4637-81ed-30b62632f088/r/composite_4250k_CENC_CTR_FHD_SDR_5c6a0416-2907-434f-8c8e-a64f924a298d_473f93ca-92d3-45c5-ac1b-b9d46ef2a39b.m3u8

Instead of complete encrypted mp4 movie file, it downloads an 812kb encrypted mp4 file which is just disney opening scene.

Thanks for solving this issue.

**Comment by nilaoda** [comment]
I am trying to solve this.

**Comment by jrSchneider2000** [comment]
Regards Nilaoda, Thanks for sharing this script works in some sites in disney + Latin America only works to extract movies, Please can help correct to download series such as WandaVision or The Mandalorian is impossible ... Thanks and good luck.

**Comment by Machow8** [comment]
@nilaoda There is a browser extension that is able to fully download the entire movie, but, as .ts, which isn't compatible with Bento4 program ( https://www.bento4.com/downloads ) which only supports mp4 file format.

The browser extension is https://github.com/puemos/hls-downloader-web-extension and since it's available in github too, i hope it can help you to solve this issue.

I wish you all the best on that task and thanks for doing your best on solving this!

**Comment by Machow8** [comment]
v2.9.4 fixed issues i was facing.

If something changes again or there are issues with downloading from other services like Netflix and Amazon Prime Video, i'll let you know.

Thanks!

**Comment by jrSchneider2000** [comment]
> v2.9.4 fixed issues i was facing.
> 
> If something changes again or there are issues with downloading from other services like Netflix and Amazon Prime Video, i'll let you know.
> 
> Thanks!

Regards Machow8, Please can you help me to download Netflix, in Prime video and Disney it works super well..Thanks
