### ISSUE TITLE
https://www.pandalive.co.kr/

### ISSUE THREAD

**Issue by wei4430018** [nilaoda/N_m3u8DL-CLI#346]
前辈pandatv视频录制下来的ts文件无法打开，老哥我是一个计算机在校生，想学习下该项目，我想问一下学习该项目需要提前学哪些知识？

**Comment by nilaoda** [comment]
暂时不支持这种fmp4直播~你可以试一下用ffmpeg或者streamlink来录制直播。

本项目的话只要能看懂C#就行了，代码质量一般般，其实没什么值得学习的。。
