### ISSUE TITLE
关于 B站/芒果 的播放和下载参数

### ISSUE THREAD

**Issue by angelkyo** [nilaoda/N_m3u8DL-CLI#35]
ffmpeg下载需要添加以下参数
`-headers "User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"【回车】"Referer: https://www.bilibili.com"【回车】
`
注意：参数里2个回车，一共是三行。这里的User-Agent要和获取链接时的User-Agent一致。

使用mpv.exe播放链接时的参数(只有一行)：
`--http-header-fields="User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36","Referer: https://www.bilibili.com"`

调用mpv.exe播放：
mpv.exe <以上参数> "https://xxxxxxxxxxxxxxxx"

芒果TV的链接播放和下载，与以上相同。

具体可参考：
![Snipaste_2019-11-20_13-43-26](https://user-images.githubusercontent.com/4989290/69212271-cc153600-0b9b-11ea-8940-895d2b3ac3a9.png)

AG视频解析3.7下载
https://www.lanzous.com/b07r5v35e 密码:35n5

另外，B站使用mpv播放，似乎没有限速，很快。
使用ffmpeg下载时，速度总是提不上来，不知道是什么原因？请nilaoda(我老大)解惑，ffmpeg有多线程参数吗？

**Comment by nilaoda** [comment]
* ffmpeg加多个header怎么在cmd里加回车？或程序调用？我只知道能在Powershell里加，用\`r\`n表示回车
```shell
PS C:\Users\nilao> ffmpeg -headers "Referer: http://www.baidu.com`r`nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`r`n" -i "https://play/index.m3u8" -v trace
```
* ffmpeg应该是没有多线程下载的
* 大佬您的软件很强大，最好用其他工具下载资源吧 ffmpeg用来下载太不靠谱了 我这边经常丢包(2017年的时候,现在不知道怎么样) 虽然足够简单. 也可以试试调用curl或者aria2这类下载器大文件(B站)

**Comment by angelkyo** [comment]
CMD好像没法的，我是程序调用
比如C#调用：
`Process p = new Process();
 p.StartInfo.FileName = Directory.GetCurrentDirectory() + "\\ffmpeg.exe";
p.StartInfo.Arguments = "-headers \"User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36\"\r\n\"Referer: https://www.bilibili.com\"\r\n" + " -i \"" + url + "\" -c copy " + "\"" + t_downfname + "\"";
 p.Start();`


你还可以把参数写进Json文件配置，从Json读取参数来启动
![Snipaste_2019-11-21_20-24-42](https://user-images.githubusercontent.com/4989290/69337935-0fa39900-0c9d-11ea-9e0e-5fca7baede3c.png)

**Comment by angelkyo** [comment]
> * ffmpeg加多个header怎么在cmd里加回车？或程序调用？我只知道能在Powershell里加，用`r`n表示回车
> 
> ```shell
> PS C:\Users\nilao> ffmpeg -headers "Referer: http://www.baidu.com`r`nUser-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36`r`n" -i "https://play/index.m3u8" -v trace
> ```
> 
> * ffmpeg应该是没有多线程下载的
> * 大佬您的软件很强大，最好用其他工具下载资源吧 ffmpeg用来下载太不靠谱了 我这边经常丢包(2017年的时候,现在不知道怎么样) 虽然足够简单. 也可以试试调用curl或者aria2这类下载器大文件(B站)

一个启动器源码，你参考下。
[MPV_Luacher.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/3874700/MPV_Luacher.zip)

**Comment by nilaoda** [comment]
> CMD好像没法的，我是程序调用
> 比如C#调用：
> `Process p = new Process(); p.StartInfo.FileName = Directory.GetCurrentDirectory() + "\\ffmpeg.exe"; p.StartInfo.Arguments = "-headers \"User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36\"\r\n\"Referer: https://www.bilibili.com\"\r\n" + " -i \"" + url + "\" -c copy " + "\"" + t_downfname + "\""; p.Start();`
> 
> 你还可以把参数写进Json文件配置，从Json读取参数来启动
> ![Snipaste_2019-11-21_20-38-20](https://user-images.githubusercontent.com/4989290/69338797-e5eb7180-0c9e-11ea-8ae4-51d1e1658628.png)

好的，不过我一般没在线观看的需求  

对了，你可以加一个调用IDM下载哔哩哔哩的整段
[IDManLib.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/3874773/IDManLib.zip)
```C#
new IDManLib.CIDMLinkTransmitterClass().SendLinkToIDM2(
                    item.Url, //URL
                    "https://www.bilibili.com", //Referer
                    "", //Cookies
                    "", //Data
                    "", //Username
                    "", //Userpassword
                    dir, //LocalPath
                    "xyz.mp4",  //LocalFileName
                    1, //Flag
                    "Mozilla/5.0",
                    null
                    ) ;
```

**Comment by angelkyo** [comment]
> 对了，你可以加一个调用IDM下载哔哩哔哩的整段
> [IDManLib.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/3874773/IDManLib.zip)
> 
> ```cs
> new IDManLib.CIDMLinkTransmitterClass().SendLinkToIDM2(
>                     item.Url, //URL
>                     "https://www.bilibili.com", //Referer
>                     "", //Cookies
>                     "", //Data
>                     "", //Username
>                     "", //Userpassword
>                     dir, //LocalPath
>                     "xyz.mp4",  //LocalFileName
>                     1, //Flag
>                     "Mozilla/5.0",
>                     null
>                     ) ;
> ```

收到~我研究一下。
ffmpeg现在下载腾讯/爱奇艺/优酷/等等.....很快的，我这边一集45分钟的剧，1080P的，2分钟不到下载完成。只有一个B站，死慢死慢！
还有就是你的ffmpeg版本太老了！！！！

**Comment by angelkyo** [comment]
> 对了，你可以加一个调用IDM下载哔哩哔哩的整段
报告nilaoda(我老大)，知道B站慢的原因了，是ffmpeg下载，保存时后缀的原因
原来我保存的后缀是.mp4，而B站的格式是flv，ffmpeg下载保存时，会根据后缀来转码！！！
改为.flv下载，直接20x的速度，也就是20分钟的视频，1-2分钟下载完成。

**Comment by nilaoda** [comment]
> > 对了，你可以加一个调用IDM下载哔哩哔哩的整段
> 
> 报告nilaoda(我老大)，知道B站慢的原因了，是ffmpeg下载，保存时后缀的原因
> 原来我保存的后缀是.mp4，而B站的格式是flv，ffmpeg下载保存时，会根据后缀来转码！！！
> 改为.flv下载，直接20x的速度，也就是20分钟的视频，1-2分钟下载完成。

现在ffmpeg这么强了啊😄 不过-c copy的话 后缀应该也不怎么影响速度啊 ffmpeg下优酷那些也是要把ts封装到mp4

**Comment by im1989** [comment]
看到大佬们的交流，肃然起敬😁😁😁

**Comment by StrollStars** [comment]
昨日开发者 @nilaoda 针对芒果TV更新了，但是下载后还是不能播放。看了前面的说明，是不是还需要导出Cookies或手动添加请求头，才能正常播放？
PS： @angelkyo 大佬这么厉害，能做个QQ无损下载解析么？

**Comment by angelkyo** [comment]
> 昨日开发者 @nilaoda 针对芒果TV更新了，但下载后还是不能播放。看了前面的说明，是不是还需要导出Cookies或手动添加请求头，才能正常播放？
> PS： @angelkyo 大佬这么厉害，能做个QQ无损下载解析么？

芒果又小小修改了，
获取的链接还要加一个_t=1575089625594参数才能播放，_t=13位时间戳（毫秒）

**Comment by StrollStars** [comment]
> 
> 
> > 昨日开发者 @nilaoda 针对芒果TV更新了，但下载后还是不能播放。看了前面的说明，是不是还需要导出Cookies或手动添加请求头，才能正常播放？
> > PS： @angelkyo 大佬这么厉害，能做个QQ无损下载解析么？
> 
> 芒果又小小修改了，
> 获取的链接还要加一个_t=1575089625594参数才能播放，_t=13位时间戳（毫秒）
> 重新下载 AG视频解析 v3.9 即可。

更新好快，谢谢。
不过想问下更新了什么？先前的版本我通过“B站选项”的选项卡下载芒果TV播放没有问题，如果是QQ音乐没看到选项卡。
PS：能否单独列出芒果TV？如果不看这个帖子我也不知道哪个选项卡下载芒果TV。

**Comment by nilaoda** [comment]
> > 昨日开发者 @nilaoda 针对芒果TV更新了，但下载后还是不能播放。看了前面的说明，是不是还需要导出Cookies或手动添加请求头，才能正常播放？
> > PS： @angelkyo 大佬这么厉害，能做个QQ无损下载解析么？
> 
> 芒果又小小修改了，
> 获取的链接还要加一个_t=1575089625594参数才能播放，_t=13位时间戳（毫秒）
> 重新下载 AG视频解析 v3.9 即可。

什么平台的M3U8需要加这个参数？PC网页我只加了referer好像就可以正常下载了
![image](https://user-images.githubusercontent.com/20772925/69903546-c60e2900-13d5-11ea-95a7-cf763969d29f.png)

**Comment by angelkyo** [comment]
> 什么平台的M3U8需要加这个参数？PC网页我只加了referer好像就可以正常下载了
> ![image](https://user-images.githubusercontent.com/20772925/69903546-c60e2900-13d5-11ea-95a7-cf763969d29f.png)

芒果的链接，调用mpv.exe播放时，需要加_t=xxxxxxxxxxxxxxxx
下载不需要这个参数。

**Comment by StrollStars** [comment]
@angelkyo 芒果TV下载出错，提示““ ”的类型初始值设定项引发异常。”

**Comment by StrollStars** [comment]
@angelkyo 最新版解析芒果TV又出错，依旧提示““� ”的类型初始值设定项引发异常。”

**Comment by ownerowner** [comment]
你好，你的那个解析器无法下载乐视会员视频，只能前10分钟观看，已经导入乐视VIP了

**Comment by 664236617** [comment]
@angelkyo大佬，优酷的貌似没办法下载了

**Comment by Aurora-1024** [comment]
> > 昨日开发者@nilaoda针对芒果电视更新了，但下载后还是不能播放。看了前面的说明，是不是还需要转换Cookie或手动添加请求头，才能正常播放？
> > PS：@angelkyo大佬这么厉害，能做个QQ无损下载解析么？
> 
> 芒果又小小修改了，
> 获取的链接加上加一个_t = 1575089625594参数才能播放，_t = 13位重新（重复）
> 重新下载AG视频解析v3.9即可。

大佬，AG视频更新链接在哪可以下到？以及AG视频怎么解析的，有开源项目吗？
