### ISSUE TITLE
DAZN CA NFL not working

### ISSUE THREAD

**Issue by PlaceboPRS** [nilaoda/N_m3u8DL-CLI#353]
Hi,

Not sure what information I should share, DAZN CA works fine for all sports except NFL for some reason:

![image](https://user-images.githubusercontent.com/23120453/105812114-e3289280-5fad-11eb-93c9-d215b90a208a.png)

You can see it works as normal until the final segment, then it can't read the last one, combine and download the audio, ends up with a folder full of the individual files.

I've tried reading various other reports to try to figure out the solution myself, tried using headers/cookies (although I'm not really sure which ones I should be including).

.json says VOD true, mpdVideo.m3u8 has #EXT-X-ENDLIST (no idea if either is relevant but I saw issues caused by these in other people's posts).

Here's the log file:

[2021-01-26_07-54-13.log](https://github.com/nilaoda/N_m3u8DL-CLI/files/5871750/2021-01-26_07-54-13.log)

Thanks in advance!

**Comment by nilaoda** [comment]
I will check. It seems that the program has parsed an extra piece.

**Comment by PlaceboPRS** [comment]
Thanks for the reply! I enabled the setting --disableIntegrityCheck and that seems to have resolved it and the download completes and can be decrypted ok! :)

I also have issues with Peacock (sometimes football matches have the wrong length they display eg 55hrs instead of 3hours but can be fixed with ffmpeg) and Viaplay (sometimes when a downloaded file is decrypted it suddenly shrinks to a small size and only shows a fraction of the full event). But I'll try to figure out those issues myself without spamming your issues section!

**Comment by nilaoda** [comment]
> Thanks for the reply! I enabled the setting --disableIntegrityCheck and that seems to have resolved it and the download completes and can be decrypted ok! :)
> 
> I also have issues with Peacock (sometimes football matches have the wrong length they display eg 55hrs instead of 3hours but can be fixed with ffmpeg) and Viaplay (sometimes when a downloaded file is decrypted it suddenly shrinks to a small size and only shows a fraction of the full event). But I'll try to figure out those issues myself without spamming your issues section!

try enable binary merge

**Comment by nilaoda** [comment]
Could you just upload the `dash.mpd`? i cant download from https://dca-voddash-perform.secure.footprint.net/bc1aphlu8kol19sub5bn8uzqb/web/stream.mpd?channel=1407&mta=en&outlet=dazn-ca&plang=en

**Comment by PlaceboPRS** [comment]
Yep no problem, attached 

[stream.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/5872636/stream.zip)

> try enable binary merge

I just grabbed a Peacock event to test and according to the output it did that automatically, audio displays 17hrs 31 mins when decrypted (correct is 2hrs 2 mins and Medianfo displays that ok)

![image](https://user-images.githubusercontent.com/23120453/105831155-aae17e00-5fc6-11eb-9f8f-a156ff80800f.png)
![image](https://user-images.githubusercontent.com/23120453/105831165-af0d9b80-5fc6-11eb-85b9-a2d6e599f117.png)
![image](https://user-images.githubusercontent.com/23120453/105831170-b2088c00-5fc6-11eb-88ae-f806645b1a7d.png)

**Comment by PlaceboPRS** [comment]
Decrypted the video and it's the same:

![image](https://user-images.githubusercontent.com/23120453/105831432-014ebc80-5fc7-11eb-8a1e-32d3791afc08.png)
![image](https://user-images.githubusercontent.com/23120453/105831479-0f9cd880-5fc7-11eb-8481-e18586cdac11.png)

Fortunately as I discovered an easy fix:

ffmpeg -i "video(Audio) decrypted.aac" -t 2:02:00 -c:v copy -c:a copy -c:s copy "video(Audio) decrypted_fixed.aac"

ffmpeg -i "video decrypted.mp4" -t 2:02:00 -c:v copy -c:a copy -c:s copy "video decrypted_fixed.mp4"

![image](https://user-images.githubusercontent.com/23120453/105831619-3ce98680-5fc7-11eb-837c-4294f3b92df3.png)

(obviously every chance these issues are not related to your very awesome N_m3u8DL-CLI! So apologies for bringing them up)

**Comment by nilaoda** [comment]
[N_m3u8DL-CLI_test_0127.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/5874827/N_m3u8DL-CLI_test_0127.zip)

I have modified some codes that calculate the total number of segments. Can you help me test whether there are any excess or missing segments? Best to test multiple websites. Waiting for your reply.

Thanks.

**Comment by PlaceboPRS** [comment]
I can give it a go! Would that help solely with the DAZN issue or with the other issues I raised?

**Comment by nilaoda** [comment]
> I can give it a go! Would that help solely with the DAZN issue or with the other issues I raised?

I tested stream.mpd, result 5636 segs. But I did not test whether it will affect mpd from other websites, so I want you to test it. 😂

**Comment by PlaceboPRS** [comment]
That I can do! :)

**Comment by PlaceboPRS** [comment]
Ok we've tried a few downloads and so far so good, maybe it fixed the issues or maybe we got lucky with the downloads!

Couple of questions/observations, the audio download, is it at all possible that could be done first? That way we can test the encryption key while we wait for the video, also the audio for some reason is always a much slower download, like 1mb/s compared to 30mb/s+ for the video, is that a server issue or it only downloads with one thread?

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/106021042-5988da00-60ff-11eb-8dc4-f937035b0539.png)


I used the [mpd-parser](https://www.npmjs.com/package/mpd-parser) of videojs, the analysis result is also 5637 segments, so I think it may be the problem of MPD itself?

**Comment by Azzuray** [comment]
Does it do the same when you mux it in MKV file ?

**Comment by PlaceboPRS** [comment]
> Does it do the same when you mux it in MKV file ?

Apologies I missed your reply, do you mean the DAZN issue or the Peacock one? But yes it's the same if muxed with MIKVToolnix.
