### ISSUE TITLE
气球云已经不支持手机userAgent观看了,不知道大佬还没有其它好的思路

### ISSUE THREAD

**Issue by buxuku** [nilaoda/N_m3u8DL-CLI#354]
现在气球云用手机userAgent播放,直接提示不支持了.如下图.
![image](https://user-images.githubusercontent.com/7866330/106119491-3bb78580-6190-11eb-9d80-8f1f76a83788.png)

换了各种手机的userAgent也不行.不知道大佬还有没其它好的解决办法,

辛苦大佬了.

**Comment by nilaoda** [comment]
抽空看看

**Comment by nilaoda** [comment]
通过调用js的形式解决了，等测试好发新版本

**Comment by buxuku** [comment]
大佬请问新版本预计什么时候发布呢,或者能否方便指点一下通过js方式手动下载的方法呢?多谢!
