### ISSUE TITLE
批量下载

### ISSUE THREAD

**Issue by benxin123** [nilaoda/N_m3u8DL-CLI#36]
能支持多个M3U8文件顺序下载嘛？

**Comment by faxianzhilu** [comment]
同求批量下载功能，可不可以考虑加入直接拖入TXT文本文件，或者粘贴多行M3U8链接来批量下载的功能，感谢！

**Comment by ownerowner** [comment]
同求，一个一个下载太麻烦，而且还得等待，因为工作忙不能操作电脑，或者外出的人不方便操作。希望能考虑这些项功能感激不尽

**Comment by nilaoda** [comment]
批量下载请使用SimpleGUI来完成 @ownerowner @faxianzhilu @benxin123

**Comment by faxianzhilu** [comment]
感谢解答，的确如此
![截图](https://user-images.githubusercontent.com/33314003/71048289-cea68380-2179-11ea-8781-4a05eb982bf4.png)

**Comment by xiaoyao202** [comment]
批量下载文件命名txt怎么搞

**Comment by faxianzhilu** [comment]
> 
> 
> 批量下载文件命名txt怎么搞

把你抓取的M3U8链接粘贴到TXT文件里，每个链接之间都换个行，然后拖到simplegui里面就可以了

**Comment by nilaoda** [comment]
> 批量下载文件命名txt怎么搞

如果要自定义文件名，使用如下格式
```
文件名1,链接1
文件名2,链接2
文件名3,链接3
```

**Comment by xiaoyao202** [comment]
收到了。谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "nilaoda"<notifications@github.com&gt;; 
发送时间: 2020年2月22日(星期六) 晚上10:19
收件人: "nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;; 
抄送: "╰☆被颩吹濄の嗄迗☆╮"<411570761@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [nilaoda/N_m3u8DL-CLI] 批量下载 (#36)



 
批量下载文件命名txt怎么搞
  
如果要自定义文件名，使用如下格式
 文件名1,链接1 文件名2,链接2 文件名3,链接3

**Comment by hktrace** [comment]
你好.我测试了下80多个文件M3U8.程序直接崩溃~~
