### ISSUE TITLE
SAMPLE-AES

### ISSUE THREAD

**Issue by girod2033** [nilaoda/N_m3u8DL-CLI#361]
Hi.
Will you be adding support for downloading HLS stream with SAMPLE-AES ?

**Comment by girod2033** [comment]
Example:
https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/subscription/stream/playlist.m3u8?cc=RU&g=2448&cdn=ap1&a=1484589502&p=90025276&st=379169935&a=1539152112&p=229004108&st=901903405&a=1545313425&p=218240702&st=858828450&a=1545313878&p=218241116&st=858829955&a=1545313347&p=218240722&st=858829199&a=1545313123&p=218240618&st=858828161&a=1545313921&p=218241098&st=858830349&a=1545314092&p=218240868&st=858829886&a=1545313953&p=218240957&st=858830884&a=1544701245&p=217817390&st=857122586

**Comment by xhlove** [comment]
if you don't have key, you have nothing.

**Comment by girod2033** [comment]
Are you talking about this?

#EXT-X-DISCONTINUITY
#EXT-X-KEY:URI="skd://itunes.apple.com/p229004108/c6",KEYFORMAT="com.apple.streamingkeydelivery",KEYFORMATVERSIONS="1",METHOD=SAMPLE-AES
#EXT-X-KEY:URI="data:text/plain;charset=UTF-16;base64,vgEAAAEAAQC0ATwAVwBSAE0ASABFAEEARABFAFIAIAB4AG0AbABuAHMAPQAiAGgAdAB0AHAAOgAvAC8AcwBjAGgAZQBtAGEAcwAuAG0AaQBjAHIAbwBzAG8AZgB0AC4AYwBvAG0ALwBEAFIATQAvADIAMAAwADcALwAwADMALwBQAGwAYQB5AFIAZQBhAGQAeQBIAGUAYQBkAGUAcgAiACAAdgBlAHIAcwBpAG8AbgA9ACIANAAuADMALgAwAC4AMAAiAD4APABEAEEAVABBAD4APABQAFIATwBUAEUAQwBUAEkATgBGAE8APgA8AEsASQBEAFMAPgA8AEsASQBEACAAQQBMAEcASQBEAD0AIgBBAEUAUwBDAEIAQwAiACAAVgBBAEwAVQBFAD0AIgBBAEEAQQBBAEEASwBZAE4AVABGAE4AagBOAGkAQQBnAEkAQwBBAGcASQBBAD0APQAiAD4APAAvAEsASQBEAD4APAAvAEsASQBEAFMAPgA8AC8AUABSAE8AVABFAEMAVABJAE4ARgBPAD4APAAvAEQAQQBUAEEAPgA8AC8AVwBSAE0ASABFAEEARABFAFIAPgA=",KEYFORMAT="com.microsoft.playready",KEYFORMATVERSIONS="1",METHOD=SAMPLE-AES
#EXT-X-KEY:URI="data:text/plain;base64,AAAAOHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAABgSEAAAAAANplNMYzYgICAgICBI88aJmwY=",KEYFORMAT="urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed",KEYFORMATVERSIONS="1",METHOD=SAMPLE-AES
#EXT-X-MAP:URI="https://vod-ap1-aoc.tv.apple.com/itunes-assets/HLSVideo124/v4/fd/e8/a4/fde8a484-e848-c95d-9fa7-6e2420a2cf3c/P229004108_A1539152112_ru_audio_gr2448-0.mp4"

**Comment by Azzuray** [comment]
You can do nothing with this.
