### ISSUE TITLE
下载央视网视频后，播放时都是马赛克

### ISSUE THREAD

**Issue by okyer** [nilaoda/N_m3u8DL-CLI#366]
大佬，你好。感谢大佬辛勤付出，为我们贡献了这么强大好用的视频下载利器。

我在下载央视网视频时，都可以成功下载到本地并合并成mp4，但是播放都是马赛克，换了几个视频源都是这样，请求是什么原因？

[国宝回家] https://dh5.cntv.myalicdn.com/asp/h5e/hls/main/0303000a/3/default/a97b017b4b874c0a899e7c45a4501a07/main.m3u8?maxbr=2048&contentid=15120519184043&cdnCode=VOD-HLS-CDN-HW

**Comment by nilaoda** [comment]
将链接里的/h5e删除

**Comment by okyer** [comment]
@nilaoda 果然好用，多谢多谢。
Happy 牛 Year.

**Comment by LiynXu** [comment]
删除H5e之后就变成无权限了
