### ISSUE TITLE
合并后发现不完整，丢失了很多Part_xxx.ts分段

### ISSUE THREAD

**Issue by heiyutian** [nilaoda/N_m3u8DL-CLI#367]
m3u8原文件时长2个多小时，下载合并后只有1个小时多点，下载选择的是2.9.5，GUI面板只勾选了二进制合并和不使用系统代理。
通过下载目录的子文件夹发现，合并出了Part_ Part_1 Part_2 Part_3四个ts大文件，最后下载目录只有一个ts文件，这个ts文件的时长发现是Part_3的，只有1个多小时，我把Part_ Part_1 Part_2 Part_3全选发现时长才是对的
怎么给你私发链接测试一下

**Comment by nilaoda** [comment]
邮箱 nilaoda@live.com

**Comment by heiyutian** [comment]
> 邮箱 [nilaoda@live.com](mailto:nilaoda@live.com)

刚给你发了，发送之前我还又测试了一遍，下载目录的文件时长还是Part_3的

**Comment by nilaoda** [comment]
二进制合并只是把所有ts分片尾首相接起来，不会修复时间轴，你可以合并完之后手动重新封装一下
```
ffmpeg -i 4590507713376314_index.ts -c copy 4590507713376314_index_fix.ts
```
