### ISSUE TITLE
cctv下载出来的视频有问题

### ISSUE THREAD

**Issue by barnett2010** [nilaoda/N_m3u8DL-CLI#377]
声音是正常的，但画面是花屏，完全没有图像

https://dh5.cntv.qcloudcdn.com/asp/h5e/hls/8000/0303000a/3/default/7533dea1d9d44937b98db2e1044771d0/8000.m3u8

**Comment by barnett2010** [comment]
https://tv.cctv.com/2020/05/01/VIDEws7ayG7LvnVtvdP9hExi200501.shtml?spm=C16868484111.P5Oitm95sIJI.0.0

**Comment by xhlove** [comment]
估计你没升级版本
参考 https://github.com/nilaoda/N_m3u8DL-CLI/issues/366

**Comment by barnett2010** [comment]
我是295版本，
果然 删除h5e就好了
https://dh5.cntv.qcloudcdn.com/asp/hls/8000/0303000a/3/default/7533dea1d9d44937b98db2e1044771d0/8000.m3u8

**Comment by waney** [comment]
```
12:48:47.366 / (NORMAL) 开始解析 https://dh5.cntv.qcloudcdn.com/asp/hls/8000/0303000a/3/default/7533dea1d9d44937b98db2e1044771d0/8000.m3u8
12:48:47.368 / (ERROR) 参数“name”不能是空字符串。
参数名: name
12:48:47.387 / (NORMAL) 远程服务器返回错误: (403) 已禁止。
12:48:47.387 / (ERROR) 远程服务器返回错误: (403) 已禁止。
12:48:48.389 / (ERROR) 参数“name”不能是空字符串。
```
如何解决地址无效的问题
