### ISSUE TITLE
i need to download DRM Mpd files..

### ISSUE THREAD

**Issue by tvserial** [nilaoda/N_m3u8DL-CLI#379]
i have kid & key for being decrypt..but need to download the files first,,,please help me anyone..

**Comment by nilaoda** [comment]
Just input mpd link...

**Comment by tvserial** [comment]
> Just input mpd link...

Thanks,,working..but i cant downlad drm videos of vtt subtitle..can you help me??
https://zee5vod.akamaized.net/drm1/elemental/dash/TV_SHOWS/ZEE_TV/March2021/01032021/Seamless/BQC_Tujhse_Hai_Raabta_CS_Ep613_Seamless_01032021_hi_b7e1de217af84a6baa4dd8a49eb49391/manifest-en.vtt

**Comment by nilaoda** [comment]
> > Just input mpd link...
> 
> Thanks,,working..but i cant downlad drm videos of vtt subtitle..can you help me??
> https://zee5vod.akamaized.net/drm1/elemental/dash/TV_SHOWS/ZEE_TV/March2021/01032021/Seamless/BQC_Tujhse_Hai_Raabta_CS_Ep613_Seamless_01032021_hi_b7e1de217af84a6baa4dd8a49eb49391/manifest-en.vtt

only support video/audio now.
