### ISSUE TITLE
直播流m3u8重复下载视频片段

### ISSUE THREAD

**Issue by lsjiaowo** [nilaoda/N_m3u8DL-CLI#38]
作者您好！
我有一个m3u8的地址，是直播流。软件运行显示重复下载已complete的视频片段，导致最终录制的视频混乱，不知道什么原因。win10系统，软件最新版，默认配置

截图如下：

![重复下载片段](https://user-images.githubusercontent.com/49240966/70388013-4ee52000-19e7-11ea-8d26-9d24e674c798.PNG)

**Comment by nilaoda** [comment]
暂时不推荐使用本软件下载直播流 之后会修复这些混乱逻辑
