### ISSUE TITLE
M3U8地址無效

### ISSUE THREAD

**Issue by qbabe** [nilaoda/N_m3u8DL-CLI#383]
@nilaoda
該視頻網站 : HAMI
我也遇到同樣問題
我有加上請求頭了但卻顯示地址無效
能不能請求幫忙告訴我哪裡出了問題
目前我的Hamivideo是有時效性的
時間到了的就不能看了
可以的話能不能請ower @nilaoda nilaoda告訴我該怎麼做?
拜託 拜託您了
謝謝

![002](https://user-images.githubusercontent.com/38503091/109040687-268b3380-7709-11eb-8104-8621aa4f370a.jpg)
![000](https://user-images.githubusercontent.com/38503091/109041756-571f9d00-770a-11eb-8598-8422da88797a.jpg)
![001](https://user-images.githubusercontent.com/38503091/109040703-2ab75100-7709-11eb-8719-fd470ce64227.jpg)

**Comment by qbabe** [comment]
> @nilaoda
> 該視頻網站 : HAMI
> 我也遇到同樣問題
> 我有加上請求頭了但卻顯示地址無效
> 能不能請求幫忙告訴我哪裡出了問題
> 目前我的Hamivideo是有時效性的
> 時間到了的就不能看了
> 可以的話能不能請ower @nilaoda nilaoda告訴我該怎麼做?
> 拜託 拜託您了
> 謝謝
> 
> ![002](https://user-images.githubusercontent.com/38503091/109040687-268b3380-7709-11eb-8104-8621aa4f370a.jpg)
> ![000](https://user-images.githubusercontent.com/38503091/109041756-571f9d00-770a-11eb-8598-8422da88797a.jpg)
> ![001](https://user-images.githubusercontent.com/38503091/109040703-2ab75100-7709-11eb-8719-fd470ce64227.jpg)

**Comment by argo5107** [comment]
另外一個國語音軌要用腳本去解析
再用軟體搭配下載
