### ISSUE TITLE
M3U8 with DRM

### ISSUE THREAD

**Issue by p2mgrup** [nilaoda/N_m3u8DL-CLI#384]
Hello,
Is it possible to download a a video with DRM??
I have a link to m3u8 and also DRM key. 
When i download this video, it's a .ts file which cannot be decrypted by ffmpeg or/and mp4decrypt.
Do you have maybe any solution to 'download' a video by N_m3u8DL-CLI with DRM key command?

**Comment by xhlove** [comment]
```bash
    --useKeyFile File           使用外部16字节文件定义AES-128解密KEY
    --useKeyBase64 Base64String 使用Base64字符串定义AES-128解密KEY
    --useKeyIV     HEXString    使用HEX字符串定义AES-128解密IV
```

**Comment by p2mgrup** [comment]
I think it's not working. This is not AES-128, in M3U8 file I have : 

#EXT-X-KEY:METHOD=SAMPLE-AES

and for example this is a DRM key:

WidevineDecryptor: Found key: db5c432345ae01f732bb21d0ab4c25ef (KID=86950d91fcd10e43aafd150ccd35f980)

So could you someone paste me how this command should looks for example?

**Comment by nilaoda** [comment]
paste the log

**Comment by p2mgrup** [comment]
@nilaoda 
Deleted the log :( but could you provide me the command which should to be used to download a .ts file? is it possible to convert also to mp4 file instant?

should to be for example : "1.m3u8 --useKeyIV db5c432345ae01f732bb21d0ab4c25ef" ??

**Comment by p2mgrup** [comment]
and part of this log when i used a command "33.m3u8 --useKeyIV "db5c432345ae01f732bb21d0ab4c25ef"

but in the program also i have info "AES is not supported yet..."
In the log i don't have this msg :


11:36:47.499 / (NORMAL) Start Parsing 33.m3u8
11:36:48.237 / (NORMAL) Parsing M3u8 Content
11:36:48.531 / (NORMAL) Writing Json: [meta.json]
11:36:50.014 / (NORMAL) Master List Found
11:36:52.184 / (NORMAL) Writing Master List Json: [playLists.json]
11:36:52.186 / (NORMAL) Auto Selected Best Definition: https://n-22-11.dcs.redcdn.pl/hls/o2/tvnplayer/vod/21_400_26776_0002/LIBCODER_HLS_720/16a52155-09b5-4dab-ab12-a966d040a18d/playlist.smil/playlist.m3u8?bandwidth=2800000&id=6&
11:36:52.187 / (NORMAL) Start Re-Parsing...
11:36:53.095 / (NORMAL) Parsing M3u8 Content
11:36:53.225 / (NORMAL) Writing Json: [meta.json]
11:36:53.704 / (NORMAL) Has External Audio Track
11:36:53.791 / (NORMAL) Start Downloading
11:36:54.377 / (NORMAL) Reading File Info...
11:36:57.208 / (NORMAL) PID 0x21: Video h264 (High), yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 90k tbn, 50 tbc
11:37:06.250 / (NORMAL) 强制退出: 强制

**Comment by nilaoda** [comment]
try enable binary merge manually

**Comment by p2mgrup** [comment]
so the correct command will be '33.m3u8 --useKeyIV "db5c432345ae01f732bb21d0ab4c25ef" --enableBinaryMerge ' ??

**Comment by p2mgrup** [comment]
It's not working.
Steps which i done :
1. Use the command : '33.m3u8 --useKeyIV "db5c432345ae01f732bb21d0ab4c25ef" --enableBinaryMerge' then is download a video .ts file which cannot be opened in VLC.
2. convert this ts file to mp4 in ffmpeg - this file is encrypted.
3. use command to decrypt this file - doesn't work - still this file is encrypted 

I'm preety sure that this key is valid.
Are you able to help me, please ;(

**Comment by nilaoda** [comment]
> I think it's not working. This is not AES-128, in M3U8 file I have :
> 
> #EXT-X-KEY:METHOD=SAMPLE-AES
> 
> and for example this is a DRM key:
> 
> WidevineDecryptor: Found key: db5c432345ae01f732bb21d0ab4c25ef (KID=86950d91fcd10e43aafd150ccd35f980)
> 
> So could you someone paste me how this command should looks for example?

Use command `33.m3u8 --enableBinaryMerge`.  

Then
1. rename `33.ts` to `33.mp4`  
2. `mp4decrypt.exe --key 86950d91fcd10e43aafd150ccd35f980:db5c432345ae01f732bb21d0ab4c25ef33.mp4 dec.mp4`

**Comment by p2mgrup** [comment]
Ok,
I will try and will get back to you with results :)

**Comment by p2mgrup** [comment]
It's not working :( 
I have encrypted a video ;(
Could you try to do it by yourself?

**Comment by mmshasan** [comment]
> It's not working :(
> I have encrypted a video ;(
> Could you try to do it by yourself?

try
mp4decrypt.exe --key 1:db5c432345ae01f732bb21d0ab4c25ef 33.mp4 output.mp4

1 is the id which can be found using mp4info.exe

**Comment by p2mgrup** [comment]
also its not working ;(
Could someone try to do it by yourself and check it?
I performed all steps:

1) command "33.m3u8 --enableBinaryMerge"
2) then use command "ffmpeg -i '1.ts' -c copy 1.mp4.
3) use command "mp4decrypt.exe --key 1:db5c432345ae01f732bb21d0ab4c25ef 1.mp4 output.mp4'

then file is still encrypted.
Could you help me please?:)

**Comment by nilaoda** [comment]
> also its not working ;(
> Could someone try to do it by yourself and check it?
> I performed all steps:
> 
> 1. command "33.m3u8 --enableBinaryMerge"
> 2. then use command "ffmpeg -i '1.ts' -c copy 1.mp4.
> 3. use command "mp4decrypt.exe --key 1:db5c432345ae01f732bb21d0ab4c25ef 1.mp4 output.mp4'
> 
> then file is still encrypted.
> Could you help me please?:)

skip step 2

**Comment by p2mgrup** [comment]
so how i should change .ts to mp4, only changing the 'extension' from .ts to .mp4?

**Comment by nilaoda** [comment]
> so how i should change .ts to mp4, only changing the 'extension' from .ts to .mp4?

yep

**Comment by p2mgrup** [comment]
OK, I will try, but in mediainfo i have this info :

FileExtension_Invalid                    : ts m2t m2s m4t m4s tmf ts tp trp ty

**Comment by p2mgrup** [comment]
not working, mp4decrypt creating a file with 0 kb as a output.

**Comment by nilaoda** [comment]
I saw the m3u8, it is MPEG-TS container, but mp4decrypt support mp4 container only.

![image](https://user-images.githubusercontent.com/20772925/109387987-6d626e80-793f-11eb-8831-558d8be35028.png)

**Comment by p2mgrup** [comment]
Ok, so i suppose that we can't do anything with that case?

**Comment by p2mgrup** [comment]
Ok, one more question, because when i opened a m3u8 from this link : https://r.cdn-ncplus.pl/ncplusgo04-vodhlsdrm01/CAP_21032316/CAP_21032316.m3u8

and then opened into your software, after choose the audio, nothing is happened. Program is closing with that logs:

LOG 2021/02/27
Save Path: C:\FFmpeg\Logs
Task Start: 2021/02/27 14:23:47
Task CommandLine: "C:\FFmpeg\N_m3u8DL-CLI_v2.9.5.exe" 

14:23:47.926 / (NORMAL) Start Parsing 2.m3u8
14:23:48.032 / (NORMAL) Parsing M3u8 Content
14:23:53.537 / (NORMAL) Writing Json: [meta.json]
14:23:53.668 / (NORMAL) Master List Found
14:23:54.079 / (NORMAL) Writing Master List Json: [playLists.json]
14:23:54.081 / (NORMAL) Auto Selected Best Definition: file:///C:/FFmpeg/CAP_21032316-avc1_2499968=13.m3u8
14:23:54.082 / (NORMAL) Start Re-Parsing...


Can we do something more?

**Comment by nilaoda** [comment]
you should paste the link into software, not m3u8 file.

![image](https://user-images.githubusercontent.com/20772925/109388680-8ec55980-7943-11eb-9f63-232011aabaec.png)

**Comment by p2mgrup** [comment]
Ahh,
I don't know how it works, but in API i can see that it's a mp4 file, but also is downloading a mp4 file and i can't do nothing with that file.

part of API :+1: 
{"Id":580402,"Url":"https://r.cdn-ncplus.pl/ncplusgo04-vodhlsdrm01/CAP_21032316/CAP_21032316.m3u8","Type":2,"Protection":5,"KeyId":"","AudioBitrate":"0","VideoBitrate":"0","MediaTracks":[{"Type":"Video","Codec":"avc1.64001f,mp4a.40.2","Bitrate":3055417,"Index":7,"Name":"720p-1","DisplayName":"720p / 2 441 kbps"},{"Type":"Video","Codec":"avc1.4d401f,mp4a.40.2","Bitrate":2472455,"Index":6,"Name":"720p","DisplayName":"720p / 1 953 kbps"},{"Type":"Video","Codec":"avc1.42c01f,mp4a.40.2","Bitrate":1306455,"Index":5,"Name":"576p","DisplayName":"576p / 977 kbps"},{"Type":"Video","Codec":"avc1.42c01e,mp4a.40.2","Bitrate":840055,"Index":4,"Name":"450p","DisplayName":"450p"},{"Type":"Video","Codec":"avc1.42c015,mp4a.40.2","Bitrate":606855,"Index":3,"Name":"270p","DisplayName":"270p / 391 kbps"},{"Type":"Audio","Index":0,"Name":"pl","DisplayName":"Polskie"},{"Type":"Audio","Index":1,"Name":"qaa","DisplayName":"Oryginalne"},{"Type":"Text","Index":2,"Name":"pl","DisplayName":"Polskie"}]}],"Duration":"00:49:00","DurationSeconds":2940,"OrderNumber":1}],"Cap":{"SessionId":"adf708d3-7c69-44a7-a837-7c45eb5075e0","SessionTimeoutSeconds":0,"CAPPublicUrl":"https://cap-ncplusgo.ncplus.pl/v1/CAP/Ping","CAPIntervalSeconds":180,"CAPRetryCount":1,"CAPRetrySeconds":1,"CAPConnectionTimeoutSeconds":30},"Signature":"781F36AD6806B0527DD2235F95FA3D7AE6C7BAB2","PlaybackConditions":{"GlobalTimeShiftDisabled":false},"Result":{"Success":true,"Code":0}}

And also the file which is a downloaded is a .ts file.

**Comment by p2mgrup** [comment]
This is a part of mpdVideo.m3u8 which is generated by your app ;)

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-PLAYLIST-TYPE:VOD
#CREATED-BY:N_m3u8DL-CLI
#EXT-VIDEO-WIDTH:1280
#EXT-VIDEO-HEIGHT:720
#EXT-CODEC:avc1.64001f
#EXT-TBR:2499.968
#EXT-X-MAP:URI="https://ec03.waw2.cache.orange.pl/canal/v/canal/vmp-ncplusgo24-voddashdrm01/CAP_21032316/CAP_21032316-avc1_2499968=13-init.mp4"
#EXT-X-KEY:METHOD=PLZ-KEEP-RAW,URI="None"
#EXTINF:2.00
https://ec03.waw2.cache.orange.pl/canal/v/canal/vmp-ncplusgo24-voddashdrm01/CAP_21032316/CAP_21032316-avc1_2499968=13-0.mp4
#EXTINF:2.00
https://ec03.waw2.cache.orange.pl/canal/v/canal/vmp-ncplusgo24-voddashdrm01/CAP_21032316/CAP_21032316-avc1_2499968=13-20000000.mp4
#EXTINF:2.00
https://ec03.waw2.cache.orange.pl/canal/v/canal/vmp-ncplusgo24-voddashdrm01/CAP_21032316/CAP_21032316-avc1_2499968=13-40000000.mp4
#EXTINF:2.00
https://ec03.waw2.cache.orange.pl/canal/v/canal/vmp-ncplusgo24-voddashdrm01/CAP_21032316/CAP_21032316-avc1_2499968=13-60000000.mp4
#EXTINF:2.00

so why .ts files is downloaded, not mp4?

**Comment by p2mgrup** [comment]
Ok with video, has been done, but i have problem with audio, because the audio file is .aac and i cannot decrypt this file.
Do you have any suggest?

**Comment by YssDiamond** [comment]
You cant just download any link and expect it to be decrypted with that key even if u can download it u will never decrypt it with that key since the m3u8 urls have fairplay so your widevine key wont work look for .mpd or .mp4 links

**Comment by p2mgrup** [comment]
Its working.

**Comment by sss-aaa** [comment]
q/ how i can download this link 
https://d1z78r8i505acl.cloudfront.net/media/Em4JFqsoVuJUQ/35efe23f/master.m3u8
can you help me ?

**Comment by RiyaSharma-123** [comment]
> Hello, Is it possible to download a a video with DRM?? I have a link to m3u8 and also DRM key. When i download this video, it's a .ts file which cannot be decrypted by ffmpeg or/and mp4decrypt. Do you have maybe any solution to 'download' a video by N_m3u8DL-CLI with DRM key command?

Hi I too have a m3u8 link and its key But I dont know how to download the video. Can you please help ? I'll provide the links
m3u8 Link = https://media-cdn.classplusapp.com/drm/67c0167bdaffe7a8566144da/playlist.m3u8

{
  "KEYS": [
    "6e3d47baf0cd91c5179a2f9725a84007:6f9dccc4787484fb3169aeeca63f1a8b",
    "070cb52973f757606d61c765c65be755:4c7379caff9557168e5ab92bbf3a03b4",
    "3ca49a72e98dda8e2b9360c7de97e9ec:e27d675a93af22a7c398f5b32ddf20b5"
  ],
  "KEY_STRING": "--key 6e3d47baf0cd91c5179a2f9725a84007:6f9dccc4787484fb3169aeeca63f1a8b --key 070cb52973f757606d61c765c65be755:4c7379caff9557168e5ab92bbf3a03b4 --key 3ca49a72e98dda8e2b9360c7de97e9ec:e27d675a93af22a7c398f5b32ddf20b5",
  "MPD": "https://media-cdn.classplusapp.com/drm/wv/67c0167bdaffe7a8566144da/8982fa25b752a3f28a497b4b10a45443/8982fa25b752a3f28a497b4b10a45443.mpd?key=null&hdnts=URLPrefix=aHR0cHM6Ly9tZWRpYS1jZG4uY2xhc3NwbHVzYXBwLmNvbS9kcm0vd3YvNjdjMDE2N2JkYWZmZTdhODU2NjE0NGRhLzg5ODJmYTI1Yjc1MmEzZjI4YTQ5N2I0YjEwYTQ1NDQz~Expires=1744058269~hmac=c89a35975f978cd20aa5c7cac2a068896335aa6a2850485187439111548857a1",
  "PSSH": "AAAAXHBzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAADwSEG49R7rwzZHFF5ovlyWoQAcSEDykmnLpjdqOK5Ngx96X6ewSEAcMtSlz91dgbWHHZcZb51VI49yVmwY=",
  "TOTAL_KEYS": 3,
  "success": true
}
