### ISSUE TITLE
Mandarin and cantonese language cannot choose downloading

### ISSUE THREAD

**Issue by frank-ZHAO1983** [nilaoda/N_m3u8DL-CLI#39]
iqiyi video with mandarin and cantonese language, however, when choose the cantonese, it still download the video of mandarin. Could u plz fix this little bug? much obliged!

**Comment by nilaoda** [comment]
could you please give me a link? i will try to fix it.

**Comment by frank-ZHAO1983** [comment]
> could you please give me a link? i will try to fix it.

Thank s for ur timely reply. Here is the link https://www.iqiyi.com/v_19rrj5q1y8.html 
As u see this vedio is with mandarine and cantonese language. I have tried many times to download the cantonese, but it failed every time. Please check it out when you are free.

And for youku and tencent videos which have 1080p and 4k options, the js script could only parse out 1080p. It will be great if you can solve the 4k option for youku and tecent videos. 

Have a good day!

Many thanks!

**Comment by jiarukai** [comment]
@nilaoda 能编译一个 Mac OS 版本吗 谢谢您了

**Comment by nilaoda** [comment]
https://github.com/nilaoda/Blog/issues/34
