### ISSUE TITLE
merge audio-video

### ISSUE THREAD

**Issue by cisko99za** [nilaoda/N_m3u8DL-CLI#390]
hi, excellent software but on video with drm the download is separate: an audio file and a video file.
need to decrypt (with key and ID) then merge with ffmpeg...
if you integrate mp4decrypt (or also put on same folder of N_m3u8DL-CLI) and same thing for ffmpeg, it would be easier if the program after downloading made a merge of the 2 files (audio&video) and decrypted creating a merged and decrypted final file... is this possible in future releases?
i have try package N_m3u8DL-CLI_v2.9.5_with_ffmpeg_and_SimpleG but same thing: one file audio and one file video...

**Comment by YssDiamond** [comment]
+1 great suggestion would love it to

**Comment by nilaoda** [comment]
i think youd better do it yourself
