### ISSUE TITLE
DMM download stopping part way through

### ISSUE THREAD

**Issue by philolisopher** [nilaoda/N_m3u8DL-CLI#398]
I'm downloading a stream from DMM, and I manage to get it started. However, it downloads a certain amount of parts and then stops. The download keeps trying to restart but fails to. 

I'll admit that I'm retarded when it comes to all of this stuff.

Thanks for any help

**Comment by philolisopher** [comment]
Hey, I think I fixed it.

**Comment by ustr0aTe** [comment]
can you share how you fix the problem?
im suck at same problem download 3part ,stop and show waiting for key.
