### ISSUE TITLE
Download never finishes

### ISSUE THREAD

**Issue by firsttobebear** [nilaoda/N_m3u8DL-CLI#400]
My parameters currently are:
`[Link, "--maxSpeed", "10000", "--retryCount", "100", "--minThreads", String(DownloadThreads), "--maxThreads", String(DownloadThreads), "--saveName", "Downloaded-Vod", "--enableDelAfterDone", "--workDir", process.cwd() + "/Temp"`

When the video gets nearly done downloading it keeps retrying: 
![image](https://user-images.githubusercontent.com/37055787/110581593-b2488b00-811f-11eb-9b45-8484565af27c.png)

I have restarted the program multiple times and it happens at the exact same download segment.

The link I am trying to download is this: https://d2nvs31859zcd8.cloudfront.net/589dd4225d5d4f396e1d_xqcow_41925934222_1615308072/chunked/index-dvr.m3u8

**Comment by nilaoda** [comment]
Are you running out of disk space?

![image](https://user-images.githubusercontent.com/20772925/110658458-a979b700-81fc-11eb-8ec8-cc0dfebf51bd.png)

**Comment by firsttobebear** [comment]
No thats the size of the file. I have over 800 gb of space: 
![image](https://user-images.githubusercontent.com/37055787/110677607-346d9980-818a-11eb-91d6-0759a588ed0b.png)

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/110807380-f1144780-82bd-11eb-9d33-004dae5abfe0.png)

some segments return `403`.

**Comment by firsttobebear** [comment]
Yea apparently for copyrighted music sections for twitch vods they return that. I have realized that I have been using the wrong URL to download these so I have fixed it and the new URL doesn't have these missing segments.
