### ISSUE TITLE
v2.9.6 下载后文件损坏

### ISSUE THREAD

**Issue by sadlulu** [nilaoda/N_m3u8DL-CLI#401]
测试下载地址：
https://stream.savvyuni.com.cn/88473e6df54b4de49137eeb52a7c4ca7/7487f68051b447c3bf75811307abcfa3-9b4252d030005ba778fff8d1bfeb4728-sd-encrypt-stream.m3u8

下载没有问题，下载完之后mp4文件无法打开，potplayer,windows自带的,和itunes都显示文件损坏
尝试了ts格式，还是无法加载

**Comment by nilaoda** [comment]
encrypt-stream.m3u8

本程序不支持阿里云解密

**Comment by yh371174229** [comment]
@nilaoda 可以提供网课视频账号，大佬是否有兴趣帮忙解决阿里云视频的解密
