### ISSUE TITLE
[BUG]SimpleG无法保存BASEURL参数，且带参数启动也不能传递

### ISSUE THREAD

**Issue by EX-XD** [nilaoda/N_m3u8DL-CLI#412]
我在SimpleG中设置好请求头和BASEURL后关闭应用，打开后只有请求头保留，BASEURL并未保留，并且M3U8地址自动填写了请求头的“Referer:”段后面的URL

启动参数完整复制下来从CMD带参数启动SimpleG，也跟直接双击启动效果一样。

附设置完后的启动参数：
"" --headers "Referer:https://*******/" --baseUrl "https://********/" --enableDelAfterDone

**Comment by nilaoda** [comment]
本来就没有支持保存baseurl的。 CMD参数是用于启动N_m3u8DL-CLI的，对simpleg没有作用
