### ISSUE TITLE
Sample-AES Decrypt Problem (v2.9.7)

### ISSUE THREAD

**Issue by n1tr099** [nilaoda/N_m3u8DL-CLI#418]
I downloaded without problems from apple tv (video/audio) but I cannot decrypt these files with the widevine keys that the console gives me. I have no problem downloading from any other platform except this one. Am I skipping a previous step? Could you help me?

Video
https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/subscription/stream/playlist.m3u8?cc=IN&g=290&cdn=ak&a=1484589502&p=90025276&st=379170910&a=1547750479&p=233890538&st=922959506&a=1556322982&p=233263262&st=920253443&a=1556323018&p=233263325&st=920255512&a=1555805268&p=232873115&st=918639663&a=1555805355&p=232873142&st=918637881&a=1555805098&p=232873302&st=918638462&a=1555805391&p=232873208&st=918638782&a=1555805362&p=232873256&st=918638306&a=1555805418&p=232873307&st=918639694

Audio
https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/subscription/stream/playlist.m3u8?cc=IN&g=2448&cdn=ak&a=1484589502&p=90025276&st=379169935&a=1547750479&p=233890538&st=922959632&a=1556322982&p=233263262&st=920253483&a=1556323018&p=233263325&st=920255499&a=1555805268&p=232873115&st=918639655&a=1555805355&p=232873142&st=918637934&a=1555805098&p=232873302&st=918639273&a=1555805391&p=232873208&st=918638729&a=1555805362&p=232873256&st=918638242&a=1555805418&p=232873307&st=918639711

Console
key: b4f101237a31de014427080476f84b3b (KID=000000000df0e2ea6331342020202020)
key: 5aa6b017738c8b2d5e67f72948e6ccb7 (KID=000000000df0e2ea6336202020202020)

This is the command line i use. Am I forgetting something?
mp4decrypt --key 1:b4f101237a31de014427080476f84b3b --show-progress "playlist_20210325221144.mp4" video.mp4
mp4decrypt --key 1:5aa6b017738c8b2d5e67f72948e6ccb7 --show-progress "playlist_20210325180848.eac3" audio.eac3

**Comment by nilaoda** [comment]
Please make sure that the key matches the downloaded stream.

**Comment by n1tr099** [comment]
I've been doing some tests... the keys only work in specific resolutions/audios. For example i cant decrypt at 1080 resolution or eac3 audio. What is this about? If the keys are the same. Is it possible that the console is not giving me all the keys or what am i missing?

**Comment by p2mgrup** [comment]
Are you providing correct id related to that file?
Which value you have in mp4info output?

**Comment by n1tr099** [comment]
The id is correct. Attached mp4info output "decrypted"
Video
[playlist_20210328183248.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/6218226/playlist_20210328183248.txt)
Audio
[playlist_20210328184623.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/6218227/playlist_20210328184623.txt)

**Comment by p2mgrup** [comment]
You dont have info in mediainfo that this file is encrypted so mp4decrypt 'doesnt know" that v/a should be decrypted.

**Comment by twizt3dkitty** [comment]
I'm pretty sure d+ 1080 requires an L1 key.  So your probably using L3 keys.

**Comment by n1tr099** [comment]
> You dont have info in mediainfo that this file is encrypted so mp4decrypt 'doesnt know" that v/a should be decrypted.

The file is still encrypted even though it has already been decrypted with its respective key, I don't know if I explain myself. Encrypted attached mp4info output.
Video
[video.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/6220209/video.txt)
Audio
[audio.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/6220208/audio.txt)

**Comment by n1tr099** [comment]
> I'm pretty sure d+ 1080 requires an L1 key. So your probably using L3 keys.

You may be right, im using L3 keys. Where can I get the L1 key? Its possible?

**Comment by momoko2806** [comment]
> I downloaded without problems from apple tv (video/audio) but I cannot decrypt these files with the widevine keys that the console gives me. I have no problem downloading from any other platform except this one. Am I skipping a previous step? Could you help me?
> 
> Video
> https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/subscription/stream/playlist.m3u8?cc=IN&g=290&cdn=ak&a=1484589502&p=90025276&st=379170910&a=1547750479&p=233890538&st=922959506&a=1556322982&p=233263262&st=920253443&a=1556323018&p=233263325&st=920255512&a=1555805268&p=232873115&st=918639663&a=1555805355&p=232873142&st=918637881&a=1555805098&p=232873302&st=918638462&a=1555805391&p=232873208&st=918638782&a=1555805362&p=232873256&st=918638306&a=1555805418&p=232873307&st=918639694
> 
> Audio
> https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/subscription/stream/playlist.m3u8?cc=IN&g=2448&cdn=ak&a=1484589502&p=90025276&st=379169935&a=1547750479&p=233890538&st=922959632&a=1556322982&p=233263262&st=920253483&a=1556323018&p=233263325&st=920255499&a=1555805268&p=232873115&st=918639655&a=1555805355&p=232873142&st=918637934&a=1555805098&p=232873302&st=918639273&a=1555805391&p=232873208&st=918638729&a=1555805362&p=232873256&st=918638242&a=1555805418&p=232873307&st=918639711
> 
> Console
> key: b4f101237a31de014427080476f84b3b (KID=000000000df0e2ea6331342020202020)
> key: 5aa6b017738c8b2d5e67f72948e6ccb7 (KID=000000000df0e2ea6336202020202020)
> 
> This is the command line i use. Am I forgetting something?
> mp4decrypt --key 1:b4f101237a31de014427080476f84b3b --show-progress "playlist_20210325221144.mp4" video.mp4
> mp4decrypt --key 1:5aa6b017738c8b2d5e67f72948e6ccb7 --show-progress "playlist_20210325180848.eac3" audio.eac3

mp4decrypt --key 1:b4f101237a31de014427080476f84b3b --key 2:5aa6b017738c8b2d5e67f72948e6ccb7 --show-progress "playlist_20210325221144.mp4" video.mp4 Try This

**Comment by n1tr099** [comment]
> > I downloaded without problems from apple tv (video/audio) but I cannot decrypt these files with the widevine keys that the console gives me. I have no problem downloading from any other platform except this one. Am I skipping a previous step? Could you help me?
> > Video
> > https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/subscription/stream/playlist.m3u8?cc=IN&g=290&cdn=ak&a=1484589502&p=90025276&st=379170910&a=1547750479&p=233890538&st=922959506&a=1556322982&p=233263262&st=920253443&a=1556323018&p=233263325&st=920255512&a=1555805268&p=232873115&st=918639663&a=1555805355&p=232873142&st=918637881&a=1555805098&p=232873302&st=918638462&a=1555805391&p=232873208&st=918638782&a=1555805362&p=232873256&st=918638306&a=1555805418&p=232873307&st=918639694
> > Audio
> > https://play.itunes.apple.com/WebObjects/MZPlay.woa/hls/subscription/stream/playlist.m3u8?cc=IN&g=2448&cdn=ak&a=1484589502&p=90025276&st=379169935&a=1547750479&p=233890538&st=922959632&a=1556322982&p=233263262&st=920253483&a=1556323018&p=233263325&st=920255499&a=1555805268&p=232873115&st=918639655&a=1555805355&p=232873142&st=918637934&a=1555805098&p=232873302&st=918639273&a=1555805391&p=232873208&st=918638729&a=1555805362&p=232873256&st=918638242&a=1555805418&p=232873307&st=918639711
> > Console
> > key: b4f101237a31de014427080476f84b3b (KID=000000000df0e2ea6331342020202020)
> > key: 5aa6b017738c8b2d5e67f72948e6ccb7 (KID=000000000df0e2ea6336202020202020)
> > This is the command line i use. Am I forgetting something?
> > mp4decrypt --key 1:b4f101237a31de014427080476f84b3b --show-progress "playlist_20210325221144.mp4" video.mp4
> > mp4decrypt --key 1:5aa6b017738c8b2d5e67f72948e6ccb7 --show-progress "playlist_20210325180848.eac3" audio.eac3
> 
> mp4decrypt --key 1:b4f101237a31de014427080476f84b3b --key 2:5aa6b017738c8b2d5e67f72948e6ccb7 --show-progress "playlist_20210325221144.mp4" video.mp4 Try This

doesnt work

**Comment by PlaceboPRS** [comment]
I'm also having the issue with Apple TV, Is there any way to get the widevine key now that the Chrome extension doesn't work?
