### ISSUE TITLE
钉钉直播回放抓到链接需要客户端认证，有没有大佬解决一下

### ISSUE THREAD

**Issue by AdoShan** [nilaoda/N_m3u8DL-CLI#431]
下载获取不到m3u8，网上查到的那个小钥匙图标的意思是需要客户端认证。
![image](https://user-images.githubusercontent.com/44154107/114680926-41107f00-9d40-11eb-9f96-a719081967c2.png)

**Comment by yzxoi** [comment]
> 下载获取不到m3u8，网上查到的那个小钥匙图标的意思是需要客户端认证。
> ![image](https://user-images.githubusercontent.com/44154107/114680926-41107f00-9d40-11eb-9f96-a719081967c2.png)

我并不认为此类问题应该出现在此 repo 的 issues 中，但我还是提供一个[方法](https://yzxoi.top/archives/1274)，希望能解决您的问题。

**Comment by AdoShan** [comment]
> > 下载获取不到m3u8，网上查到的那个小钥匙图标的意思是需要客户端认证。
> > ![image](https://user-images.githubusercontent.com/44154107/114680926-41107f00-9d40-11eb-9f96-a719081967c2.png)
> 
> 我并不认为此类问题应该出现在此 repo 的 issues 中，但我还是提供一个[方法](https://yzxoi.top/archives/1274)，希望能解决您的问题。

非常感谢。我解决了问题。忘了回来关闭该issues。
