### ISSUE TITLE
直播流录制程序一直是waitng状态

### ISSUE THREAD

**Issue by AdoShan** [nilaoda/N_m3u8DL-CLI#432]
不管使用的是--liveRecDur参数还是--downloadRange程序都一直是  ”waiting，获取m3u8内容状态“  直播链接为钉钉课堂直播链接。
`N_m3u8DL-CLI.exe 'https://dtlive-bj.dingtalk.com/live_hp/后续链接不公布' --workDir "E:\Download\Video" --saveName "Test.flv" --downloadRange 00:10:00`
![image](https://user-images.githubusercontent.com/44154107/115192236-1f870d00-a11d-11eb-96d1-46e243054cdd.png)

**Comment by nilaoda** [comment]
仅支持HLS录制。不支持FLV。

**Comment by AdoShan** [comment]
> 仅支持HLS录制。不支持FLV。

感谢解惑。学到了很多知识

**Comment by AdoShan** [comment]
> 仅支持HLS录制。不支持FLV。

后续考虑支持FLV吗？

**Comment by nilaoda** [comment]
> > 仅支持HLS录制。不支持FLV。
> 
> 后续考虑支持FLV吗？

推荐使用streamlink
