### ISSUE TITLE
CB站今天好像不能下载了（后来发现是个别主播才有此现象

### ISSUE THREAD

**Issue by heiyutian** [nilaoda/N_m3u8DL-CLI#435]
抓的m3u8之前一直都可以下载，今天测试过发现远程win机和本地加走代理都直接退出，试了用ffmpeg可以下载。
刚又试了其它主播没有问题可以下载，不知道为什么那个主播用这个软件不能下载。重复试了几次都是那个主播的秒退出下载。

**Comment by nilaoda** [comment]
使用`-loglevel debug`看看ffmpeg的请求头，我想可能是User-Agent的问题，你修改为ffmpeg的UA再下载试试

**Comment by heiyutian** [comment]
> 使用`-loglevel debug`看看ffmpeg的请求头，我想可能是User-Agent的问题，你修改为ffmpeg的UA再下载试试

我当时也以为是UA的问题，试过改成当前浏览器UA，还是不能下载，不过第二天再去下载那个主播，是可以成功下载的
