### ISSUE TITLE
youku ts

### ISSUE THREAD

**Issue by YYJavaGit** [nilaoda/N_m3u8DL-CLI#44]
现在优酷的ts是不是都加密了，下载出来的都不能用ffmpeg直接合并了吧，有没有其他办法

**Comment by YYJavaGit** [comment]
还是说只有部分的视频被加密了

**Comment by nilaoda** [comment]
部分视频加密了

**Comment by YYJavaGit** [comment]
有没有办法抓他的key解密，嘿嘿

**Comment by snow212-cn** [comment]
> 部分视频加密了

诚问有没有其他办法

**Comment by xhlove** [comment]
可以试试这个：https://github.com/xhlove/vvtoolbox-gui-series

**Comment by nilaoda** [comment]
https://nilaoda.github.io/N_m3u8DL-CLI/youku.html
