### ISSUE TITLE
Is there a function to combine audio and video upon completion?

### ISSUE THREAD

**Issue by atakurt034** [nilaoda/N_m3u8DL-CLI#442]
Is there a function to combine audio and video upon completion? Downloaded a m3u8 and mpd file.

**Comment by nilaoda** [comment]
not supported yet

**Comment by atakurt034** [comment]
Ok thanks

**Comment by BondeDK** [comment]
I'm using for disney+

@ echo off

set path=C:\Users\Administrator\Desktop\Downloader-Decrypt

echo.

set /p folder= Video Name to be Saved as (No spaces - use underscore between words '-'):

echo.

mkdir C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%

set /p stream=Input MPD from stream detector:

N_m3u8DL-CLI_v2.9.7.exe "%stream%" --workDir C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder% --saveName "stream" --enableDelAfterDone --enableMuxFastStart

ren C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%\stream(Audio).* 

ren C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%\stream.* stream.mp4

echo.

set /p key=enter key: 

echo.

set /p kid=enter kid: 

echo Video being created.........

mp4decrypt.exe --key %kid%:%key% C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%\stream(Audio).eac3 C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%\decrypted-audio.eac3

mp4decrypt.exe --key %kid%:%key% C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%\stream.mp4 C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%\decrypted-video.mp4

mkvmerge.exe -o C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%.mkv C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%\decrypted-video.mp4 C:\Users\Administrator\Desktop\Downloader-Decrypt\%folder%\decrypted-audio.eac3

cls  






Change C:\Users\Administrator\Desktop\Downloader-Decrypt to your location
You need FMPEG.exe, mkvmerge.exe, N_m3u8DL-CLI_v2.9.7.exe, mp4decrypt.exe,

(On Disney+ search for ctr-all in network tap and use that m3u3 link) it will give you 5.1 audio i dont now if you can download more than one audio track at a time but i don't think so might be a limitation with N_m3u8DL-CLI (nilavoda can confirm or deny that)
