### ISSUE TITLE
2.9.7 下载N_m3u8DL-CLI_v2.9.7_with_ffmpeg_and_SimpleG.zip文件 报毒

### ISSUE THREAD

**Issue by moshengren88** [nilaoda/N_m3u8DL-CLI#443]
2.9.7报毒

_Originally posted by @moshengren88 in https://github.com/nilaoda/N_m3u8DL-CLI/issues/206#issuecomment-840573142_

**Comment by nilaoda** [comment]
https://www.microsoft.com/en-us/wdsi/filesubmission

可以自行提交检测
