### ISSUE TITLE
请问同一m3u8如何设置不同分段不同的base64编码的key？

### ISSUE THREAD

**Issue by luojunyuan** [nilaoda/N_m3u8DL-CLI#445]
我有一个m3u8文件，他把视频切割成了上百个分段。
每相隔20个分段，就有一个对应的key值。

我测试将第一个大分段（前20个分段）另存为新的m3u8文件后，将其对应的key进行base64编码后，使用 `m3u8-cli` 填入参数 `--useKeyBase64` 可以成功下载第一个大分段的视频播放。但是我并不清楚如何给其他片段填入不同的编码后的key值，以直接下载整个完整视频。

**Comment by nilaoda** [comment]
程序是支持这种不同KEY的情况的，m3u8形式如下：
```
#EXT-X-KEY:METHOD=AES-128,URI="base64:FlbuiVfsWLt4f33qLIrC2w=="
#EXTINF:4.004,
0.ts
#EXTINF:4.004,
1.ts
...
#EXT-X-KEY:METHOD=AES-128,URI="base64:ZezuiVfsWLoUif33qLerPc2=="
#EXTINF:4.004,
101.ts
#EXTINF:4.004,
102.ts
```

**Comment by luojunyuan** [comment]
> 程序是支持这种不同KEY的情况的，m3u8形式如下：
> 
> ```
> ...
> #EXT-X-KEY:METHOD=AES-128,URI="base64:FlbuiVfsWLt4f33qLIrC2w=="
> #EXTINF:4.004,
> 0.ts
> #EXTINF:4.004,
> 1.ts
> ...
> #EXT-X-KEY:METHOD=AES-128,URI="base64:ZezuiVfsWLoUif33qLerPc2=="
> #EXTINF:4.004,
> 101.ts
> #EXTINF:4.004,
> 102.ts
> ...
> ```

您好，我想额外再询问一下N_m3u8可以做到合并本地已有的，带key的ts文件吗，我查看了文档说明不太明白 使用 `--baseUrl` 是需要填充在线的原始地址？我看到 issue #145  似乎和我情况类似，但 `--useKeyFile File` 或  `--useKeyBase64` 参数只能作用到整个文件的样子。
我的文件夹目录结构是

```
00.ts
01.ts
02.ts
03.ts
index.m3u8
```

index.m3u8 文件大概这样

```m3u8
#EXTM3U
...
#EXT-X-KEY:METHOD=AES-128
...
#EXT-X-KEY:METHOD=AES-128,URI="base64:WFVibnMxdW1aOURJWjZqbw=="
#EXTINF:10.000000,
00.ts
#EXTINF:10.000000,
01.ts
...
#EXT-X-KEY:METHOD=AES-128,URI="base64:WFp6NTk2WEhKZVVXSWd5aw=="
#EXTINF:10.000000,
02.ts
#EXTINF:10.000000,
03.ts
...
#EXT-X-ENDLIST
```

我尝试了命令 `.\N_m3u8DL-CLI_v2.9.7.exe "absolute_path_to\index.m3u8" --saveName "local"`

他告诉我
``` powershell
05:24:22.967 文件名称：local
05:24:22.968 存储路径：MyPath\N_m3u8DL-CLI_v2.9.7_with_ffmpeg_and_SimpleG\Downloads
05:24:22.972 开始解析
05:24:23.000 获取m3u8内容
05:24:23.003 解析m3u8内容
05:24:23.005 获取m3u8 key...
05:24:23.018 写出meta.json
05:24:23.097 文件时长：21m16s
05:24:23.098 总分片：128, 已选择分片：128
05:24:23.116 开始下载文件
05:24:23.125 读取文件信息...
             PID 0x100: Video h264, yuv420p(progressive), 1280x720 [SAR 4096:4095 DAR 65536:36855], 25 fps, 25 tbr, 90k              PID 0x101: Audio aac, 22050 Hz, stereo, fltp, 52 kb/s
05:24:23.172 等待下载完成...
05:24:23.198 填充无效，无法被移除。
```

**Comment by luojunyuan** [comment]
😅
