### ISSUE TITLE
请教，直播的M3U8流如何直接下载成MP4？

### ISSUE THREAD

**Issue by solaris-9** [nilaoda/N_m3u8DL-CLI#455]
默认是TS的，直播结束了也不会转成MP4

**Comment by nilaoda** [comment]
不支持~

**Comment by nilaoda** [comment]
> > 不支持~
> 
> @nilaoda 界面里那个“混流mp4边下边看”的选项是什么意思？

在下载普通m3u8时，下载完成后使用ffmpeg合并写入faststart参数。可以使mp4更快的在播放器中播放。
