### ISSUE TITLE
大佬 阿里云的视频是一直都不支持，还是之前支持过后来取消掉了？

### ISSUE THREAD

**Issue by yh371174229** [nilaoda/N_m3u8DL-CLI#460]
大佬 阿里云的视频是一直都不支持，还是之前支持过后来取消掉了？
阿里云的视频有没有什么思路可以解密啊，求指导

**Comment by nilaoda** [comment]
短暂支持过

**Comment by yh371174229** [comment]
感谢您的回复，阿里云视频解密这块如果有啥好的思路，请大佬指教，可以提供极客时间或者光环软考的账号测试
