### ISSUE TITLE
无法下载某个网站视频

### ISSUE THREAD

**Issue by ICLXL** [nilaoda/N_m3u8DL-CLI#465]
![image](https://user-images.githubusercontent.com/30027321/123527248-6c382700-d710-11eb-9013-1771ffac3d1d.png)

但Potplayer可以正常播放这个m3u8文件

![image](https://user-images.githubusercontent.com/30027321/123527382-9fc78100-d711-11eb-9bb0-2020524d2660.png)

m3u8 地址:https://www.baobuzz.com/m3u8/236963.m3u8?sign=811ae52382b7dd1d247f705e1bcaddf4

**Comment by ICLXL** [comment]
https://www.nunuyy.cc/dianying/4095.html  这是视频网站,上面的那个m3u8地址可能会失效,不要F12打开获取m3u8 地址,这个网站有反爬机制会爆内存,可以用Fiddler这种工具抓下包拿m3u8地址,或者@我下,我重新抓条
![image](https://user-images.githubusercontent.com/30027321/123527931-2da56b00-d716-11eb-9d6c-ad7a41612b5b.png)

**Comment by ICLXL** [comment]
[236963.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/6720804/236963.txt)

m3u8 文件

**Comment by nilaoda** [comment]
感觉反馈, 请等待下个版本修复.

**Comment by fgcd8964** [comment]
> 
> 
> [236963.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/6720804/236963.txt)
> 
> m3u8 文件
老哥打扰了，请问233网校也是这样，能否指导一下怎么解决下载，课程已付费，明年到期，32位KEY 不知道怎么转成16可以自定义下载，233网校的KEY-toren感觉是每次会变
