### ISSUE TITLE
Selling Chrome 2209 Leaked CDM

### ISSUE THREAD

**Issue by CDM2022** [nilaoda/N_m3u8DL-CLI#468]
own extracted chrome 2209 working with amazon , netflix & all

https://commerce.coinbase.com/checkout/d5bfac19-e8fd-4684-8d8a-503143320e76

**Comment by loveyoursupport** [comment]
show some proof

**Comment by CDM2022** [comment]
what proof you need

**Comment by loveyoursupport** [comment]
chrome cdm proof , what is your discord or email address?

**Comment by nilaoda** [comment]
no selling

**Comment by astravaganza** [comment]
don't pay attention
