### ISSUE TITLE
直播流bug

### ISSUE THREAD

**Issue by mskgroup** [nilaoda/N_m3u8DL-CLI#47]
直播流录制一段时间，无法继续录制，无限提示获取或获取、写出循环，手动停止时提示：
未经处理的异常：System.ArgumentOutOfRangeException:该值必须大于或等于零，且必须小于控制台缓冲区在改维度的大小。
参数名：top
实际值是 15014（这个值不固定）
    在System.Console.SetCursorPosition(Int 32 left, Int32 top)
    在N_m3u8_CLI.NetCore.Program.HandlerRoutine(Int32 CtrlType)

**Comment by zhangyining215** [comment]
问下，这个软件怎么录制直播？
