### ISSUE TITLE
m3u8类型识别错误，导致无法下载

### ISSUE THREAD

**Issue by 1357310795** [nilaoda/N_m3u8DL-CLI#472]
是央视的一个视频。
源文件：
[111.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/6860155/111.zip)
源文件内容：
#EXTM3U8
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-1.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-2.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-3.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-4.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-5.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-6.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-7.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-8.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-9.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-10.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-11.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-12.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-13.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-14.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-15.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-16.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-17.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-18.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-19.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-20.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-21.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-22.mp4
http://cntv.vod.cdn.myqcloud.com/flash/mp4video63/TMS/2019/11/17/bc6b661e047a4e94b0718c02f951dd11_h2642000000nero_aac16-23.mp4

不知道为什么软件给识别成了直播流，然后报错
![QQ截图20210722133551](https://user-images.githubusercontent.com/35869804/126594033-86661b28-ebbd-4848-90ba-8a58088c2ae4.png)

**Comment by nilaoda** [comment]
该文件非正确的m3u8格式

**Comment by 1357310795** [comment]
文件原来是m3u格式的，N_m3u8DL-CLI直接打开报错和上面一样
我用potplayer打开另存为了m3u8格式，又是错误的……
希望软件能支持m3u格式😊

**Comment by nilaoda** [comment]
> 文件原来是m3u格式的，N_m3u8DL-CLI直接打开报错和上面一样
> 我用potplayer打开另存为了m3u8格式，又是错误的……
> 希望软件能支持m3u格式😊
文件不是m3u/m3u8格式。。
