### ISSUE TITLE
朋友你好，你的软件 不错，想付费找你 做一些定制的修改

### ISSUE THREAD

**Issue by liu33210000** [nilaoda/N_m3u8DL-CLI#475]
如何能联系上你，可以私信给我一个方便的联系方式吗  v.x最好 扣.扣也行

**Comment by nilaoda** [comment]
nilaoda@live.com

**Comment by liu33210000** [comment]
我这边使用你的软件大多时候都是调用它&nbsp;&nbsp; 下面的需求可以定制一下吗 多少钱？
1.
软件在使用过程中出现卡着不走的情况 有时候下载到90多了%结果完全不动了
想给软件 加一个能监控的功能
监控软件开始下载，如果这条下载超时间 比如 10分钟都没有下载完 就强行停止 直接跳出！
2
直播的下载也是
能不是监控 下载的文件 ，当文件大小 超时没有大小变化的时候 直接强行停止 直接跳出！

另外发现可能有个BUG的地方
-workDir&nbsp; 当保存文件夹 最后一个字符是空格会出错的情况（能不能加个自动过滤 当保存文件夹 最后字符中空格去掉）
