### ISSUE TITLE
有key及m3u8地址 但是下载不了该网站的视频

### ISSUE THREAD

**Issue by MrX-1214** [nilaoda/N_m3u8DL-CLI#476]
下载不了该网站的视频http://www.itbaizhan.com/course/id/23752.html
一直显示填充无效
![sshot-2021-07-28- 20-41-30](https://user-images.githubusercontent.com/58872647/127326470-b7c93ab7-7bcf-4efb-baa9-2355cf6ee094.png)
m3u8的地址与key（已转成base64）都有，不知道为什么就是下载不了
![sshot-2021-07-28- 20-44-11](https://user-images.githubusercontent.com/58872647/127324526-e1836405-26e7-47b7-a340-91df13b419a6.png)
![sshot-2021-07-28- 20-44-45](https://user-images.githubusercontent.com/58872647/127324540-55d05df5-4a05-4b4e-b7b0-2401c240b443.png)
![sshot-2021-07-28- 20-44-05](https://user-images.githubusercontent.com/58872647/127324542-c958b233-e451-4a48-a024-bf03d458bf16.png)
下面是m3u8操作时的截图
![sshot-2021-07-28- 20-47-59](https://user-images.githubusercontent.com/58872647/127326749-e9f35efd-9afc-491b-9dc5-4729272800d9.png)

请各位大佬帮小弟看看🌹🌹🌹

**Comment by nilaoda** [comment]
不支持此网站

**Comment by MrX-1214** [comment]
> 不支持此网站
好吧，那大佬可以更新一下吗

**Comment by 81pla** [comment]
@MrX-1214 想问下你的那个key是怎么解码的啊，我下下来一个 也是乱码的key 感谢
