### ISSUE TITLE
字符串“”不是有效的 TimeSpan 值。

### ISSUE THREAD

**Issue by 10362227** [nilaoda/N_m3u8DL-CLI#481]
N_m3u8DL-CLI_v2.9.7 https://live.corusdigitaldev.com/groupd/live/49a91e7f-1023-430f-8d66-561055f3d0f7/live.isml/.mpd
10:22:53.706 开始解析
10:22:53.730 获取m3u8内容
10:22:55.201 开始解析MPD内容...
10:22:56.672 字符串“”不是有效的 TimeSpan 值。

这是直播流，我手动下载片段可以，用你这个软件下载报错

**Comment by nilaoda** [comment]
暂不支持
