### ISSUE TITLE
下载下来的是raw.m3u8文件

### ISSUE THREAD

**Issue by YinghaoHung** [nilaoda/N_m3u8DL-CLI#482]
您好，下载https://hls.videocc.net/9b52ce99c4/e/9b52ce99c4e6297ddfc20d843143753e_3.m3u8?pid=1628084520359X1542905&device=desktop
时，download里面是一个raw.m3u8文件
这是日志：
LOG 2021/08/04
Save Path: C:\Users\追逐\Desktop\N_m3u8DL-CLI_v2.9.7_with_ffmpeg_and_SimpleG_2\Logs
Task Start: 2021/08/04 21:44:14
Task CommandLine: "C:\Users\追逐\Desktop\N_m3u8DL-CLI_v2.9.7_with_ffmpeg_and_SimpleG_2\N_m3u8DL-CLI_v2.9.7.exe" 

21:44:14.498 / (NORMAL) 开始解析 https://hls.videocc.net/9b52ce99c4/e/9b52ce99c4e6297ddfc20d843143753e_3.m3u8?pid=1628084520359X1542905&device=desktop
21:44:20.344 / (NORMAL) 解析m3u8内容
21:44:20.352 / (NORMAL) 获取m3u8 key... https://hls.videocc.net/9b52ce99c4/e/9b52ce99c4e6297ddfc20d843143753e_3.key

**Comment by nilaoda** [comment]
下载器不支持这个网站

**Comment by YinghaoHung** [comment]
有什么解决办法吗请问




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月4日(星期三) 晚上9:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nilaoda/N_m3u8DL-CLI] 下载下来的是raw.m3u8文件 (#482)





 
下载器不支持这个网站
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by nilaoda** [comment]
这篇文章可能有帮助

https://blog.weimo.info/archives/599/

**Comment by YinghaoHung** [comment]
好的，谢谢
---原始邮件---
***@***.***&gt;
发送时间:2021年8月4日 星期三 下午9:56
***@***.***&gt;
***@***.******@***.***&gt;
主题:Re: [nilaoda/N_m3u8DL-CLI] 下载下来的是raw.m3u8文件 (#482)



这篇文章可能有帮助

https://blog.weimo.info/archives/599/

&mdash;
You&nbsp;are&nbsp;receiving&nbsp;this&nbsp;because&nbsp;you&nbsp;authored&nbsp;the&nbsp;thread.
Reply&nbsp;to&nbsp;this&nbsp;email&nbsp;directly,view&nbsp;it&nbsp;on&nbsp;GitHub,&nbsp;orunsubscribe.
Triage&nbsp;notifications&nbsp;on&nbsp;the&nbsp;go&nbsp;with&nbsp;GitHub&nbsp;Mobile&nbsp;foriOSorAndroid.
