### ISSUE TITLE
批量下载bat文件

### ISSUE THREAD

**Issue by ownerowner** [nilaoda/N_m3u8DL-CLI#493]
之前记得在这里下载了但是长时间不用误删了，就是能够按顺序批量命令的文件不需要自己手动一个一个命名，for循环那个，然后新建一个txt文件。
echo off ……
希望大佬能发一下，谢谢

**Comment by nilaoda** [comment]
使用SimpleG完成：

* txt内容如下
  ```
  EP01,http://127.0.0.1/1.m3u8
  EP02,http://127.0.0.1/2.m3u8
  ```

或

* txt内容如下
  ```
  http://127.0.0.1/1.m3u8
  http://127.0.0.1/2.m3u8
  ```

然后将txt文件拖入“M3U8地址”一栏，点击“GO”后会自动生成bat并执行

**Comment by ownerowner** [comment]
> 使用SimpleG完成：
> 
> * txt内容如下
>   ```
>   EP01,http://127.0.0.1/1.m3u8
>   EP02,http://127.0.0.1/2.m3u8
>   ```
> 
> 或
> 
> * txt内容如下
>   ```
>   http://127.0.0.1/1.m3u8
>   http://127.0.0.1/2.m3u8
>   ```
> 
> 然后将txt文件拖入“M3U8地址”一栏，点击“GO”后会自动生成bat并执行

savename 没办法搞啊，按1 2 3 4顺序，下载一百集的电视剧那敲100下数字了
