### ISSUE TITLE
Adding support for downloading from Amazon mpd 

### ISSUE THREAD

**Issue by Essam3152** [nilaoda/N_m3u8DL-CLI#496]
Hi, in this comment mpd we get after modifying an Amazon link to get the audio in DDP2.0 but it does not work with N_m3u8DL-CLI now, please if possible modify N_m3u8DL-CLI to recognize it. 

https://github.com/Satsuoni/widevine-l3-guesser/issues/1#issuecomment-903261156

the modified mpd

https://s3-iad-2.cf.dash.row.aiv-cdn.net/ceec/72d6/0608/4568-88b4-ed09e94f33a4/fc988e6d-97c2-4635-a048-9773fc61171e_corrected.mpd

**Comment by nilaoda** [comment]
fixed: https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/1157247671
