### ISSUE TITLE
m3u8解密修复

### ISSUE THREAD

**Issue by dwthn110** [nilaoda/N_m3u8DL-CLI#497]
”优酷“的m3u8跟新了加密方式，当前你这个工具不支持此解密方式直接跳过了解密，视频虽然能够下载，但不能播放，望有时间修复一下
谢谢！

**Comment by nilaoda** [comment]
请看[Readme](https://github.com/nilaoda/N_m3u8DL-CLI#readme)

**Comment by dwthn110** [comment]
你那里在有没有什么工具，可以解密youku“m3u8"文件的，可以推荐给我吗？不是你开发的也行，
谢谢
辛苦大佬了！
