### ISSUE TITLE
想问下key下载下来后是乱码应该怎么处理

### ISSUE THREAD

**Issue by 81pla** [nilaoda/N_m3u8DL-CLI#498]
```https://hls.videocc.net/510de8f5bb/2/510de8f5bbb059cfe3bbe907091eeb72_3.m3u8?pid=1629781520783X1788489&device=desktop```
这是m3u8的地址，里面的key下载下来后打开是乱码
![image](https://user-images.githubusercontent.com/17949410/130559774-160e624f-d603-407c-8ea9-6a2ef24d4aa7.png)

```
W Ì±‘•Ÿ¬.öJ§§—-I§õq=×žZxåQ Ú¢›
```

**Comment by 81pla** [comment]
[510de8f5bbb059cfe3bbe907091eeb72_3.key.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/7036606/510de8f5bbb059cfe3bbe907091eeb72_3.key.zip)

**Comment by 81pla** [comment]
好像是32位的，怎么办呢
![image](https://user-images.githubusercontent.com/17949410/130560717-cbfc8407-6b52-4e9a-be0f-5b4ce5908d67.png)

**Comment by 81pla** [comment]
看了下网站是用的保利威视的

**Comment by 81pla** [comment]
解决了，记录一下方便其他人，保利威视的m3u8里key文件下载下来是乱码，实际是加密过的，用不了。
需要拿到未加密的key使用，用抓包工具代理一下```https://player.polyv.net/script/player.js```这个文件，下面是修改过的文件，这样控制台可以直接显示未加密的，然后使用```http://www.tomeko.net/online_tools/hex_to_base64.php?lang=en```转码为base64使用即可。
[player.js.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/7037079/player.js.zip)

![image](https://user-images.githubusercontent.com/17949410/130571631-3f0e672c-12e2-453f-a2d3-c00fec1a1fe2.png)

**Comment by lingchuanbo** [comment]
V12版本的pdx可以破解吗？

**Comment by Luffy-liang** [comment]
保利威的现在好像用不了拉

**Comment by pandareen** [comment]
> 解决了，记录一下方便其他人，保利威视的m3u8里key文件下载下来是乱码，实际是加密过的，用不了。 需要拿到未加密的key使用，用抓包工具代理一下`https://player.polyv.net/script/player.js`这个文件，下面是修改过的文件，这样控制台可以直接显示未加密的，然后使用`http://www.tomeko.net/online_tools/hex_to_base64.php?lang=en`转码为base64使用即可。 [player.js.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/7037079/player.js.zip)
> 
> ![image](https://user-images.githubusercontent.com/17949410/130571631-3f0e672c-12e2-453f-a2d3-c00fec1a1fe2.png)

Hello can you tell me how do I spoof the player.js in chrome? How to do the packet sniffer?
您好，您能告诉我如何在 chrome 中欺骗 player.js 吗？ 如何做数据包嗅探器？

**Comment by Lingchen218** [comment]
> 解决了，记录一下方便其他人，保利威视的m3u8里key文件下载下来是乱码，实际是加密过的，用不了。 需要拿到未加密的key使用，用抓包工具代理一下`https://player.polyv.net/script/player.js`这个文件，下面是修改过的文件，这样控制台可以直接显示未加密的，然后使用`http://www.tomeko.net/online_tools/hex_to_base64.php?lang=en`转码为base64使用即可。 [player.js.zip](https://github.com/nilaoda/N_m3u8DL-CLI/files/7037079/player.js.zip)
> 
> ![image](https://user-images.githubusercontent.com/17949410/130571631-3f0e672c-12e2-453f-a2d3-c00fec1a1fe2.png)

这个好像现在的v12不能解决吧?

**Comment by pandareen** [comment]
@Lingchen218 thanks for responding. I have found the key is 32 bytes instead of 16 bytes which is AES-128 standard. How to get the 16Byte key from this methods?

**Comment by Lingchen218** [comment]
你好！主人有事！主人收到信息会第一时间回复你的

**Comment by iwenr** [comment]
> https://hls.videocc.net/510de8f5bb/2/510de8f5bbb059cfe3bbe907091eeb72_3.m3u8?pid=1629781520783X1788489&device=desktop

你好，请问key怎么下载。现在请求报400

**Comment by pandareen** [comment]
> > https://hls.videocc.net/510de8f5bb/2/510de8f5bbb059cfe3bbe907091eeb72_3.m3u8?pid=1629781520783X1788489&device=desktop
> 
> 你好，请问key怎么下载。现在请求报400

Yes big guy it always gives `403`. Heres another example for you with key and iv both in hex

```
m3u8=https://hls.videocc.net/9215d65496/3/9215d65496349bbf54a2d145531c5853_1.m3u8?pid=1651341314495X1027088&device=desktop
iv=b09e785aa91c6ac6c039e9fd4f68bc26
key=8dbe7c1927fa4706901bc26d6b820ed3c13a325c371826c41318a6ee44737de4
```

**Comment by iwenr** [comment]
> 
**thanks**
problem solved
https://github.com/nilaoda/N_m3u8DL-CLI/issues/648#issuecomment-1114086067

**Comment by Lingchen218** [comment]
> > https://hls.videocc.net/510de8f5bb/2/510de8f5bbb059cfe3bbe907091eeb72_3.m3u8?pid=1629781520783X1788489&device=desktop
> 
> 你好，请问key怎么下载。现在请求报400

这个只能请求一次，第二次就失效了，有个js的函数，执行那个

**Comment by iwenr** [comment]
> > > https://hls.videocc.net/510de8f5bb/2/510de8f5bbb059cfe3bbe907091eeb72_3.m3u8?pid=1629781520783X1788489&device=desktop
> > 
> > 
> > 你好，请问key怎么下载。现在请求报400
> 
> 这个只能请求一次，第二次就失效了，有个js的函数，执行那个

可以请教完整步骤吗，弄了好几天没弄好

**Comment by chuccp** [comment]
https://github.com/chuccp/chrome_extensions   利用谷歌插件破解保利威

**Comment by jjmathy** [comment]
thanks a lot
