### ISSUE TITLE
Problem with Amazon MPD

### ISSUE THREAD

**Issue by coryyyyy1** [nilaoda/N_m3u8DL-CLI#503]
Using this modified N_m3u8DL-CLI for a while i released that he grabs DDP2.0 normal and DDP5.1 as well, but he adds more segments to the audio file. It decrypts, etc, but with the extra segments. Sometimes the audio comes out with 3h when the movie it's 1h30m, or a 1gb audio file when it's suppost to be an 500mb one, etc. But when i search manually in the mpd and download manually the audio, it's the right one, so i think the N_m3u8DL-CLI it's the problem!

**Comment by Essam3152** [comment]
@nilaoda You could test using this modified mpd

https://s3-iad-2.cf.dash.row.aiv-cdn.net/ceec/72d6/0608/4568-88b4-ed09e94f33a4/fc988e6d-97c2-4635-a048-9773fc61171e_corrected.mpd

and this is the original audio file

https://s3-iad-2.cf.dash.row.aiv-cdn.net/ceec/72d6/0608/4568-88b4-ed09e94f33a4/fc988e6d-97c2-4635-a048-9773fc61171e_audio_14.mp4

https://github.com/Satsuoni/widevine-l3-guesser/issues/1#issuecomment-903261156

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/132123071-45ec061f-5352-41f8-8947-75c3b92ce805.png)

![image](https://user-images.githubusercontent.com/20772925/132123074-01299e4d-f548-4543-99ff-77444ac841c8.png)

Totally same... Casue your problem

Try newest version: https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/1202873707
