### ISSUE TITLE
Merge .ts segments to .ts file format

### ISSUE THREAD

**Issue by oknchm** [nilaoda/N_m3u8DL-CLI#504]
So as the title says, I want to merge the downloaded .ts segments to .ts file format also instead of mp4. I tried using `--muxSetJson` but the final video still converted to mp4. Thank you!

```
{
    "muxFormat": "ts", 
    "fastStart": "True", 
    "poster": "", 
    "audioName": "", 
    "title": "", 
    "copyright": "", 
    "comment": ""
}
```

**Comment by nilaoda** [comment]
can you show me your commandline? are you use `--enableBinaryMerge`?

**Comment by oknchm** [comment]
Yes, I tried with and without `--enableBinaryMerge`, but the results are both mp4.

> `"https://sample.m3u8" --saveName "MIAL813DSGL150000100" --enableDelAfterDone --enableMuxFastStart --enableBinaryMerge`

**Comment by nilaoda** [comment]
when you use `--enableBinaryMerge`, it's always binary concat.

you can just rename from `.mp4` to `.ts` or anything you want.

**Comment by oknchm** [comment]
I see, what's the difference between merging videos using binary concat vs ffmpeg?

Also, is it better to rename from `.mp4` to `.ts` and then decrypt? Or decrypt the `.mp4` file first and then rename to `.ts`?

**Comment by nilaoda** [comment]
> I see, what's the difference between merging videos using binary concat vs ffmpeg?
> 
> Also, is it better to rename from `.mp4` to `.ts` and then decrypt? Or decrypt the `.mp4` file first and then rename to `.ts`?

same. mp4decrypt will ignore file extensions
