### ISSUE TITLE
windows 10 自带病毒软件，报有病毒，下载后直接删除

### ISSUE THREAD

**Issue by liuyug** [nilaoda/N_m3u8DL-CLI#51]
windows 10 自带病毒软件，报有病毒，下载后直接删除

**Comment by nilaoda** [comment]
可以下载源代码自行编译使用。报毒是因为发布的exe程序打包了dll文件。

**Comment by whwnow** [comment]
请问这个问题能解决么？直接被删除了很麻烦，不是人人都会编译T T

**Comment by nilaoda** [comment]
> 请问这个问题能解决么？直接被删除了很麻烦，不是人人都会编译T T

关闭Windows Defender，使用火绒

**Comment by whwnow** [comment]
额，习惯 Defender 了，没有其他技术上的方案取消报毒么

**Comment by nilaoda** [comment]
> 额，习惯 Defender 了，没有其他技术上的方案取消报毒么
Defender难道连白名单功能都没有吗……

**Comment by whwnow** [comment]
已经白名单了，下载成功，很好用，star+1

**Comment by nilaoda** [comment]
> 已经白名单了，下载成功，很好用，star+1
> 
> 不过要是能从技术上解决报错，使用体验会更好

我把dll打包进exe 就会报毒 不打包又有很多人问为什么软件无法运行 我能怎么办呢……实在难受就别用了 确实没有什么好的解决方案

**Comment by snhun** [comment]
> > 已经白名单了，下载成功，很好用，star+1
> > 不过要是能从技术上解决报错，使用体验会更好
> 
> 我把dll打包进exe 就会报毒 不打包又有很多人问为什么软件无法运行 我能怎么办呢……实在难受就别用了 确实没有什么好的解决方案

有一说一，如果决定是小众软件，怎么运行完美就好，不会的就自动跳过了。
又是免费，又是开源的，作者开心想怎么做就怎么做呗。
