### ISSUE TITLE
N_m3u8DL-CL it's duplicating the movie length 

### ISSUE THREAD

**Issue by DarkHorse-APP2** [nilaoda/N_m3u8DL-CLI#511]
Too many days I go I was trying to download some videos from Amazon but the downloader had been duplicating the movie length for no reason.  For example this movie:

![Movie Length](https://user-images.githubusercontent.com/90475360/133024927-053f37fd-847f-47ec-8cfd-8b2f580ca090.jpg)
Its length is approximately 1h52m18s but when I paste the .mpd file to N_m3u8DL-CL its given me a wrong timing (length) like this:

![Downloading Info](https://user-images.githubusercontent.com/90475360/133025299-7700045f-68cf-46cb-ba97-b1b9d2ac945f.jpg)

Can you please fix this error as soon as you can?

**Comment by nilaoda** [comment]
Same issue #503 

Download artifacts from here: https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/1202972652

**Comment by DarkHorse-APP2** [comment]
> Same issue #503
> 
> Download artifacts from here: https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/1202972652

Thank you so much bro, now it works properly.
