### ISSUE TITLE
程式下载所有分片合併后变成0kb的mp4档

### ISSUE THREAD

**Issue by OflyingchickenO** [nilaoda/N_m3u8DL-CLI#515]
感谢大大的程式,真的很好用,但用一段时间发现了一个问题。
是这样的,一开始我以为只出现在合併分片大于2000个,导致封装出现问题。
但是,在最近有一个500多分片的合併封装也出现了,合併后变成0kb的情况。

以上就是我发现的一个情况滙报,分片合併后变成0kb 的一个情况。

附上上述问题的m3u8:
https://b.baobuzz.com/m3u8/435502.m3u8?sign=b3336b9b4ced513a4e3794effcb662f1

我是把m3u8 下载下来再利用用程序处理的。

**Comment by OflyingchickenO** [comment]
我最后尝试自己用ffmpeg 合併一次也不行:ffmpeg.exe -f concat -safe 0 -i 0.txt -c copy out.mp4

 Could not find tag for codec bmp in stream #0, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --
以上是报错内容
是不是不支援影片编码的问题,ffmpeg 暂不支援,
如果是,有什麽方法可以解决呢?

**Comment by nilaoda** [comment]
这种是利用图床来存储视频切片 文件前被增加了BMP的header信息，导致ffmpeg错误的识别为BMP图片，自然不能合并了。

![image](https://i.loli.net/2021/09/17/8SfQmJ4ZC5TUGxK.png)

目前程序已经支持了自动取出PNG的header，暂不支持BMP。之后可能会加入此功能。

**Comment by OflyingchickenO** [comment]
感谢大大抽空,并且快速回应此问题,谢谢解惑,非常感谢!
