### ISSUE TITLE
突出其来的异常，求解

### ISSUE THREAD

**Issue by wfmc** [nilaoda/N_m3u8DL-CLI#52]
如下图：
![批注 2020-01-29 204047](https://user-images.githubusercontent.com/50252599/73358872-892db800-42da-11ea-85f0-b179f3fe3c6e.jpg)

重新下载程序也不行，重启机器也不行

**Comment by nilaoda** [comment]
新版本应该不会出现这种问题了

**Comment by wfmc** [comment]
威武
