### ISSUE TITLE
I can't download videos from m3u8 files??

### ISSUE THREAD

**Issue by datlm2** [nilaoda/N_m3u8DL-CLI#525]
![Capture](https://user-images.githubusercontent.com/77060739/136228452-eeafdba8-b13a-44e9-99ff-72a85ff3928c.PNG)

M3U8 file: https://www.mediafire.com/file/d3r2aye1rt9pdlz/video.m3u8/file

**Comment by nilaoda** [comment]
Could not resolve host: apird-hbq.rdgogo.xyz
