### ISSUE TITLE
Join mpd Video + Audio

### ISSUE THREAD

**Issue by gt-nik** [nilaoda/N_m3u8DL-CLI#528]
N_m3u8DL download successfully 2 separate files: "FileName.mpd.mp4" and "FileName.mpd(Audio).aac"
from link: https://mediaserve.ert.gr/bpk-vod/vodext/default/zaketa-na-pareis-s02-ep02-diazygio-a-la-fouly/zaketa-na-pareis-s02-ep02-diazygio-a-la-fouly/index.mpd

after this i am expecting to also join them like: FFmpeg.exe -loglevel warning -i "Path2Video" -i "Path2Audio" -c copy "Path2JoinedFile"

Best Regards

**Comment by nilaoda** [comment]
Because many mpds are encrypted, they cannot be muxed directly. Therefore, the program will not mux them by default.
