### ISSUE TITLE
大佬这个报错怎么解决

### ISSUE THREAD

**Issue by UUZT** [nilaoda/N_m3u8DL-CLI#530]
![3403c79b09683ab0bd6d2f959caa2edf_136311203-0c60f5d0-9d98-475d-a9a4-48b08beaa4b9](https://user-images.githubusercontent.com/90137732/136997706-ab9824d7-a887-48e8-80cd-2114ab4e3fc6.png)
大佬这个怎么解决

**Comment by nilaoda** [comment]
请不要发表无关话题。
