### ISSUE TITLE
大大软件后期能考虑添加mpd方式的解密视频下载功能？

### ISSUE THREAD

**Issue by tb0668** [nilaoda/N_m3u8DL-CLI#536]
如果不能的话，可以提供一下下载思路吗

**Comment by tb0668** [comment]
> 下载后使用mp4decrypt解密

大大 为什么有时候会出现下载的视频一帧模糊一帧清晰？是软件bug识别错误把不同分辨率视频混在一起了？

**Comment by nilaoda** [comment]
> > 下载后使用mp4decrypt解密
> 
> 大大 为什么有时候会出现下载的视频一帧模糊一帧清晰？是软件bug识别错误把不同分辨率视频混在一起了？

希望把mpd文件和meta.json发一下
