### ISSUE TITLE
老大，提示指定的密钥大小对于此算法无效怎么解决呀

### ISSUE THREAD

**Issue by zxcv1996711** [nilaoda/N_m3u8DL-CLI#539]
![微信图片_20211102110702](https://user-images.githubusercontent.com/59657458/139780739-7d7977bd-9ee5-40b8-a6c1-c033b6dd87ce.png)
气球云的链接

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/139795274-8931a604-79cb-426a-b14d-531958b63d4d.png)
