### ISSUE TITLE
爱奇艺互动剧采集问题

### ISSUE THREAD

**Issue by YYJavaGit** [nilaoda/N_m3u8DL-CLI#54]
刚才看爱情公寓5 13集的时候发现是什么互动剧，用了好几个脚本都是400多mb这应该是高清之类的，正常一集大概是1.5g，有什么办法解析这个附链接https://www.iqiyi.com/v_19rv45tof4.html 麻烦大佬能看一下吗

**Comment by YYJavaGit** [comment]
因为是多选择模式，要是能获取所有的选择就好了

**Comment by nilaoda** [comment]
这一集 只有TV端才有4K，网页应该没有互动选择吧 解析出是1080p的一整集吧？

**Comment by YYJavaGit** [comment]
刚才网页的试了，有互动的
在2020年01月30日 19:32，nilaoda 写道：

这一集 只有TV端才有4K，网页应该没有互动选择吧 解析出是1080p的一整集吧？
