### ISSUE TITLE
#EXT-X-PLAYLIST-TYPE:VOD标签被识别为无用url,然后进程结束

### ISSUE THREAD

**Issue by keysLo** [nilaoda/N_m3u8DL-CLI#542]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:6,
https://lf3-static.bytednsdoc.com/obj/tos-cn-o-0000/b11aa92fd54348cbad089e94fcd0badf
#EXTINF:6,
https://lf6-static.bytednsdoc.com/obj/tos-cn-o-0000/7d72240fa014492d85b413f938a96825
#EXTINF:5.4,
https://lf9-static.bytednsdoc.com/obj/tos-cn-o-0000/3e1dc2b479e94dbcaf7d609c6c280f61
#EXTINF:3.32,
https://lf1-cdn-tos.bytegoofy.com/obj/tos-cn-o-0000/e453a2ff69b943e182c138e9baea950a
#EXTINF:4.64,
https://lf3-cdn-tos.bytegoofy.com/obj/tos-cn-o-0000/2b3e3e324caf432b9656bfaf6ad36902
#EXTINF:6.12,
https://lf6-cdn-tos.bytegoofy.com/obj/tos-cn-o-0000/36c86cfe32a4417996eada2ec5a9b5fd

**Comment by nilaoda** [comment]
我测试了你提供的这一段，存为m3u8文件下载没有问题

**Comment by keysLo** [comment]
我试了下另存为可以，直接用不行，请帮忙看下curl  https://sod.bunediy.com/20211103/uCcSTvGI/index.m3u8 > 2.m3u8 这样就可以
N_m3u8DL-CLI_v2.9.7.exe  https://sod.bunediy.com/20211103/uCcSTvGI/index.m3u8

Speed: waiting
Progress: waiting


08:09:32.059 File Name: index_20211117081101
08:09:32.059 Save Path: C:\Users\upload\Downloads\N_m3u8DL-CLI_v2.9.7_with_ffmp
08:09:32.059 Start Parsing
08:09:32.074 Downloading M3u8 Content
08:09:32.059 Parsing M3u8 Content
08:09:32.059 Invalid M3u8 (NOT Contain #EXTM3U)
08:09:32.059 Invalid Uri


> 我测试了你提供的这段，存为m3u8文件下载没有问题

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/142243553-3b69d5e3-0d13-49eb-9853-89dd15cd6f8c.png)

尝试使用最新版：https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/1453674792

**Comment by keysLo** [comment]
可以了，谢谢
