### ISSUE TITLE
大佬新版本的支持爱奇艺DRM-JSON自动转换为m3u8如何使用呢

### ISSUE THREAD

**Issue by UUZT** [nilaoda/N_m3u8DL-CLI#551]
大佬M3U8下载器新版本的支持爱奇艺DRM-JSON自动转换为m3u8功能如何使用呢，把下载的JSON文件拉到下载器里面下载就自动关闭窗口什么反应都没有，通过dash链接下载的json文件，不知道是哪里出了问题，求大佬指点

**Comment by nilaoda** [comment]
```js
javascript:eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('3 C=D.E.F.8.G.8.H.I.1b.z.1c.J;C.K(7(j,k){9(j.1d){3 l="";9(j.A==1e){L{9(1f(1g(M))=="7"){}}N(e){3 m=v O();m.P("Q","R://1h.S.T/U/1i/1j.U",6);m.V=7(){3 a=5.W("1k");a.Y=m.Z;5.1l("1m")[0].1n(a)};m.11(B)}3 n=j.1o;3 o="#1p\\n";n.K(7(b,c){3 e=b.l;3 f="R://z.J.S.T/1q";3 h=f+e;L{3 t=D.E.F.8.G.8.H.I.1r.z.t;h=f+e+"%1s%1t%1u=1&t="+t+"&1v="+/1w=(\\d+)/g.12(e)[1]+"&1x=4&1y=0&1z="+M(t+/\\/(\\w{10,})/g.12(e)[1])}N(13){1A.1B(13)}3 i=v O();i.1C("1D/1E");i.P("Q",h,6);i.V=7(){3 a=1F.1G(i.Z);o+="#1H:0\\n"+a["l"]+"\\n"};i.11(B)});o+="#1I-X-1J";l=o}14{l=j.A}3 p=v 1K([l],{1L:"Y/1M"});3 q=1N.1O(p);3 r=(5.x.15("-")!=-1?5.x.1P(0,5.x.15("-")):5.x.16(/\\s/,""))+"y"+j.1Q+"y"+(j.1R==2?"1S":"1T")+"y"+5.1U("1V-1W-1X")[0].1Y.16(/:/,".")+"y"+(j.1Z/17/17).20(2)+"21.A";3 s=5.W("a");s.22=q;s.23=r;s.24.25="26";3 u;9(18.19){u=v 19("1a")}14{u=5.27("28");u.29("1a",2a,6,18,0,0,0,0,0,6,6,6,6,0,B)}s.2b(u)}})',62,136,'|||var||document|false|function|engine|if||||||||||||||||||||||new||title|_|data|m3u8|null|info|playerObject|_player|package|adproxy|movieinfo|current|video|forEach|try|cmd5x|catch|XMLHttpRequest|open|GET|https|iqiyi|com|js|onload|createElement||text|responseText||send|exec|err|else|indexOf|replace|1024|window|MouseEvent|click|originalData|program|_selected|undefined|typeof|eval|static|common|f6a3054843de4645b34d205a9f377d25|script|getElementsByTagName|head|appendChild|fs|EXTM3U|videos|boss|E2|9C|97domain|QY00001|qd_uid|ib|ptime|ibt|console|error|overrideMimeType|application|json|JSON|parse|EXTINF|EXT|ENDLIST|Blob|type|plain|URL|createObjectURL|substring|scrsz|code|H264|H265|getElementsByClassName|iqp|time|dur|innerText|vsize|toFixed|MB|href|download|style|display|none|createEvent|MouseEvents|initMouseEvent|true|dispatchEvent'.split('|'),0,{}))
```

**Comment by 479873740** [comment]
多谢大佬

**Comment by daliali2088** [comment]
> ```js
> javascript:eval(function(p,a,c,k,e,r){e=function(c){return(c<a?'':e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return'\\w+'};c=1};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p}('3 C=D.E.F.8.G.8.H.I.1b.z.1c.J;C.K(7(j,k){9(j.1d){3 l="";9(j.A==1e){L{9(1f(1g(M))=="7"){}}N(e){3 m=v O();m.P("Q","R://1h.S.T/U/1i/1j.U",6);m.V=7(){3 a=5.W("1k");a.Y=m.Z;5.1l("1m")[0].1n(a)};m.11(B)}3 n=j.1o;3 o="#1p\\n";n.K(7(b,c){3 e=b.l;3 f="R://z.J.S.T/1q";3 h=f+e;L{3 t=D.E.F.8.G.8.H.I.1r.z.t;h=f+e+"%1s%1t%1u=1&t="+t+"&1v="+/1w=(\\d+)/g.12(e)[1]+"&1x=4&1y=0&1z="+M(t+/\\/(\\w{10,})/g.12(e)[1])}N(13){1A.1B(13)}3 i=v O();i.1C("1D/1E");i.P("Q",h,6);i.V=7(){3 a=1F.1G(i.Z);o+="#1H:0\\n"+a["l"]+"\\n"};i.11(B)});o+="#1I-X-1J";l=o}14{l=j.A}3 p=v 1K([l],{1L:"Y/1M"});3 q=1N.1O(p);3 r=(5.x.15("-")!=-1?5.x.1P(0,5.x.15("-")):5.x.16(/\\s/,""))+"y"+j.1Q+"y"+(j.1R==2?"1S":"1T")+"y"+5.1U("1V-1W-1X")[0].1Y.16(/:/,".")+"y"+(j.1Z/17/17).20(2)+"21.A";3 s=5.W("a");s.22=q;s.23=r;s.24.25="26";3 u;9(18.19){u=v 19("1a")}14{u=5.27("28");u.29("1a",2a,6,18,0,0,0,0,0,6,6,6,6,0,B)}s.2b(u)}})',62,136,'|||var||document|false|function|engine|if||||||||||||||||||||||new||title|_|data|m3u8|null|info|playerObject|_player|package|adproxy|movieinfo|current|video|forEach|try|cmd5x|catch|XMLHttpRequest|open|GET|https|iqiyi|com|js|onload|createElement||text|responseText||send|exec|err|else|indexOf|replace|1024|window|MouseEvent|click|originalData|program|_selected|undefined|typeof|eval|static|common|f6a3054843de4645b34d205a9f377d25|script|getElementsByTagName|head|appendChild|fs|EXTM3U|videos|boss|E2|9C|97domain|QY00001|qd_uid|ib|ptime|ibt|console|error|overrideMimeType|application|json|JSON|parse|EXTINF|EXT|ENDLIST|Blob|type|plain|URL|createObjectURL|substring|scrsz|code|H264|H265|getElementsByClassName|iqp|time|dur|innerText|vsize|toFixed|MB|href|download|style|display|none|createEvent|MouseEvents|initMouseEvent|true|dispatchEvent'.split('|'),0,{}))
> ```

大大可以请教一下 如果有4K的话 是有什么方法可以下载的吗
