### ISSUE TITLE
win10下載新版2.47 exe會出現有病毒Trojan:Script/Conteban.A!ml 有辦法解決嗎

### ISSUE THREAD

**Issue by danny740211** [nilaoda/N_m3u8DL-CLI#56]
file: E:\N_m3u8DL-CLI\N_m3u8DL-CLI_v2.4.7.exe
Trojan:Script/Conteban.A!ml
請問這有辦法解決嗎
使用2.41沒有跳出錯誤

**Comment by wangiori20** [comment]
允许在设备上不就好了
