### ISSUE TITLE
BILIBILI M3U8下载失败

### ISSUE THREAD

**Issue by zhangsenpei** [nilaoda/N_m3u8DL-CLI#566]
请问现在是否能通过m3u8下载BILIBILI的视频呢，我试了软件抓取的链接都下载失败

**Comment by nilaoda** [comment]
可能需要请求头

**Comment by zhangsenpei** [comment]
比较喜欢收藏无水印的，试了几款功能包括去水印的，都去不掉=-=

**Comment by nilaoda** [comment]
> 比较喜欢收藏无水印的，试了几款功能包括去水印的，都去不掉=-=

使用`-tv`尝试下载无水印片源

**Comment by zhangsenpei** [comment]
![image](https://user-images.githubusercontent.com/79370772/144986548-fb601893-7d04-4e15-9c7f-f860f00a0c23.png)
fan'ju番剧无法去水印么

**Comment by cfandora** [comment]
> ![image](https://user-images.githubusercontent.com/79370772/144986548-fb601893-7d04-4e15-9c7f-f860f00a0c23.png) fan'ju番剧无法去水印么

bilibili大陆和港澳台的番剧都是有水印的，然后单独分出来的国际版(主要为东南亚地区)是无水印的，账号是分开的，会员也要单独购买
