### ISSUE TITLE
I tried to find the m3u8 address, but the video was broken.

### ISSUE THREAD

**Issue by ansi93** [nilaoda/N_m3u8DL-CLI#567]
The m3u8 url I found

"https://apionvod41.seezntv.com/ktmain1/cold/CP/52341/202112/media/MIAL76F0SGL150000100_DRM/MIAL76F0SGL150000100_DRM_H.m3u8?sid=00000D000000414000080000C7000000"

I tried putting in the URL, but the downloaded file was broken.

> C:\ffmpeg\bin>N_m3u8DL-CLI_v2.9.9 "https://apionvod41.seezntv.com/ktmain1/cold/CP/52341/202112/media/MIAL76F0SGL150000100_DRM/MIAL76F0SGL150000100_DRM_H.m3u8?sid=00000D000000414000080000C7000000"
N_m3u8DL-CLI version 2.9.9 2018-2021
  built date: 20211123
23:27:11.921 File Name: MIAL76F0SGL150000100_DRM_H_20211207232711
23:27:11.921 Save Path: C:\ffmpeg\bin\Downloads
23:27:11.928 Start Parsing  https://apionvod41.seezntv.com/ktmain1/cold/CP/52341/202112/media/MIAL76F0SGL150000100_DRM/MIAL76F0SGL150000100_DRM_H.m3u8?sid=00000D000000414000080000C7000000
23:27:12.240 Writing Json: [meta.json]
23:27:12.291 Master List Found
23:27:12.427 Writing Master List Json: [playLists.json]
23:27:12.429 Auto Selected Best Definition
23:27:12.430 Start Re-Parsing...
23:27:12.491 Downloading M3u8 Key...
23:27:12.491 SAMPLE-AES Is Not Supported Yet, Ignore Decrypt, And Use Binary Merge
23:27:12.491 SAMPLE-AES Is Not Supported Yet, Ignore Decrypt, And Use Binary Merge
23:27:12.495 Writing Json: [meta.json]
23:27:12.521 File Duration: 15m38s
23:27:12.523 Original Count: 188, Selected Count: 188
23:27:12.535 Has External Audio Track
23:27:12.538 Start Downloading
23:27:12.538 Downloading Map File...
23:27:12.573 Downloading First Segement...
23:27:12.741 Reading File Info...
             PID NULL: Video h264 (avc1 / 0x31637661), none, 1920x1080, 60k tbr, 60k tbn, 120k tbc (default)
23:27:13.361 Waiting For Completion...
23:27:18.426 Download Complete
23:27:18.427 Start Merging...
23:27:18.431 Binary Merging... Please Wait...
N_m3u8DL-CLI version 2.9.9 2018-2021
  built date: 20211123
23:27:19.156 Start Downloading External Audio Track...
23:27:19.200 Downloading M3u8 Key...
23:27:19.200 SAMPLE-AES Is Not Supported Yet, Ignore Decrypt, And Use Binary Merge
23:27:19.200 SAMPLE-AES Is Not Supported Yet, Ignore Decrypt, And Use Binary Merge
23:27:19.204 Writing Json: [meta.json]
23:27:20.211 Start Downloading
23:27:20.213 Downloading Map File...
23:27:20.246 Downloading First Segement...
23:27:20.286 Reading File Info...
             PID NULL: Audio aac (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 127 kb/s (default)
23:27:20.910 Waiting For Completion...
23:27:22.008 Download Complete
23:27:22.010 Start Merging...
23:27:22.015 Binary Merging... Please Wait...
23:27:22.095 Task Done

**Comment by nilaoda** [comment]
DRM protected content NOT SUPPORTED
