### ISSUE TITLE
下载twitcasting的m3u8文件时合并不成功

### ISSUE THREAD

**Issue by bingshuangw** [nilaoda/N_m3u8DL-CLI#57]
在下载https://dl158.twitcasting.tv/tc.vod/v/591075572-1580538858-1580567658-9171e0b9-62f0769ae3e80a12/fmp4/index.m3u8 这个m3u8文件时，合并会报错
![TIM截图20200201163016](https://user-images.githubusercontent.com/45138664/73589383-9e8c2780-4510-11ea-9682-a84633cc3293.png) 而且合并出的视频播放有问题

**Comment by nilaoda** [comment]
通过`二进制合并`可正常下载，之后新版本修复

**Comment by bingshuangw** [comment]
我测试了一下，通过二进制合并后的文件并不能正常播放。前几秒播放正常，但是后面视频画面跳动而且没有声音，如果仅合并音频轨道的话可以正常提取出音频

**Comment by nilaoda** [comment]
> 我测试了一下，通过二进制合并后的文件并不能正常播放。前几秒播放正常，但是后面视频画面跳动而且没有声音，如果仅合并音频轨道的话可以正常提取出音频

修改成mp4后缀呢

**Comment by bingshuangw** [comment]
mp4后缀也是一样的问题

**Comment by bingshuangw** [comment]
我看到一篇博客，感觉比较符合这个问题，[关于 FFmpeg 合并 HLS/m3u8 流 TS 切片时出现 Non-monotonous DTS in output stream 的问题](https://iyn.me/i/post-32.html)，可以参考一下

**Comment by nilaoda** [comment]
再发一个m3u8可好，之前的失效了

**Comment by bingshuangw** [comment]
https://dl101.twitcasting.tv/tc.vod/v/591075572-1580725800-1580754600-9171e0b9-2de14413940dd2ea/fmp4/index.m3u8，网址是https://twitcasting.tv/hmwr_4/movie/591075572

**Comment by nilaoda** [comment]
我试了一下二进制合并 很正常啊
![image](https://user-images.githubusercontent.com/20772925/73660275-d0e58280-46d2-11ea-9b67-c0358beeb4d2.png)

**Comment by bingshuangw** [comment]
我人晕了，原来是播放器的问题，原来用的mpv播放器播放不了
