### ISSUE TITLE
老大，我的批处理脚本问题在哪，提示地址无效，单独下又可以

### ISSUE THREAD

**Issue by xiaoxiaoliya** [nilaoda/N_m3u8DL-CLI#578]
"N_m3u8DL-CLI_v2.9.9.exe" "https://valipl-vip.cp31.ott.cibntv.net/65728168E47307146D96062DC/05007E00006180E7678BB780000000D37DEB01-5DFD-4ADA-9B11-4C926004C320_video.m3u8?ccode=0502&duration=1477&expire=18000&psid=8d83f425f6491d3ca73e46f1be977d1443346&ups_client_netip=db90a4af&ups_ts=1640710268&ups_userid=1104021290&apscid=&mnid=&umt=1&type=cmaf4hd3&utid=PoU7Gvh4ux0CAXp2qYX6eieM&vid=XNTE5OTQ4NTQ4MA%3D%3D&s=eaac6f7662474171bcda&iv=1&sp=&t=6d456319bfd897e&cug=2&bc=2&si=3&eo=1&vkey=Bea549ae8d29bd7880214f79c2c881cf7" --saveName 10 --enableDelAfterDone --disableDateInfo --useKeyBase64 i1xw6NuhZGaY4xiZrQxpWA==

只列出了一条,而且我在使用gui填key解密时不可以，提示数据块不完整
用指令下载并解密时又正常 望解答

**Comment by nilaoda** [comment]
BAT中需要把`%`替换为`%%`
