### ISSUE TITLE
无效的m3u8，地址无效怎么处理啊？

### ISSUE THREAD

**Issue by jasondong1999** [nilaoda/N_m3u8DL-CLI#579]
我这边显示无效的m3u8，地址无效。怎么处理呢，该网站是需要登陆会员的。
![image_2021-12-29_13-27-07](https://user-images.githubusercontent.com/95381728/147630306-7256ecdc-9325-4acf-88da-f3e8c678f37f.png)

**Comment by nilaoda** [comment]
尝试置入Cookie

**Comment by jasondong1999** [comment]
> 尝试置入Cookie

请问Cookie在哪里置入

**Comment by yongganint** [comment]
加一 怎么置入Cookie

**Comment by zhangdaren** [comment]
header请求头

**Comment by jasondong1999** [comment]
解决
