### ISSUE TITLE
有人會 mgstage 的破解嗎？

### ISSUE THREAD

**Issue by 9DA73860** [nilaoda/N_m3u8DL-CLI#585]
有大神可以賜教嗎 謝啦
希望可以造福人群

**Comment by violetteflutter** [comment]
你有账号的话我可以试试

**Comment by missdgsn** [comment]
我刚学会，但是怎么下下来的都是720P的，我也不清楚这个网站的6000K下的1080P到底藏在哪

**Comment by 9DA73860** [comment]
> 

大神可以分享技術嗎, 一直找不到密鑰啊, 可以加 telegram?
有沒有試過去 Sokmil ? 那裡都有蚊香社的 1080p

**Comment by 9DA73860** [comment]
> 我刚学会，但是怎么下下来的都是720P的，我也不清楚这个网站的6000K下的1080P到底藏在哪



> 我刚学会，但是怎么下下来的都是720P的，我也不清楚这个网站的6000K下的1080P到底藏在哪

**Comment by 9DA73860** [comment]
> 我刚学会，但是怎么下下来的都是720P的，我也不清楚这个网站的6000K下的1080P到底藏在哪

大神可以分享技術嗎, 一直找不到密鑰啊, 可以加 telegram?
有沒有試過去 Sokmil ? 那裡都有蚊香社的 1080p

**Comment by missdgsn** [comment]
> 

sokmil现在整个日本AV破解最大提供者都搞不了，别想了。
MGSTAGE我研究了一下，还是有1080P的，不过画面看发布的情况，技术不用想了，大家都不会提供的

**Comment by 9DA73860** [comment]
> > 
> 
> sokmil现在整个日本AV破解最大提供者都搞不了，别想了。 MGSTAGE我研究了一下，还是有1080P的，不过画面看发布的情况，技术不用想了，大家都不会提供的

花了半個月時間 最後都會破解了 Sokmil 和 Mgs啦 
有些 mgs 根本就沒有 1080P

**Comment by sishenzhisi** [comment]
大佬能教一下么

**Comment by Mak0760** [comment]
> > > 
> > 
> > 
> > sokmil现在整个日本AV破解最大提供者都搞不了，别想了。 MGSTAGE我研究了一下，还是有1080P的，不过画面看发布的情况，技术不用想了，大家都不会提供的
> 
> 花了半個月時間 最後都會破解了 Sokmil 和 Mgs啦 mgs player 下的都是 6000k, 有1080p 就有, 沒有也怪 mgs 窮

大佬可以教下么，有偿
