### ISSUE TITLE
爱奇艺获取M3U8地址的JS是不是不能用了

### ISSUE THREAD

**Issue by forget726** [nilaoda/N_m3u8DL-CLI#592]
我登录爱奇艺VIP，然后点击JS脚本，没有一点反应，是不是失效了？其他网站的JS我没试过。还有那么多爱奇艺的脚本，应该点哪个（PS：其实我都试了，都没反应）

**Comment by weixiangnan** [comment]
爱奇艺确实失效了，腾讯视频还能用

**Comment by nilaoda** [comment]
已失效，现在4K清晰度全部加密了

**Comment by chopper-go** [comment]
找到下载4k的办法了吗？

**Comment by forget726** [comment]
没有



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月24日(星期五) 晚上11:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nilaoda/N_m3u8DL-CLI] 爱奇艺获取M3U8地址的JS是不是不能用了 (Issue #592)





 
找到下载4k的办法了吗？

**Comment by hero7069** [comment]
谁知道方法吗？
