### ISSUE TITLE
录制直播

### ISSUE THREAD

**Issue by zhangyining215** [nilaoda/N_m3u8DL-CLI#60]
请教下这个软件怎样录制直播，需要如何操作 谢谢

**Comment by nilaoda** [comment]
目前不推荐使用本软件录制直播

**Comment by zhangyining215** [comment]
那有什么推荐吗？？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nilaoda"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月11日(星期二) 中午1:22
收件人:&nbsp;"nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;;
抄送:&nbsp;"? ????"<zhangyining215@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 录制直播 (#60)




目前不推荐使用本软件录制直播

**Comment by nilaoda** [comment]
> 那有什么推荐吗？？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"nilaoda"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月11日(星期二) 中午1:22 收件人:&nbsp;"nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;; 抄送:&nbsp;"? ????"<zhangyining215@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 录制直播 (#60) 目前不推荐使用本软件录制直播 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

https://github.com/streamlink/streamlink
