### ISSUE TITLE
 能否考虑集成You-Get , Youtube-dl , Annie，等工具 

### ISSUE THREAD

**Issue by SONGjiemo** [nilaoda/N_m3u8DL-CLI#604]
我支持其他 youtube-dl、you-get、lux 工具。 更多网站可以下载。
youtube-dl 地址
https://github.com/ytdl-org/youtube-dl
you-get
https://github.com/soimort/you-get
lux
https://github.com/iawia002/lux

期待答复。
工具设计建议，GUI可以做一个选择然后启用选择（ youtube-dl、you-get、lux ）对应的功能。

**Comment by nilaoda** [comment]
不会支持，他只是一个小工具。
