### ISSUE TITLE
希望新增對SAMPLE-AES-CTR解密

### ISSUE THREAD

**Issue by ustr0aTe** [nilaoda/N_m3u8DL-CLI#621]
網址: https://stagecrowd.live/s/sc/page/live_player_test
m3u8: https://bcovlive-a.akamaihd.net/2d12a0883b56406b9bdfba9f51961095/ap-northeast-1/6160987587001/playlist_wv.m3u8
Mappingweb: https://bcovlive-a.akamaihd.net/2d12a0883b56406b9bdfba9f51961095/ap-northeast-1/6160987587001/profile_0/init.mp4
url和IV都有包括在m3u8
url內包Base64解出assetId看似key?
![螢幕擷取畫面 2022-03-13 140026](https://user-images.githubusercontent.com/67262252/158047189-c7dbfac1-8b5c-4247-b7fb-3d8261eecc01.png)

**Comment by Ink-33** [comment]
先说结论，这个站最近也在关注，下载视频应该是不太可能的了。

这个站使用的是`brightcove`提供的媒体点播服务，所有的视频和直播都使用了drm技术进行保护（`Widevine`和`Fairplay`）

实际上加密方式为`sample-aes`几乎就代表使用的drm技术，目前来看这个站最好的解决方案还是使用采集卡录制

**Comment by 592767809** [comment]
![QQ截图20240223162805](https://github.com/nilaoda/N_m3u8DL-CLI/assets/42226845/258eed31-f0a8-4733-8f3d-16ac6d142089)
这个地址可以尝试这个key来解密
98fe2cc47352f0170a03d2eeb41d0488:9b35588ce16dc0894af4fdd5a01abcb5

**Comment by linewon** [comment]
> 先说结论，这个站最近也在关注，下载视频应该是不太可能的了。
> 
> 这个站使用的是`brightcove`提供的媒体点播服务，所有的视频和直播都使用了drm技术进行保护（`Widevine`和`Fairplay`）
> 
> 实际上加密方式为`sample-aes`几乎就代表使用了drm技术，目前来看这个站最好的解决方案还是使用采集卡录制

method=sample-aes，但是我拿到了秘钥，要怎么对视频进行解密啊？
怎么确定他的加密模式，是aes-cbc，还是aes-ctr？
