### ISSUE TITLE
N_m3u8DL-CLI 2.9.9下载优酷视频出现如下问题

### ISSUE THREAD

**Issue by hcyxd** [nilaoda/N_m3u8DL-CLI#622]
<a href="https://imgtu.com/i/bL8Ju8"><img src="https://s1.ax1x.com/2022/03/14/bL8Ju8.png" alt="bL8Ju8.png" border="0" /></a>

**Comment by nilaoda** [comment]
请注意，下载器不支持优酷视频。

**Comment by hcyxd** [comment]
收到，谢谢啦



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年03月14日 11:01 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [nilaoda/N_m3u8DL-CLI] N_m3u8DL-CLI 2.9.9下载优酷视频出现如下问题 (Issue #622) |

请注意，下载器不支持优酷视频。

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
