### ISSUE TITLE
Nilaoda, 现在软件下载YY高清视频，断断续续

### ISSUE THREAD

**Issue by rufan321** [nilaoda/N_m3u8DL-CLI#624]
Nilaoda, 现在软件下载YY高清视频，断断续续，好像YY系统增加视频下载识别的样子，如果在potplayer看直播，是没有断续，下载也没事，但是用N_m3u8DL-CLI来下载，视频太多断续，是不是要更新一下m3u8DL软件，老大。

**Comment by nilaoda** [comment]
软件对于直播的判断机制不太完善，最好用别的软件比如streamlink来录制直播吧~

**Comment by rufan321** [comment]
谢谢老大的回复

**Comment by rufan321** [comment]
streamlink不支持YY直播录制，老大还有其他软件推荐吗

**Comment by rufan321** [comment]
谢谢老大

**Comment by rufan321** [comment]
老大，这个问题解决了，是下载工具的问题，我找了52pojie里面的，很萌下载器，就没有这个问题了，不知道N_m3u8DL-CLI那个地方要设置呢，我一直没去设置其他参数，只设路径来下载
