### ISSUE TITLE
可否增加使用m3u8文件合并ts并转mp4，不要直接合成ts转mp4，因为发现合并的视频会卡顿。

### ISSUE THREAD

**Issue by wuabuhuan** [nilaoda/N_m3u8DL-CLI#625]
可否增加使用m3u8文件合并ts并转mp4，不要直接合成ts转mp4，因为发现合并的视频会卡顿。

**Comment by nilaoda** [comment]
可以使用二进制合并，然后再手动转换封装

**Comment by nilaoda** [comment]
你说的“m3u8合并的”是什么操作😕

**Comment by wuabuhuan** [comment]
ffmpeg  -i xxx.ts -vcodec copy -acodec copy -absf aac_adtstoasc  xxx.mp4
ffmpeg  -i raw.m3u8 -vcodec copy -acodec copy -absf aac_adtstoasc  xxx.mp4
这个区别

**Comment by nilaoda** [comment]
希望提供m3u8文件或链接我看看
