### ISSUE TITLE
在 Pycharm 用 Popen 打开会停止工作, System.IO.IOException: System.Console.get_WindowWidth(); N_m3u8DL_CLI.LOGGER.PrintLine(String text, Int32 printLevel)

### ISSUE THREAD

**Issue by ZHLONG-CN** [nilaoda/N_m3u8DL-CLI#626]
Pycharm的控制台输出没有窗口, 编写下面的代码

```python
from subprocess import Popen, PIPE

exe = 'N_m3u8DL-CLI_v2.9.9.exe'
p = Popen(args=[exe, download_url, '--saveName "%s"' % filename], stdout=PIPE, stdin=PIPE)
```

运行会发生异常:

```
δ��������쳣:  System.IO.IOException: �����Ч��

   �� System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   �� System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   �� System.Console.get_WindowWidth()
   �� N_m3u8DL_CLI.LOGGER.PrintLine(String text, Int32 printLevel)
   �� N_m3u8DL_CLI.NetCore.Program.Main(String[] args)
```

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/1978428674

**Comment by IPjoshua** [comment]
> https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/1978428674

N_m3u8DL-CLI version 2.9.9 2018-2021
  built date: 20211123
                                                             
10:38:37.440 д��meta.json
                                                            
10:38:37.499 �ļ�ʱ����00m28s
                                                           
10:38:37.500 �ܷ�Ƭ��5, ��ѡ���Ƭ��5
                                                            
10:38:37.501 ʶ��Ϊֱ����, ��ʼ¼��...
                                                              
10:38:37.507 <1647655929 Downloading>
                                                           
10:38:37.561 <1647655929 Complete>
                                                              
10:38:37.563 ��ȡ�ļ���Ϣ...
                                                             
10:38:37.673 <1647655930 Downloading>
                                                           
10:38:37.712 <1647655930 Complete>
                                                              
10:38:37.712 <1647655931 Downloading>
                                                            
10:38:37.731 <1647655931 Complete>
                                                            
10:38:37.731 <1647655932 Downloading>
                                                            
10:38:37.776 <1647655932 Complete>
                                                           
10:38:37.776 <1647655933 Downloading>
                                                           
10:38:37.806 <1647655933 Complete>
                                                              
10:38:37.806 Waiting...
                                                            
10:38:37.806 ���Ӧ�ó���û�п���̨�����̨������ͨ���ļ��������ض������޷���ȡ�����볢��ʹ�� Console.Read��

[Done] exited with code=0 in 0.724 seconds

怎么才能支持直播呢？
