### ISSUE TITLE
老大，今天又遇到了，一直卡在下载map文件

### ISSUE THREAD

**Issue by xiaoxiaoliya** [nilaoda/N_m3u8DL-CLI#627]
![image](https://user-images.githubusercontent.com/94291982/159278645-3e842464-e879-4433-b261-bcc0912e9334.png)

**Comment by xiaoxiaoliya** [comment]
解决了老大。我自己的问题

**Comment by daliali2088** [comment]
亲 问一下 怎么解决的  跟你同样的问题
