### ISSUE TITLE
Dash

### ISSUE THREAD

**Issue by MyGoodbye** [nilaoda/N_m3u8DL-CLI#630]
我下载爱奇艺dash链接下不了呢？

**Comment by MyGoodbye** [comment]
下下来的dash.json 可以通过脚本直接转成m3u8文件吗

**Comment by nilaoda** [comment]
Dash是通SimpleG来实现下载的，N_m3u8DL-CLI 本身不支持。

https://github.com/nilaoda/N_m3u8DL-CLI-SimpleG/blob/8d6f9181c25f6f82de6b58f3d1bbe0e0daea237a/N_m3u8DL-CLI-SimpleG/MainWindow.xaml.cs#L287-L319
