### ISSUE TITLE
How can I download Udemy.com ?

### ISSUE THREAD

**Issue by rajhlinux** [nilaoda/N_m3u8DL-CLI#631]
Hello,

How can I download videos from Udemy.com?

I have the decryption keys.

All I would like to do is download the encrypted video.

I can decrypt the video on my PC.

Thanks.

**Comment by CHITTIMOTU** [comment]
i can able to downland Udemy coerces with this repo earlier [https://github.com/Puyodead1/udemy-downloader](url)
But this need widewine decryption keys. earlier most of users uses used widewine  guesser chrome extensions to get those keys, but that method is not working now,

currently few people are getting key's from getting keys from PSSH, headers ,license url, and MPD url, But those are different and may not work with above repo

I am not sure, i also failed to get the proper keys, 
keys getting from this [http://getwvkeys.cc/](url) are not working for me

**Comment by rajhlinux** [comment]
The getwvkeys.cc CDM got revoked from Udemy.com, it will not work.

You'll need to obtain a new CDM that is not revoked.
