### ISSUE TITLE
求推荐一个播放.ts文件的应用，我用potplayer打不开

### ISSUE THREAD

**Issue by wordscode** [nilaoda/N_m3u8DL-CLI#634]
Built-in Async Reader::Output

==========================
无法获取 音频|视频 信息。(不支持播放加密媒体)
==========================

Media Type 0:
--------------------------
Unknown

[AM_MEDIA_TYPE]
  majortype: MEDIATYPE_Stream {E436EB83-524F-11CE-9F53-0020AF0BA770}
  subtype: MEDIASUBTYPE_MPEG2_TRANSPORT {E06D8023-DB46-11CF-B4D1-00805F6CBBEA}
  formattype: GUID_NULL {00000000-0000-0000-0000-000000000000}
  bFixedSizeSamples: 1
  bTemporalCompression: 0
  lSampleSize: 1
  cbFormat: 0

**Comment by SkyTeamWater** [comment]
vlc
