### ISSUE TITLE
求求了，出个linux版！

### ISSUE THREAD

**Issue by wuabuhuan** [nilaoda/N_m3u8DL-CLI#639]
求求了，出个linux版！求求了，出个linux版！求求了，出个linux版！😢

**Comment by nilaoda** [comment]
嗯~ o(*￣▽￣*)o

**Comment by wuabuhuan** [comment]
❤❤❤❤❤❤❤❤❤❤❤

**Comment by talway** [comment]
支持，需要一个，

**Comment by YUIIUY** [comment]
确实...希望能在Debian上用...

**Comment by vincentTea** [comment]
我修改了一下，弄出了一个.net 6的版本
https://github.com/vincentTea/N_m3u8DL-CLI-.Net-6-

**Comment by dixtdf** [comment]
> 我修改了，弄了一个 [https://github.com/vincentTea/N_m3u8DL-CLI-.Net-6-的版本](https://github.com/vincentTea/N_m3u8DL-CLI-.Net-6-)

mono运行还是直接运行？

**Comment by vincentTea** [comment]
> 

注意一个问题：ffmpeg调用的路径我并没有处理，需要在编译后的目录下建立个ffmpeg.exe的软链：
先用：whereis ffmpeg 看看ffmpeg在哪个路径，比如我的：/usr/bin/ffmpeg
ln -s /usr/bin/ffmpeg ./ffmpeg.exe

**Comment by TianLanSky** [comment]
支持

**Comment by whp98** [comment]
同求

**Comment by nilaoda** [comment]
@wuabuhuan @talway @YUIIUY @dixtdf @TianLanSky @whp98 
请关注全新跨平台版本：https://github.com/nilaoda/N_m3u8DL-RE
