### ISSUE TITLE
小白求助，折腾小鹅通平台下载，添加请求头，baseurl，自定义key，iv均无用

### ISSUE THREAD

**Issue by t20161216** [nilaoda/N_m3u8DL-CLI#644]
不添加请求头会报m3u8地址无效，添加了如下三条请求头后，取得了重大进步
Host: encrypt-k-vod.xet.tech|Referer: https://apphfuydjku5721.pc.xiaoe-tech.com/|User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Mobile Safari/537.36
但是会在开始下载文件这步卡住
16:45:31.671 下载首分片...
16:45:38.087 读取文件信息...
             Error in reading file
16:45:38.089 等待下载完成...
16:48:21.462 完成数量 0 / 237
16:48:21.463 重试次数 1 / 15
![image](https://user-images.githubusercontent.com/24600595/163963384-3a4dffb8-189e-4ea7-a3e1-5c984242a5a9.png)

经过对比发现，在simpleG中填写BASEURL会跳过报错，但是进度一直不增加，想来是我没找到正确的baseurl，网上查了半天无解

![image](https://user-images.githubusercontent.com/24600595/163967174-017ed468-e3bc-477f-acae-b32cbdc8ff88.png)

后来发现下载目录里的json有一些其他信息，添加后仍无结果，贴上日志求助大佬。
LOG 2022/04/19
Save Path: C:\Users\qq\Downloads\Compressed\N_m3u8DL-CLI_v2.9.9_with_ffmpeg_and_SimpleG\Logs
Task Start: 2022/04/19 17:32:37
Task CommandLine: "C:\Users\qq\Downloads\Compressed\N_m3u8DL-CLI_v2.9.9_with_ffmpeg_and_SimpleG\N_m3u8DL-CLI_v2.9.9.exe" "https://encrypt-k-vod.xet.tech/529d8d60vodtransbj1252524126/3ebc4e5b387702297940810469/drm/voddrm.token.ZDVlNDY1YjVlNjQyYjQ5YTJ1ajNPUi9xaWRqcjI2bGhCUlAvdnlaUStsTVh5VGhPOGlHZFRudHdINkRrZTNpOQ.v.f421218.m3u8?t=625fcea9&exper=0&us=hKH4V3kKi2bz&whref=apphfuydjku5721.pc.xiaoe-tech.com&sign=83d6c88d6f306b02b17e2f8d0573ca88" --saveName "apphfuydjku5721.pc.xiaoe-tech.com.Pragma" --headers "Accept: */*|Accept-Encoding: gzip, deflate, br|Accept-Language: zh-CN,zh;q=0.9|Cache-Control: no-cache|Connection: keep-alive|Origin: https://apphfuydjku5721.pc.xiaoe-tech.com|Pragma: no-cache|sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="100", "Google Chrome";v="100"|sec-ch-ua-mobile: ?1|sec-ch-ua-platform: "Android"|Sec-Fetch-Dest: empty|Sec-Fetch-Mode: cors|Sec-Fetch-Site: cross-site|Host: encrypt-k-vod.xet.tech|Referer: https://apphfuydjku5721.pc.xiaoe-tech.com/|User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Mobile Safari/537.36" --baseUrl "https://apphfuydjku5721.pc.xiaoe-tech.com/v.f421220_0.ts?start=0&end=511935&type=mpegts&exper=0&sign=a121ad9a7ef90227bb2fc3f2deaedad8&t=625fbc87&us=aTk8dI7NKBjd&whref=apphfuydjku5721.pc.xiaoe-tech.com" --useKeyBase64 "KYF/2z3j5jgyMgN5Rv0kew==" --useKeyIV "0x00000000000000000000000000000000" --enableDelAfterDone 

17:32:37.671 / (NORMAL) 开始解析 https://encrypt-k-vod.xet.tech/529d8d60vodtransbj1252524126/3ebc4e5b387702297940810469/drm/voddrm.token.ZDVlNDY1YjVlNjQyYjQ5YTJ1ajNPUi9xaWRqcjI2bGhCUlAvdnlaUStsTVh5VGhPOGlHZFRudHdINkRrZTNpOQ.v.f421218.m3u8?t=625fcea9&exper=0&us=hKH4V3kKi2bz&whref=apphfuydjku5721.pc.xiaoe-tech.com&sign=83d6c88d6f306b02b17e2f8d0573ca88
17:32:37.727 / (ERROR) 必须使用适当的属性或方法修改“Connection”标头。
参数名: name
17:32:37.950 / (ERROR) 必须使用适当的属性或方法修改“Connection”标头。
参数名: name
17:32:38.318 / (NORMAL) 获取m3u8 key... base64:KYF/2z3j5jgyMgN5Rv0kew==
17:32:38.319 / (ERROR) 无效的m3u8
17:32:38.424 / (NORMAL) 开始下载文件
17:32:38.435 / (ERROR) 必须使用适当的属性或方法修改“Connection”标头。
参数名: name
17:32:38.767 / (ERROR) 输入数据不是完整的块。

**Comment by intersdp** [comment]
没错，我下载小鹅通视频也遇到了楼主所说的障碍，但是使用手机上的UC浏览器却能把小鹅通已购买的整个视频下载下来

**Comment by f9021003** [comment]
請問有找到方法可以下載小鵝通影片了嗎？

**Comment by chenzijie-chenxiaoli-chentong** [comment]
可以下载的，@cenjy9

**Comment by chenzijie-chenxiaoli-chentong** [comment]
代下QQ：1033383881

**Comment by BunnyMaster** [comment]
# 方式一：有些麻烦 
推荐查看教程：`https://www.52pojie.cn/thread-1689801-1-1.html`  这个教程需要懂点js逆向的
# 方式二
也有简单的办法，直接将第一个视频地址如：`https://c-vod-hw-k.xiaoeknow.com/asset/4a55418f88fec538483577fffb5fc0b0/8000007_OmpCpnYx1ikR_0.ts?&sign=1xx6a5c8781ca65bxxxebbc31be51&t=65244872&us=fMwYtBxxx`
将里面的`0.ts`替换成`.m3u8`即可，之后就能拿到可以处理的m3u8文件了
>这里面只要是视频地址都可以这样替换的，只要替换成后缀是m3u8 的就可以了

之后就能看到地址了，将下载器中BASEURL地址填上，也就是视频开始的地址不包含m3u8后面的内容，如上面的``https://c-vod-hw-k.xiaoeknow.com/asset/4a55418f88fec538483577fffb5fc0b0/`

将m3u8文件中URL地址的下载下来，拖到下载器中就可以使用了

我也是今天发现的，因为key做了处理，并不是拿来就能用的

**Comment by Cyiming** [comment]
> # 方式一：有些麻烦
> 推荐查看教程：`https://www.52pojie.cn/thread-1689801-1-1.html` 这个教程需要懂点js逆向的
> 
> # 方式二
> 也有简单的办法，直接将第一个视频地址如：`https://c-vod-hw-k.xiaoeknow.com/asset/4a55418f88fec538483577fffb5fc0b0/8000007_OmpCpnYx1ikR_0.ts?&sign=1xx6a5c8781ca65bxxxebbc31be51&t=65244872&us=fMwYtBxxx` 将里面的`0.ts`替换成`.m3u8`即可，之后就能拿到可以处理的m3u8文件了
> 
> > 这里面只要是视频地址都可以这样替换的，只要替换成后缀是m3u8 的就可以了
> 
> 之后就能看到地址了，将下载器中BASEURL地址填上，也就是视频开始的地址不包含m3u8后面的内容，如上面的``[https://c-vod-hw-k.xiaoeknow.com/asset/4a55418f88fec538483577fffb5fc0b0/`](https://c-vod-hw-k.xiaoeknow.com/asset/4a55418f88fec538483577fffb5fc0b0/%60)
> 
> 将m3u8文件中URL地址的下载下来，拖到下载器中就可以使用了
> 
> 我也是今天发现的，因为key做了处理，并不是拿来就能用的

请问https://c-vod-hw-k.xiaoeknow.com/asset/20c4444622c4b129180632eafc83bfc2/8000007_XAltxIveTasX_26.ts?sign=455e557064702bf1072480b94a4ff213&t=65b19e3c&us=JZiYNCkpVp

是要换成
https://c-vod-hw-k.xiaoeknow.com/asset/20c4444622c4b129180632eafc83bfc2/8000007_XAltxIveTasX_26.m3u8么
然后填入
https://c-vod-hw-k.xiaoeknow.com/asset/20c4444622c4b129180632eafc83bfc2
不行啊
