### ISSUE TITLE
大大 问一下这个应该加什么请求头才可以开始下载

### ISSUE THREAD

**Issue by huliad2022** [nilaoda/N_m3u8DL-CLI#646]
MPD：`https://vsu.play.kakao.com/vod/rvolpc60dkb56j370uv7y38sm/dash/vhs/cenc/adaptive.mpd?px-time=1650638913&px-path=%2Fvod%2Frvolpc60dkb56j370uv7y38sm%2Fdash%2Fvhs%2Fcenc%2F&px-hash=ccbc0afd15697ad46dce16b37916b1cd`

网站：`https://tv.kakao.com/channel/3964341/cliplink/428129636`

IP：韩国

尝试加了referer，origin，user-agent
下载都是一直显示下载map文件

![image](https://user-images.githubusercontent.com/77323405/164709510-112deacf-bd96-4cad-abe2-5218bf26c119.png)

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/164747274-4ad7e921-c690-4731-bc86-db7b980dfc4f.png)

这网站后面要拼接mpd链接的参数才能，软件没识别出这个

先临时针对性修了，到这里下载 https://github.com/nilaoda/N_m3u8DL-CLI/actions

**Comment by huliad2022** [comment]
谢谢大大 这站最近才改成这样的 之前加请求头就可以下   
![10485998](https://user-images.githubusercontent.com/77323405/164750913-394226c4-f746-4a42-b76c-259985af6f2d.png)
