### ISSUE TITLE
HAMIVIDEO M3U8提取

### ISSUE THREAD

**Issue by argo5107** [nilaoda/N_m3u8DL-CLI#649]
https://hamivideo.hinet.net/product/179167.do?cs=2

不知道有沒有大神有辦法提取

https://hamivideo.hinet.net/product/179118.do?cs=2

尚食就有辦法擷取

@nilaoda 
是否可以幫忙確認看看 我是哪個環節有問題

**Comment by xiaoxiaoliya** [comment]
> https://hamivideo.hinet.net/product/179167.do?cs=2
> 
> 不知道有沒有大神有辦法提取
> 
> https://hamivideo.hinet.net/product/179118.do?cs=2
> 
> 尚食就有辦法擷取
> 
> @nilaoda 是否可以幫忙確認看看 我是哪個環節有問題

widevine加密，请关注其他repo

**Comment by argo5107** [comment]
> repo
所以是有可能破解的嗎?

**Comment by soonayun** [comment]
> https://hamivideo.hinet.net/product/179167.do?cs=2
> 
> 不知道有沒有大神有辦法提取
> 
> https://hamivideo.hinet.net/product/179118.do?cs=2
> 
> 尚食就有辦法擷取
> 
> @nilaoda 是否可以幫忙確認看看 我是哪個環節有問題

你下载hami video其他影片，下载完成的文件有音频吗

**Comment by soonayun** [comment]
我是用idm抓取Hami video的m3u8地址，请问你是如何查找提取音軌的? 最后用什么软件将视频和音轨合并的？

argo5107 ***@***.***> 于2022年4月26日周二 09:22写道：

**Comment by argo5107** [comment]
我是用腳本去解析+F12去手動解析 
HAMI新上的動畫跟影片 影片跟音軌都是分開的
最後可以用小丸工具箱合併

**Comment by soonayun** [comment]
好的谢谢

argo5107 ***@***.***> 于2022年4月26日周二 22:51写道：

**Comment by xiaoxiaoliya** [comment]
> > repo
> > 所以是有可能破解的嗎?

是的

**Comment by xiaoxiaoliya** [comment]
> > > > repo
> > > > 所以是有可能破解的嗎?
> > 
> > 
> > 是的
> 
> 有可能跟您請教這部分的資訊嗎?

提供邮箱，如果我有时间，会把key发送给你。

**Comment by argo5107** [comment]
> > > > > repo
> > > > > 所以是有可能破解的嗎?
> > > 
> > > 
> > > 是的
> > 
> > 
> > 有可能跟您請教這部分的資訊嗎?
> 
> 提供邮箱，如果我有时间，会把key发送给你。

argo3c@gmail.com
還請幫忙 這部分我是新手 到時候再麻煩多多指導

**Comment by argo5107** [comment]
> > > > > > 回购
> > > > > > 所以是有可能破解的吗？
> > > > 
> > > > 
> > > > 是的
> > > 
> > > 
> > > 有可能和您一起教这部分的信息吗？
> > 
> > 
> > 提供邮箱，如果我有时间，把钥匙发送给你。
> 
> 我也需要 現在還能提供嗎 郵箱：[zxxznb3@gmail.com](mailto:zxxznb3@gmail.com) 有tg嗎 如果有的話可以吧tg的id一起發到郵箱里嗎 我也想討論..

我目前是還沒收到
HAMI有不少資源都有上DRM

**Comment by smallwhitedesu** [comment]
> 

可能還沒有空吧 現在hami是新的都有DRM加密了

**Comment by nilaoda** [comment]
DRM的网站我不想搞，可以关注一下其他项目

**Comment by soonayun** [comment]
> DRM的网站我不想搞，可以关注一下其他项目

你好，请问能否增加hami video 下载后的音轨文件和视频文件合并的功能！谢谢感激不尽！

**Comment by argo5107** [comment]
> > DRM的网站我不想搞，可以关注一下其他项目
> 
> 你好，请问能否增加hami video 下载后的音轨文件和视频文件合并的功能！谢谢感激不尽！

那是M3U8直接強制兩個分開下載 只能事後手動合併

**Comment by argo5107** [comment]
> DRM的网站我不想搞，可以关注一下其他项目

收到 謝謝您的回覆

**Comment by argo5107** [comment]
謝謝大家的熱情回復

**Comment by xiaoxiaoliya** [comment]
> [zxxznb3@gmail.com](mailto:zxxznb3@gmail.com)

已回复。

**Comment by argo5107** [comment]
> > [zxxznb3@gmail.com](mailto:zxxznb3@gmail.com)
> 
> 已回复。

我好像還沒收到

**Comment by smallwhitedesu** [comment]
> > [zxxznb3@gmail.com](mailto:zxxznb3@gmail.com)
> 
> 已回复。

收到

**Comment by hopradio** [comment]
> > > > > repo
> > > > > 所以是有可能破解的嗎?
> > > 
> > > 
> > > 是的
> > 
> > 
> > 有可能跟您請教這部分的資訊嗎?
> 
> 提供邮箱，如果我有时间，会把key发送给你。

大佬能給個KEY嗎？

**Comment by OhGui** [comment]
所以最后是如何获取到的，大佬们能说下吗

**Comment by yoyo890121** [comment]
有抓到key，但decrypt後是花屏檔案
是key錯誤解密失敗嗎?

**Comment by hahaccc32** [comment]
> > > > > repo
> > > > > 所以是有可能破解的嗎?
> > > 
> > > 
> > > 是的
> > 
> > 
> > 有可能跟您請教這部分的資訊嗎?
> 
> 提供邮箱，如果我有时间，会把key发送给你。

希望也能拿到key，真的感激不盡
