### ISSUE TITLE
为什么总是下载到快好的时候卡住呢？

### ISSUE THREAD

**Issue by Tao-Bath** [nilaoda/N_m3u8DL-CLI#65]
快下载完的时候一直重试

**Comment by nilaoda** [comment]
日志里
```
(ERROR) DOWN: 远程服务器返回错误: (520) Origin Error。
```
你试着在请求头那里填写对应Origin

**Comment by Tao-Bath** [comment]
> 日志里
> 
> ```
> (ERROR) DOWN: 远程服务器返回错误: (520) Origin Error。
> ```
> 
> 你试着在请求头那里填写对应Origin

请问如何查看origin呢？

**Comment by Tao-Bath** [comment]
> 日志里
> 
> ```
> (ERROR) DOWN: 远程服务器返回错误: (520) Origin Error。
> ```
> 
> 你试着在请求头那里填写对应Origin

大神，我把origin， referer，user-agent都添加到header里了。现在能下载了，但是下载完了以后命令行最下面出现2行红字，然后关闭了，也没合并。
