### ISSUE TITLE
N_m3u8DL-CLI配合Linetv.tw剧集解析工具出现「地址无效」

### ISSUE THREAD

**Issue by qbabe** [nilaoda/N_m3u8DL-CLI#653]
N_m3u8DL-CLI配合Linetv.tw剧集解析工具LinetvParser.v2.0使用『强制转为FHD』后，出现「地址无效」
能否修復『强制转为FHD』所产生的「地址无效」呢?
谢谢

C:\N_m3u8DL-CLI_v2.9.9_with_ffmpeg_and_SimpleG>N_m3u8DL-CLI.exe "[https://d3c7rimkq79yfu.cloudfront.net/13384/1/v4/13384-ep
s-1_FHD.m3u8?Expires=1652183704263&Key-Pair-Id=K3A3HFLQY0L90Y&Signature=tWRvts4Z
WXLotOJePsyqwJrLfP~pV~mz1D46T8SX~Nk30Le5LHXnyb1ziZIfA6QIjJjbBg7fWTu~igAPKBeVby9c
2fbGzZdfNl8uaJW5y9Jj8NgTylsM99yO~97uPLQFHGh~LXjLxAdQ0heKwJAMGEylM1it6kc0UMInPL3d
M2iYFT9HCOkLklX5CzZc4XOmQ1Axoh5Y8UkU5-T4w9G1rJSMFjorM5PCPk4n-tSoRIKliwEMEAV5zCHr
1VnsG8vr4ZKtmGHxZNmRl5esrtKviUWy-d11MXA4VhuJMkm10ELsJWiaP4XMaKwuM4cqNTp8oqzlI9u4
wp~4z-dl-jhN7A__](https://d3c7rim
kq79yfu.cloudfront.net/13384/1/v4/13384-eps-1_FHD.m3u8?Expires=1652183704263&Key
-Pair-Id=K3A3HFLQY0L90Y&Signature=tWRvts4ZWXLotOJePsyqwJrLfP~pV~mz1D46T8SX~Nk30L
e5LHXnyb1ziZIfA6QIjJjbBg7fWTu~igAPKBeVby9c2fbGzZdfNl8uaJW5y9Jj8NgTylsM99yO~97uPL
QFHGh~LXjLxAdQ0heKwJAMGEylM1it6kc0UMInPL3dM2iYFT9HCOkLklX5CzZc4XOmQ1Axoh5Y8UkU5-
T4w9G1rJSMFjorM5PCPk4n-tSoRIKliwEMEAV5zCHr1VnsG8vr4ZKtmGHxZNmRl5esrtKviUWy-d11MX
A4VhuJMkm10ELsJWiaP4XMaKwuM4cqNTp8oqzlI9u4wp~4z-dl-jhN7A__)" --saveName "意外的旅
程_第1集" --headers "authentication:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.
eyJhdWQiOiJ1cm46Y2hvY290diIsImlzcyI6Imh0dHBzOi8vd3d3LmNob2NvdHYuY29tLnR3IiwiZXhw
IjoxNjUyMTg1MjExLCJ1cm46YW1hem9uZTphd3M6ZWxhc3RpY3RyYW5zY29kZTpjb250ZW50a2V5aWRl
bnRpZmllciI6IjVlMWRjNjkyLThiOTMtNGRkYy1hMjdlLTg0MWM5MjE5M2UxMCIsImlhdCI6MTY1MjE4
MzQxMX0.6JgFQIDevFb-Rd0-XBEPX4E5oDg7BhDQUxPfxtJ_Mm8" --enableDelAfterDone --enab
leBinaryMerge
N_m3u8DL-CLI version 2.9.9 2018-2021
  built date: 20211123

19:50:24.573 文件名称：意外的旅程_第1集
19:50:24.606 存储路径：G:\N_m3u8DL-CLI_v2.9.9_with_ffmpeg_and_SimpleG\Downloads
19:50:24.679 开始解析  [https://d3c7rimkq79yfu.cloudfront.net/13384/1/v4/13384-ep
s-1_FHD.m3u8?Expires=1652183704263&Key-Pair-Id=K3A3HFLQY0L90Y&Signature=tWRvts4Z
WXLotOJePsyqwJrLfP~pV~mz1D46T8SX~Nk30Le5LHXnyb1ziZIfA6QIjJjbBg7fWTu~igAPKBeVby9c
2fbGzZdfNl8uaJW5y9Jj8NgTylsM99yO~97uPLQFHGh~LXjLxAdQ0heKwJAMGEylM1it6kc0UMInPL3d
M2iYFT9HCOkLklX5CzZc4XOmQ1Axoh5Y8UkU5-T4w9G1rJSMFjorM5PCPk4n-tSoRIKliwEMEAV5zCHr
1VnsG8vr4ZKtmGHxZNmRl5esrtKviUWy-d11MXA4VhuJMkm10ELsJWiaP4XMaKwuM4cqNTp8oqzlI9u4
wp~4z-dl-jhN7A__](https://d3c7rimkq79yfu.cloudfront.net/13384/1/v4/13384-ep)
s-1_FHD.m3u8?Expires=1652183704263&Key-Pair-Id=K3A3HFLQY0L90Y&Signature=tWRvts4Z
WXLotOJePsyqwJrLfP~pV~mz1D46T8SX~Nk30Le5LHXnyb1ziZIfA6QIjJjbBg7fWTu~igAPKBeVby9c
2fbGzZdfNl8uaJW5y9Jj8NgTylsM99yO~97uPLQFHGh~LXjLxAdQ0heKwJAMGEylM1it6kc0UMInPL3d
M2iYFT9HCOkLklX5CzZc4XOmQ1Axoh5Y8UkU5-T4w9G1rJSMFjorM5PCPk4n-tSoRIKliwEMEAV5zCHr
1VnsG8vr4ZKtmGHxZNmRl5esrtKviUWy-d11MXA4VhuJMkm10ELsJWiaP4XMaKwuM4cqNTp8oqzlI9u4
wp~4z-dl-jhN7A__
19:50:30.819 地址无效
19:50:30.820 文件名称：意外的旅程_第1集
19:50:30.820 存储路径：G:\N_m3u8DL-CLI_v2.9.9_with_ffmpeg_and_SimpleG\Downloads
19:50:30.822 开始解析  [https://d3c7rimkq79yfu.cloudfront.net/13384/1/v4/13384-ep
s-1_FHD.m3u8?Expires=1652183704263&Key-Pair-Id=K3A3HFLQY0L90Y&Signature=tWRvts4Z
WXLotOJePsyqwJrLfP~pV~mz1D46T8SX~Nk30Le5LHXnyb1ziZIfA6QIjJjbBg7fWTu~igAPKBeVby9c
2fbGzZdfNl8uaJW5y9Jj8NgTylsM99yO~97uPLQFHGh~LXjLxAdQ0heKwJAMGEylM1it6kc0UMInPL3d
M2iYFT9HCOkLklX5CzZc4XOmQ1Axoh5Y8UkU5-T4w9G1rJSMFjorM5PCPk4n-tSoRIKliwEMEAV5zCHr
1VnsG8vr4ZKtmGHxZNmRl5esrtKviUWy-d11MXA4VhuJMkm10ELsJWiaP4XMaKwuM4cqNTp8oqzlI9u4
wp~4z-dl-jhN7A__](https://d3c7rimkq79yfu.cloudfront.net/13384/1/v4/13384-ep
s-1_FHD.m3u8?Expires=1652183704263&Key-Pair-Id=K3A3HFLQY0L90Y&Signature=tWRvts4Z
WXLotOJePsyqwJrLfP~pV~mz1D46T8SX~Nk30Le5LHXnyb1ziZIfA6QIjJjbBg7fWTu~igAPKBeVby9c
2fbGzZdfNl8uaJW5y9Jj8NgTylsM99yO~97uPLQFHGh~LXjLxAdQ0heKwJAMGEylM1it6kc0UMInPL3d
M2iYFT9HCOkLklX5CzZc4XOmQ1Axoh5Y8UkU5-T4w9G1rJSMFjorM5PCPk4n-tSoRIKliwEMEAV5zCHr
1VnsG8vr4ZKtmGHxZNmRl5esrtKviUWy-d11MXA4VhuJMkm10ELsJWiaP4XMaKwuM4cqNTp8oqzlI9u4
wp~4z-dl-jhN7A__)

**Comment by qbabe** [comment]
@nilaoda [nilaoda](https://github.com/nilaoda)
请问为什麽closed这个issue呢?
请问有解决的方案了吗?

**Comment by nilaoda** [comment]
> @nilaoda [nilaoda](https://github.com/nilaoda) 请问为什麽closed这个issue呢? 请问有解决的方案了吗?

Linetv.tw剧集解析工具已经停止维护
