### ISSUE TITLE
N_m3u8DL-CLI 已停止工作

### ISSUE THREAD

**Issue by lbcake** [nilaoda/N_m3u8DL-CLI#654]
![image](https://user-images.githubusercontent.com/26319880/167705846-c446e489-0f22-42fb-9ba2-61fe508e9d4b.png)
问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	N_m3u8DL-CLI_v2.9.9.exe
  应用程序版本:	2.9.9.0
  应用程序时间戳:	619c9703
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24384
  故障模块时间戳:	5c6e248c
  异常代码:	e0434352
  异常偏移:	000000000000be0d
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	2413
  其他信息 2:	2413de213f38e5efe700010a55469627
  其他信息 3:	1688
  其他信息 4:	168850878e0a3a6069bb4727db571db6

联机阅读隐私声明:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0804

如果无法获取联机隐私声明，请脱机阅读我们的隐私声明:
  C:\Windows\system32\zh-CN\erofflps.txt

请问这是什么问题？如何处理？目前点击GO就停止工作    使用环境win7

**Comment by nilaoda** [comment]
你的系统或.net framework版本不支持本地化

**Comment by lbcake** [comment]
> 你的系统或.net framework版本不支持本地化

已解决  .net环境问题。 可以close了

**Comment by as5asf4** [comment]
老哥 怎么解决，今天碰到了 一模一样的提示，求帮助

**Comment by lbcake** [comment]
> 老哥 怎么解决，今天碰到了 一模一样的提示，求帮助

看不到我最后的回复吗？ 自己安装.net

**Comment by as5asf4** [comment]
老哥 安了也这样
