### ISSUE TITLE
m3u8dl 闪退

### ISSUE THREAD

**Issue by windright** [nilaoda/N_m3u8DL-CLI#655]
使用actions中的build_lasted注册Protocol URL后，在网页中使用m3u8dl下载闪退，日志只记录到解析链接
![image](https://user-images.githubusercontent.com/37796675/167983781-ca9961a8-c3b5-4270-9b66-dce3b2cca5b8.png)

**Comment by Marvll** [comment]
解析AppleTV m3u8闪退

**Comment by nilaoda** [comment]
尝试在cmd中手动输入命令行（日志的Task CommandLine），查看异常信息

**Comment by soonayun** [comment]
> 尝试在cmd中手动输入命令行（日志的Task CommandLine），查看异常信息

你好，请问能否增加hami video 下载后的音轨文件和视频文件合并的功能！谢谢感激不尽！

**Comment by windright** [comment]
> 尝试在cmd中手动输入命令行（日志的Task CommandLine），查看异常信息

手动输入没有问题，就是网页中点击 <a href="m3u8dl:aHR0cHM6Ly9iLmJhb2J1enouY29tL20zdTgvNTYxNDM4Lm0zdTg/c2lnbj0wYzE0ZWM3ODUxM2YxYmMyODc5MjhhZDU5YTQyODg0Mw==" data-title="坏蛋联盟 超清">https://b.baobuzz.com/m3u8/561438.m3u8?sign=0c14ec78513f1bc287928ad59a428843</a> 元素，弹出弹窗后，窗口进行到解析链接时就直接闪退了

![image](https://user-images.githubusercontent.com/37796675/168191091-d454efe0-78fc-4902-88e5-0654cd6e3393.png)

**Comment by windright** [comment]
找到问题了，在URL Protocol 的command 中添加上 &pause 后，成功输出了问题所在。

这个访问被拒绝应该怎么解决呢？

![image](https://user-images.githubusercontent.com/37796675/168194433-bd78bd26-4fd8-47a0-9527-b28bcd0f068a.png)

**Comment by windright** [comment]
默认存储路径的问题，加上工作目录就好了，没有工作目录的话，默认存储路径为“C/Windows/system32/Downloads”，这样子会造成对路径的访问被拒绝，所以会直接闪退。
