### ISSUE TITLE
大佬这个网站不支持吗,求帮忙看看

### ISSUE THREAD

**Issue by UUZT** [nilaoda/N_m3u8DL-CLI#658]
视频地址：https://hamivideo.hinet.net/play/189276/OTT_VOD_0000287524.do

m3u8地址：https://webvodad-hamivideo.cdn.hinet.net/vod/hamivideo2/hamivideo-2318-2318104985_f_001/_/hd_6840-hls-ae-all-ma-6s/index.m3u8?url_type=&token=uUT3ynXiA_N6U2bSLLsnuw&expires=1653426127&content_id=287524&product_id=7016&serial_no=1650074331-23-36-62-55-34&auth_type=free&auth_by=google_102108064130192236384&sales_plan_id=&ts_id=&chsm=bf6e27da159ffd00&auth_login_id=google_102108064130192236384

key地址:https://hls-hichannel.cdn.hinet.net/keys/a.key

这个网站需要台湾IP才能观看,尝试直接填入m3u8地址无法下载，最后在F12里面找到key下载使用,一样的原因提示m3u8地址无效，大佬可以帮忙看看吗,这个要怎么解决呢

**Comment by UUZT** [comment]
看了大佬以往的记录找到方法解决了，打扰了大佬

**Comment by sanar-ss** [comment]
想问一下，你最后咋解决的呢？
