### ISSUE TITLE
m3u8dl://协议浏览器调用

### ISSUE THREAD

**Issue by plasx520** [nilaoda/N_m3u8DL-CLI#661]
未经处理的异常:  System.FormatException: Base-64 字符数组或字符串的长度无效。
   在 System.Convert.FromBase64_Decode(Char* startInputPtr, Int32 inputLength, Byte* startDestPtr, Int32 destLength)
   在 System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   在 System.Convert.FromBase64String(String s)
   在 N_m3u8DL_CLI.NetCore.Program.Main(String[] args)

链接m3u8dl:"https://ukzyvod3.ukubf5.com/20220409/O8sFUo8A//2000kb/hls/index.m3u8"
m3u8dl://"https://ukzyvod3.ukubf5.com/20220409/O8sFUo8A//2000kb/hls/index.m3u8"

**Comment by nilaoda** [comment]
```
"https://ukzyvod3.ukubf5.com/20220409/O8sFUo8A//2000kb/hls/index.m3u8"
```
经过Base64编码后结果为 
```
Imh0dHBzOi8vdWt6eXZvZDMudWt1YmY1LmNvbS8yMDIyMDQwOS9POHNGVW84QS8vMjAwMGtiL2hscy9pbmRleC5tM3U4Ig==
```

正确链接为
```
m3u8dl://Imh0dHBzOi8vdWt6eXZvZDMudWt1YmY1LmNvbS8yMDIyMDQwOS9POHNGVW84QS8vMjAwMGtiL2hscy9pbmRleC5tM3U4Ig==
```

**Comment by plasx520** [comment]
感谢投稿怕冷爱上雪，您的投稿已收到，当晚就会开始审核。分享精神最可贵，如果稿件没有通过也非常感谢您投稿！软件无怕冷爱上雪版权的审核通过也不会发放奖励请勿使用快压流氓软件打包压缩包 发现一律略过

**Comment by plasx520** [comment]
> ```
> "https://ukzyvod3.ukubf5.com/20220409/O8sFUo8A//2000kb/hls/index.m3u8"
> ```
> 
> 经过Base64编码后结果为
> 
> ```
> Imh0dHBzOi8vdWt6eXZvZDMudWt1YmY1LmNvbS8yMDIyMDQwOS9POHNGVW84QS8vMjAwMGtiL2hscy9pbmRleC5tM3U4Ig==
> ```
> 
> 正确链接为
> 
> ```
> m3u8dl://Imh0dHBzOi8vdWt6eXZvZDMudWt1YmY1LmNvbS8yMDIyMDQwOS9POHNGVW84QS8vMjAwMGtiL2hscy9pbmRleC5tM3U4Ig==
> ```

我的好哥哥你加了两个双斜杠反而不行了，你自己的示范链接都不行了，删掉就行了。我又折腾了半天。。。。。。。。哈哈哈笑死我了
