### ISSUE TITLE
求助m3u8dl://油猴一键下载js问题

### ISSUE THREAD

**Issue by plasx520** [nilaoda/N_m3u8DL-CLI#665]
![image](https://user-images.githubusercontent.com/59572466/170278548-288e7f9d-2b3c-4b02-bdd9-4b576d7b3f7f.png)
油猴插件写的js代码一键下载
`// ==UserScript==
// @name         m3u8-downloader-N_m3u8DL-CLI
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  try to take over the world!
// @include      *
// @author       You
// @match        https://tool.ip138.com/base64/
// @icon         https://icons.duckduckgo.com/ip2/ip138.com.ico
// @grant        none

// ==/UserScript==

(function() {
  'use strict';
  var m3u8Target = ''
  var originXHR = window.XMLHttpRequest

  function ajax(options) {
    options = options || {};
    let xhr = new originXHR();
    if (options.type === 'file') {
      xhr.responseType = 'arraybuffer';
    }

    xhr.onreadystatechange = function() {
      if (xhr.readyState === 4) {
        let status = xhr.status;
        if (status >= 200 && status < 300) {
          options.success && options.success(xhr.response);
        } else {
          options.fail && options.fail(status);
        }
      }
    };

    xhr.open("GET", options.url, true);
    xhr.send(null);
  }

  // 检测 m3u8 链接的有效性
  function checkM3u8Url(url) {
    ajax({
      url,
      success: (fileStr) => {
        if (fileStr.indexOf('.ts') > -1) {
          appendDom()
          m3u8Target = url
          console.log(url)
        }
      }
    })
  }

  function resetAjax() {
    if (window._hadResetAjax) { // 如果已经重置过，则不再进入。解决开发时局部刷新导致重新加载问题
      return
    }
    window._hadResetAjax = true

    var originOpen = originXHR.prototype.open
    window.XMLHttpRequest = function() {
      var realXHR = new originXHR()
      realXHR.open = function(method, url) {
        url.indexOf('.m3u8') > 0 && checkM3u8Url(url)
        originOpen.call(realXHR, method, url)
      }
      return realXHR
    }
  }

  function appendDom() {
    if (document.getElementById('m3u8-download-dom')) {
      return
    }
    var domStr = `
  <div style="
    margin-top: 6px;
    padding: 6px 10px ;
    font-size: 18px;
    color: white;
    cursor: pointer;
    border-radius: 4px;
    border: 1px solid #eeeeee;
    background-color: #3D8AC7;
  " id="m3u8-jump">视频下载</div>
  <div style="
    margin-top: 4px;
    height: 34px;
    width: 34px;
    line-height: 34px;
    display: inline-block;
    border-radius: 50px;
    background-color: rgb(0 231 255 / 50%);
  " id="m3u8-close">
    <a style="padding-top: 4px; width: 24px; cursor: pointer; " >X</a>
  </div>
    `
    var $section = document.createElement('section')
    $section.id = 'm3u8-download-dom'
    $section.style.position = 'fixed'
    $section.style.zIndex = '9999'
    $section.style.top = '20px'
    $section.style.left = '20px'
    $section.style.textAlign = 'center'
    $section.innerHTML = domStr
    document.body.appendChild($section);

    var m3u8Jump = document.getElementById('m3u8-jump')
    var m3u8Close = document.getElementById('m3u8-close')

    m3u8Close.addEventListener('click', function() {
      $section.remove()
    })

    m3u8Jump.addEventListener('click', function() {
      var m3u8Target2 = ('"' + m3u8Target + '" --workDir "%USERPROFILE%\Downloads\m3u8dl" --saveName "abc" --enableDelAfterDone --disableDateInfo --noProxy')
      window.open('m3u8dl:' + window.btoa(m3u8Target2))
    })
  }

  resetAjax()
})();

`
由于window.btoa('china is so nb') // 编码的base64存在问题想用其他的代替可是都不行
m3u8dl:<base64编码的客户端命令行文本>
**加密后就是这个样子的还是不行**
m3u8dl:Imh0dHBzOi8vdWt6eXZvZDMudWt1YmY1LmNvbS8yMDIyMDQwOS8zVXZwRUtBWS8yMDAwa2IvaGxzL2luZGV4Lm0zdTg=IiAtLXdvcmtEaXIgIiVVU0VSUFJPRklMRSVcRG93bmxvYWRzXG0zdThkbCIgLS1zYXZlTmFtZSAiYWJjIiAtLWVuYWJsZURlbEFmdGVyRG9uZSAtLWRpc2FibGVEYXRlSW5mbyAtLW5vUHJveHk=

**Comment by nilaoda** [comment]
正确格式是`m3u8dl://xx`，不是`m3u8dl:xx`
