### ISSUE TITLE
优酷下载合并失败

### ISSUE THREAD

**Issue by LiuChangFreeman** [nilaoda/N_m3u8DL-CLI#67]
是这一集:https://v.youku.com/v_show/id_XMjI2ODA4MTEy
> 22:07:14.246 文件名称：鹿鼎记
> 22:07:14.248 存储路径：C:\videos
> 22:07:14.251 开始解析地址...
> 22:07:14.274 获取m3u8内容
> 22:07:14.414 解析m3u8内容
> 22:07:14.431 写出meta.json
> 22:07:14.484 文件时长：44m53s
> 22:07:14.485 总分片：270, 已选择分片：270
> 22:07:14.502 开始下载文件
> 22:07:14.508 下载首分片...
> 22:07:14.861 读取文件信息...
>              PID 0x100: Video h264, none, 90k tbr, 90k tbn, 180k tbc
>              PID 0x101: Audio aac (LC), mono, fltp, 295 kb/s
> 22:07:16.085 等待下载完成...
> 22:07:34.440 完成数量 269 / 270
> 22:07:34.440 重试次数 1 / 15
> 22:07:37.450 开始下载文件
> 22:07:37.568 已下载完毕
> 22:07:37.569 开始合并分片...
> 22:07:37.585 使用ffmpeg合并...请耐心等待
> 22:07:38.043 [aac @ 00000242fc572040] Prediction is not allowed in AAC-LC.
> 22:07:38.044     Last message repeated 1 times
> 22:07:38.044 [aac @ 00000242fc572040] channel element 1.5 is not allocated
> 22:07:38.044 [aac @ 00000242fc572040] Sample rate index in program config element does not match the sam
> 22:07:38.050 [aac @ 00000242fc572040] Inconsistent channel configuration.
> 22:07:38.050 [aac @ 00000242fc572040] get_buffer() failed
> 22:07:38.050 [aac @ 00000242fc572040] channel element 3.6 is not allocated
> 22:07:38.050 [aac @ 00000242fc572040] Number of bands (14) exceeds limit (11).
> 22:07:38.050 [aac @ 00000242fc572040] Reserved bit set.
> 22:07:38.051 [aac @ 00000242fc572040] Number of bands (19) exceeds limit (14).
> 22:07:38.051 [aac @ 00000242fc572040] channel element 2.8 is not allocated
> 22:07:38.051 [aac @ 00000242fc572040] Dependent coupling is not supported together with LTP
> 22:07:38.051     Last message repeated 17 times
> 22:07:38.051 [aac @ 00000242fc572040] Multiple frames in a packet.
> 22:07:38.052 [aac @ 00000242fc572040] Sample rate index in program config element does not match the sam
> 22:07:38.052 [aac @ 00000242fc572040] decode_pce: Input buffer exhausted before END element found
> 22:07:38.052 [aac @ 00000242fc572040] channel element 3.9 is not allocated
> 22:07:38.052 [aac @ 00000242fc572040] channel element 1.3 is not allocated
> 22:07:38.052 [aac @ 00000242fc572040] channel element 3.8 is not allocated
> 22:07:38.052 [aac @ 00000242fc572040] More than one AAC RDB per ADTS frame is not implemented. Update yo
> 22:07:38.054 [aac @ 00000242fc572040] SBR was found before the first channel element.s a feature which h
> 22:07:38.054 [aac @ 00000242fc572040] channel element 1.5 is not allocated
> 22:07:38.055 [aac @ 00000242fc572040] channel element 2.0 is not allocated
> 22:07:38.055 [aac @ 00000242fc572040] channel element 2.15 is not allocated
> 22:07:38.055 [aac @ 00000242fc572040] Sample rate index in program config element does not match the sam
> 22:07:38.057 [aac @ 00000242fc572040] Inconsistent channel configuration.
> 22:07:38.057 [aac @ 00000242fc572040] get_buffer() failed
> 22:07:38.058 [aac @ 00000242fc572040] Number of scalefactor bands in group (50) exceeds limit (40).
> 22:07:38.059 [aac @ 00000242fc572040] channel element 2.7 is not allocated
> 22:07:38.061 [aac @ 00000242fc572040] Reserved bit set.
> 22:07:38.061 [aac @ 00000242fc572040] Number of bands (6) exceeds limit (5).
> 22:07:38.062 [aac @ 00000242fc572040] Reserved bit set.
> 22:07:38.063 [aac @ 00000242fc572040] Prediction is not allowed in AAC-LC.
> 22:07:38.063 [aac @ 00000242fc572040] channel element 2.0 is not allocated
> 22:07:38.064 [aac @ 00000242fc572040] Reserved bit set.
> 22:07:38.065 [aac @ 00000242fc572040] Prediction is not allowed in AAC-LC.
> 22:07:38.073 [aac @ 00000242fc572040] channel element 3.12 is not allocated
> 22:07:38.074 [aac @ 00000242fc572040] Reserved bit set.
> 22:07:38.075 [aac @ 00000242fc572040] Number of scalefactor bands in group (58) exceeds limit (49).
> 22:07:38.076 [aac @ 00000242fc572040] Number of scalefactor bands in group (54) exceeds limit (41).
> 22:07:38.077 [aac @ 00000242fc572040] Prediction is not allowed in AAC-LC.
> 22:07:38.077 [aac @ 00000242fc572040] channel element 2.4 is not allocated
> 22:07:38.078 [aac @ 00000242fc572040] Reserved bit set.
> 22:07:38.079 [aac @ 00000242fc572040] Prediction is not allowed in AAC-LC.
> 22:07:38.079 [aac @ 00000242fc572040] channel element 1.1 is not allocated
> 22:07:38.080 [aac @ 00000242fc572040] channel element 3.15 is not allocated
> 22:07:38.080 [mpegts @ 00000242fc54cc00] start time for stream 0 is not set in estimate_timings_from_pts
> 22:07:38.082 [mpegts @ 00000242fc54cc00] Could not find codec parameters for stream 0 (Video: h264 ([27]
> 22:07:38.082 Consider increasing the value for the 'analyzeduration' and 'probesize' options
> 22:07:38.083 [mpegts @ 00000242fc54cc00] Could not find codec parameters for stream 1 (Audio: aac (LC) (
> 22:07:38.087 Consider increasing the value for the 'analyzeduration' and 'probesize' options
> 22:07:38.087 [mp4 @ 00000242fce5d0c0] dimensions not set
> 22:07:38.088 Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument

**Comment by nilaoda** [comment]
```
22:07:14.861 读取文件信息...
PID 0x100: Video h264, none, 90k tbr, 90k tbn, 180k tbc
PID 0x101: Audio aac (LC), mono, fltp, 295 kb/s
```
加密视频，暂不支持。
