### ISSUE TITLE
N_m3u8DL-CLI 下载 和  ffmpeg 有什么区别？

### ISSUE THREAD

**Issue by azyghqsavx** [nilaoda/N_m3u8DL-CLI#675]
N_m3u8DL-CLI 下载 和  ffmpeg 有什么区别？
ffmpeg -i [视频链接] [保存文件]
ffmpeg -i 'http://link.to.your/video.m3u8' test.mp4

N_m3u8DL-CLI.exe  [视频链接] [保存文件]

**Comment by nilaoda** [comment]
本工具适配了更多网站，以及会更稳定

**Comment by azyghqsavx** [comment]
> 本工具使用了更多的网站，并且会更稳定
哦
Linux 不能用么？
