### ISSUE TITLE
能否把分片路径与合并路径分开设置？

### ISSUE THREAD

**Issue by YorkMoon** [nilaoda/N_m3u8DL-CLI#678]
想把分片缓存路径设置到内存盘，然后再合并到硬盘上
或者
有没有办法在视频合并后，自动移动到指定路径

谢谢！

**Comment by awei78** [comment]
同需要此功能，附议

**Comment by nilaoda** [comment]
N_m3u8DL-CLI 不会新增新功能，可以前往 https://github.com/nilaoda/N_m3u8DL-RE/issues 进行反馈
