### ISSUE TITLE
能否更新一下教程，如针对bilibili，IDM可以直接下载，在 N_m3u8DL里贴上地址带上cookie无效？

### ISSUE THREAD

**Issue by tingerwish** [nilaoda/N_m3u8DL-CLI#679]
如对于  https://www.bilibili.com/cheese/play/ep9893?csource=common_findlecture_lecturecard_null
用IDM 可以解析出地址
https://upos-sz-mirrorcos.bilivideo.com/upgcxcode/40/63/396296340/396296340_u1-1-29.mp4?e=ig8euxZM2rNcNbR1hzdVhwdlhWRzhwdVhoNvNC8BqJIzNbfqXBvEqxTEto8BTrNvN0GvT90W5JZMkX_YN0MvXg8gNEV4NC8xNEV4N03eN0B5tZlqNxTEto8BTrNvNeZVuJ10Kj_g2UB02J0mN0B5tZlqNCNEto8BTrNvNC7MTX502C8f2jmMQJ6mqF2fka1mqx6gqj0eN0B599M=&uipk=5&nbs=1&deadline=1655271860&gen=playurlv2&os=cosbv&oi=1928774469&trid=89fe224e87b64807861cab0994cbd6ccu&mid=0&platform=pc&upsig=b930160a1df70685a16ef8dab0488f2f&uparams=e,uipk,nbs,deadline,gen,os,oi,trid,mid,platform&bvc=vod&nettype=0&orderid=0,3&agrr=1&bw=113896&logo=80000000

在N_m3u8DL里带上cookie 就可以了吗？

**Comment by nilaoda** [comment]
哔哩哔哩用的不是m3u8，建议使用我的另一个软件下载：[BBDown](https://github.com/nilaoda/BBDown)
