### ISSUE TITLE
下载csdn学院视频用不了，已经抓到包，加密是这个阿里云视频【AliyunVoDEncryption】

### ISSUE THREAD

**Issue by ihuangke** [nilaoda/N_m3u8DL-CLI#68]
`		{
	"RequestId": "77D2B178-E033-4FD3-BAFD-AFBD10AA078B",
	"PlayInfoList": {
		"PlayInfo": [{
			"Format": "m3u8",
			"Plaintext": "g6+xkMdXdXDrA2v+YG0+yZFKRaXFdLL7kp4cOiCqeMo=\r\n",
			"PreprocessStatus": "UnPreprocess",
			"StreamType": "video",
			"ModificationTime": "2019-11-15T02:43:21Z",
			"Specification": "H264.HD",
			"Height": 1080,
			"PlayURL": "https://vedu.csdnimg.cn/654c02a6fc23426083206d2df01d6782/e57e47012045499ca3ed115b0b534812-233b2f6d9c83554791bf8b8a3e400d35-4k-encrypt-stream.m3u8",
			"EncryptType": "AliyunVoDEncryption",
			"Rand": "MtnxHxDxbJZtTpKkSDNZPc6LJNbIqvNCm9hCX91EWDM=\r\n",
			"NarrowBandType": "0",
			"CreationTime": "2019-11-15T02:42:10Z",
			"Status": "Normal",
			"WatermarkId": "0fae8e768efc6c1bf3299411301465d8",
			"JobId": "7278486170ff4cc0846ebc72155030a1",
			"Duration": "456.6465",
			"Encrypt": 1,
			"Width": 1920,
			"Fps": "25",
			"Bitrate": "519.508",
			"Size": 29653992,
			"Definition": "4K"
		}]
	},
	"VideoBase": {
		"CoverURL": "https://vedu.csdnimg.cn/61ca430ea60f458b9038ad5fae6fc284/snapshots/0d2254dd421d42adbf92c93442be0c96-00005.jpg",
		"CreationTime": "2019-11-15T02:42:03Z",
		"TranscodeMode": "FastTranscode",
		"Status": "Normal",
		"MediaType": "video",
		"Duration": "456.64",
		"VideoId": "654c02a6fc23426083206d2df01d6782",
		"OutputType": "cdn",
		"Title": "ali_video/26755/340102.mp4"
	}
}`

以上是抓到的请求内容，用这个工具一直下载不了，望解决。

加密是不是这个？
"PlayURL": "https://vedu.csdnimg.cn/654c02a6fc23426083206d2df01d6782/e57e47012045499ca3ed115b0b534812-233b2f6d9c83554791bf8b8a3e400d35-4k-encrypt-stream.m3u8",

**"EncryptType": "AliyunVoDEncryption",**

提示错误内容如下：

`ffmpeg version N-81489-ga37e6dd Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --disable-w32threads --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-libebur128 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libschroedinger --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 29.100 / 55. 29.100
  libavcodec     57. 54.101 / 57. 54.101
  libavformat    57. 48.101 / 57. 48.101
  libavdevice    57.  0.102 / 57.  0.102
  libavfilter     6. 57.100 /  6. 57.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[aac @ 057dd8a0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 057dd8a0] channel element 2.2 is not allocated
[aac @ 057dd8a0] More than one AAC RDB per ADTS frame is not implemented. Update your FFmpeg version to the newest one from Git. If the problem still occurs, it means that your file has a feature which has not been implemented.
[aac @ 057dd8a0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of bands (42) exceeds limit (31).
[aac @ 057dd8a0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] ms_present = 3 is reserved.
[aac @ 057dd8a0] Prediction is not allowed in AAC-LC.
[aac @ 057dd8a0] SBR was found before the first channel element.
[aac @ 057dd8a0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 057dd8a0] Number of scalefactor bands in group (44) exceeds limit (40).
[aac @ 057dd8a0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 057dd8a0] channel element 1.9 is not allocated
[aac @ 057dd8a0] channel element 2.1 is not allocated
[aac @ 057dd8a0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of scalefactor bands in group (56) exceeds limit (43).
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] invalid band type
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of bands (18) exceeds limit (15).
[aac @ 057dd8a0] Number of scalefactor bands in group (42) exceeds limit (40).
[aac @ 057dd8a0] channel element 2.5 is not allocated
[aac @ 057dd8a0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of bands (15) exceeds limit (12).
[aac @ 057dd8a0] Number of bands (12) exceeds limit (7).
[aac @ 057dd8a0] channel element 3.9 is not allocated
[aac @ 057dd8a0] channel element 1.12 is not allocated
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of bands (8) exceeds limit (3).
[aac @ 057dd8a0] Number of bands (13) exceeds limit (10).
[aac @ 057dd8a0] Number of scalefactor bands in group (60) exceeds limit (40).
[aac @ 057dd8a0] Assuming an incorrectly encoded 7.1 channel layout instead of a spec-compliant 7.1(wide) layout, use -strict 1 to decode according to the specification instead.
[aac @ 057dd8a0] Sample rate index in program config element does not match the sample rate index configured by the container.
[aac @ 057dd8a0] Inconsistent channel configuration.
[aac @ 057dd8a0] get_buffer() failed
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of bands (30) exceeds limit (27).
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of bands (19) exceeds limit (14).
[aac @ 057dd8a0] Number of scalefactor bands in group (62) exceeds limit (40).
[aac @ 057dd8a0] channel element 3.13 is not allocated
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of bands (42) exceeds limit (27).
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of scalefactor bands in group (14) exceeds limit (12).
[aac @ 057dd8a0] Number of bands (14) exceeds limit (10).
[aac @ 057dd8a0] Reserved bit set.
[aac @ 057dd8a0] Number of bands (22) exceeds limit (10).
[aac @ 057dd8a0] channel element 3.15 is not allocated
[aac @ 057dd8a0] Number of bands (4) exceeds limit (2).
[aac @ 057dd8a0] channel element 3.2 is not allocated
[hls,applehttp @ 0512ad60] decoding for stream 1 failed
[hls,applehttp @ 0512ad60] Could not find codec parameters for stream 0 (Video: h264 ([27][0][0][0] / 0x001B), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
[hls,applehttp @ 0512ad60] Could not find codec parameters for stream 1 (Audio: aac ([15][0][0][0] / 0x000F), 36 channels, fltp): unspecified sample rate
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, hls,applehttp, from 'https://vedu.csdnimg.cn/654c02a6fc23426083206d2df01d6782/e57e47012045499ca3ed115b0b534812-233b2f6d9c83554791bf8b8a3e400d35-4k-encrypt-stream.m3u8':
  Duration: 00:07:36.52, start: 2.833556, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), none, 90k tbr, 90k tbn, 180k tbc
    Metadata:
      variant_bitrate : 0
    Stream #0:1: Audio: aac ([15][0][0][0] / 0x000F), 36 channels, fltp
    Metadata:
      variant_bitrate : 0
[mp4 @ 05867920] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[mp4 @ 05867920] sample rate not set
Output #0, mp4, to 'C:\\Video.mp4':
    Stream #0:0: Audio: aac, 36 channels
    Metadata:
      variant_bitrate : 0
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument`

下载视频的网址是这个的：
https://edu.csdn.net/course/detail/6521

**Comment by ihuangke** [comment]
[2020-02-20_00-15-27.log](https://github.com/nilaoda/N_m3u8DL-CLI/files/4225995/2020-02-20_00-15-27.log)
[2020-02-20_00-15-27_ffreport.log](https://github.com/nilaoda/N_m3u8DL-CLI/files/4225996/2020-02-20_00-15-27_ffreport.log)

使用最新的版本【v2.4.9】试了一下，还是闪退了。

下载这个地址的csdn视频：https://edu.csdn.net/course/play/1223

**Comment by xhlove** [comment]
可参考：https://github.com/nilaoda/N_m3u8DL-CLI/issues/78

**Comment by ihuangke** [comment]
> 可参考：#78

解决了，就是断点的时候chrome浏览器很卡很卡，假死一样，点很久才反应。。。有点慢。。

希望有更简单的小工具可以提取之。谢谢分享！
