### ISSUE TITLE
v3.0.1 从GUI点Go会直接闪退

### ISSUE THREAD

**Issue by TheCGDF** [nilaoda/N_m3u8DL-CLI#680]
旧版本无此问题。
删除所有文件后重新运行依然会闪退。
将GUI中生成的命令参数复制到shell运行则无异常，推测是GUI的问题。

**Comment by nilaoda** [comment]
我这边测试正常

**Comment by 619954559** [comment]
> 我这边测试正常

大佬您好，我测试了一下，当选中的包含链接的txt文件过大（约20条链接）时，从gui中点击go会闪退。当txt文件仅包含3-5条链接时，可以正常运行。

**Comment by youzisay** [comment]
> 我这次正常测试

用的Win10 21H2最新版，从SimpleG点击GO，CLI出现几秒就闪退无法下载，单独启动CLI可以粘贴链接下载

**Comment by TheCGDF** [comment]
> 是不是你把程序文件放在C盘了，试着用管理员模式打开再下载

没有。
试了，没用。

**Comment by nilaoda** [comment]
```
File: N_m3u8DL-CLI-SimpleG.exe
CRC-32: cefac60f
MD4: 6332cc3384d4f8f1869ef03c13e21a39
MD5: 540e4ca270c0c2e3a8deaf4bf03e3353
SHA-1: 2183a77f54ae449beeb613171b3d28c768a475ab
```
确认一下文件是否一致，另外可以试试升级.Net framework版本到4.6或以上

**Comment by TheCGDF** [comment]
应该是setkey导致的闪退

**Comment by nilaoda** [comment]
在Win10 1909 / Server 2019 / Win11均无法复现……你看下通过Windows自带的事件查看器能不能找到一些原因

**Comment by nilaoda** [comment]
另外可以的话 录制一段视频或gif放上来我看下是什么现象

**Comment by TheCGDF** [comment]
https://github.com/nilaoda/N_m3u8DL-CLI-SimpleG/pull/1
