### ISSUE TITLE
mpd

### ISSUE THREAD

**Issue by MyGoodbye** [nilaoda/N_m3u8DL-CLI#683]
請問下載mpd檔的時候可以選擇視頻分辨率和字幕語言嗎?

**Comment by MyGoodbye** [comment]
我每次下載都是默認的,想自定義下載一下.

**Comment by nilaoda** [comment]
目前不支持，可以使用其他软件进行选择轨道下载，如 [XstreamDL-CLI](https://github.com/xhlove/XstreamDL-CLI)

**Comment by nilaoda** [comment]
请使用 https://github.com/nilaoda/N_m3u8DL-RE
