### ISSUE TITLE
51cto已购买付费视频下载不了

### ISSUE THREAD

**Issue by d8899p** [nilaoda/N_m3u8DL-CLI#69]
51cto付费视频已经购买，但是我复制请求头的时候却和网易云的不一样，51cto的m3u8也抓不了

**Comment by Eacolt** [comment]
同问，求如何下载51Cto的视频？

**Comment by d8899p** [comment]
我可以帮你下，付过费的51视频

**Comment by d8899p** [comment]
> 同问，求如何下载51Cto的视频？

这个你信得过我的话，可以帮你下，不然你去看看其他项目有没有相关教程
