### ISSUE TITLE
(ERROR) 无效的m3u8

### ISSUE THREAD

**Issue by shengkelong** [nilaoda/N_m3u8DL-CLI#691]
![image](https://user-images.githubusercontent.com/24505935/175826401-15d63a0a-20a9-4e1e-b0ae-110ebf9cd2be.png)
最后解析出来的m3u8是这个样子的

**Comment by nilaoda** [comment]
这不是m3u8

**Comment by shengkelong** [comment]
@nilaoda 那么请问这个视频大概是什么格式的呢，还是加密了

**Comment by nilaoda** [comment]
无法辨认
