### ISSUE TITLE
Any way to catch Apple Music?

### ISSUE THREAD

**Issue by florinsdistortedvision** [nilaoda/N_m3u8DL-CLI#692]
Hello, great tool, getting m3u8 from apple music can download and parse its ts files correctly, but no audio is found (there is a .aac file with correct file size and length in VLC).
![Untitled](https://user-images.githubusercontent.com/97384306/176388549-4e5a6435-cdce-4a25-a318-9066979b856d.jpg)

Download is successful btw, just took the picture before it closed itself.

Here is the link for reference/testing:
https://aod-ssl.itunes.apple.com/itunes-assets/Music118/v4/2e/7f/14/2e7f1480-c95b-b02c-fa24-5e285d6ce3a8/mzaf_A1445310459.rphq.aac.wa.m3u8

**Comment by plasx520** [comment]
不支持ISO-23001-7加密方式,

**Comment by Maoge-HUB** [comment]
Excuse me, I want to know how to download Apple Music, and how to get the m3u8 link, how to get the DRM key, can you tell me in detail, thank you!
