### ISSUE TITLE
下载的视频声音像是放慢了

### ISSUE THREAD

**Issue by qingchunnh** [nilaoda/N_m3u8DL-CLI#693]
像是在剪辑软件里把声音调慢了，声音变的很粗很奇怪，下载30分钟的视频没有问题，我下载的视频是6个小时的声音就变成这样了，视频前面是放慢视频后半部分就是很快的加速的那种声音，视频速度也加速了，这是怎么回事

**Comment by nilaoda** [comment]
开启二进制合并

**Comment by qingchunnh** [comment]
> 开启二进制合并

谢谢作者有效果，我下的是虎牙的回放自己看的，开头有一段十几分钟声音是放慢的那种感觉，不知道是怎么回事

**Comment by qingchunnh** [comment]
> 开启二进制合并

不对，是开头大概5秒的时间声音像是放慢的，虎牙的回放有3段一段是刚开直播十几分钟一段是刚开播十几分钟后面的内容还有一段是完整的回放，下完整的回放不用二进制合并开头的十几分钟是放慢，我看文件他有Part_0和Part_1，Part_0里面的视频音频采样率是44100，但是Part_1里的采样率是20000左右比特率是60多，如果单独下载开头的十几分钟的视频采样率就正常，下载完整的视频使用二进制合并开头5秒左右声音有放慢的效果

**Comment by qingchunnh** [comment]
对不起作者是虎牙那边的问题，感谢你的解答
