### ISSUE TITLE
Specified Key Size Invalid to This Algorithm 

### ISSUE THREAD

**Issue by sr093906** [nilaoda/N_m3u8DL-CLI#695]
Sample m3u8 file:

https://v3.dious.cc/20220409/LOGlBJGP/1500kb/hls/index.m3u8
[index.m3u8.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/9055180/index.m3u8.txt)

Key file(downloaded from https://v3.dious.cc/20220409/LOGlBJGP/1500kb/hls/key.key)
[key.key.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/9055187/key.key.txt)

How to Re-produce the Issue:

M3U8 address:
https://v3.dious.cc/20220409/LOGlBJGP/1500kb/hls/index.m3u8

BASE URL:
https://v3.dious.cc/

Custom KEY:
5d91133bfdfdca8c

Also, a big thank you for long-time maintenance, How can I sponsor the project? You know not many entertainments are available during lock-down period for common people, and the project comes to rescue.

**Comment by nilaoda** [comment]
Just download m3u8 directly...

```
N_m3u8DL-CLI.exe "https://v3.dious.cc/20220409/LOGlBJGP/1500kb/hls/index.m3u8"
```

![image](https://user-images.githubusercontent.com/20772925/177598559-7806aec8-4659-4286-aafa-05d5e1ad43db.png)

---

Sponsor the project through Alipay. 

You can find the QR code in the Readme.

**Comment by nilaoda** [comment]
@sr093906 can you record video/gif for it
