### ISSUE TITLE
这个能解决吗

### ISSUE THREAD

**Issue by aoteman5255661** [nilaoda/N_m3u8DL-CLI#7]
https://1258712167.vod2.myqcloud.com/5a81e359vodtranssh1258712167/879d0c3c5285890789965294313/drm/v.f30739.m3u8?t=5d28c6ee&exper=0&us=8048546905154199209&sign=434c6ef1f10eed8316a91fea1a78724f

**Comment by nilaoda** [comment]
视频播放页是什么？你这个链接key获取不到

**Comment by aoteman5255661** [comment]
腾讯课堂的内容   之前视频可以用IDM就能下来，新的视频就变成这样了    https://www.lanzous.com/i4jvrcd

**Comment by aoteman5255661** [comment]
https://www.lanzous.com/i4jvx1i   播放页面，但是跟上面的不是对应的

**Comment by aoteman5255661** [comment]
https://ke.qq.com/cgi-bin/qcloud/get_dk?edk=CiB%2Fx0ojtbWPczVObjj7RFJOKb4Uf42nGdJCtloVSbzOVhCO08TAChiaoOvUBCokOTMyNDg4YmItOWZjYS00MzFiLWJiYjItNjFmMDhjYjNlYmM3&fileId=5285890789965294313&keySource=VodBuildInKMS

这个是不是key
