### ISSUE TITLE
tx课堂下载视频出现【指定的密钥大小对于此算法无效】的情况如何处理

### ISSUE THREAD

**Issue by UsagiErina** [nilaoda/N_m3u8DL-CLI#702]
![QQ截图20220714130748](https://user-images.githubusercontent.com/94761065/178903707-8ce958a5-97a9-4a3b-9894-1156685c8075.png)

**Comment by gengyulin** [comment]
同上，有没有大佬有解决方法

**Comment by Tiger661** [comment]
同上，这是啥原因呀

**Comment by nilaoda** [comment]
我找了一个试看的课 貌似可以正常下载

**Comment by kumukaihua** [comment]
刚才刚下载tx课堂视频，还是提示“指定的密钥大小对于此算法无效果”

**Comment by UsagiErina** [comment]
> 我找了一个试看的课看起来可以正常下载

感觉tx改付费课加密方式了 以前下载过的也是这样下载不了

**Comment by UsagiErina** [comment]
> 我找了一个试看的课看起来可以正常下载

感觉是不是tx付费改课加密方式了 以前下载过的感觉也这样下载不了

**Comment by BigPizzaV3** [comment]
我也遇到了

**Comment by masato-xd** [comment]
mark 的确是改了,,[某课堂下载分析](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1663346&highlight=%C6%F3%B6%EC)

**Comment by Tiger661** [comment]
> mark 的确是改了,,[某课堂下载分析](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1663346&highlight=%C6%F3%B6%EC)

谢谢大佬指明方向，但是俺是小白，这个操作有点看不懂咋办呀。

**Comment by xifangczy** [comment]
他的key在其他地方 并不在m3u8文件里。
这已经超出了N_m3u8DL-CLI的职责，不可能傻瓜化处理tx课堂网站，不然可太刑了。
需要自己去寻找key 方法么... 不是这里的讨论范围吧。

**Comment by dltsdr** [comment]
> mark 的确是改了,,[某课堂下载分析](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1663346&highlight=%C6%F3%B6%EC)
果然好使，大佬牛逼

**Comment by cloudnzk** [comment]
> mark 的确是改了,,[某课堂下载分析](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1663346&highlight=%C6%F3%B6%EC)
按照这个方法找key，顺利下载。谢谢大佬

**Comment by UsagiErina** [comment]
> mark 是改了,,[某课堂下载分析](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1663346&highlight=%C6%F3%B6%EC)

大佬牛的 感谢

**Comment by f9021003** [comment]
已經按照此文章取得key
但小鵝通 還是無法下載成功

請問是不是要填iv 阿？


> > mark 是改了,,[某课堂下载分析](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1663346&highlight=%C6%F3%B6%EC)
> 
> 大佬牛的 感谢

**Comment by azh3ng** [comment]
> mark 的确是改了,,[某课堂下载分析](https://www.52pojie.cn/forum.php?mod=viewthread&tid=1663346&highlight=%C6%F3%B6%EC)

感谢大佬给出了最核心的 key 的获取方法

下面是稍微方便一点的使用办法：
1. 打开播放页
2. 按 F12 打开 DevTools
3. 刷新页面，DevTools 切换到网络（Network）tab，搜索找到 m3u8 的请求
4. 切换到启动器（Initiator），找到负责解码的 js（我找到的是 `lib_fd2a4cb1.js`），点击
5. 搜索 decryptkey ，在最后一个搜索结果，的下一行加断点（我找到的是`r.loader = null,`）
6. 刷新播放页
7. 等执行到断点处，页面会卡住，此时切换到 DevTools，按 Esc 调出控制台（Console）
8. 复制粘贴，在 Console 执行下面的 js ，会输出可用的下载命令
```js
// 将 Uint8Array 转换为十六进制数的数组
let hexArray = Array.from(r.levelkey.key, byte => byte.toString(16).padStart(2, '0')).map(function(hexString) {
  return parseInt(hexString, 16); // 转换为字节
});

// 将字节编码为 Base64 字符串
let base64String = btoa(String.fromCharCode.apply(null, hexArray));

// 获取文件名
let fileName = document.querySelector("#react-body > div.study-header > div.current-task-name.header-item").innerHTML;

let m3u8dl = `n_m3u8dl "${r.baseurl}" --useKeyBase64 ${base64String} --workDir "D:\\download" --enableDelAfterDone --saveName "${fileName}"`

console.log(m3u8dl)
```

**Comment by cqzaiercn** [comment]
我用webdriver 抓取方式 怎么解析到这个key？  头大
