### ISSUE TITLE
下载m3u8存在key没有操作成功，求帮助

### ISSUE THREAD

**Issue by luzihang123** [nilaoda/N_m3u8DL-CLI#71]
视频地址：http://online.fxyjs.com/classModule/video/605062/598185/2342224/0/0

抓包得出：
m3u8地址：http://hls.videocc.net/de956abe74/7/de956abe74a37a78e4cf157eb6efcc07.m3u8
key地址：http://hls.videocc.net/playsafe/de956abe74/7/de956abe74a37a78e4cf157eb6efcc07_2.key?token=b9f807c8-71c5-475b-b0a4-c988d5103626-o2944056

![image.png](https://i.loli.net/2020/02/18/zHMxyBc5juGtDrq.png)
![image.png](https://i.loli.net/2020/02/18/96jVdZKbgkOW5Rw.png)

**Comment by nilaoda** [comment]
非常规AES-128，key是32字节的

**Comment by luzihang123** [comment]
> 非常规AES-128，key是32字节的
意思是比较难吗？可以给一点解决思路吗？

---
4个月前，我也是下载了同样的视频，现在这个网站应该是升级了反爬。
```shell
fmpeg -i http://hls.videocc.net/de956abe74/7/de956abe74a37a78e4cf157eb6efcc07.m3u8 "工商管理01".mp4
```
![image.png](https://i.loli.net/2020/02/19/U1oj3C2zRZyObVi.png)

**Comment by luzihang123** [comment]
查了一圈资料，觉得应该是key有实效，文档写的5min，好像是这个原因吧？
> 原来的视频，开启了web的授权播放功能了
> https://dev.polyv.net/2015/uncategorized/websqbf/

**Comment by luzihang123** [comment]
所以这个m3u8基本下载不了吧？
https://www.52pojie.cn/thread-1013988-1-1.html

**Comment by luzihang123** [comment]
看起来是搞不定保利威的加密了
https://www.52pojie.cn/thread-1067676-1-1.html

**Comment by xhlove** [comment]
其实key很简单拿到。
首先搜索关键词`decryptdata`，如下：
http://puui.qpic.cn/vshpic/0/E48g_2r88noETx7RZD6TCiC4nySAmwTNrNOcAq_0pcrtD4_s_0/0
然后进入这个blob，在这个地方下断点，如下：
http://puui.qpic.cn/vshpic/0/k_Nx0I-KJgblPFtC5U60ks_t1HXJHMA0C5BGh5IAyE766ZOO_0/0
然后你就能看到真实的key了，当然IV就是m3u8链接返回的IV，解密模式是AES-CBC
这个视频（高清）的key是`hu9/BaDh7HY8OIhVwpYKyw==`，iv是`0x70611bb83492601ef8a9738c905f5da9`
解密后的视频如下：http://puui.qpic.cn/vshpic/0/Q39pD6IMHXxtVZEPOhFOxy4Lsy5c59VUJhUqNxfVdnA1iI0R_0/0
