### ISSUE TITLE
下载完成后，文件大小为0字节

### ISSUE THREAD

**Issue by YY-China** [nilaoda/N_m3u8DL-CLI#715]
**m3u8**地址如下：
https://qod.yimeiq.cn/39813aa734304b218e77952798f9bfd1/aec8833c48204034a5360339c7b42614-c4e9b9d663e356fafbe64258cce6f93e-ld-encrypt-stream.m3u8?auth_key=1661474963-null-null-634d5a5e90297ddd0b36bb1a23da78bb

**分片无法播放，合并分片后的文件大小显示为0字节，谢谢作者指导**！

**Comment by nilaoda** [comment]
无法指导。本程序不承诺提供对特殊加密的解密功能。
