### ISSUE TITLE
 远程服务器返回错误: (403)

### ISSUE THREAD

**Issue by spiritedRunning** [nilaoda/N_m3u8DL-CLI#717]
`
11:03:25.711 / (NORMAL) 开始解析 https://video-player.lintcode.com/v2/api/play-list/093ba5ae-280f-11ed-952e-0242ac1a0002.m3u8?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxdWFsaXR5IjoiMTA4MHAiLCJrZXkiOiIxNzdkMDVkZDU1MWFkMzg1NmUxMjRkNGY1ODk4YzM5MiIsIml2IjoiZWNjMjU5OTY2YWVjNmExOTAyMmRiOWRhMGI4ZmZkMDkiLCJleHAiOjE2NjIxMzAwNjAsInV1aWQiOiIwOTNiYTVhZS0yODBmLTExZWQtOTUyZS0wMjQyYWMxYTAwMDIiLCJpc19zdXAiOnRydWV9.Dfwu3m6pgR0x9YhExVdLujZEr9s0OzNIyiqm0jSNjlY

11:03:26.110 / (NORMAL) 获取m3u8 key... https://video-player.lintcode.com/v2/api/play-list/0fbdc058-28e9-11ed-80dd-0242ac1f0002/key.key?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJxdWFsaXR5IjoiMTA4MHAiLCJrZXkiOiIxNzdkMDVkZDU1MWFkMzg1NmUxMjRkNGY1ODk4YzM5MiIsIml2IjoiZWNjMjU5OTY2YWVjNmExOTAyMmRiOWRhMGI4ZmZkMDkiLCJleHAiOjE2NjIxMzAwNjAsInV1aWQiOiIwOTNiYTVhZS0yODBmLTExZWQtOTUyZS0wMjQyYWMxYTAwMDIiLCJpc19zdXAiOnRydWV9.Dfwu3m6pgR0x9YhExVdLujZEr9s0OzNIyiqm0jSNjlY
11:03:26.207 / (NORMAL) 写出meta.json
11:03:26.292 / (NORMAL) 开始下载文件
11:03:26.405 / (ERROR) DOWN: 远程服务器返回错误: (403) 已禁止。 https://video1.lintcode.com/encrypt/fdf3b648-d25b-4bda-90a4-46b41e26e11d/mNbnws_1080p0.ts?sign=17be1926880423035f810d16f11c8ee2&t=1662087895
11:03:27.407 / (ERROR) DOWN: AUTO RETRY 1/3 https://video1.lintcode.com/encrypt/fdf3b648-d25b-4bda-90a4-46b41e26e11d/mNbnws_1080p0.ts?sign=17be1926880423035f810d16f11c8ee2&t=1662087895
11:03:27.463 / (ERROR) DOWN: 远程服务器返回错误: (403) 已禁止。 https://video1.lintcode.com/encrypt/fdf3b648-d25b-4bda-90a4-46b41e26e11d/mNbnws_1080p0.ts?sign=17be1926880423035f810d16f11c8ee2&t=1662087895
11:03:28.466 / (ERROR) DOWN: AUTO RETRY 2/3 https://video1.lintcode.com/encrypt/fdf3b648-d25b-4bda-90a4-46b41e26e11d/mNbnws_1080p0.ts?sign=17be1926880423035f810d16f11c8ee2&t=1662087895
11:03:28.529 / (ERROR) DOWN: 远程服务器返回错误: (403) 已禁止。 https://video1.lintcode.com/encrypt/fdf3b648-d25b-4bda-90a4-46b41e26e11d/mNbnws_1080p0.ts?sign=17be1926880423035f810d16f11c8ee2&t=1662087895
11:03:29.532 / (ERROR) DOWN: AUTO RETRY 3/3 https://video1.lintcode.com/encrypt/fdf3b648-d25b-4bda-90a4-46b41e26e11d/mNbnws_1080p0.ts?sign=17be1926880423035f810d16f11c8ee2&t=1662087895
11:03:29.597 / (ERROR) DOWN: 远程服务器返回错误: (403) 已禁止。 https://video1.lintcode.com/encrypt/fdf3b648-d25b-4bda-90a4-46b41e26e11d/mNbnws_1080p0.ts?sign=17be1926880423035f810d16f11c8ee2&t=1662087895
11:03:29.610 / (NORMAL) 读取文件信息...
11:03:29.612 / (NORMAL) Error in reading file
`

**Comment by missdgsn** [comment]
你这个TOKEN应该是一次性的，就不能放在下载器里面
