### ISSUE TITLE
錄製直播時，請求頭命令會有BUG

### ISSUE THREAD

**Issue by MAN-GOR** [nilaoda/N_m3u8DL-CLI#718]
在直播流裡添加「--headers」，僅僅第一次獲取的直播片段會添加相關請求頭，第二次獲取的直播片段會使用軟件默認請求頭，而不是我添加的請求頭，導致直播不能下載，軟件會一直提示「Waiting...」。

第一次獲取的片段，因為請求頭添加了「Origin」，所以下載成功：
![螢幕擷取畫面 2022-09-02 130438](https://user-images.githubusercontent.com/92726453/188062929-3123e361-e273-4e30-93ea-14b3bac649b3.png)
第二次獲取的片段，因為使用了軟件默認請求頭，而不是我添加的請求頭，所以下載失敗：
![螢幕擷取畫面 2022-09-02 130447](https://user-images.githubusercontent.com/92726453/188062936-f00da592-8e6c-4329-bb38-74cd3c3709b1.png)
命令行一直提示「Waiting...」：
![螢幕擷取畫面 2022-09-02 130749](https://user-images.githubusercontent.com/92726453/188063121-2baaa780-1cc2-43bb-858a-2a02450c614d.png)

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/2993783161
