### ISSUE TITLE
 Error in reading file！

### ISSUE THREAD

**Issue by SusuDOS** [nilaoda/N_m3u8DL-CLI#719]
下载报错: Error in reading file

完整日志如下：
LOG 2022/09/02
Save Path: C:\MyTools\M3u8Downloader\Logs
Task Start: 2022/09/02 22:38:02
Task CommandLine: "C:\MyTools\M3u8Downloader\N_m3u8DL-CLI_v3.0.2.exe" "https://rapidtai.com/videos/202109/30/615525631f80ab0822bf7c27/f5g48a/index.m3u8?random=BcgdEfB3dDCD5454AeD4" --workDir "D:\001" --saveName "index" --maxThreads "12" --minThreads "8" --retryCount "8" --timeOut "15" --proxyAddress "http://127.0.0.1:10809" --enableDelAfterDone --enableBinaryMerge 

22:38:02.492 / (NORMAL) 开始解析 https://rapidtai.com/videos/202109/30/615525631f80ab0822bf7c27/f5g48a/index.m3u8?random=BcgdEfB3dDCD5454AeD4
22:38:06.879 / (NORMAL) 获取m3u8 key... /videos/202109/30/615525631f80ab0822bf7c27/ts.key
22:38:07.219 / (NORMAL) 写出meta.json
22:38:07.478 / (NORMAL) 开始下载文件
22:38:08.148 / (ERROR) DOWN: 远程服务器返回错误: (404) 未找到。 https://v8cdn.snmovie.com/videos/202109/30/615525631f80ab0822bf7c27/f5g48a/index0.ts
22:38:09.158 / (ERROR) DOWN: AUTO RETRY 1/3 https://v8cdn.snmovie.com/videos/202109/30/615525631f80ab0822bf7c27/f5g48a/index0.ts
22:38:10.975 / (ERROR) DOWN: 远程服务器返回错误: (404) 未找到。 https://v8cdn.snmovie.com/videos/202109/30/615525631f80ab0822bf7c27/f5g48a/index0.ts
22:38:11.991 / (ERROR) DOWN: AUTO RETRY 2/3 https://v8cdn.snmovie.com/videos/202109/30/615525631f80ab0822bf7c27/f5g48a/index0.ts

似乎是需要校验一些东西，而该校验的信息未带参数请求！比如：在浏览器中键入m3u8中的切片地址得到404未找到提示；但，使用IDM可以正常下载m3u8中的分片。

为防止连接在复制过程中被修改，已对应检测确定连接未被修改！

![](https://www.hualigs.cn/image/63121717567b9.jpg)

![](https://www.hualigs.cn/image/6312171752cc3.jpg)

**Comment by nilaoda** [comment]
增加请求头`Referer: https://v8cdn.snmovie.com`
