### ISSUE TITLE
请问下怎么设置合并后不自动转码？

### ISSUE THREAD

**Issue by yyxiaofeng** [nilaoda/N_m3u8DL-CLI#722]
请问下下载m3u8链接视频完成后，怎么设置ts合并后不自动转码成MP4，我想要的是ts文件，不想转码？

**Comment by nilaoda** [comment]
开启二进制合并

**Comment by yyxiaofeng** [comment]
老大，为啥potplay能播放这个直播源http://platin4k.eu/kralkerim/8TKLyJivVEA/73801，但N_m3u8DL-CLI无法解析呢？

**Comment by nilaoda** [comment]
> 

这不是m3u8形式的直播源 参考https://github.com/nilaoda/N_m3u8DL-CLI/issues/723

**Comment by yyxiaofeng** [comment]
大佬，按照这个curl http://platin4k.eu/kralkerim/8TKLyJivVEA/73801 -o test.ts  下载，为何只能下载5秒视频就自动断了呢，求解
