### ISSUE TITLE
首分片ts无画面导致整个ts合并文件无法正常播放

### ISSUE THREAD

**Issue by 775405984** [nilaoda/N_m3u8DL-CLI#724]
直播流，首分片ts是一个没有画面的音频，是黑屏的。
我手贱点了合并后删除分片，导致现在的文件不能正常播放后面的画面。
potplayer只能识别音频，怎么拖动进度都不能看到画面
tsMuxeR 也只能识别音频
![image](https://user-images.githubusercontent.com/7196377/188451496-581899cc-c3e4-40d2-9d61-a67fe2a3350a.png)
SMMVSplitter、剪映等视频编辑软件也只能识别音频。
但是HandBrake却可以正常识别视频，并有图片预览
![image](https://user-images.githubusercontent.com/7196377/188451961-72c895cc-ad88-421f-b504-25cd78794b25.png)
medlexo软件输出的mp4也只是包了壳的音频。

咋整？不会要我用handbrake重新转码吧？
「合并文件.ts」https://www.aliyundrive.com/s/xpDEbW7oqbV 提取码: e0w8

**Comment by nilaoda** [comment]
使用TSDoctor即可修复

点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
链接：https://www.aliyundrive.com/s/cRNRr82jLp5
