### ISSUE TITLE
Choose Quality for m3u8 streams

### ISSUE THREAD

**Issue by mostafasmh1996** [nilaoda/N_m3u8DL-CLI#727]
Please add the ability to choose Video and Audio quality for m3u8 streams

**Comment by nilaoda** [comment]
already can do it...

**Comment by mostafasmh1996** [comment]
I know, but with some m3u8 streams can't do that
It will download the best quality

**Comment by nilaoda** [comment]
Any link?

**Comment by mostafasmh1996** [comment]
https://vod-ftc-eu-west-1.media.dssott.com/ps01/disney/29a73209-b706-4f21-8384-acddccb154d2/ctr-all-6cf6fec6-94dc-4f8b-ae67-5ada60ee1e83-42bd5bca-f9a8-4299-83e3-0fb2b4ec0a62.m3u8

**Comment by nilaoda** [comment]
![image](https://user-images.githubusercontent.com/20772925/190104948-b32e7d5e-6ae4-4692-8764-53403321839b.png)

For 1:
```
N_m3u8DL-RE.exe "https://vod-ftc-eu-west-1.media.dssott.com/ps01/disney/29a73209-b706-4f21-8384-acddccb154d2/ctr-all-6cf6fec6-94dc-4f8b-ae67-5ada60ee1e83-42bd5bca-f9a8-4299-83e3-0fb2b4ec0a62.m3u8" -sv res=3840:codecs=dvh1
```

For 2:
```
N_m3u8DL-RE.exe "https://vod-ftc-eu-west-1.media.dssott.com/ps01/disney/29a73209-b706-4f21-8384-acddccb154d2/ctr-all-6cf6fec6-94dc-4f8b-ae67-5ada60ee1e83-42bd5bca-f9a8-4299-83e3-0fb2b4ec0a62.m3u8" -sv res=3840:codecs=hvc1
```

For 9:
```
N_m3u8DL-RE.exe "https://vod-ftc-eu-west-1.media.dssott.com/ps01/disney/29a73209-b706-4f21-8384-acddccb154d2/ctr-all-6cf6fec6-94dc-4f8b-ae67-5ada60ee1e83-42bd5bca-f9a8-4299-83e3-0fb2b4ec0a62.m3u8" -sv res=1920:codecs=dvh1
```

**Comment by nilaoda** [comment]
Sorry, N_m3u8DL-CLI can not select quality, [N_m3u8DL-RE](https://github.com/nilaoda/N_m3u8DL-RE) can do it...

**Comment by nilaoda** [comment]
btw do you have the deception key? for test
