### ISSUE TITLE
腾讯视频下载失败

### ISSUE THREAD

**Issue by pbxs666** [nilaoda/N_m3u8DL-CLI#73]
试了好多视频，大多数在下载开始就没速度或者下载了一些就没速度了，只有极少数在为掉速度之前下载成功。
例如这个：
原视频：https://v.qq.com/x/cover/nug3wu4a6zvwy8s/a0025rkiidv.html
m3u8链接：https://ltsws.qq.com/jNGCHHVKyEokM0quUjJL4c-jks0HiSm4rGVzaD3N_ePzgE0c19tDv9J78syT-cyGta-3qrFUImoBwzxzBa5SkGYaVfIedNvYWOl4XCBHxECajkXZg1tzgyvawnyqo3ot-bgHAa76Ie1IDDwO-y2rg7nMM_vaXkgdYC-hpeOnsHE/a0025rkiidv.321004.ts.m3u8?ver=4

版本：N_m3u8DL-CLI_v2.4.9
求大神解答

**Comment by ihuangke** [comment]
解密需要自己想办法了。。。。可以下载而已

**Comment by wyl5602443** [comment]
你们是怎么解析这些影视站的M3U8地址的啊？
