### ISSUE TITLE
Drm m3u8

### ISSUE THREAD

**Issue by sss-aaa** [nilaoda/N_m3u8DL-CLI#731]
how i can download this link 
https://d1z78r8i505acl.cloudfront.net/media/Em4JFqsoVuJUQ/35efe23f/master.m3u8
its a drm with m3u8

**Comment by nilaoda** [comment]
tool can only download, no decrypt...

**Comment by sss-aaa** [comment]
> tool can only download, no decrypt...

why ?

**Comment by nilaoda** [comment]
> > tool can only download, no decrypt...
> 
> why ?

learn about DRM pls

**Comment by sss-aaa** [comment]
> > > يمكن تنزيل الأداة فقط ، ولا يمكن فك تشفير ...
> > 
> > 
> > لماذا ا ؟
> 
> تعرف على الثابتة والمتنقلة DRM

Can you help me learn the way or the path? Or you can decode the video because I need it very much
