### ISSUE TITLE
不支持SAMPLE一AES加密方式,将不被处理,旦强制开启二进制合并

### ISSUE THREAD

**Issue by despairTK** [nilaoda/N_m3u8DL-CLI#736]
下载完成合并后，播放画面为花屏。下载过程中提示：不支持SAMPLE一AES加密方式,将不被处理,旦强制开启二进制合并。
![QQ截图20221007151305](https://user-images.githubusercontent.com/111871110/194492669-b5788d01-5178-439f-9c3e-bcabb86ae067.jpg)

**Comment by nilaoda** [comment]
不支持
