### ISSUE TITLE
有办法破解dmm的视频流吗

### ISSUE THREAD

**Issue by lvzhenbo** [nilaoda/N_m3u8DL-CLI#74]
最近买了一部，然后发现只有视频流和加密下载文件。尝试找到m3u8链接下载，发现key是个链接。大佬，有办法吗？

**Comment by nilaoda** [comment]
贴一下m3u8片段

**Comment by lvzhenbo** [comment]
> 贴一下m3u8片段

#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:0
#EXT-X-KEY:METHOD=AES-128,URI="https://www.dmm.co.jp/service/-/drm_iphone?ld=%2BATyVhRvEXdMSt%2BFy63sPqLEcJSpug172WuiQ6%2BZyDs3vCQm9xcpibKVs2E7pGCxvlKoCnNOaWxJEZ0gLm4LEzXeynaKHXsbUjBvcbfhGFoz7%2F42MGjwfNs9KSe8Hsed&luid=cojp"
#EXTINF:4.004,
media_b6000000_0.ts

**Comment by zywhb** [comment]
nilaoda 新版cli2.60 不重定向取得的 m3u8下载后，生成两个文件，一个视频和一个音频，但都是加密的，能解吗
https://v.youku.com/v_show/id_XNDUxNDQ4MDQyOA==.html?spm=a2hcb.12701310.app.5~5!2~5!3~5~5~5!5~5~5~5~A

**Comment by 1405040117** [comment]
你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载

**Comment by lvzhenbo** [comment]
> 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载

好的感谢

**Comment by leoli730** [comment]
> 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载

得到密钥用在哪裡？

**Comment by 1405040117** [comment]
> > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> 
> 得到密钥用在哪裡？

使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入

**Comment by NyxiaSha** [comment]
> > > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> > 
> > 
> > 得到密钥用在哪裡？
> 
> 使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入

大佬，dmm m3u8 链接好像都不是固定了，每次打开中间都有一段会变化了 这个有什么解决方案嘛

**Comment by RRRRRm** [comment]
> > > > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > > > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > > > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> > > 
> > > 
> > > 得到密钥用在哪裡？
> > 
> > 
> > 使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入
> 
> 大佬，dmm m3u8 链接好像都不是固定了，每次打开中间都有一段会变化了 这个有什么解决方案嘛

请问您找到解决方案了吗

**Comment by 1405040117** [comment]
> > > > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > > > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > > > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> > > 
> > > 
> > > 得到密钥用在哪裡？
> > 
> > 
> > 使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入
> 
> 大佬，dmm m3u8 链接好像都不是固定了，每次打开中间都有一段会变化了 这个有什么解决方案嘛

> > > > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > > > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > > > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> > > 
> > > 
> > > 得到密钥用在哪裡？
> > 
> > 
> > 使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入
> 
> 大佬，dmm m3u8 链接好像都不是固定了，每次打开中间都有一段会变化了 这个有什么解决方案嘛

我记得前面的playlist.m3u8的链接是不变的，保存这个链接，后面需要下载，访问这个链接重定位得到具体码率的m3u8实时链接即可，只不过这个key在一开始就要及时保存下来，否则后面账号或者影片失效，key就下载不了了

**Comment by 1405040117** [comment]
> > > > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > > > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > > > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> > > 
> > > 
> > > 得到密钥用在哪裡？
> > 
> > 
> > 使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入
> 
> 大佬，dmm m3u8 链接好像都不是固定了，每次打开中间都有一段会变化了 这个有什么解决方案嘛

我记得前面的playlist.m3u8的链接是不变的，保存这个链接，后面需要下载，访问这个链接重定位得到具体码率的m3u8实时链接即可，只不过这个key在一开始就要及时保存下来，否则后面账号或者影片失效，key就下载不了了

**Comment by 1405040117** [comment]
> > > > > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > > > > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > > > > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> > > > 
> > > > 
> > > > 得到密钥用在哪裡？
> > > 
> > > 
> > > 使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入
> > 
> > 
> > 大佬，dmm m3u8 链接好像都不是固定了，每次打开中间都有一段会变化了 这个有什么解决方案嘛
> 
> 请问您找到解决方案了吗 @NyxiaSha

见我回复，其实很简单。。。

**Comment by RRRRRm** [comment]
> > > > > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > > > > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > > > > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> > > > 
> > > > 
> > > > 得到密钥用在哪裡？
> > > 
> > > 
> > > 使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入
> > 
> > 大佬，dmm m3u8 链接好像都不是固定了，每次打开中间都有一段会变化了 这个有什么解决方案嘛
> 
> 我记得前面的playlist.m3u8的链接是不变的，保存这个链接，后面需要下载，访问这个链接重定位得到具体码率的m3u8实时链接即可，只不过这个key在一开始就要及时保存下来，否则后面账号或者影片失效，key就下载不了了

谢谢您，成功搞起来了

**Comment by lvzhenbo** [comment]
收到一堆邮件才发现，这边推荐一个浏览器插件，叫抓猫，也在github上开源的，可以直接抓到m3u8链接

**Comment by tkbianyuan** [comment]
> > > > > 你都知道了这个Key是个链接，直接访问这个链接，会得到一个文件，用HEX编辑器打开就是16字节的密钥，然后你可以直接把16进制文本复制出来转换成base64编码再用工具下载
> > > > > 然后，这个Key链接的访问是需要账号cookie的，需要在浏览器登录好DMM账号，然后新开一个页面，F12打开开发者工具，然后访问这个链接抓包，查看响应，Preview选项卡能看到base64编码的密钥直接复制出来即可，主要Chrome浏览器太新的版本不会显示base64编码而是乱码，所以最好用360浏览器
> > > > > m3u8文件里的ts片段都是用的相对路径，你需要把m3u8的URL进行截取拼接到ts文件名前面形成完整的URL，这个m3u8才能拿去进行下载
> > > > 
> > > > 
> > > > 得到密钥用在哪裡？
> > > 
> > > 
> > > 使用AES算法解密ts文件中的二进制数据时，需要把获取到的解密密钥传入
> > 
> > 
> > 大佬，dmm m3u8 链接好像都不是固定了，每次打开中间都有一段会变化了 这个有什么解决方案嘛
> 
> 我记得前面的playlist.m3u8的链接是不变的，保存这个链接，后面需要下载，访问这个链接重定位得到具体码率的m3u8实时链接即可，只不过这个key在一开始就要及时保存下来，否则后面账号或者影片失效，key就下载不了了

您好大佬，我按你说的16字节密钥提取了，base64编码也转换了。然后在新页面找到cookie，我没什么编程基础，不知道这个访问链接抓包Preview选项卡能看到base64编码在哪？最后这个相对路径是把后面这个  /playlist.m3u8?ld=IBaD 换成media_b6000000_0.ts 吗? 我用 N_m3u8DL-CLI-SimpleG.exe 试了很多次，不是地址不正确 或者  填充无效、无法被移除 。具体应该怎么操作啊，谢谢！

**Comment by linuxxx** [comment]
这个方式还行得通吗？

**Comment by lvzhenbo** [comment]
> 这个方式还行得通吗？

https://github.com/nilaoda/N_m3u8DL-CLI/issues/473#issuecomment-922425699

**Comment by zywhb** [comment]
兄弟，行不通了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nilaoda/N_m3u8DL-CLI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月19日(星期天) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 有办法破解dmm的视频流吗 (#74)





  
这个方式还行得通吗？
  
#473 (comment)
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvzhenbo** [comment]
可以啊，我前几天刚买了一部，可以下载啊。
哦顺便提醒一下，别挖坟了，不是有一个issue开着的吗

**Comment by zywhb** [comment]
兄弟，优酷的大多是cmaf加密了，原来的提取cmaf密码的失效了，另外aes加密的也变了，兄弟能共享一下方法吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nilaoda/N_m3u8DL-CLI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月6日(星期天) 晚上7:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 有办法破解dmm的视频流吗 (#74)





 
可以啊，我前几天刚买了一部，可以下载啊。
 哦顺便提醒一下，别挖坟了，不是有一个issue开着的吗
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lvzhenbo** [comment]
兄弟，你来错地方了

**Comment by zywhb** [comment]
哈哈，刚看完女足比赛，可能。谢谢兄弟




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nilaoda/N_m3u8DL-CLI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月6日(星期天) 晚上9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 有办法破解dmm的视频流吗 (#74)





 
兄弟，你来错地方了
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
