### ISSUE TITLE
go程序掉用 下载速度变慢 

### ISSUE THREAD

**Issue by fc221** [nilaoda/N_m3u8DL-CLI#742]
![image](https://user-images.githubusercontent.com/24759664/197390035-6d2260ba-2011-4bbc-bf4a-0c04630dadfe.png)
我用golang程序去掉用发现没有直接执行命令下载速度快
图1 直接掉用
![image](https://user-images.githubusercontent.com/24759664/197390104-5f16c7bc-09d9-4722-9bc7-1df57ca01cbf.png)
图2 go程序掉用
![image](https://user-images.githubusercontent.com/24759664/197390134-781f96f0-2f26-44e3-b58d-f8c4d3dec6ae.png)

**Comment by nilaoda** [comment]
我试着用`exec.Command`调用了一下 不会很慢

```golang
package main

import (
	"fmt"
	"os"
	"os/exec"
)

func main() {
	url := "http://xxx.m3u8"

	fmt.Println(url)

	commands := []string{url, "--minThreads", "8", "--stopSpeed", "500", "--enableDelAfterDone", "--disableDateInfo", "--noProxy"}
	cmd := exec.Command("N_m3u8DL-CLI_v3.0.2.exe", commands...)

	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	err := cmd.Run()
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println("=====OK=====")
}

```

**Comment by fc221** [comment]
我直接用和 exec.Command 都下过同一个地址 在N_m3u8DL-CLI_v3.0.2.exe --workDir “./xxx” --savenName “1” “https://m3u.haiwaikan.com/xm3u8/4c001a37de06495c29b22e7d3489402cb5e1fe779455455c6a78d677c6136e2e9921f11e97d0da21.m3u8”
的情况下 exec.Command 跟限速了 100一样
我exec.Command 三开 任务管理下载速度 100 * 3

**Comment by fc221** [comment]
而 直接使用N_m3u8DL-CLI_v3.0.2.exe --workDir “./xxx” --savenName “1” “https://m3u.haiwaikan.com/xm3u8/4c001a37de06495c29b22e7d3489402cb5e1fe779455455c6a78d677c6136e2e9921f11e97d0da21.m3u8” 下载速度能上g

**Comment by nilaoda** [comment]
> 感谢 查明原因了

什么原因？

**Comment by fc221** [comment]
资源cdn的问题 我找了个 没有执行过的 发现直接掉用和 exec.Command 子进程执行速度是一样的
如果执行过一次的话 cdn上面有缓存了 第二次执行估计就命中缓存了 速度就变快了
