### ISSUE TITLE
调用N_m3u8DL-CLI可以批量传入m3u8地址吗？

### ISSUE THREAD

**Issue by hpyer2016** [nilaoda/N_m3u8DL-CLI#747]
请问老大是否可以将m3u8地址保存在本地txt文件，以读文件的形式批量下载？如果可以，保存的格式是怎么样的（带title、workDir等参数）？启动参数怎么设置？感谢！

**Comment by nilaoda** [comment]
借助SimpleG可以做到，也可以自己写BAT脚本

**Comment by hpyer2016** [comment]
谢谢
