### ISSUE TITLE
怎么并行运行多个下载任务？批处理？

### ISSUE THREAD

**Issue by lweo** [nilaoda/N_m3u8DL-CLI#751]
自己折腾了好久都没搞定，想用for循环并行运行多个m3u8DL，下载不同的直播。txt文档里填好链接和下载参数，运行bat就同时下载多个任务。

求大佬指教~

eg:
`D:\小工具\N_m3u8DL-CLI_v3.0.2\N_m3u8DL-CLI_v3.0.2.exe "https://p8.vzan.com/1745260768/111275402644272296/live.m3u8?zbid=1745260768&tpid=905221039&type=0" --workDir "H:\K\Videos" --saveName "2022年中国药物滥用防治协会家庭与青少年工作分会年会暨游戏障碍诊疗新进展培训班" --enableDelAfterDone --headers "Referer:https://wx.vzan.com/"
D:\小工具\N_m3u8DL-CLI_v3.0.2\N_m3u8DL-CLI_v3.0.2.exe "https://liveplay-dx.xiaoeknow.com/live/5060_MGFT5edHehKAsDP5_720P.m3u8?time=1670125894482&uuid=u_lp_1641695467_61da48ebac290_aBMSlc" --workDir "H:\K\Videos" --saveName "中小学生心理健康教育高端论坛" --enableDelAfterDone --headers "Referer:https://appc75jwmhz4298.h5.xiaoeknow.com/"`

**Comment by nilaoda** [comment]
```bat
start cmd /K N_m3u8DL-CLI_v3.0.2.exe xxx
start cmd /K N_m3u8DL-CLI_v3.0.2.exe xxx
start cmd /K N_m3u8DL-CLI_v3.0.2.exe xxx
start cmd /K N_m3u8DL-CLI_v3.0.2.exe xxx
```

**Comment by lweo** [comment]
> ```batchfile
> start cmd /K N_m3u8DL-CLI_v3.0.2.exe xxx
> start cmd /K N_m3u8DL-CLI_v3.0.2.exe xxx
> start cmd /K N_m3u8DL-CLI_v3.0.2.exe xxx
> start cmd /K N_m3u8DL-CLI_v3.0.2.exe xxx
> ```

谢谢大佬回复~

这个代码每行要输入start，怎么做可以只用输入下载任务链接，或者作为参数直接调用？

**Comment by pjy612** [comment]
弄个 excel 写个公式 拉一遍。。。
