### ISSUE TITLE
请求增加一个自定义HTTP request query parametes功能

### ISSUE THREAD

**Issue by shanzhaozhen** [nilaoda/N_m3u8DL-CLI#755]
请求增加一个自定义HTTP request query parametes功能

可能有些视频需要签名参数，而不需要cookies的，面向微信用户的视频网站打多如此，no session，没有cookies

![image](https://user-images.githubusercontent.com/29800728/208451783-203c3ede-cd2c-4330-b24d-01a9a18d3c3b.png)

**Comment by nilaoda** [comment]
这不就是url中的参数？

**Comment by shanzhaozhen** [comment]
> 这不就是url中的参数？

是的，不带这些参数会403

**Comment by nilaoda** [comment]
那你自己改url就好了呀……
