### ISSUE TITLE
求教mgstage视频流破解方法

### ISSUE THREAD

**Issue by sishenzhisi** [nilaoda/N_m3u8DL-CLI#757]
有人会破解mgstage视频流么

**Comment by kurtn2005** [comment]
Downie就能下载了。话说你还能付款吗？我的信用支付提示失败了。

> 有人会破解mgstage视频流么

**Comment by sishenzhisi** [comment]
这个还能下么我弄了个streamgaga一直下不动

**Comment by sishenzhisi** [comment]
只有mac版啊

**Comment by kurtn2005** [comment]
> 只有mac版啊

这个只有Mac的，看看有没有类似的吧。

**Comment by sishenzhisi** [comment]
视频是有drm的这个能破解么

**Comment by kurtn2005** [comment]
没有 DRM，我购买的视频都没有，但我最近没有买，不知道改了没。发自我的 iPhone在 2022年12月28日，17:00，sishenzhisi ***@***.***> 写道：﻿
视频是有drm的这个能破解么

**Comment by sishenzhisi** [comment]
没有drm么，为啥我用idm下载下来的都是花屏没声音啊？我是用bitcash买的。

**Comment by kurtn2005** [comment]
你可以取一下 m3u8，把里面的 ts 段下回来一个然后用播放器试试。我的 m3u8里面是没有 drm 信息的。没看到有 key 什么的。发自我的 iPhone在 2022年12月28日，19:21，sishenzhisi ***@***.***> 写道：﻿
没有drm么，为啥我用idm下载下来的都是花屏没声音啊？我是用bitcash买的。

**Comment by sishenzhisi** [comment]
是mgstage网站的么，我截取的都花屏没声音。

**Comment by sishenzhisi** [comment]
你多长时间没下载了

**Comment by kurtn2005** [comment]
> 你多长时间没下载了

我最后一次购买时2月25日，之后信用卡就不能用了，就没再买。

<img width="408" alt="image" src="https://user-images.githubusercontent.com/23029247/209938003-bd6e81aa-2536-4463-b621-8db1e589b2ef.png">

**Comment by sishenzhisi** [comment]
这是用的downie么

**Comment by sishenzhisi** [comment]
我购买的streamgaga经反馈修复了今天可以下载了😉

**Comment by kurtn2005** [comment]
> streamgaga

streamgaga支持DMM吗？

**Comment by sishenzhisi** [comment]
支持

**Comment by kurtn2005** [comment]
> 支持

好的，谢谢。我去下载一个试试，最近DMM升级DRM了，以前的老方法都不行了。

**Comment by sishenzhisi** [comment]
需要很好的日本vpn

**Comment by sishenzhisi** [comment]
你会下载sokmil的视频么

**Comment by kurtn2005** [comment]
> 你会下载sokmil的视频么

没用过这个，不知道。
