### ISSUE TITLE
sokmil

### ISSUE THREAD

**Issue by sishenzhisi** [nilaoda/N_m3u8DL-CLI#763]
sokmil的视频怎么破解啊

**Comment by ken19191** [comment]
老实说我也想知道

**Comment by sishenzhisi** [comment]
mgstage也行啊

**Comment by ken19191** [comment]
问题在key身上,找遍网站也找不到怎样拿key

**Comment by sishenzhisi** [comment]
sokmil没有也没事主，要是想找mgstage的之前有个软件可以下现在又不行了

**Comment by yugimaster** [comment]
找到16字节key和.m3u8文件，然后自己挂一个服务器来访问本地的.m3u8

**Comment by sishenzhisi** [comment]
mgstage的有了不会sokmil的

**Comment by yugimaster** [comment]
> mgstage的有了不会sokmil的

你是用工具还是通过浏览器调试来找的，sokmil在网页播放视频的有一个请求会返回影片的参数信息。在里面可以找到不同带宽的m3u8链接，每个m3u8里面都有key的URI

**Comment by sishenzhisi** [comment]
我是用工具的

**Comment by yugimaster** [comment]
> 我是用工具的

工具我不太清楚，可能不同工具只能用于不同的网站。但是它们最终的目的都是为了拿到key, m3u8和BaseUrl。我目前试过DMM，sokmil的资源在N_m3u8DL-CLI中下载都没问题，

**Comment by sishenzhisi** [comment]
dmm的好找sokmil的就不会了

**Comment by yugimaster** [comment]
> dmm的好找sokmil的就不会了

你好好找找吧，要先找到有关影片信息的数据，key文件是一个以结尾hls.dat的http链接

**Comment by sishenzhisi** [comment]
sokmil不是有mpd加密么

**Comment by sishenzhisi** [comment]
我就找到一个mpd文件

**Comment by yugimaster** [comment]
> sokmil不是有mpd加密么
![image](https://user-images.githubusercontent.com/7067431/219564414-3817a555-cdb3-46fb-beda-41039a54241d.png)
网页找到的是这个啊

**Comment by sishenzhisi** [comment]
大佬用的什么浏览器啊

**Comment by yugimaster** [comment]
> 大佬用的什么浏览器啊
Chrome

**Comment by sishenzhisi** [comment]
你这是插件吧

**Comment by yugimaster** [comment]
> 你这是插件吧

这个Chrome的插件，用来测试接口的

**Comment by sishenzhisi** [comment]
![IMG20230217144944](https://user-images.githubusercontent.com/121494681/219570616-18bdd416-a119-4fbc-b0a7-30d9bdd1c20a.jpg)
是在这里面找么

**Comment by yugimaster** [comment]
> ![IMG20230217144944](https://user-images.githubusercontent.com/121494681/219570616-18bdd416-a119-4fbc-b0a7-30d9bdd1c20a.jpg) 是在这里面找么

你这个链接响应的内容是什么啊，像是这个

**Comment by sishenzhisi** [comment]
![IMG20230217161854](https://user-images.githubusercontent.com/121494681/219590681-80d68e57-f47b-462c-af1f-981c33786aab.jpg)
一串这个

**Comment by yugimaster** [comment]
@sishenzhisi 那不是这个，你得找到响应是一个Json文件的链接，里面有很多参数信息，这些都是加密文件

**Comment by sishenzhisi** [comment]
![IMG20230217163842](https://user-images.githubusercontent.com/121494681/219595183-5d6d7b4d-5a7e-4bca-8b50-38c2d4d4560e.jpg)
这个？

**Comment by yugimaster** [comment]
![1676624215826](https://user-images.githubusercontent.com/7067431/219599181-9b90ece5-7280-428a-96e4-e941c1c9ce94.png)
应该是这个

**Comment by sishenzhisi** [comment]
![IMG20230217165946](https://user-images.githubusercontent.com/121494681/219599817-3c47f789-cde1-425b-8717-b80873e2f27d.jpg)
响应就是个这个

**Comment by yugimaster** [comment]
没有数据？你是不是已经过期了

**Comment by sishenzhisi** [comment]
![IMG20230217170905](https://user-images.githubusercontent.com/121494681/219601856-db81711c-1ac2-4984-9997-12dd69e6ebb0.jpg)
是不是应该是这个啊

**Comment by sishenzhisi** [comment]
![IMG20230217171426](https://user-images.githubusercontent.com/121494681/219602921-88afa3fa-e139-47a4-afd2-9dd08f8a4e74.jpg)
这个页面么

**Comment by yugimaster** [comment]
没错，你去这个链接里面找m3u8和key

**Comment by sishenzhisi** [comment]
![IMG20230217172530](https://user-images.githubusercontent.com/121494681/219605412-b282f617-8d2e-40dc-9000-765642a6f273.jpg)
key在这里面么

**Comment by sishenzhisi** [comment]
这个怎么用啊

**Comment by yugimaster** [comment]
> 这个怎么用啊

你直接在这个工具试着下这个m3u8链接呗

**Comment by sishenzhisi** [comment]
不行地址无效

**Comment by yugimaster** [comment]
不行的话，你可能得用本地的m3u8，然后用windows代理服务器生成一个代理m3u8地址。再用m3u8DL去下下载它，--baseurl 这个参数要加上

**Comment by sishenzhisi** [comment]
大佬你怎么弄的

**Comment by yugimaster** [comment]
就我上面说的这个方法啊

**Comment by sishenzhisi** [comment]
ok

**Comment by sishenzhisi** [comment]
-baseurl这个参数在哪啊

**Comment by sishenzhisi** [comment]
好的

**Comment by sishenzhisi** [comment]
![IMG20230217220601](https://user-images.githubusercontent.com/121494681/219677124-ffa1d352-f6e4-4905-95aa-f7f575944b8d.jpg)
是不是因为秘钥没解密的原因所以下载失败啊

**Comment by yugimaster** [comment]
密钥不对？你有放到我说的Chrome插件里，试下能有响应内容么？

**Comment by yugimaster** [comment]
就URI="......."这里面的是，但看你这个key的链接好像不完整，按理说都是https或者http开头

**Comment by sishenzhisi** [comment]
算了这样吧太费劲了谢谢了

**Comment by sishenzhisi** [comment]
请问你的hls.dat的链接是在哪里找的

**Comment by yugimaster** [comment]
> 

m3u8文件里的“URI=”里

**Comment by sishenzhisi** [comment]
他的加密方式是sample-aes看来需要解密

**Comment by yugimaster** [comment]
这可能是另一种AES加密方法，我测过的m3u8都是AES-128

**Comment by sishenzhisi** [comment]
我在网上查了查skd://这种开头的是drm加密

**Comment by yugimaster** [comment]
你可以看看在网页调试窗口，这个skd://有没有响应返回数据

**Comment by sishenzhisi** [comment]
没有

**Comment by sishenzhisi** [comment]
如果你感兴趣的话你可以试试能不能找到key哦
sokmil.com 账号1049728066@qq.com 密码qq15233743809

**Comment by yugimaster** [comment]
> 如果你感兴趣的话你可以试试能不能找到key哦 sokmil.com 账号[1049728066@qq.com](mailto:1049728066@qq.com) 密码qq15233743809

QQ聊吧

**Comment by sishenzhisi** [comment]
1049728066

**Comment by Mak0760** [comment]
> 这可能是另一种AES加密方法，我测过的m3u8都是AES-128

老哥，请问sokmil现在还能破解吗，能否教教我，有偿

**Comment by lwx1660677335** [comment]
sokmil购买视频破解,当前只破解了租赁的视频具体参见图片,中间需要用到猫扑插件
![2](https://github.com/nilaoda/N_m3u8DL-CLI/assets/12846588/fecaefbf-9ae9-4ed0-95c7-1431844ce82a)

![3](https://github.com/nilaoda/N_m3u8DL-CLI/assets/12846588/2fc7b697-8a81-4723-9bb1-83f1b642b0de)

![1](https://github.com/nilaoda/N_m3u8DL-CLI/assets/12846588/09285878-9297-458c-9427-d12c267b2a2e)

**Comment by lwx1660677335** [comment]
> > 这可能是另一种 AES 加密方法，我猜过的 m3u8 都是 AES-128
> 
> 老哥，请问sokmil现在还能破解吗，能否教教我，有偿

我已经破解，需要下载请联系QQ1660677335
