### ISSUE TITLE
mgstage

### ISSUE THREAD

**Issue by sishenzhisi** [nilaoda/N_m3u8DL-CLI#767]
有偿求mgstage网站视频破解方法

**Comment by mossan0101** [comment]
mgstageはwidevineを使用しています。https://www.videohelp.com/ で widevine を検索してください。そうすることで、毎月の動画や購入した動画をダウンロードすることができます :)

**Comment by mossan0101** [comment]
mgstage uses widevine. Please search for widevine on https://www.videohelp.com/. By doing so, you will be able to download monthly videos or purchased videos. :)

**Comment by sishenzhisi** [comment]
I don't know how to understand the secret mgstage video and download
