### ISSUE TITLE
friday

### ISSUE THREAD

**Issue by MyGoodbye** [nilaoda/N_m3u8DL-CLI#768]
你好，那个friday的mpd没法解析，这个可以有方法吗

**Comment by nilaoda** [comment]
friday我记得需要请求头吧

**Comment by MyGoodbye** [comment]
感谢你的回复，然而我加了user-agent和refere请求头，仍然显示地址错误

**Comment by MyGoodbye** [comment]
请问这个friday没有其他方案可供下载吗

**Comment by MyGoodbye** [comment]
大佬，实在尝试过很多方法，均已失败而终，不知能否提供一个方法呢？

**Comment by MyGoodbye** [comment]
我把mpd文件下载下来，然后丢进去，一直显示正在下载mpd文件
