### ISSUE TITLE
能否利用GPU加速ffmpeg合并视频

### ISSUE THREAD

**Issue by 454592673** [nilaoda/N_m3u8DL-CLI#769]
批量下载时候，合并会卡住，能否利用GPU加速呢，csdn上有例子
https://blog.csdn.net/wuzhongli/article/details/104922901

**Comment by nilaoda** [comment]
合并的时候只是复制视频流，只和硬盘速度有关，并不会重编码视频，所以GPU的硬件加速无用武之地。。
