### ISSUE TITLE
超过1800个部分合并？

### ISSUE THREAD

**Issue by ShenKang4181** [nilaoda/N_m3u8DL-CLI#771]
![image](https://user-images.githubusercontent.com/50401776/215769606-60e22196-d058-4b91-98c8-dc6bd9ca0b26.png)

**Comment by nilaoda** [comment]
超过1800个无法使用ffmpeg单次合并。程序将每N个分片进行二进制合并，产生若干较大的分片，然后再使用ffmpeg合并这些较大分片得到完整视频。

**Comment by ShenKang4181** [comment]
原来如此
