### ISSUE TITLE
小白提问，关于403的解决方法；链接后缀无法被加入导致的读取文件失败

### ISSUE THREAD

**Issue by AlexKSera** [nilaoda/N_m3u8DL-CLI#778]
这是日志文件的记录，403
远程服务器返回错误: (403) 已禁止。 https://pri-cdn-tx.xiaoeknow.com/appXRiS28ch1870/private_index/v.f421220.ts?start=0&end=44559&type=mpegts

这是网页F12的TS文件地址
https://encrypt-k-vod.xet.tech/fdae72e7vodtranshk1252524126/210d0d645285890814035209433/drm/v.f421220.ts?start=0&end=44559&type=mpegts&sign=ccd2025537bf45e64d924bfabb7685b5&t=641b733c&us=KgEyYnGqXV

看了其他的issue后尝试添加头，但是直接就无法解析了

想问下这种ts前后缀都有固定字段的链接如何解析？
谢谢

**Comment by nilaoda** [comment]
你需要自行针对小鹅通来进行特殊处理。同时需要自行寻找他的解密KEY。

**Comment by AlexKSera** [comment]
嗯，昨天试了试已经完成Key的寻找和TS完整片段下载了，问题已解决。

**Comment by ZhangXY-Magic** [comment]
> 嗯，昨天试了试已经完成Key的寻找和TS完整片段下载了，问题已解决。

大佬，请问下key怎么寻找呢
