### ISSUE TITLE
请问如何解密CSDN上的视频，跪求方法！

### ISSUE THREAD

**Issue by Eacolt** [nilaoda/N_m3u8DL-CLI#78]
CSDN链接地址：https://edu.csdn.net/course/play/7886/161292
m3u8地址：
https://vedu.csdnimg.cn/e3481f1510cf4cc2a51be2bc3df1f0db/0005334d07c8486fa638b5f26bce2b5f-bc28a139509c01ab3838874e6556be30-4k-encrypt-stream.m3u8

用你的那个EXE文件打开，直接输入m3u8地址，得到的是一个0字节的mp4文件和一个
文件夹，这是为啥呢，怎么得到完整的视频呢

**Comment by d8899p** [comment]
csdn是阿里云加密的，同求大佬在线解答

**Comment by xhlove** [comment]
以下是手动获取key的方法：
- 首先打开视频播放页面
- F12，搜索关键字符串`_sce_dlgtqredxx`
- 进入aliplayer-min.js，该js地址是：https://player.alicdn.com/resource/daily/20190514/de/prismplayer/2.8.3/aliplayer-min.js
- 在如图所示的地方下断点，F5刷新（注意在network一栏选定Disable Cache），等待视频加载
![下断点](http://puui.qpic.cn/vshpic/0/qoFrSqKavHwbvEbOUYm74M5zIr1UelXumxH9hqRPcXrR2jCP_0/0)
![Disable Cache](http://puui.qpic.cn/vshpic/0/eRKR1du54yxmv2gqRu3W8yAb1yoqxPJOlAKeqtCYsD1iPlRS_0/0)
- 此时在console执行`btoa(String.fromCharCode.apply(null, new Uint8Array(i._sce_dlgtqredxx)))`即可得到base64形式的key
![得到base64形式的key](http://puui.qpic.cn/vshpic/0/eRKR1du54yxmv2gqRu3W8yAb1yoqxPJOlAKeqtCYsD1iPlRS_0/0)

发布于：https://blog.weimo.info/archives/440/

**Comment by xhlove** [comment]
补充：注意这里的界面方式是AES-ECB，并非AES-CBC

**Comment by nilaoda** [comment]
得到key可以使用楼上大佬的下载器下载解密：
https://github.com/xhlove/vvtoolbox-gui-series

**Comment by xhlove** [comment]
> 得到key可以使用楼上大佬的下载器下载解密：
> https://github.com/xhlove/vvtoolbox-gui-series

下载器需要改一下才能适配这个...明天更新下

**Comment by xhlove** [comment]
> > 得到key可以使用楼上大佬的下载器下载解密：
> > https://github.com/xhlove/vvtoolbox-gui-series
> 
> 下载器需要改一下才能适配这个...明天更新下

v0.4.0已支持&发布，key要手动获取，解密模式是AES-YK

**Comment by ihuangke** [comment]
https://player.alicdn.com/resource/daily/20190514/de/prismplayer/2.8.3/aliplayer-min.js

我这里看到的这个js只有两行，压缩了，怎么显示跟你的一样多行的呢，一行无法断点啊。。谢谢

**Comment by xhlove** [comment]
> https://player.alicdn.com/resource/daily/20190514/de/prismplayer/2.8.3/aliplayer-min.js
> 
> 我这里看到的这个js只有两行，压缩了，怎么显示跟你的一样多行的呢，一行无法断点啊。。谢谢

前面文章有补充动图演示，在左下角有个格式化的按钮。
[动图演示](http://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBHZNkQAAFYwDIQ.gif)

**Comment by ihuangke** [comment]
完美解决了，就是断点的时候chrome浏览器很卡很卡，假死一样，点很久才反应。。。有点慢。。

**Comment by nilaoda** [comment]
> 完美解决了，就是断点的时候chrome浏览器很卡很卡，假死一样，点很久才反应。。。有点慢。。

https://blog.weimo.info/archives/441/

**Comment by nilaoda** [comment]
@ihuangke 
分析方案楼上大佬都写清楚了，这里推荐一种简单的获取key方案：

修改`aliplayer-min.js`的这里`i._sce_dlgtqredxx = n`

![image](https://user-images.githubusercontent.com/20772925/75113822-fe976900-568b-11ea-814d-e703bd479d09.png)

将修改后的js文件上传到某文件存储服务器上，使用[Gooreplacer](https://github.com/jiacai2050/gooreplacer)插件将请求修改到我们自己的js：

原始：
```
https://player.alicdn.com/resource/daily/20190514/de/prismplayer/2.8.3/aliplayer-min.js
```

修改为：
```
https://pan.iqiyi.com/ext/paopao/?token=eJxjYGBgmBQtsZUBBHb9ZwUAFk8DeQ.bin
```
如下图：

![image](https://user-images.githubusercontent.com/20772925/75113846-37374280-568c-11ea-8830-10ab564865f6.png)

这样在浏览器播放的时候就会弹出当前文件的key了：

![image](https://user-images.githubusercontent.com/20772925/75113857-56ce6b00-568c-11ea-999b-2a8bb131aa27.png)

最后使用支持这种解密的下载器解密就好了

**Comment by todaycoder001** [comment]
这个key我在抓取的网页的api返回中能得到的，问题是我怎么用N_m3u8DL-CLI来下载这个m3u8的资源？

**Comment by todaycoder001** [comment]
> 这个key我在抓取的网页的api返回中能得到的，问题是我怎么用N_m3u8DL-CLI来下载这个m3u8的资源？

补充一下，我是MACOS

**Comment by nilaoda** [comment]
> > 这个key我在抓取的网页的api返回中能得到的，问题是我怎么用N_m3u8DL-CLI来下载这个m3u8的资源？
> 
> 补充一下，我是MACOS

N_m3u8DL-CLI_Core 暂时不会支持这种解密

**Comment by ihuangke** [comment]
`得到key可以使用楼上大佬的下载器下载解密：
https://github.com/xhlove/vvtoolbox-gui-series`
已经可以了，按照上面的方法，使用Gooreplacer插件，弹出密钥轻松多了。。。感谢！

**Comment by Eacolt** [comment]
感谢大佬们相助！我这就去试试~

**Comment by ijrou** [comment]
> 以下是手动获取key的方法：
> 
> * 首先打开视频播放页面
> * F12，搜索关键字符串`_sce_dlgtqredxx`
> * 进入aliplayer-min.js，该js地址是：https://player.alicdn.com/resource/daily/20190514/de/prismplayer/2.8.3/aliplayer-min.js
> * 在如图所示的地方下断点，F5刷新（注意在network一栏选定Disable Cache），等待视频加载
>   ![下断点](https://camo.githubusercontent.com/b7932c5e35df7c4d57d701704406663d88551eb5/687474703a2f2f707575692e717069632e636e2f7673687069632f302f716f467253714b61764877627645624f55596d37344d357a49723155656c58756d7848396871525063587252326a43505f302f30)
>   ![Disable Cache](https://camo.githubusercontent.com/cb4e46ea93977ceb2fa374cb010d2b78243c9369/687474703a2f2f707575692e717069632e636e2f7673687069632f302f65524b52316475353479786d76326771527533573879416231796f7178504a4f6c414b657174435973443169506c52535f302f30)
> * 此时在console执行`btoa(String.fromCharCode.apply(null, new Uint8Array(i._sce_dlgtqredxx)))`即可得到base64形式的key
>   ![得到base64形式的key](https://camo.githubusercontent.com/cb4e46ea93977ceb2fa374cb010d2b78243c9369/687474703a2f2f707575692e717069632e636e2f7673687069632f302f65524b52316475353479786d76326771527533573879416231796f7178504a4f6c414b657174435973443169506c52535f302f30)
> 
> 发布于：https://blog.weimo.info/archives/440/

大佬，最近我已经找到了阿里云的数据流加密这块，csdn其实用到的就是ecb，但是鉴于对mp4结构本身的不熟悉，导致进度一直停滞，看到你推出的工具，发现确实挺不错的，想申请下联系邮箱方式，请求下一些问题，不知可否方便？本人的邮箱：services@priapus.cn

**Comment by ijrou** [comment]
> 补充：注意这里的界面方式是AES-ECB，并非AES-CBC

# csdn学院用阿里云点播加密方式是使用AES-ECB算法的，你的AES-YK我没反编译，在我的了解中AES中也没有这种加密模式，但是差不多意思就是以对下载的加密ts文件中的音视频数据流（已被加密）和获取到的key进行AES-ECB解密，我说得没错吧...
