### ISSUE TITLE
顺利下载了ts流文件，但是最后的合并文件无效，大小为0kb。

### ISSUE THREAD

**Issue by Chinees-zhang** [nilaoda/N_m3u8DL-CLI#784]
![download界面](https://github.com/nilaoda/N_m3u8DL-CLI/assets/95740471/60d8474e-a1f3-46e2-a9dd-40daef26c404)

<img width="623" alt="download界面1" src="https://github.com/nilaoda/N_m3u8DL-CLI/assets/95740471/ef74f3a2-fa4b-4eef-8c9d-09b01c33d46a">

**Comment by Bruce-sudo143** [comment]
I have the same question? Why is that?

**Comment by Chinees-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在正忙，无法亲自回复您的邮件。我将在抽时间，尽快给您回复。

**Comment by ZY-Robert** [comment]
来信已收到，谢谢！

**Comment by 520131420** [comment]
同问，下载完视频后，无法播放，合并后大小为0

**Comment by Chinees-zhang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我现在正忙，无法亲自回复您的邮件。我将在抽时间，尽快给您回复。

**Comment by nilaoda** [comment]
这种情况多半是视频无法解密导致
