### ISSUE TITLE
程式閃退

### ISSUE THREAD

**Issue by hcpeter15** [nilaoda/N_m3u8DL-CLI#785]
LOG 2023/05/28
Save Path: F:\巴哈動漫瘋 下載\N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG\Logs
Task Start: 2023/05/28 23:44:51
Task CommandLine: "F:\巴哈動漫瘋 下載\N_m3u8DL-CLI_v3.0.2_with_ffmpeg_and_SimpleG\N_m3u8DL-CLI_v3.0.2.exe" "https://m3u.haiwaikan.com/xm3u8/58738ff1212253de06932f0461fad0965ed4ca3e6e9270c7bdee11955014e8c99921f11e97d0da21.m3u8" --workDir "F:\巴哈動漫瘋 下載" --saveName "通往夏天的隧道，離別的出口" --enableDelAfterDone --enableMuxFastStart 

23:44:51.473 / (NORMAL) 開始解析 https://m3u.haiwaikan.com/xm3u8/58738ff1212253de06932f0461fad0965ed4ca3e6e9270c7bdee11955014e8c99921f11e97d0da21.m3u8

請問大老，為何會造成這個問題
還沒開始跑就直接閃退了

**Comment by nilaoda** [comment]
![image](https://github.com/nilaoda/N_m3u8DL-CLI/assets/20772925/67f75f13-5cc4-4c56-a68e-005f7676ea2b)

这里`#EXTINF`标签缺失了对应URL 导致程序闪退了

已经在最新的Actions中修复此问题：
https://github.com/nilaoda/N_m3u8DL-CLI/actions/runs/5162986406

更推荐使用全新的下载器：https://github.com/nilaoda/N_m3u8DL-RE
