### ISSUE TITLE
希望的改进

### ISSUE THREAD

**Issue by whxuezhe** [nilaoda/N_m3u8DL-CLI#792]
可以自定义下载保存路径，而不是静默C盘m3u8dl文件夹，希望可以自定义命名所下载的视频文件名集数等；其二是问下全新的跨平台版本，推进进度是否方便透个风，毕竟过去一年了？还有就是一些1300以上切片文件的资源，到最后20个切片时；速度只有64K上下。

**Comment by xbstory** [comment]
https://github.com/nilaoda/N_m3u8DL-RE

**Comment by whxuezhe** [comment]
可是RE用的是PS命令，我似乎不了解语法；不能像CLI那样-猫抓解析显示命令、复制到CLI中，很简单的操作就可以下载。例如：CLI是这样："https://m3u8.wolongcdnm3u8.com:65/4fe2c5ef/index.m3u8" --workDir "%USERPROFILE%\Downloads\m3u8dl" --saveName "m3u8解析_1689736768113" --enableDelAfterDone --headers "Referer:https://jx.wolongzywcdn.com:65/"
RE说是要加. \N_m3u8DL_RE.exe "https://m3u8.wolongcdnm3u8.com:65/4fe2c5ef/index.m3u8" --workDir "%USERPROFILE%\Downloads\m3u8dl" --saveName "m3u8解析_1689736768113" --enableDelAfterDone --headers "Referer:https://jx.wolongzywcdn.com:65/"
然而我加了，PS终端报错；不是正确的指令、不包含函数啥的；无法像CLI那样解析执行下载。求指导我这条笨龙，谢谢！
