### ISSUE TITLE
希望能增加修改ts参数的选项

### ISSUE THREAD

**Issue by tom613951** [nilaoda/N_m3u8DL-CLI#798]
如图,部分m3u8文件里的ts列表并没有参数
![image](https://github.com/nilaoda/N_m3u8DL-CLI/assets/111942871/3035e6a4-1839-44b6-81be-15f8f8f0e0cb)

**Comment by ZY-Robert** [comment]
来信已收到，谢谢！

**Comment by nilaoda** [comment]
请使用 [N_m3u8DL-RE](https://github.com/nilaoda/N_m3u8DL-RE), 它支持
```
--append-url-params                      将输入Url的Params添加至分片, 对某些网站很有用, 例如 kakao.com [default: False]
```
