### ISSUE TITLE
优酷视频无法合成

### ISSUE THREAD

**Issue by zhangyining215** [nilaoda/N_m3u8DL-CLI#80]
优酷视频用js链接获取到的m3u8链接在下载器里下载完成后文件无数据，显示0字节，浏览器为360极速浏览器

**Comment by zhangyining215** [comment]
视频地址为：https://v.youku.com/v_show/id_XNDUyNjg3OTQyOA==.html?s=8e04233ad1c7472da337&scm=20140719.rcmd.15319.show_8e04233ad1c7472da337
获取到的m3u8地址为：http://valipl-vip.cp31.ott.cibntv.net/697416E04A833714F531F5312/05004A00005E4C396F8BB78000000055B41E61-FD82-4AF9-82A3-A091367C470D-1-114.m3u8?ccode=0502&duration=2575&expire=18000&psid=9639022d4e52f062bf6f4c0d52de47b8&ups_client_netip=3a123dbb&ups_ts=1582260463&ups_userid=778544785&utid=uhtYFtzGnmYCAToSPbvFCYS6&vid=XNDUyNjg3OTQyOA%3D%3D&vkey=Afccf18138f132c4f7f304473faf0c9f9&sm=1&operate_type=1&dre=u38&si=78&dst=1&iv=1&s=8e04233ad1c7472da337&bc=2
网页上清晰度为HDR，语言为粤语

**Comment by zhangyining215** [comment]
把m3u8地址放到IDM里成功下载为ts文件，但播放只有前5秒，且都是广告

**Comment by nilaoda** [comment]
优酷视频可使用此软件下载
https://github.com/xhlove/vvtoolbox-gui-series

**Comment by zhangyining215** [comment]
这个软件也不行，添加进链接，选好保存位置开始后自己退出了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nilaoda"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 晚上6:07
收件人:&nbsp;"nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;;
抄送:&nbsp;"? ????"<zhangyining215@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 优酷视频无法合成 (#80)




优酷视频可使用此软件下载
 https://github.com/xhlove/vvtoolbox-gui-series

**Comment by nilaoda** [comment]
> 这个软件也不行，添加进链接，选好保存位置开始后自己退出了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"nilaoda"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月21日(星期五) 晚上6:07 收件人:&nbsp;"nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;; 抄送:&nbsp;"? ????"<zhangyining215@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 优酷视频无法合成 (#80) 优酷视频可使用此软件下载 https://github.com/xhlove/vvtoolbox-gui-series — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

好好研究Readme

**Comment by zhangyining215** [comment]
用自述文件给的js代码获取出来的key貌似不被认可，提示：video_sizes中没有key的情况



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"nilaoda"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月21日(星期五) 晚上9:10
收件人:&nbsp;"nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;;
抄送:&nbsp;"? ????"<zhangyining215@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 优酷视频无法合成 (#80)



 
这个软件也不行，添加进链接，选好保存位置开始后自己退出了
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"nilaoda"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月21日(星期五) 晚上6:07 收件人:&nbsp;"nilaoda/N_m3u8DL-CLI"<N_m3u8DL-CLI@noreply.github.com&gt;; 抄送:&nbsp;"? ????"<zhangyining215@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [nilaoda/N_m3u8DL-CLI] 优酷视频无法合成 (#80) 优酷视频可使用此软件下载 https://github.com/xhlove/vvtoolbox-gui-series — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
好好研究Readme
