### ISSUE TITLE
Tools stop working on SiriusXM

### ISSUE THREAD

**Issue by Sei969** [nilaoda/N_m3u8DL-CLI#809]
Reference link: https://github.com/nilaoda/N_m3u8DL-CLI/issues/166

Now after 2 years, the tool stopped working on SiriusXM. They changed the method of transmission and now the cookies have a form like: "AUTH_TOKEN=%7B%22deviceGrant%22%3A%7B%22deviceId%22%3A%22090ff4f1-ae00-4e24-8d08..."

So my question: Is it still possible to use the tool to download from SiriusXM? Thank you for any reply to get me on the right way!

**Comment by Sei969** [comment]
答案是肯定的

**Comment by pabstsmeared** [comment]
I am able to use hxxps://github.com/andrew0/SiriusXM for live capture but have had no luck with on demand material. I am also interested in help capturing on demand material.
