### ISSUE TITLE
下载的dmm影片不是全片一樣畫質

### ISSUE THREAD

**Issue by KsuiKin** [nilaoda/N_m3u8DL-CLI#819]
下載的時間會看到總容量會不斷改變，下載完看的時候畫質在某時間變模糊，怎麼解決

**Comment by Logosng** [comment]
我試過
畫質設定不要AUTO，M3U8選擇高清

**Comment by scadaren** [comment]
这个会出现的原因是和IP地址有关，我是用clash选择系统代理。可解决此问题。不过目前dmm加密升级，m3u8方式已经无法使用

**Comment by sosijung** [comment]
> 这个会出现的原因是和IP地址有关,我是用clash选择系统代理。 可解决此问题。 不过目前dmm加密升级,m3u8方式已经无法使用

Hi. Can you explain in detail how to solve that problem?
