### ISSUE TITLE
错误	CS0103	当前上下文中不存在名称“DecrypterYK”	N_m3u8DL-CLI Downloader.cs	

### ISSUE THREAD

**Issue by mskgroup** [nilaoda/N_m3u8DL-CLI#82]
错误	CS0103	当前上下文中不存在名称“DecrypterYK”	N_m3u8DL-CLI Downloader.cs

**Comment by mskgroup** [comment]
2.5.0的版本

**Comment by nilaoda** [comment]
这个文件暂时没传，如果想让程序跑起来可以把`Downloader.cs`中的`DecrypterYK.Decrypt`都改为`Decrypter.AES128Decrypt`

**Comment by mskgroup** [comment]
好的

在 2020-02-24 12:58:44，nilaoda <notifications@github.com> 写道：


这个文件暂时没传，如果想让程序跑起来可以把Downloader.cs中的DecrypterYK.Decrypt都改为Decrypter.AES128Decrypt
