### ISSUE TITLE
现在有办法下载cctv的视频了吗？

### ISSUE THREAD

**Issue by zhht1204** [nilaoda/N_m3u8DL-CLI#824]
看之前2021的issue似乎说ts流加密了，现在有没有相关研究进展欸。求教。

**Comment by scadaren** [comment]
我也在寻找公开的资料，目前应该已经破解但是只有小范围传播。

**Comment by zhht1204** [comment]
看到现在在RE那个库更新，这里issue关掉了就。目前发现是接口里有一个不加密的链接，但是没法直接用来下最高清晰度的，需要一些处理。
