### ISSUE TITLE
新出的这个一键破解工具各位用了吗？

### ISSUE THREAD

**Issue by ghost** [nilaoda/N_m3u8DL-CLI#825]
https://github.com/EidVnex/DMM-Decrypt-Jav-It

VR可以解，2D和4K的未测试。
原理不懂，不过大概和现有的都相同吧。

另外，我还是喜欢手动破解，求问一个4K破解的问题：
4K里包含多个KID和KEY，获取到之后如何使用FFMPEG载入呢？
mp4dump 支持多个key，但是破解出来的和ffmpeg还是不相同，有谁知道如何用ffmpeg解4k？

**Comment by nilaoda** [comment]
使用mp4decrypt
