### ISSUE TITLE
国家中小学智慧教育平台不能下载

### ISSUE THREAD

**Issue by FreeVB** [nilaoda/N_m3u8DL-CLI#834]
你好，为什么[国家中小学智慧教育平台](https://basic.smartedu.cn/)的视频不能下载呀？

![50db3d4e11c9efae470829ee44e4f19](https://github.com/user-attachments/assets/74837a7e-4fa7-42c3-86d2-5a2214d0b54f)

**Comment by nilaoda** [comment]
网课平台通常有一些其他的限制，本项目不负责解答
