### ISSUE TITLE
输入的数据不是完整的块

### ISSUE THREAD

**Issue by Iron237** [nilaoda/N_m3u8DL-CLI#836]
在下载时出现如下情况，随机停止运行
![image](https://github.com/user-attachments/assets/8facb672-47ff-41da-aed8-e4425f6b0ac1)

**Comment by Yhyu8903** [comment]
<img width="746" height="459" alt="Image" src="https://github.com/user-attachments/assets/2dbb1326-532c-408e-88a8-379249534067" />

**Comment by Yhyu8903** [comment]
该怎么解决呀
