### ISSUE TITLE
带EXT-X-MAP的M3U8怎么下载？

### ISSUE THREAD

**Issue by SueSongHao** [nilaoda/N_m3u8DL-CLI#837]
要怎么操作，请问各位大佬？

#EXTM3U
#EXT-X-TARGETDURATION:10
#EXT-X-ALLOW-CACHE:YES
#EXT-X-PLAYLIST-TYPE:VOD
#EXT-X-VERSION:6
#EXT-X-MEDIA-SEQUENCE:1
#EXT-X-MAP:URI="init-v1-a1.mp4"

**Comment by nilaoda** [comment]
https://github.com/nilaoda/N_m3u8DL-RE

**Comment by SueSongHao** [comment]
> https://github.com/nilaoda/N_m3u8DL-RE

谢谢大佬回复，我尝试用RE去下载，但显示“WARN : Response status code does not indicates success: 403 (Forbidden)."

是不是无解？

**Comment by SueSongHao** [comment]
我试着用当前播放页面去请求头Referer，但依然是403。是这样操作嘛？
