### ISSUE TITLE
2.5.1版本更改了直播流录制方式后，录制出的视频出现卡顿

### ISSUE THREAD

**Issue by mskgroup** [nilaoda/N_m3u8DL-CLI#85]
2.5.1版本更改了直播流录制方式后，录制出的视频出现卡顿
经常会出现如下两个Complete提示：
19:23:26.990 Waiting...
19:23:27.994 <6688 Downloading>
**19:23:28.344 <6688 Complete>**
19:23:28.346 Waiting...
**19:23:28.347 <6688 Complete>**
19:23:28.349 Waiting...
19:23:30.467 <6689 Downloading>
19:23:31.135 <6689 Complete>

我修改了以下源码：
_timer.Interval = (targetduration - 2) * 300_
因为该间隔为1000ms时，经常出现获取空段（如<**6321** Complete>Waiting...<**6325** Downloading>）

**Comment by mskgroup** [comment]
还会出现这种提示
19:27:47.823 <6861 Downloading>
19:27:51.775 <6861 Downloading>
19:27:55.919 <6861 Downloading>
19:27:57.280 <6861 Complete>

**Comment by mskgroup** [comment]
目前尚不排除是直播流卡顿而造成录制的卡顿

**Comment by nilaoda** [comment]
反馈已收到，后续继续调整下逻辑

**Comment by mskgroup** [comment]
> 反馈已收到，后续继续调整下逻辑

辛苦啦

**Comment by nilaoda** [comment]
> > 反馈已收到，后续继续调整下逻辑
> 
> 辛苦啦

能否提供一个链接测试？

**Comment by mskgroup** [comment]
> > > 反馈已收到，后续继续调整下逻辑
> > 
> > 
> > 辛苦啦
> 
> 能否提供一个链接测试？

这个抱歉……但我最近会测试一些其他的直播源，如果出现类似的问题将提供给您测试
