### ISSUE TITLE
请添加禁用更新选项

### ISSUE THREAD

**Issue by youxia2016** [nilaoda/N_m3u8DL-CLI#90]
我将这个软件当作一个第三方下载工具

每天下载几千至几万个m3u8，每次启动都会检查更新，如果没有代理 响应会很慢 很消耗时间

建议加一个选项 可以选择是否进行更新，而不是强制更新

**Comment by nilaoda** [comment]
新版本在程序目录下创建`NO_UPDATE`文件可以禁止启动时检测更新
