### ISSUE TITLE
程序会卡住 不动

### ISSUE THREAD

**Issue by youxia2016** [nilaoda/N_m3u8DL-CLI#93]
首先感谢对禁用更新的支持  已经使用上了

程序会卡住  不做任何重试,之前版本好像没有这个问题 (我下载的点播 不是直播)

![卡住](https://user-images.githubusercontent.com/16131728/75537485-3585ca00-5a52-11ea-8629-6c2a8095c20d.png)

17:28:13.260 / (NORMAL) <4135 Downloading>
17:28:13.635 / (NORMAL) <4135 Complete>
17:28:13.734 / (NORMAL) <4136 Complete>
17:28:13.745 / (NORMAL) <4136 Downloading>
17:28:14.044 / (NORMAL) <4136 Downloading>
17:28:14.052 / (NORMAL) <4136 Complete>
17:28:14.072 / (NORMAL) <4139 Complete>
17:28:14.100 / (NORMAL) <4141 Downloading>
17:28:14.107 / (NORMAL) <4141 Complete>
17:28:14.153 / (NORMAL) <4141 Complete>
17:28:14.185 / (NORMAL) <4142 Downloading>
17:28:14.243 / (NORMAL) <4142 Complete>
17:28:14.333 / (NORMAL) <4144 Complete>
17:28:14.362 / (NORMAL) <4145 Complete>
17:28:14.393 / (NORMAL) <4146 Complete>
17:28:14.401 / (NORMAL) <4146 Complete>
17:28:14.452 / (NORMAL) <4149 Downloading>
17:28:14.561 / (NORMAL) <4149 Complete>
17:28:14.590 / (NORMAL) <4149 Downloading>
17:28:14.731 / (NORMAL) <4149 Downloading>
17:28:14.759 / (NORMAL) <4149 Complete>
17:28:14.767 / (NORMAL) <4149 Complete>
17:28:14.787 / (NORMAL) <4151 Complete>
17:28:14.819 / (NORMAL) <4152 Downloading>
17:28:14.877 / (NORMAL) <4152 Complete>
17:28:14.902 / (NORMAL) <4153 Downloading>
17:28:14.915 / (NORMAL) <4153 Downloading>
17:28:14.924 / (NORMAL) <4153 Downloading>
17:28:14.927 / (NORMAL) <4153 Complete>
17:28:14.995 / (NORMAL) <4153 Complete>
17:28:15.024 / (NORMAL) <4153 Complete>
17:28:15.050 / (NORMAL) <4153 Complete>
17:28:15.079 / (NORMAL) <4153 Complete>
17:28:15.140 / (NORMAL) <4153 Downloading>
17:28:15.159 / (NORMAL) <4153 Complete>
17:28:15.168 / (NORMAL) <4153 Complete>
17:28:15.220 / (NORMAL) <4153 Complete>
17:28:15.269 / (NORMAL) <4153 Downloading>
17:28:15.320 / (NORMAL) <4153 Downloading>
17:28:15.331 / (NORMAL) <4153 Complete>
17:28:15.353 / (NORMAL) <4153 Downloading>
17:28:15.514 / (NORMAL) <4153 Complete>
17:28:15.543 / (NORMAL) <4153 Complete>
17:28:15.573 / (NORMAL) <4153 Downloading>
17:28:15.619 / (NORMAL) <4153 Complete>
17:28:15.782 / (NORMAL) <4153 Downloading>
17:28:15.819 / (NORMAL) <4153 Complete>
17:28:16.003 / (NORMAL) <4153 Downloading>
17:28:16.032 / (NORMAL) <4153 Complete>
17:28:16.099 / (NORMAL) <4153 Complete>
17:28:16.216 / (NORMAL) <4153 Complete>
17:28:16.232 / (NORMAL) <4153 Complete>
17:28:16.248 / (NORMAL) <4153 Downloading>
17:28:16.324 / (NORMAL) <4153 Downloading>
17:28:16.357 / (NORMAL) <4153 Complete>
17:28:16.364 / (NORMAL) <4153 Complete>
17:28:16.416 / (NORMAL) <4153 Complete>
17:28:16.431 / (NORMAL) <4153 Complete>
17:28:16.505 / (NORMAL) <4153 Complete>
17:28:16.534 / (NORMAL) <4153 Downloading>
17:28:16.562 / (NORMAL) <4153 Downloading>
17:28:16.604 / (NORMAL) <4153 Complete>
17:28:16.755 / (NORMAL) <4153 Complete>
17:28:16.773 / (NORMAL) <4153 Downloading>
17:28:16.808 / (NORMAL) <4153 Downloading>
17:28:16.808 / (NORMAL) <4153 Complete>
17:28:16.837 / (NORMAL) <4153 Complete>
17:28:16.852 / (NORMAL) <4153 Downloading>
17:28:17.113 / (NORMAL) <4153 Downloading>
17:28:17.156 / (NORMAL) <4153 Complete>
17:28:17.201 / (NORMAL) <4153 Downloading>
17:28:17.201 / (NORMAL) <4153 Downloading>
17:28:17.265 / (NORMAL) <4153 Complete>
17:28:17.268 / (NORMAL) <4153 Downloading>
17:28:17.294 / (NORMAL) <4153 Complete>
17:28:17.326 / (NORMAL) <4153 Complete>
17:28:17.338 / (NORMAL) <4153 Downloading>
17:28:17.360 / (NORMAL) <4153 Complete>
17:28:17.388 / (NORMAL) <4153 Complete>
17:28:17.414 / (NORMAL) <4153 Complete>
17:28:17.470 / (NORMAL) <4153 Downloading>
17:28:17.503 / (NORMAL) <4153 Complete>
17:28:17.529 / (NORMAL) <4153 Complete>
17:28:17.569 / (NORMAL) <4153 Complete>
17:28:17.601 / (NORMAL) <4153 Complete>
17:28:17.644 / (NORMAL) <4153 Complete>
17:28:17.674 / (NORMAL) <4153 Downloading>
17:28:17.693 / (NORMAL) <4153 Complete>
17:28:17.740 / (NORMAL) <4153 Complete>
17:28:17.755 / (NORMAL) <4153 Downloading>
17:28:17.765 / (NORMAL) <4153 Complete>
17:28:17.781 / (NORMAL) <4153 Downloading>
17:28:17.803 / (NORMAL) <4153 Complete>
17:28:17.819 / (NORMAL) <4153 Downloading>
17:28:17.863 / (NORMAL) <4153 Complete>
17:28:17.920 / (NORMAL) <4153 Complete>
17:28:17.928 / (NORMAL) <4153 Complete>
17:28:17.934 / (NORMAL) <4153 Complete>
17:28:17.941 / (NORMAL) <4153 Complete>
17:28:17.950 / (NORMAL) <4153 Complete>
17:28:17.958 / (NORMAL) <4153 Complete>
17:28:18.009 / (NORMAL) <4153 Complete>
17:28:18.068 / (NORMAL) <4153 Complete>
17:28:18.075 / (NORMAL) <4153 Complete>
17:28:18.083 / (NORMAL) <4153 Complete>
17:28:18.114 / (NORMAL) <4153 Complete>
17:28:18.172 / (NORMAL) <4153 Complete>
17:28:18.184 / (NORMAL) <4153 Complete>
17:28:18.196 / (NORMAL) <4153 Complete>
17:28:18.227 / (NORMAL) <4153 Complete>
17:28:18.258 / (NORMAL) <4153 Complete>
17:28:18.258 / (NORMAL) <4153 Complete>
17:30:16.026 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
17:30:39.864 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
17:34:24.071 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。

**Comment by youxia2016** [comment]
![卡住2](https://user-images.githubusercontent.com/16131728/75541258-8c8e9d80-5a58-11ea-9b46-d5e59ffb6ea4.png)

18:17:58.917 / (NORMAL) <548 Downloading>
18:17:58.988 / (NORMAL) <548 Downloading>
18:17:59.000 / (NORMAL) <548 Downloading>
18:17:59.011 / (NORMAL) <548 Complete>
18:17:59.021 / (NORMAL) <548 Complete>
18:17:59.198 / (NORMAL) <550 Downloading>
18:17:59.231 / (NORMAL) <550 Downloading>
18:17:59.311 / (NORMAL) <550 Complete>
18:17:59.414 / (NORMAL) <551 Complete>
18:17:59.509 / (NORMAL) <552 Downloading>
18:17:59.573 / (NORMAL) <552 Complete>
18:17:59.645 / (NORMAL) <552 Complete>
18:17:59.722 / (NORMAL) <552 Downloading>
18:17:59.846 / (NORMAL) <552 Downloading>
18:17:59.883 / (NORMAL) <552 Complete>
18:17:59.949 / (NORMAL) Waiting...
18:17:59.980 / (NORMAL) <552 Complete>
18:18:00.029 / (NORMAL) Waiting...
18:18:00.128 / (NORMAL) <552 Complete>
18:18:00.184 / (NORMAL) <552 Complete>
18:18:00.231 / (NORMAL) Waiting...
18:18:00.262 / (NORMAL) Waiting...
18:18:00.294 / (NORMAL) Waiting...
18:18:00.294 / (NORMAL) Waiting...
18:26:17.712 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
18:26:23.892 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
18:27:20.065 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
18:28:31.965 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
18:29:12.010 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
18:30:00.237 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。

**Comment by nilaoda** [comment]
直播录制？

**Comment by youxia2016** [comment]
是点播视频，不是直播

**Comment by nilaoda** [comment]
> 是点播视频，不是直播

点播视频，理论上不会出现`18:17:59.573 / (NORMAL) <552 Complete>`这种输出，是你的m3u8文件底部没有以`#EXT-X-ENDLIST`结尾吗？是的话自行补上或者修改`meta.json`中的vod标识，然后使用此文件重新下载让程序走点播下载的流程

**Comment by youxia2016** [comment]
LOG 2020/02/28
Save Path: D:\AfreecaTV下载\Logs
Task Start: 2020/02/28 18:17:06
Task CommandLine: "N_m3u8DL-CLI.exe" "http://vod-archive-global-cdn-z01.afreecatv.com/video/_definst_/smil:vod/20200206/923/220754923/REGL_E63CB8F5_220754923_1.smil/playlist.m3u8" --saveName ahrum0912_52737435_20200207003047 --workDir "F:\AfreecaTV" --headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" --maxThreads 32 --minThreads 16 --retryCount 20 --disableDateInfo --enableDelAfterDone

18:17:06.376 / (NORMAL) Start Parsing http://vod-archive-global-cdn-z01.afreecatv.com/video/_definst_/smil:vod/20200206/923/220754923/REGL_E63CB8F5_220754923_1.smil/playlist.m3u8
18:17:06.924 / (NORMAL) Parsing Content
18:17:06.972 / (NORMAL) Writing Json: [meta.json]
18:17:07.020 / (NORMAL) Master List Found
18:17:07.036 / (NORMAL) Writing Master List Json: [playLists.json]
18:17:07.114 / (NORMAL) Select Playlist: http://vod-archive-global-cdn-z01.afreecatv.com/mapped-vod/20200206/923/220754923/REGL_E63CB8F5_220754923_1.php/live/0/index-f2-v1-a1.m3u8
18:17:07.114 / (NORMAL) Start Re-Parsing
18:17:08.191 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
18:17:08.238 / (NORMAL) Living Stream Found
18:17:08.254 / (NORMAL) Start Recording
18:17:08.285 / (NORMAL) Waiting...
18:17:16.575 / (NORMAL) Master List Found
18:17:16.575 / (NORMAL) Writing Master List Json: [playLists.json]
18:17:16.591 / (NORMAL) Select Playlist: http://vod-archive-global-cdn-z01.afreecatv.com/mapped-vod/20200206/923/220754923/REGL_E63CB8F5_220754923_1.php/live/0/index-f2-v1-a1.m3u8
18:17:16.607 / (NORMAL) Start Re-Parsing
18:17:16.965 / (NORMAL) <1 Downloading>
18:17:17.125 / (NORMAL) <1 Complete>
18:17:17.156 / (NORMAL) Reading Video Info
18:17:17.250 / (NORMAL) PID 0x100: Video h264, yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 31 fps, 30 tbr, 90k tbn, 62 tbc
18:17:17.250 / (NORMAL) PID 0x101: Audio aac, 44100 Hz, stereo, fltp, 131 kb/s
18:17:17.265 / (NORMAL) PID 0x102: Data timed_id3 (ID3  / 0x20334449)
18:17:17.265 / (NORMAL) <2 Downloading>
18:17:17.389 / (NORMAL) <2 Complete>
18:17:17.399 / (NORMAL) <3 Downloading>
18:17:17.476 / (NORMAL) <3 Complete>
18:17:17.484 / (NORMAL) <4 Downloading>
18:17:17.579 / (NORMAL) <4 Complete>
18:17:17.598 / (NORMAL) <5 Downloading>
18:17:17.685 / (NORMAL) <5 Complete>
18:17:17.685 / (NORMAL) <6 Downloading>
18:17:17.809 / (NORMAL) <6 Complete>

查看2个m3u8文件应该没有问题，2个m3u8文件放入附件了

[playlist.m3u8.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/4266708/playlist.m3u8.txt)

[index-f2-v1-a1.m3u8.txt](https://github.com/nilaoda/N_m3u8DL-CLI/files/4266712/index-f2-v1-a1.m3u8.txt)

**Comment by youxia2016** [comment]
18:17:07.114 / (NORMAL) Start Re-Parsing
18:17:08.191 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
18:17:08.238 / (NORMAL) Living Stream Found
18:17:08.254 / (NORMAL) Start Recording

这里好像出错了，是因为读取文件不全吗？ 我这边代理服务器速度为1000mb,我下载速度接近600Mb/s

**Comment by youxia2016** [comment]
LOG 2020/02/28
Save Path: D:\AfreecaTV视频下载\Logs
Task Start: 2020/02/28 19:14:33
Task CommandLine: "N_m3u8DL-CLI.exe" "http://vod-archive-global-cdn-z01.afreecatv.com/video/_definst_/smil:vod/20200201/422/220627422/REGL_C933A744_220627422_1.smil/playlist.m3u8" --saveName ahrum0912_52367667_20200202000323 --workDir "F:\AfreecaTV" --headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" --maxThreads 32 --minThreads 16 --retryCount 20 --disableDateInfo --enableDelAfterDone

19:14:33.054 / (NORMAL) Start Parsing http://vod-archive-global-cdn-z01.afreecatv.com/video/_definst_/smil:vod/20200201/422/220627422/REGL_C933A744_220627422_1.smil/playlist.m3u8
19:14:35.007 / (NORMAL) Parsing Content
19:14:35.054 / (NORMAL) Writing Json: [meta.json]
19:14:35.086 / (NORMAL) Master List Found
19:14:35.101 / (NORMAL) Writing Master List Json: [playLists.json]
19:14:35.179 / (NORMAL) Select Playlist: http://vod-archive-global-cdn-z01.afreecatv.com/mapped-vod/20200201/422/220627422/REGL_C933A744_220627422_1.php/live/0/index-f2-v1-a1.m3u8
19:14:35.195 / (NORMAL) Start Re-Parsing
19:14:36.257 / (ERROR) 远程服务器返回错误: (500) 内部服务器错误。
19:14:36.304 / (NORMAL) Living Stream Found
19:14:36.320 / (NORMAL) Start Recording
19:14:36.336 / (NORMAL) Waiting...
19:14:46.949 / (NORMAL) Master List Found
19:14:46.964 / (NORMAL) Writing Master List Json: [playLists.json]
19:14:46.980 / (NORMAL) Select Playlist: http://vod-archive-global-cdn-z01.afreecatv.com/mapped-vod/20200201/422/220627422/REGL_C933A744_220627422_1.php/live/0/index-f2-v1-a1.m3u8
19:14:46.996 / (NORMAL) Start Re-Parsing
19:14:48.707 / (NORMAL) <1 Downloading>
19:14:48.831 / (NORMAL) <1 Complete>
19:14:48.847 / (NORMAL) Reading Video Info
19:14:48.956 / (NORMAL) PID 0x100: Video h264, yuv420p(progressive), 1280x720 [SAR 1:1 DAR 16:9], 31 fps, 30 tbr, 90k tbn, 62 tbc
19:14:48.956 / (NORMAL) PID 0x101: Audio aac, 44100 Hz, stereo, fltp, 126 kb/s
19:14:48.972 / (NORMAL) PID 0x102: Data timed_id3 (ID3  / 0x20334449)
19:14:48.972 / (NORMAL) <2 Downloading>
19:14:49.166 / (NORMAL) <2 Complete>
19:14:49.190 / (NORMAL) <3 Downloading>

这个也显示 Living Stream Found ，并且出错

**Comment by youxia2016** [comment]
LOG 2020/02/28
Save Path: D:\AfreecaTV视频下载\Logs
Task Start: 2020/02/28 19:13:00
Task CommandLine: "N_m3u8DL-CLI.exe" "http://vod-archive-global-cdn-z01.afreecatv.com/video/_definst_/smil:vod/20200202/894/220651894/REGL_F2C4C5A1_220651894_1.smil/playlist.m3u8" --saveName ahrum0912_52491598_20200202232647 --workDir "F:\AfreecaTV" --headers "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36" --maxThreads 32 --minThreads 16 --retryCount 20 --disableDateInfo --enableDelAfterDone

19:13:00.088 / (NORMAL) Start Parsing http://vod-archive-global-cdn-z01.afreecatv.com/video/_definst_/smil:vod/20200202/894/220651894/REGL_F2C4C5A1_220651894_1.smil/playlist.m3u8
19:13:00.333 / (NORMAL) Parsing Content
19:13:00.334 / (NORMAL) Writing Json: [meta.json]
19:13:00.601 / (NORMAL) Master List Found
19:13:00.633 / (NORMAL) Writing Master List Json: [playLists.json]
19:13:00.726 / (NORMAL) Select Playlist: http://vod-archive-global-cdn-z01.afreecatv.com/mapped-vod/20200202/894/220651894/REGL_F2C4C5A1_220651894_1.php/live/0/index-f2-v1-a1.m3u8
19:13:00.742 / (NORMAL) Start Re-Parsing
19:13:00.963 / (NORMAL) Parsing Content
19:13:00.986 / (NORMAL) Writing Json: [meta.json]
19:13:01.064 / (NORMAL) Start Downloading
19:13:01.215 / (NORMAL) Reading Video Info

这个就是正常的，没有显示Living Stream Found

**Comment by nilaoda** [comment]
N_m3u8DL-CLI_v2.5.4测试了
http://vod-archive-global-cdn-z01.afreecatv.com/video/_definst_/smil:vod/20200206/923/220754923/REGL_E63CB8F5_220754923_1.smil/playlist.m3u8

没有发现问题


![image](https://user-images.githubusercontent.com/20772925/75545927-7be32500-5a62-11ea-965e-5a70ff2fc4e1.png)

**Comment by youxia2016** [comment]
我的感觉 就是  程序读取m3u8文件 因为网络问题，没有读取完整，导致变成了 直播流，并不是每次都出错，而是随机的
