### ISSUE TITLE
我尝试修改了HLSLiveDownloader中检测新分片的机制

### ISSUE THREAD

**Issue by mskgroup** [nilaoda/N_m3u8DL-CLI#94]
我将>0修改为了!=0，目前来看好像效果不错，没在出现过之前的问题
`   if (toDownList.Count != 0)
                Record();`

然后将以下内容删除或注释
       ` /*private bool isNewSeg()
        {
            if (toDownList.Count > 0)
                return true;
            return false;
        }*/`

**Comment by nilaoda** [comment]
刚才 @youxia2016 提交了新的版本，你试试[v2.5.6](https://github.com/nilaoda/N_m3u8DL-CLI/releases/latest)直播录制表现怎么样

**Comment by mskgroup** [comment]
> 刚才 @youxia2016 提交了新的版本，你试试[v2.5.6](https://github.com/nilaoda/N_m3u8DL-CLI/releases/latest)直播录制表现怎么样

12:28:16.474 <1683 Downloading>
12:28:16.817 <1683 Complete>
12:28:16.818 Waiting...
12:28:17.894 定时器间隔 4.5s 下次进入时间:2020/3/3 12:28:22
12:28:19.175 <1685 Downloading>
12:28:21.108 <1685 Complete>

会丢一个分片

**Comment by mskgroup** [comment]
timer.Interval = TotalDuration * 1000-500;

把它改成-500就不会出现丢分片了
2:44:58.817 <6724 Downloading>
12:44:59.104 <6724 Complete>
12:44:59.105 Waiting...
12:44:59.719 定时器间隔 4.5s 下次进入时间:2020/3/3 12:45:04
12:45:00.764 <6725 Downloading>
12:45:02.383 <6725 Complete>

**Comment by mskgroup** [comment]
还有个问题，就是下载网络不是很好的时候，会发生这种情况
15:12:25.905 <2763 Downloading>
15:12:26.848 定时器间隔 4.5s 下次进入时间:2020/3/3 15:12:31
15:12:27.961 <2763 Downloading>

**Comment by mskgroup** [comment]
15:25:23.419 <3280 Downloading>
15:25:23.704 定时器间隔 4.5s 下次进入时间:2020/3/3 15:25:28
15:25:24.167 <3280 Complete>

其实间隔这句话没必要提示出来

**Comment by nilaoda** [comment]
试一下最新源码

**Comment by mskgroup** [comment]
在通常的情况下不会丢失或重复分片
_未确定：在个别下载卡顿，下载时间过长时会出现积压，从而导致重复或丢失分片_

偶尔会出现以下两次Complete的情况：
<1 Downloading>
 <1 Complete>
Waiting
 <1 Complete>
Waiting
<2 Downloading>

实测修改为以下代码后可以解决两次Complete：
```
            if (toDownList.Count != 0)
                Record();
```

**Comment by nilaoda** [comment]
试一下新的`HLSLiveDownloader.cs`

**Comment by mskgroup** [comment]
> 试一下新的`HLSLiveDownloader.cs`
开头会丢一个分片，录制过程中偶尔也会丢分片

14:27:57.926 识别为直播流, 开始录制
14:27:57.939 <918 Downloading>
14:27:59.126 <918 Complete>
14:27:59.131 读取文件信息...
14:27:59.855 <919 Downloading>
14:28:00.503 <919 Complete>
14:28:00.504 <920 Downloading>
14:28:01.125 <920 Complete>
14:28:01.126 Waiting...
14:28:03.151 <922 Downloading>


14:30:28.907 <1020 Complete>
14:30:28.909 Waiting...
14:30:31.984 <1022 Downloading>

**Comment by mskgroup** [comment]
`timer.Interval = TotalDuration * 1000 - 1000;`
修改回-1000后，不会再丢分片

**Comment by nilaoda** [comment]
搞错了定时器的单位，你再试试看

**Comment by mskgroup** [comment]
目前来看没有问题了，没有丢分片，也没有重复，也没有complete重复提示
